### ISSUE TITLE
Using DebugBar only in local environment

### ISSUE THREAD

**Issue by ludo237** [barryvdh/laravel-debugbar#10]
I've a question and I can't figured it out.

I'm using, locally, your awesome debugbar and it works like a charm. But the problem comes when I publish, remotely, my project and the debugbar is still there.

Inside /boostrap/start.php I've

``` php
$env = $app->detectEnvironment(array(
    'local' => array('ludo.*','Ludo-MBPro.*'),
));
```

That allow me to use a /app/local/ folder for local configuration and it works fine for everythings. How can I enable debugbar to works only in local Env? Is there any kind of setup ? I can't spot it.

Edit: At the moment I've setup the ServiceProvider and the Alias inside the /app/local/app.php file. Is this the best way to handle it?

**Comment by adrianogl** [comment]
in routes.php

if($env == 'local') {
    Debugbar::enable();
} else {
    Debugbar::disable();
}
