### ISSUE TITLE
Cannot enable Debugbar at runtime with middleware

### ISSUE THREAD

**Issue by divdax** [barryvdh/laravel-debugbar#1000]
At some point this didn't work anymore. The Middleware is defined and users debug is set to 1. The Middleware is defined and setting the config is called etc. If i set debugbar.enabled = true in the config debugbar is shown. Any ideas?

```php
class DebugBarMiddleware
{
    public function handle($request, Closure $next)
    {
        \Debugbar::disable();

        if (auth()->check() && auth()->user()->debug) {
                config(['app.debug' => true]);
                config(['debugbar.enabled' => true]);

                \Debugbar::enable();
        }

        return $next($request);
    }
}
```

**Comment by nicoja** [comment]
Have you solved the problem ?

From my side, using \Debugbar::enable() or \Debugbar::disable(); create the exception : Call to undefined method DebugBar\DebugBar::enable() or Call to undefined method DebugBar\DebugBar::disable()

If I use :
app('debugbar')->disable(); or app('debugbar')->enable(); it works.

Hope it helps.

Thus, is the README is stil correct ? Or do we made bad integration ?

**Comment by G4Zz0L1** [comment]
Any idea on this? I'm in the same situation.
If I set `DEBUGBAR_ENABLED` to true everything's fine.
But if I set it to false, and then use `debugbar()->enable()` in the middleware, it doesn't show.
If on the next line I do `dump(debugbar()->isEnabled())` it returns true, and `dump(debugbar()->getData())` contains everything, but the bar it's not there.

**Comment by matiazar** [comment]
> Any idea on this? I'm in the same situation.
> If I set `DEBUGBAR_ENABLED` to true everything's fine.
> But if I set it to false, and then use `debugbar()->enable()` in the middleware, it doesn't show.
> If on the next line I do `dump(debugbar()->isEnabled())` it returns true, and `dump(debugbar()->getData())` contains everything, but the bar it's not there.

same to me !

  class DebugBar
  {
      public function handle($request, Closure $next, $guard = null)
      {
          if (Auth::check() && Auth::user()->hasRole(['admin', 'superadmin'])) {
  //            app('debugbar')->enable();
              \Debugbar::enable();
          }
  
          dump(debugbar()->isEnabled());
          dump(debugbar()->getData());
          return $next($request);
  }

**Comment by laurenceHR** [comment]
Hi, I made a custom package with a custom ServiceProvider to allow enable debugbar in Middleware when this is disabled by .env
https://github.com/jaguarsoft-vendor/laravel-debugbar
