### ISSUE TITLE
Any documentation on how to debug jobs in a queue?

### ISSUE THREAD

**Issue by saleemepoch** [barryvdh/laravel-debugbar#1002]
Hi,

I have jobs running in a queue and I need to find out which functions/queries might need optimisation. Is there a way to measure time at various points in a job and have that logged or reported somewhere?

**Comment by khanalpride** [comment]
I think while on development/local, you can just use the `sync` queue to test the job in same process runtime.
then you will get all the query details as well. After you are happy with that, you can change that to redis or some other in production.
