### ISSUE TITLE
Malicious typosquatting package

### ISSUE THREAD

**Issue by nCrazed** [barryvdh/laravel-debugbar#1004]
Just wanted to bring your attention to this package: https://packagist.org/packages/barrydvh/laravel-debugbar (note the `dvh` vs `vdh`) spelling in the namespace.

It's a fork (not done via GH interface, so GH is not going to pick up on the relationship) of this project with the following additions at the time of this writing: 

1. Changes in spelling across the project that mask the typo:
    * https://github.com/raysn0w/laravel-debugbar/commit/90caf97702e2f03e0da1d7f153e8db3a64b83928
    * https://github.com/raysn0w/laravel-debugbar/commit/99a84fd6df0b420eab21c35f8d3846225e0107f7
2. Pulls in a a separate package (by the same author):
    * https://github.com/raysn0w/laravel-debugbar/commit/9917264a6c8314e10901b741d342e52973e81e01
3. Attaches a (for now) seemingly harmless,  custom middleware to the `web` group:
    * https://github.com/raysn0w/laravel-debugbar/commit/43b34419ccb481e6ed81271d99f7a785593f2677
    The base64 encoded error response looks like an attempt at to mask any uncaught errors in the payload via an unrelated error message that can't be easily traced back to this package:
        > Database integrity failed, please perform database maintenance.

The end goal appears to be to extract .env secrets out of unsuspecting user of the package by eventually pulling in a yet another package from the same author: https://github.com/raysn0w/illustrate/blob/master/src/middleware/EncryptSession.php

**Comment by nCrazed** [comment]
Ping @sisve he's the one that brought my attention to this and might be able to shed some more light on the situation.

**Comment by nCrazed** [comment]
Looks like the package got pulled from packagist.

**Comment by barryvdh** [comment]
Someone brought this to my attention as well. I've reported it to Packagist yesterday and they removed it. Thanks for the warning!
