### ISSUE TITLE
XSS in timeline from query

### ISSUE THREAD

**Issue by oprudkyi** [barryvdh/laravel-debugbar#1007]
Hi, 

barryvdh/laravel-debugbar v3.2.8

in timeline tab, bottom table 

sample query 
```
\DB::statement("SELECT * FROM users WHERE id = '<script>debugger;alert(5);</script>' OR SLEEP(2)");
```

![image](https://user-images.githubusercontent.com/3018472/74998683-0c69a600-5462-11ea-8277-8acfbde8d15c.png)

**Comment by Twavesx** [comment]
could u share the link ??

**Comment by oprudkyi** [comment]
@Twavesx
https://github.com/maximebf/php-debugbar/blob/1a1605b8e9bacb34cc0c6278206d699772e1d372/src/DebugBar/Resources/widgets.js#L506

**Comment by oprudkyi** [comment]
recreated it as https://github.com/maximebf/php-debugbar/issues/448
