### ISSUE TITLE
Ajax request returns 500 internal server error

### ISSUE THREAD

**Issue by Adam-78** [barryvdh/laravel-debugbar#1008]
ajax requests are returning 500 internal server error. When I view the logs I get the following error:

    [2020-02-26 19:09:13] local.ERROR: Header may not contain more than a single header, new line
    detected {"userId":1,"exception":"[object] (ErrorException(code: 0): Header may not contain 
    more than a single header, new line detected at /home/vagrant/myapp/vendor/symfony/http- 
    foundation/Response.php:341)

This error happens when debugbar is enabled and the following setting in debugbar.php is set to true:

    'add_ajax_timing' => true,

Please refer to the following where the issue is further documented: https://github.com/laravel/framework/issues/31602

**Comment by AegirLeet** [comment]
Does disabling the `db` collector help?

**Comment by barryvdh** [comment]
Any idea what the lines are in there? Not sure why a new line would be present.

**Comment by AegirLeet** [comment]
I'm thinking it might be due to a query containing newlines and https://github.com/barryvdh/laravel-debugbar/blob/42d5da5379a7860093f8e4032167e4cb5ebec180/src/DataCollector/QueryCollector.php#L144 using the query as the measurement label.
