### ISSUE TITLE
Debugbar Not Showing Because Blocked by CSP

### ISSUE THREAD

**Issue by PanjiNamjaElf** [barryvdh/laravel-debugbar#1016]
Hello..
How to put nonce on debugbar inline script to avoid blocked by secure header ?

I use this library [bepsvpt/secure-headers](https://github.com/bepsvpt/secure-headers)

**Comment by barryvdh** [comment]
Can you provide feedback on. #1013 and https://github.com/barryvdh/laravel-debugbar/issues/847 ?

**Comment by PanjiNamjaElf** [comment]
I have read that pull before..
and try to do composer update and remove & install debugbar again but when i see on debugbar vendor folder no "$cspNonce" parameter on JavascriptRenderer constructor..

i see if Travis Build CI Failed...
am i must edit the package manually to add the nonce based on that pull? 🤔

**Comment by barryvdh** [comment]
Upstream php-debugbar needs to be updated to. I want to make it configurable, see https://github.com/barryvdh/laravel-debugbar/issues/847#issuecomment-593864388

**Comment by PanjiNamjaElf** [comment]
Ok.. i will wait for next update...   😃

**Comment by jtallinger** [comment]
For anyone coming here and wondering if this is solved and how to make it work. I solved it by using a recent version of the package (>Sep 2023 / version >3.12.2) and by adding following to app/Providers/AppServiceProvider.php (Laravel 10):

```php
if ($this->app->isLocal()) {
    // Set CSP nonce for Laravel Debugbar during development
    if (class_exists(\Barryvdh\Debugbar\Facades\Debugbar::class) && app()->bound('debugbar')) {
        app('debugbar')->getJavascriptRenderer()->setCspNonce(csp_nonce());
    }
}
```

Finally no more CSP warnings during development. Thanks for an excellent package and thanks for the work to get this issue solved 😀 👍
