### ISSUE TITLE
RFC: Add the ability to exclude Connections by name or exclude queries that match specific patterns

### ISSUE THREAD

**Issue by simensen** [barryvdh/laravel-debugbar#1019]
For SQL logging systems that also happen to log to SQL, the logging itself tiggers infinite recursion. I've been able to limit that impact a bit by doing a dirty hack blocking the insert queries of those logs from being logged themselves. I've not been able to find a way to hide them from the Laravel debugbar, tho.

Had a suggestion to try using different DB connections, but that doesn't seem to have any impact on Laravel's debugbar.

Some ideas I've had involved either adding the ability to filter / exclude logging based on connection name. This would work if I were to log to the same database under a different connection name for the audit logging. Otherwise, if I had a way to filter queries that should or should not be logged, that could work, too.

Is there already a solution I could use to achieve my goals of excluding these audit logs from Laravel debugbar? If not, and if I wanted to add this functionality, what is the best way for me to move forward on this that would have the highest likelihood of getting accepted?

![image](https://user-images.githubusercontent.com/191200/79002308-cce04180-7b15-11ea-8932-d37e49e3ed73.png)

![image](https://user-images.githubusercontent.com/191200/79002323-d2d62280-7b15-11ea-92bb-4190e38920bb.png)

**Comment by barryvdh** [comment]
I don't think there is yet. You could try `withoutEvents()` perhaps? https://stackoverflow.com/questions/29407818/is-it-possible-to-temporarily-disable-event-in-laravel/51301753
