### ISSUE TITLE
"Class 'Barryvdh\Debugbar\Facade' not found" after update

### ISSUE THREAD

**Issue by mityukov** [barryvdh/laravel-debugbar#1025]
Hi, 

Could you advise on how to properly install Debugbar on local environment only, but not to get "Barryvdh\Debugbar\Facade" on the production?

Here's the issue:
1. The debugbar is in the  `require-dev` section of composer.json
2. The deployment script on production runs composer with `--no-dev` flag
3. As the result, I get Class 'Barryvdh\Debugbar\Facade' not found…

**Comment by mityukov** [comment]
As a workaround, I've moved `barryvdh/laravel-debugbar` to the `require` section.  As I understand it — it'w won't interfere in any way when the APP_DEBUG is false.

**Comment by barryvdh** [comment]
Are you using Composer 2? If so, update Laravel to the latest patch version.

**Comment by mityukov** [comment]
Composer version 1.8.4 2019-02-11 10:52:10

I think the issue is that I don't have two separate codebases: one for local and another one for production. So, when php meets this code:
```php
// config/app.php

    'aliases' => [
        // ... 
        'Debugbar' => Barryvdh\Debugbar\Facade::class,
```

.. or this:
```
// app/Services/Something.php

\Debugbar::anything(...)
```

, it will throw that error, in case if:
a) dependencies were compiled with `--no-dev` option (which is often on production)
AND
b) debugbar was installed with `--dev` flag.

There's simply no this package in 'vendor', nor any of its classes are registered in the autoload.

As a workaround, I've moved debugbar to "require" section (from "require-dev"). Although, your documentation suggests installing it with `--dev`, so, it might be helpful to add something on possible implications of this approach.

**Comment by ZermattChris** [comment]
Here I am struggling with the same issue... and yet nobody else seems to be getting stuck here.

Either my github deploy script fails (composer installing dependencies)
 or
Production grinds to a halt, because I can't reference Barryvdh\Debugbar\Facade (class not found).

Lots of old, outdated info out there -- as yet to find what's borked, which seems odd as I'm not doing anything out of the ordinary in my new/little Laravel project.

Works great in Dev mode! :-)

Would love to push messages to the Debugbar while developing and then have everything still work on production (no Debugbar).

**Comment by erikn69** [comment]
Did you try this
```php
debugbar()?->{DEBUGBAR_METHOD}('message')
```

**Comment by ZermattChris** [comment]
Thanks for the feedback!

I'm not nearly competent enough to start hacking the internals of something in the /vendor package.

This is what I've done -- seems simple enough (and works):
```
        if (App::environment('local')) {
            \Barryvdh\Debugbar\Facades\Debugbar::info('Debugbar message test xxx');
        }
```
I spent some hours trying every combo of install and config, that I could find online. Nothing seemed to really work -- just wanted a few dev messages :-)

Thanks again!
