### ISSUE TITLE
`local.ERROR: Debugbar exception: Undefined property: stdClass::$id`  on most routes

### ISSUE THREAD

**Issue by pxdnbluesoul** [barryvdh/laravel-debugbar#1032]
This is happening on just about all of my routes, debugbar won't display once I am logged in at all, and anything that involves a model being displayed in a view seems to be returning between 1-6 of these errors in STDERR.

The application is otherwise working normally.

Laravel 6.18.11, Laravel-Debugbar 3.3.2

**Comment by itepifanio** [comment]
Same error here, but in my case, it was published the debugbar config and the option db.explain was enabled as true when I change this error stopped

**Comment by ipontt** [comment]
Setting db.explain to false solved it for me as well.

**Comment by lamtranb** [comment]
Hello guys,
This issue is still present in 3.5.2, really I don't want to disable db.explain
