### ISSUE TITLE
Latest version is just TOO slow

### ISSUE THREAD

**Issue by snapey** [barryvdh/laravel-debugbar#1033]
I've been a big fan of Debugbar over the years, but this latest release has me turning it off all the time.  Its just too slow.  Running the Chrome performance monitoring tools shows loads of time being spent rendering the debugbar.

I've never really noticed the additional time in the previous version, but this new styling is just not worth it for me.

**Comment by barryvdh** [comment]
The styling shouldn't change much? Maybe you have some additional collectors running? Maybe disable a few to see if the problem lies there? Any collectors with high numbers?

**Comment by nkeena** [comment]
For me it was the `views` collector. I'm using it with livewire and have a lot of components that have to load. Having that collector active was significantly slowing things down

**Comment by MicroDreamIT** [comment]
@barryvdh I am running some big queries but your debugbar freezes the browser, if i make PDO to false then it become normal again.

**Comment by barryvdh** [comment]
big queries or many queries?

**Comment by barryvdh** [comment]
An alternative is Telescope with Telescope Toolbar: https://github.com/fruitcake/laravel-telescope-toolbar

**Comment by altwei** [comment]
I also have a problem with slow

/_debugbar/assets/stylesheets?v=1595294073
/_debugbar/assets/javascript?v=1595294073

Requests for the above two addresses are surprisingly slow, often taking a minute

I'm using WSL

**Comment by warmwhisky** [comment]
I've been getting this issue with the same files too. I only have 3 collectors on: Views, Session and Routes. I thought it was Apache and have been editing Apache configs for quite some time until I found this thread and the same issue
/_debugbar/assets/stylesheets
/_debugbar/assets/javascript

![Screenshot from 2020-11-29 18-06-13](https://user-images.githubusercontent.com/579186/100547198-12e94180-326e-11eb-9915-ed45a58115ef.png)

Seems to be the downloading part of the scripts that takes way too long. In the same request there is an 800kb file downloading in 28ms. Both debugbar files here are less than 350kb so something strange is going on.

**Comment by barryvdh** [comment]
I might look into publishing some of the files indeed.

**Comment by barryvdh** [comment]
Though normally the files are cached, with the de tools open they aren't always. Not sure why it's almost 10 seconds though.

**Comment by iKlsR** [comment]
Still having this problem. The javascript attracts a 2 second wait time to an empty page.

**Comment by barryvdh** [comment]
Maybe we could cache the result for slow filesystems

**Comment by StoneyEagle** [comment]
For running Laravel inside a docker container you could mount the storage folder inside a volume instead of your local file system.

**Comment by leettaylor** [comment]
If anyone is still struggling with a slow Debugbar due to the number of views loaded. I've added a PR (#1327) which allows you to exclude certain paths via a config.

Feel free to [use my fork](https://github.com/leettaylor/laravel-debugbar/tree/view-exclude) until it's (hopefully) merged:

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/leettaylor/laravel-debugbar.git"            
        }
    ],
    "require-dev": {
        "barryvdh/laravel-debugbar": "dev-view-exclude",
    }
}
