### ISSUE TITLE
What version is this reporting

### ISSUE THREAD

**Issue by mikeerickson** [barryvdh/laravel-debugbar#1034]
Hey @barryvdh 

Curious, what version is reported on the right side of the bar?

IN the bar, it is showing 7.3.8

![image](https://user-images.githubusercontent.com/183153/80870304-766cab80-8c5a-11ea-9f9e-1c90dee76fd1.png)

But artisan is reporting 

![image](https://user-images.githubusercontent.com/183153/80870344-b2a00c00-8c5a-11ea-8597-22589c77df1b.png)

**Comment by barryvdh** [comment]
Php 7.3.8

**Comment by mikeerickson** [comment]
Ahhhhh, sorry about that. I should of know that
