### ISSUE TITLE
DataCollector rendering issue

### ISSUE THREAD

**Issue by CedNet** [barryvdh/laravel-debugbar#1035]
When using a custom DataCollector for an API my app is consuming things render wrong just like a previous issue with ModelCollector. 

Actual code usage inside the class consuming the API:
```
self::$debug = app()->make('debugbar');
self::$debug->addCollector(new MessagesCollector('SugarCRM'));
$time_start = microtime(true);

// and later (
self::$debug->getCollector('SugarCRM')->addMessage($data, $method . ' - ' . $url.' ('.number_format(microtime(true) - $time_start, 2).'s)');
```

The end result is:
![image](https://user-images.githubusercontent.com/1974807/81148108-f0af6f80-8f7b-11ea-9ca7-0ee96fcdba8e.png)

The issue is the extra "labels" at the bottom. The per line rendering seems correct.

**Comment by barryvdh** [comment]
Yeah you're kind misusing the labels like this. Not sure what best option is, you could also use a differect collector (like the models collector currently)

**Comment by CedNet** [comment]
Yeah :) tried creating my own collector but each time I end up having to make my own widget template. It's too much work. Can't spend too much time on this. 

Closing this issue.
