### ISSUE TITLE
Refused to load the font 'data:application/font-woff;charset=utf-8;base6 ,____(character string)' because it violates the following Content Security Policy directive: "font-src 'self'

### ISSUE THREAD

**Issue by benzsos** [barryvdh/laravel-debugbar#1040]
When I run the page and look at the console tab. I found this error. 

<img width="717" alt="Screen Shot 2563-05-18 at 15 53 52" src="https://user-images.githubusercontent.com/16951630/82193672-e730ea80-991f-11ea-90ad-8ba4f6072083.png">

How to fix it ? Please give me a solution. Thank you

**Comment by AlexMalikov94** [comment]
The Content-Security-Policy meta-tag allows you to reduce the risk of XSS attacks by allowing you to define where resources can be loaded from, preventing browsers from loading data from any other locations. This makes it harder for an attacker to inject malicious code into your site.

<meta http-equiv="Content-Security-Policy" content="default-src 'self'">

**Comment by barryvdh** [comment]
Yeah see https://github.com/barryvdh/laravel-debugbar/pull/1013
Will need to look into that

**Comment by vanushwashere** [comment]
Any news on this ?
