### ISSUE TITLE
Unnecessary routing information is displayed by "artisan route:list" command.

### ISSUE THREAD

**Issue by kakisoft** [barryvdh/laravel-debugbar#1046]
I'm always helped by a great tool Laravel Debugbar.

But, I ran into a bit problem.
When I use the "php artisan route:list" command to display the routing information, I get the "_debugbar" information that I don't need.

The content is here.
![laravel-debug](https://user-images.githubusercontent.com/20323093/83641589-b5d74080-a5e8-11ea-9fc9-5dac1d3c2f30.png)

The routing information starting with "_debugbar" is I don't need it.
Is it possible to hide this information?

By the way, I tried to set  "APP_DEBUG=false" in the .env file and disabled the Laravel Debugbar, but it was still displayed.

<ENV>
Laravel Framework 6.18.13
barryvdh/laravel-debugbar - version: v3.3.3

**Comment by assoft** [comment]
Pretty annoying... Is there a way to **fix it**?

### Without Debugbar
![without-debugbar](https://user-images.githubusercontent.com/835239/86524348-32786b80-be82-11ea-9854-f4d34084cd58.png)

### With Debugbar
![with-debugbar](https://user-images.githubusercontent.com/835239/86524347-2f7d7b00-be82-11ea-92f3-3f64870a69ac.png)

**Comment by n1crack** [comment]
any updates on this ? same problem here.

**Comment by denkeel** [comment]
The command you need:
`php artisan route:list --except-path _debugbar,`

**Comment by kakisoft** [comment]
@denkeel 
Thank you for your reply.

I tried the command you told me.

However, it didn't work.
Here is the message appeared.

> The "--except-path" option does not exist.

Is this due to the version of Laravel?

I tried the following two versions and both got the same error message.

Laravel Framework 5.5.50
Laravel Framework 8.15.0

**Comment by denkeel** [comment]
@kakisoft Yes, the problem is the version of Laravel. This feature is actually brand new hah. It was released only in **Laravel 8.34** two month ago, so need to use this version or above

**Comment by kakisoft** [comment]
@denkeel 
Thank you for your great information!
Then It actually worked. Now i got routing detail without debugbar

Also, i wrote about it on my blog ,in Japanese though.
https://www.kakistamp.com/entry/2021/05/07/005940
