### ISSUE TITLE
Gate Tab: false marked as error

### ISSUE THREAD

**Issue by bomshteyn** [barryvdh/laravel-debugbar#1048]
When  using the gate tab:

Any ability check that returns `false` is marked as `error`. 
Is this by design? Shouldn't these be marked as `allowed` / `blocked` not as `success` / `error`.

Since `error` is used to denote actual errors in other tabs, it's a bit confusing seeing `error` for a case of gate returning `false`. 

<img width="1431" alt="Screen Shot 2020-06-07 at 2 31 30 PM" src="https://user-images.githubusercontent.com/4259699/83976984-a0556580-a8cb-11ea-93ba-b67f43ea63d4.png">

**Comment by bomshteyn** [comment]
Yes, still present

**Comment by hapidjus** [comment]
I could take a stab at this, if there is any interest.
