### ISSUE TITLE
laravel-debugbar + require.js => jQuery is not defined

### ISSUE THREAD

**Issue by dmitry-ivanov** [barryvdh/laravel-debugbar#105]
Hi there!

Are there any elegant solutions for `laravel-debugbar` + `require.js` usage?
Separate include (not via `require.js`) of `jquery` - helps, but this is dirty solution according to `require.js`...

Thank you!

**Comment by claar** [comment]
Same problem -- debugbar is not RequireJS/AMD compatible. In looking at the source code, I'm not sure yet what the easiest way would be to fix this :/

**Comment by claar** [comment]
My current workaround is to tell DebugBar not to inject its javascript:

```php
// Make Debugbar play nicely with requirejs -- tell it only to inject CSS, not JS
Debugbar::getJavascriptRenderer()->setIncludeVendors('css');
```

**Comment by barryvdh** [comment]
You can also set that in the config. Or use the excludeVendor option to just remove jquery.

**Comment by refear99** [comment]
@barryvdh I have the same problem. 
any solution now ?

**Comment by barryvdh** [comment]
Started working on that here: https://github.com/maximebf/php-debugbar/commit/c3268ca12248485a56d8fadf6489a277ef40d2e9

Any thoughts from people with requirejs experience?
