### ISSUE TITLE
Model names cutoff

### ISSUE THREAD

**Issue by liran-co** [barryvdh/laravel-debugbar#1057]
Longer models paths are cut off and there's no way to resize the column:

<img width="575" alt="CleanShot 2020-07-13 at 11 33 54@2x" src="https://user-images.githubusercontent.com/5923787/87323495-da360f00-c4fc-11ea-9e76-c74edd43e9ba.png">

**Comment by azrahn** [comment]
Same problem here. Did you find any solution?

**Comment by barryvdh** [comment]
This should be fixed with the latest release (yesterday)

**Comment by azrahn** [comment]
Hi Barry,
I can confirm that after updating to the latest version it is fixed for me.
Thank you.
