### ISSUE TITLE
Feature idea: Collection metrics

### ISSUE THREAD

**Issue by SpiritSaint** [barryvdh/laravel-debugbar#1058]
> Sometimes you would solve code problems using collections. 

Sql Metrics are helpful to track performance issues, what about collections? 

Metrics based on collection iterations would be a nice feature.

I dont know if the package actually implements this feature,
I would help to make a PR if some one can guide the feature development.

**Comment by barryvdh** [comment]
Not sure how we would tap into those collections, there are not really events for that right?

**Comment by demency** [comment]
Thanks @barryvdh for your fast response,
I really appreciate your code.

You're right!
There are no events here, just anonymous functions passed as callbacks
That's CollectionCollector would be hard tricked to implement

How do you usually implement a collector when you don't have events?
