### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by Easy987** [barryvdh/laravel-debugbar#1059]
Hello,
I have tried installing it under Laravel 7.2 and it doesnt show up.
The package will support 7.2 in the future?

I want to check query execution times and memory usage, there is a package which i can use for this?

Thanks!

**Comment by StDeniks** [comment]
+1, I have same problem:
<pre>composer require barryvdh/laravel-debugbar --dev
Using version ^3.3 for barryvdh/laravel-debugbar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package:  [32mbarryvdh/laravel-debugbar [39m
Discovered Package:  [32mfacade/ignition [39m
Discovered Package:  [32mfideloper/proxy [39m
Discovered Package:  [32mfruitcake/laravel-cors [39m
Discovered Package:  [32mlaravel/tinker [39m
Discovered Package:  [32mnesbot/carbon [39m
Discovered Package:  [32mnunomaduro/collision [39m
 [32mPackage manifest generated successfully. [39m
48 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

>git status -s
 M composer.json
 M composer.lock

>git diff composer.json
error: cannot spawn less: No such file or directory
diff --git a/composer.json b/composer.json
index efa91c7..e357f13 100644
--- a/composer.json
+++ b/composer.json
@@ -16,6 +16,7 @@
         "laravel/tinker": "^2.0"
     },
     "require-dev": {
+        "barryvdh/laravel-debugbar": "^3.3",
         "facade/ignition": "^2.0",
         "fzaninotto/faker": "^1.9.1",
         "mockery/mockery": "^1.3.1",
</pre>
How to enable auto-discower?

**Comment by Easy987** [comment]
My problem was fixed, i didnt have a body tag

**Comment by Sohail-Ansari** [comment]
@Easy987 @StDeniks 

_GOTO:_    config/debugbar.php

_TURN THIS:_

**'enabled' => env('DEBUGBAR_ENABLED',false),**

_INTO THIS_ 

**'enabled' => env('DEBUGBAR_ENABLED',null),**

Its in line 15 of the file in my case. 
**For Laravel 7+**
