### ISSUE TITLE
Lazy load debugbar / information

### ISSUE THREAD

**Issue by garygreen** [barryvdh/laravel-debugbar#1075]
At the moment all information is rendered, such as syntax highlighting, trace stacks, sql queries, etc even if you haven't opened the debugbar. This massively slows down page render even if you don't intend to investigate debugbar for that request.

It would be great if debugbar was lazily loaded - so it only renders each tab/section once opened. That way debugbar can just render the navigation bar - minimal HTML and javascript executation and won't slow page down.

**Always render navigation bar**
![image](https://user-images.githubusercontent.com/1702638/89322033-96f23a80-d67b-11ea-8dcf-b2453d77f5ed.png)

**Lazy load tab/section once clicked on**
![image](https://user-images.githubusercontent.com/1702638/89321857-5b577080-d67b-11ea-98e2-5dd1af98cfbf.png)

**Comment by SuperDJ** [comment]
It would already be faster if it wasn't relying on jQuery.
