### ISSUE TITLE
what booting and application means in time line

### ISSUE THREAD

**Issue by farshadff** [barryvdh/laravel-debugbar#1077]
hi , i have an application which i am using debug bar on it and the booting time of apllication is close to 1 sec . and on each api and request it makes load so heavy like 1 sec or more i wanted to know what each of them means because my application time is so low but booting is so high thanks

**Comment by alirzaj** [comment]
this is not an issue of package! you had to ask this in a forum discussion

booting is the process of preparing all the services that laravel provides 

you can use php artisan optimize in laravel 7 to do some caching and improve this time

p.s if you have heavy service providers in your own do sth about them

**Comment by barryvdh** [comment]
Booting is the time from the request start until the debugbar is booted in the booted() section of the service providers. Everything before that is the framework itself + service providers registering (and perhaps some booting, depending on the order)

**Comment by farshadff** [comment]
@barryvdh thanks for the answer

**Comment by bilogic** [comment]
![image](https://github.com/barryvdh/laravel-debugbar/assets/946010/4d51aaeb-b16f-41cf-a604-69c0d8fb8759)

There is a fair amount of empty space below, why not have a legend?

**Comment by str** [comment]
It would be awesome to have more details for the "booting part", to unfold it and to better understand why it is taking so long.

**Comment by parallels999** [comment]
@str make it possible, feel free to open a PR
