### ISSUE TITLE
Laravel-debugbar not work in laravel7

### ISSUE THREAD

**Issue by netwons** [barryvdh/laravel-debugbar#1078]
Laravel-debugbar not work in laravel7

**Comment by RomanTruhanov** [comment]
the plugin works just checked if you configured everything correctly try to add it in the HTML request after index.php=debugbar the plugin should be activated

**Comment by krisnaw** [comment]
Tried to install it in both Laravel v6 and v7 on local Valet, but keep getting ` Allowed memory size of 1610612736 bytes exhausted`. Any tips?

**Comment by barryvdh** [comment]
Increase your composer memory limit.

**Comment by jfrosorio** [comment]
I had the same problem myself. This should do the trick:

**Comment by netwons** [comment]
> This should do the trick:
> 
> ```
> COMPOSER_MEMORY_LIMIT=-1 composer require barryvdh/laravel-debugbar --dev
> ```

I got the answer

**Comment by geoff-maddock** [comment]
I'm able to install the debug bar in laravel 7, but the ui is broken.  Any additional tips after installing?

**Comment by netwons** [comment]
okey

**Comment by awadheshmeshram** [comment]
Hi  @barryvdh , I am not able to install this package in laravel 5.8 , still getting the below errors.
[https://paste.pics/B7JQ6](url)
[https://paste.pics/B7JQD](url)
