### ISSUE TITLE
Install on PHP 7.4

### ISSUE THREAD

**Issue by brandy** [barryvdh/laravel-debugbar#1081]
Is it possible to install this or a previous version o on PHP 7.4.x? 

My server only has PHP7.4 right now, and I don't want to upgrade to 8. When running composer install i get this:
```
This package requires php ^8.0 but your PHP version (7.4.6) does not satisfy that requirement.
```

**Comment by azrahn** [comment]
Strange, the required version for the latest version of debugbar is php 7.0
from the composer.json
"php": ">=7.0",

**Comment by iksaku** [comment]
Please ensure that in your `composer.json` file you have the following:
```json
{
    "minimum-stability": "dev",
    "prefer-stable": true,
}
```

Then, install debugbar using:
`composer install --dev barryvdh/laravel-debugbar:^3.4`

**Comment by RahulDey12** [comment]
I don't think this error for debugbar
