### ISSUE TITLE
Unreadable yellow on black with white and yellow text 

### ISSUE THREAD

**Issue by mbalandis** [barryvdh/laravel-debugbar#1083]
Dark theme seems to have an issue with readability or am I missing something?

See example: https://share.getcloudapp.com/z8uZZgwA

**Comment by barryvdh** [comment]
Are you on the latest version?

**Comment by mbalandis** [comment]
> Are you on the latest version?

Yes v3.4.1

**Comment by ekvedaras** [comment]
That is some serious yellow :) Which browser do you use? Could you inspect it and show which CSS is applying that color?
