### ISSUE TITLE
Issues in theme values

### ISSUE THREAD

**Issue by Algeneralo** [barryvdh/laravel-debugbar#1089]
Changing the value of `theme` in the config file doesn't change it on the views.
I'm using a dark mode for the browser, and I want to change the debugbar to the light theme not dark one but it I am not able to do that.
Note: config are cleared and it's not cached.  

Version: v3.4.1
Browser: opera

**Comment by barryvdh** [comment]
Did you try a hard-refresh of your browser assets?

**Comment by barryvdh** [comment]
I added the theme to the asset url in https://github.com/barryvdh/laravel-debugbar/commit/fefd8cda640575270c23b0fe75dcb4e4b6eec7b9 which should make the switching of assets instant.

**Comment by Algeneralo** [comment]
@barryvdh thanks 
works after cleaning the cache
