### ISSUE TITLE
0 templates were rendered

### ISSUE THREAD

**Issue by mankowitz** [barryvdh/laravel-debugbar#1093]
When using debugbar, the Views tab has a badge of zero and has the message "0 templates were rendered".  This is new behavior for this route and at least one view is being rendered. What other information would help debug?

php 7.4.9
laravel 7.25.0
debugbar 3.4.1

**Comment by ujstha** [comment]
![image](https://user-images.githubusercontent.com/26536607/110985387-144dfe00-8375-11eb-9b53-9139a4bff2b0.png)

**Comment by zappaciato** [comment]
I have the same problem. 
PHP Version: 7.4.29 Laravel Version = 5.7.29
It renders view templates but just for a split of a second

**Comment by Dach0** [comment]
I have that problem too.

**Comment by Dach0** [comment]
Ohhh...I've found a solution (at least for me) :) It's actually pretty cool. If you have some ajax calls on the view, as I did, they'll be registered in debugbar. So you have to switch in the select menu between requests. So here:
![image](https://user-images.githubusercontent.com/40193265/194526618-cde67cba-eb86-4531-a5e5-39a4ab3a27c9.png)

and voila:
![image](https://user-images.githubusercontent.com/40193265/194527254-0eed1f25-19b2-4040-bca7-faf307f7c625.png)
