### ISSUE TITLE
Future Feature Request - Memory Usage Detailed Information

### ISSUE THREAD

**Issue by lcallif** [barryvdh/laravel-debugbar#1099]
Would it be possible to be able to see what is taking the memory usage (and how much) ?   Specifically, what memory Laravel is taking vs the App.  And possibly the break down for the App's memory usage.  

I was able to determine Laravel's memory usage by putting ' return "hello"; ' at the beginning of the Controller.  This helped a lot to see if there was a memory issue I needed to deal with.  Fortunately, the memory usage was a vast major of the memory usage, which left a reasonable amount of memory usage for the App.   It still would be nice to see what is using the rest...

Just in case it helps:
   Mac: 10.15.6
   Laravel: 7.26.1

Thank you!!!

**Comment by barryvdh** [comment]
Hmm so get the peak memory at boot or something?
