### ISSUE TITLE
Debugbar send htpp requests over http while site uses https

### ISSUE THREAD

**Issue by soncemvo** [barryvdh/laravel-debugbar#1100]
If your site uses Cloudflare with "Flexible" https debugbar cant detect https and try to send request via http

`javascript?v=1598771297:2 Mixed Content: The page at 'https://***/api/checkPhone' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://***/_debugbar/cache/checkPhone_ca5'. This request has been blocked; the content must be served over HTTPS.`

**Comment by barryvdh** [comment]
This is probably a wrong configuration of TrustedProxies because the urls are generated with the framework.

**Comment by soncemvo** [comment]
I have set cloudflare ip to TrustedProxies  - no result, same error

**Comment by soncemvo** [comment]
ok, the solution:

if you use flex SSL on cloudflare, make sure to set http(not httpS) proto in url of config/app.php
