### ISSUE TITLE
Not showed for homepage? 

### ISSUE THREAD

**Issue by sazareks** [barryvdh/laravel-debugbar#1106]
I have rout Route::get('/', 'HomeController@home')->name('home'); but debugbar not showed panel for home page.

src/LaravelDebugbar.php method isDebugbarRequest() for homepage return false but why? maybe is a bug?

**Comment by jud3v** [comment]
Hello did you find the problem, community ( me too ) will love fix the bug with your solution if you can share it thank you <3

**Comment by sazareks** [comment]
Hi. the problem was solved by updating laravel 8 as there was apparently a breakdown + installation is mandatory via composer requre --dev
