### ISSUE TITLE
TwigProfileCollector version

### ISSUE THREAD

**Issue by pataar** [barryvdh/laravel-debugbar#1108]
Hi!

It seems that the TwigProfileCollector depends on old dated functions of Twig 1.x. 
It's pretty easy to upgrade these and make them compatible with Twig 2.x / 3.x.

Would a pull request be appreciated? If so, I'd gladly make one.

Alternatively a Twig3ProfileCollector could be made. Just as it has been done with Propel.
See:
![image](https://user-images.githubusercontent.com/3403851/93908657-325c6f00-fcff-11ea-9f9c-df9a72214584.png)

**Comment by pataar** [comment]
@barryvdh What do you suggest?

**Comment by barryvdh** [comment]
For Laravel, I actually never use the Twig collector. Does is have any benefit over the regular view collector?

**Comment by pataar** [comment]
We use a Lumen project with Twig, so the regular view collector doesn't work for us. But in the current state it's unusable because of the Twig 1.x usage.
