### ISSUE TITLE
Call to undefined function xdebug_is_enabled

### ISSUE THREAD

**Issue by mshamaseen** [barryvdh/laravel-debugbar#1136]
according to [xdebug](https://xdebug.org/docs/upgrade_guide#Changes-to-Functions) `xdebug_is_enabled` function has been removed.

and now it is throwing errors telling that 

> Call to undefined function xdebug_is_enabled()

whenever I run an API call.

suggestions?

**Comment by kkamara** [comment]
Did you manage to resolve?

**Comment by tdtm** [comment]
The function exists in xdebug 2, but has been removed in xdebug 2. The solution is to PR a change to either:
- remove the call to xdebug_is_enabled; or
- do `function_exists('xdebug_is_enabled') && xdebug_is_enabled()`; or
- declare dependency on xdebug2 specifically.
