### ISSUE TITLE
Debugbar lose messages after refresh - requesting feature to persist/let messages

### ISSUE THREAD

**Issue by terremoth** [barryvdh/laravel-debugbar#1145]
I am in a scenario like this:
- the user enters in the product page, it pays for the product, and WHEN it is processing, I am sending the messages via Debugbar::info(...), but after finish the gateway payment process, it refreshes the page.   
Só I would like to persist this messages there, inside debugbar even if the page is refreshed. Maybe a button to remove the text when we want, or just persist these infos in a variable time, like only for 1 or 2 minutes, just to see what is happening.

(ps: I can't stop or change the refresh page process - it will be refreshed in the end and I don't want to lose the messages)

**Comment by barryvdh** [comment]
You can use the browse option to view older requests, on the right side of the debugbar.
