### ISSUE TITLE
Question: Why no PHP types instead of PHPdoc?

### ISSUE THREAD

**Issue by FunctionDJ** [barryvdh/laravel-debugbar#1147]
I've browsed through a few files and saw that PHP data types are barely used.
The `composer.json` says that the minimum required PHP version is 7.2, which supports data types.
Why is this library using PHPdoc primarily instead? Not a critique, just curious.

**Comment by barryvdh** [comment]
Because it's built 5 years ago and back then it was PHP 5.5 or something

**Comment by FunctionDJ** [comment]
oh okay. i guess it would be too much work to update everything with types.
