### ISSUE TITLE
Load routes in ServiceProvider

### ISSUE THREAD

**Issue by netsnatch** [barryvdh/laravel-debugbar#1149]
https://github.com/barryvdh/laravel-debugbar/blob/cae0a8d1cb89b0f0522f65e60465e16d738e069b/src/ServiceProvider.php#L33

`loadRoutesFrom()` should be in `boot()` method instead of `register` (https://laravel.com/docs/8.x/packages#routes)

**Comment by rust-7** [comment]
@netsnatch is this causing a "Target class [App\Http\Barryvdh\Debugbar\ServiceProvider] does not exist." error ? because thats what I'm getting.

**Comment by netsnatch** [comment]
@rust-7 No, it does not cause an error.

In your case, the problem is in the namespace - **App\Http**\Barryvdh\Debugbar\ServiceProvider

**Comment by rust-7** [comment]
> @rust-7 No, it does not cause an error.
> 
> In your case, the problem is in the namespace - **App\Http**\Barryvdh\Debugbar\ServiceProvider

Where do I have to do the modification ?

**Comment by netsnatch** [comment]
Check config/app.php file. And remove App\Http part from class name.
But maybe it's not your case.

**Comment by rust-7** [comment]
> Check config/app.php file. And remove App\Http part from class name.
> But maybe it's not your case.

Well, the `App\Http` is not mentioned in the documentation. It just says `\Barryvdh\Debugbar\ServiceProvider::class,` But I tried with and without, nothing to do...

**Comment by netsnatch** [comment]
It was mentioned in error message. _Target class [App\Http\Barryvdh\Debugbar\ServiceProvider] does not exist_
So the problem is not in config/app.php

App\Http\Barryvdh looks strange.
