### ISSUE TITLE
Not loading on Rest API calls that return Json.

### ISSUE THREAD

**Issue by andrewex** [barryvdh/laravel-debugbar#1151]
I have a brand new Laravel 8 install with Laravel Debugbar installed. Everything loads correctly when I load a web page. The problem is when I run API endpoints that return JSON. In previous versions, I can run an API endpoint that returns JSON, and it injects a **debug** property with all the app/db profiling. I am unable to get the debug property to load with the response.

**Comment by derryberni** [comment]
I got same issue

**Comment by vlauciani** [comment]
+1

**Comment by mokhosh** [comment]
same. this is what i'm getting:
```json
// what i actually returned
{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}
// what debugbar added
<link rel='stylesheet' type='text/css' property='stylesheet' href=''>
<script type='text/javascript' src=''></script>
<script type="text/javascript">jQuery.noConflict(true);</script>
<script></script><style></style>
<script type="text/javascript"></script>
```

**Comment by vlauciani** [comment]
+1

**Comment by mokhosh** [comment]
ok then +1
