### ISSUE TITLE
Same number of queries and models on every page

### ISSUE THREAD

**Issue by Crouxie** [barryvdh/laravel-debugbar#1156]
Hello, 

can u please help me out? Debugbar stopped capturing queries and models. It is showing only 4 queries from spatie package when loading permissions and roles. It seems like everything else is ignored.

- `laravel version: 7.28.4`
- `debugbar version: 3.5.1 (same issue on latest 3.5.2)`

Thanks for help!

**Comment by SuganyaUitoux** [comment]
I am also facing the same issue. Can someone help me with this.

- Laravel - 5.8
- Debugger - 3.4
