### ISSUE TITLE
debugbar not showing

### ISSUE THREAD

**Issue by jigsaw075** [barryvdh/laravel-debugbar#1159]
hello, i have a project with laravel version 7.28. i run `composer require barryvdh/laravel-debugbar --dev`, after that i added `Barryvdh\Debugbar\ServiceProvider::class,` to app/config.php. then i run `php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"`. even though APP_DEBUG in .env is true, debugbar not showing. where did i make mistake, any ideas?

**Comment by jigsaw075** [comment]
i added `'Debugbar' => Barryvdh\Debugbar\Facade::class,` to facades too

**Comment by golaod** [comment]
Do you use PDO as storage? Cause it doesn't work for me either when migrations were not fired and they won't be cause package's service provider doesn't register any migrations sadly

**Comment by jigsaw075** [comment]
i was lack of planning so i'm not be able to migrate tables. i just manually edit tables. i'm assuming my problem was about Laravel Speed Page. because somehow the bar came back when i remove that package
