### ISSUE TITLE
Enable debugbar at runtime

### ISSUE THREAD

**Issue by G4Zz0L1** [barryvdh/laravel-debugbar#1162]
I'm on Laravel 8.33.1 with debugbar on 3.5.2.

I've set `DEBUGBAR_ENABLED` and/or `enabled` in the config to `false`.
Then with a middleware added at the end of `$middlewareGroups` in the `web` group, I'll check for the condition to show the debugbar:

```php
public function handle(Request $request, Closure $next)
{
    if (Auth::check()) {
        debugbar()->enable();
    }

    return $next($request);
}
```

The debugbar doesn't show, and it's not present on the page source with the inspector.
If I do `dump(debugbar()->isEnabled())` right after the enable, it returns `true`.
If I set `DEBUGBAR_ENABLED` to true, everything's working fine.

I've poked around with the service provider and middleware of debugbar, it seems that if it's disabled when it reaches the service provider, it can't be injected again, but I don't understand why.

Any idea on this?

EDIT: same thing with the error pages: I can't disable the debugbar globally and re-enable it on middleware, so it shows on every error page. I'm starting to think that there's gotta be a better way to manage this, if I want to leave the debugbar only for a single user on normal routed pages.

**Comment by G4Zz0L1** [comment]
Anyone on this? I can't be the only one in this setup. There are other issues similar to this one, but they're inconcludent.

**Comment by G4Zz0L1** [comment]
So, I guess I'll have to stick with that unwanted behaviour?

**Comment by G4Zz0L1** [comment]
Okay, I've been tinkering with this like **a lot**, and I've discovered some stuff.
LaravelDebugbar class enable/disable methods are not what I thought (unlike what it says in the documentation at this link https://github.com/barryvdh/laravel-debugbar#enablingdisabling-on-run-time).
AFAIK its not possible to turn on or off the debugbar at runtime, due to the fact that if it is enabled from the beginning it is already injected into the response and cannot be removed, while if it is disabled from the beginning it cannot be reinjected (also because the css and js routes checks the enabled status with another middleware).
In light of this (for my current knowledge of Laravel) I think it's not possible to get what I want, so I think it is appropriate to give up, unless someone who understands this more than me can find any feasible solution, without touching the core of this package.
The only positive thing about this situation is that I have learned a lot of things about laravel internals (ServiceProvider and Middleware, specifically).

**Comment by matiazar** [comment]
> ```
> $response = $next($request);
> ```

doesnt work for me.. it now shows the debugbar. but all info is null or zero

**Comment by matiazar** [comment]
I have made it.. its so easy

you only need to put this code on your middleware
    if (Auth::check()) {
        debugbar()->enable();
    }

   $response = $next($request);

and in Kernel.php
insert \Barryvdh\Debugbar\Middleware\InjectDebugbar::class, after your middleware


    protected $middlewareGroups = [
    'web' => [
               ...
                \App\Http\Middleware\DebugbarEnabler::class, // my middleware
                **\Barryvdh\Debugbar\Middleware\InjectDebugbar::class,**
            ],

**Comment by sngrl** [comment]
> I have made it.. its so easy

But debugbar service routes (JS, CSS, etc. - in this file: `debugbar-routes.php`) tries to inject at the first call of the InjectDebugbar, and using DebugbarEnabled middleware, which abort request with 404 code when debugbar is not enabled (and it's not enabled at the first InjectDebugbar call)

**Comment by sngrl** [comment]
@barryvdh we need your support for old and still actual problem

**Comment by sngrl** [comment]
My solution:

1. Install Debugbar 
2. Enable Debugbar by default via `DEBUGBAR_ENABLED=true` directive at .env file
3. Create custom middleware, for example app/Http/Middleware/UseAuth.php, and provide your specific logic for Debugbar disabling:
```
<?php

namespace App\Http\Middleware;

class UseAuth
{
    public function handle($request, Closure $next)
    {
        if (!($user = \Auth::user()) || !$user->isSuperAdmin()) {
            debugbar()->disable();
        }

        return $next($request);
    }
}
```
4. Add your middleware to file app/Http/Kernel.php:
```
    protected $middlewareGroups = [
        'web' => [
            //...........................
            \App\Http\Middleware\UseAuth::class,
        ],
```
5. Disable Debugbar on error pages (for example 404 Page not found or 500 Server error) at app/Exceptions/Handler.php:
```
    public function register()
    {
        debugbar()->disable();

        $this->reportable(function (Throwable $e) {
            //
        });
    }
```

**Comment by G4Zz0L1** [comment]
> But I would like to be able to implement the same, but without the Debugbar enabled by default

I've fixed it with this, it works flawlessly
https://github.com/barryvdh/laravel-debugbar/issues/1162#issuecomment-817179179

**Comment by barryvdh** [comment]
I kinda understand the want for this, but I'm really not keen on opening debugbar on any live environment. I don't want to accidentally expose something.

**Comment by laurenceHR** [comment]
Hi, I made a custom package for ovveride ServiceProvider and handle enable-disable on demand.
https://github.com/jaguarsoft-vendor/laravel-debugbar
