### ISSUE TITLE
Issue with Octane

### ISSUE THREAD

**Issue by simpledev** [barryvdh/laravel-debugbar#1166]
It appears that there is a query time measurement issue with Octane. The result is displayed in seconds by launching "php artisan octane: start --watch" while by starting with "php artisan serve" the result is displayed in milliseconds.

![Capture d’écran 2021-04-06 à 17 38 05](https://user-images.githubusercontent.com/2912268/113738610-5a417c00-96ff-11eb-85f3-105dcbe0ede7.png)

![Capture d’écran 2021-04-06 à 17 37 02](https://user-images.githubusercontent.com/2912268/113738699-67f70180-96ff-11eb-98aa-424d15ecc187.png)

**Comment by barryvdh** [comment]
Just the first start?

**Comment by barryvdh** [comment]
Is that with Swoole or Roadrunner? Roadrunner seems fine for me:
![image](https://user-images.githubusercontent.com/973269/113759707-aeeff180-9715-11eb-899a-de59fd314a82.png)

I'm guessing the request time isn't updated or something.

**Comment by barryvdh** [comment]
I would guess the LARAVEL_START value isn't updated, so maybe we should ignore that in case of Swoole.

**Comment by simpledev** [comment]
Yes, with Roadrunner it seems fine for me too.

**Comment by barryvdh** [comment]
Does Laravel Telescope show the time correctly?

**Comment by simpledev** [comment]
Yes the duration is in milliseconds.
