### ISSUE TITLE
Stop showing but not disable

### ISSUE THREAD

**Issue by tomadmiraal** [barryvdh/laravel-debugbar#1171]
Hi,
I’m wondering if its posible to stop showing the debugbar but not disable it?

case:
We have caching enabled and the bar should not be displayed in the cached page. However, I want to know what happend. I can do that by using the debugbar history on a route with the debugbar display option enabled.

Is this posible? And how?

**Comment by pkruczynski** [comment]
@tomadmiraal:
This is my own solution. Regardless of the configuration, I can force the bar to be shown by appending to the URL: `?debug=1`
In this example, limited to local address only, but you can omit it 

config/debugbar.php:

```
    'enabled'   => value(function () {
                    if (isset($_REQUEST['debug']) && ! isPublicIP())
                        return filter_var($_REQUEST['debug'], FILTER_VALIDATE_BOOLEAN);
                    return env('DEBUGBAR_ENABLED', env('APP_DEBUG', false)) && ! isPublicIP();
                }),
```
