### ISSUE TITLE
Octane: Target class [config] does not exist.

### ISSUE THREAD

**Issue by captenmasin** [barryvdh/laravel-debugbar#1174]
Debugbar version: 3.5.5
Laravel version: 8.40.0
Octane version: 0.4.0

I'm not too well-versed in how Octane is supposed to handle app and config methods, but it seems to be erroring when using `$this->app['config']` ?

<img width="1214" alt="Screenshot 2021-04-28 at 11 28 50 pm" src="https://user-images.githubusercontent.com/25454872/116480668-a8b6e600-a879-11eb-907e-7aea57969f66.png">

This is just a plain page with Debugbar and Octane enabled, nothing else funky going on

**Comment by zhuchunshu** [comment]
I also encountered the same problem

**Comment by barryvdh** [comment]
Can you test the dev version? https://github.com/barryvdh/laravel-debugbar/pull/1179

**Comment by ajnorman-dev** [comment]
The dev version fixes the DB collector

**Comment by ImJustToNy** [comment]
I also confirm that #1179 fixes the issue.

**Comment by ImJustToNy** [comment]
I also confirm that thar PR fixes the problem.
