### ISSUE TITLE
v3.5.6 Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by linaspasv** [barryvdh/laravel-debugbar#1182]
After upgrading from 3.5.5 to 3.5.6 - DB statements are not showing for AJAX calls anymore, resulting in ``Cannot read property 'length' of undefined`` JS error in the console.

![image](https://user-images.githubusercontent.com/1407067/118121994-e9c30480-b3fa-11eb-8cdc-4e4eea897875.png)

**Comment by ivqonsanada** [comment]
Have same problem here after updating. The view tab say: `undefined templates were rendered`
![Screenshot from 2021-05-14 00-52-01](https://user-images.githubusercontent.com/36329890/118165605-abefcb80-b44e-11eb-919a-5f19c8d1d108.png)

**Comment by socieboy** [comment]
@linaspasv Are you using Inertia? i got the same problem, i don't know if is related of inertiajs?

**Comment by linaspasv** [comment]
> @linaspasv Are you using Inertia? i got the same problem, i don't know if is related of inertiajs?

No I am not using inertia. It is just a simple jquery post request with html response.

**Comment by bakerkretzmar** [comment]
I'm getting this too, but in Firefox so the error message is `data.statements is undefined`. Confirmed it appears on v3.5.6, I'm using Inertia but it doesn't seem to be related.

**Comment by barryvdh** [comment]
Reverted with https://github.com/barryvdh/laravel-debugbar/pull/1183
Will tag a new release
