### ISSUE TITLE
Query backtrace results always limited to 5

### ISSUE THREAD

**Issue by amadeann** [barryvdh/laravel-debugbar#1186]
In the "Queries" tab, when I expand a given query, in the "Metadata" section, the backtrace is always limited to 5 results per query.

I tried setting `debug_backtrace_limit` config value to different values (e.g. `50` or `0`), but it has no effect. When I add some paths that I see in the backtrace to `backtrace_exclude_paths` setting, new paths in the backtrace show up, but they are always limited to 5. I also deleted the browser cache.

I am using laravel-debugbar `v3.5.7` and Laravel `v8.42.1`.

Does anyone know how to make the debugbar show unlimited backtrace for queries?

**Comment by henriquecm** [comment]
I had the same problem, so I gave a look at the source.
The debug_backtrace_limit works, but after that the result is always sliced for the 5 first results.
I don't know if that is intended or a oversight.

https://github.com/barryvdh/laravel-debugbar/blob/f6f0f895a33cac801286a74355d146bb5384a5da/src/DataCollector/QueryCollector.php#L164

**Comment by AntonCooper** [comment]
+1 for getting this fixed

**Comment by lex0r** [comment]
+1.
I see little point in offering a backtrace limit setting (with a default value of 50) which effectively results in only 5 lines. It seems to be a compromise as showing 50 items might bee too overwhelming. However a new settings is needed that tells how many lines should be displayed.

**Comment by kleninmaxim** [comment]
+1
Let's buid it as option

**Comment by jebbyk** [comment]
+1

**Comment by Nutickets** [comment]
+1

**Comment by erikn69** [comment]
Try #1541
