### ISSUE TITLE
Error when install debugbar

### ISSUE THREAD

**Issue by aledevil** [barryvdh/laravel-debugbar#1188]
Hello there,
i'm trying to install debugbar, but got always this error.

`C:\xampp\htdocs\XXXXX>composer require illuminate/routing
Warning: This development build of Composer is over 60 days old. It is recommended to update it by running "C:\Users\XXXXX\AppData\Local\ComposerSetup\bin\composer.phar self-update" to get the latest version.
Using version ^7.30 for illuminate/routing
./composer.json has been updated
Running composer update illuminate/routing
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires illuminate/routing ^7.30, found illuminate/routing[v7.30.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

This is my system info:
Laravel Framework 5.8.38

**Comment by OlivierHILDENBRAND** [comment]
Hello, i think u just need to update composer with "composer self-update" before to try "composer require barryvdh/laravel-debugbar --dev".

**Comment by HughMartinJFS** [comment]
@OlivierHILDENBRAND I ran into the same issue as @aledevil but running composer self-update didn't fix it - still got the same issue, lol - been trying to get this working for 3 days now XD. I'm running Laravel 5.7

**Comment by aledevil** [comment]
issue still open, i've tried the @OlivierHILDENBRAND solution, but not working
