### ISSUE TITLE
Version 3.6 broken when db explain enabled

### ISSUE THREAD

**Issue by jason-nabooki** [barryvdh/laravel-debugbar#1191]
PR https://github.com/barryvdh/laravel-debugbar/pull/1190 introduced a bug causing the debugbar to break and not load if DB explain is enabled.

It's trying to read from a 'duration' property on $statements which does exist for explain items.

@denis-chmel 

**Steps to replicate**
Set options.db.explain.enabled = true in debugbar config.

**Logs**
[2021-06-02 04:01:15] local.ERROR: Debugbar exception: Undefined index: duration

**Comment by lrnz-nabooki** [comment]
We've noticed that the new entries (explain) pushed to that array do not contains that key: "duration". I can see two potential solutions for that issue.

1. Skip the iteration where the "duration" key is not set;
2. Skip the iteration when the "$statement['key'] === 'explain";

Please guys, let us know if any of the above solutions are acceptable and we're happy to open a PR.

**Comment by barryvdh** [comment]
I think solution 1 is good. Can you pr that?

**Comment by lrnz-nabooki** [comment]
Hey @barryvdh . Thanks for the reply.

I've just created a PR to fix that: https://github.com/barryvdh/laravel-debugbar/pull/1192

Cheers.

**Comment by jason-nabooki** [comment]
Thanks guys. 3.6.1 resolves the issue.
