### ISSUE TITLE
Request watcher

### ISSUE THREAD

**Issue by barryvdh** [barryvdh/laravel-debugbar#1198]
So basically with the new Http Events, we can do something similar to https://github.com/laravel/telescope/pull/1073
Maybe we can combine it with https://github.com/hannesvdvreken/guzzle-debugbar to provide a base request logger and just a method to wrap Guzzle Clients manually (`eg debugbar()->trackRequests($client)`)

**Comment by barryvdh** [comment]
I think we can use the events from the HttpClient. For Guzzle, those can be used with this handler: https://gist.github.com/barryvdh/4940a43268345c2bd9f3b4b58b01e374

**Comment by barryvdh** [comment]
It's probably cleanest to extend the Guzzle client to use the Laravel events (as the example above does) and then just hook into those requests. That would work for the HttpClient from Laravel out of the box, and doesn't require Debugbar specific handlers for Guzzle.

**Comment by uyab** [comment]
Any update on this?

**Comment by jonnywilliamson** [comment]
Currently tearing my hair out on trying to get the guzzle-debug bar to work when using the Laravel Http Client Pool. It's fine if it's just simple requests, but any request coming from a pool is not being logged.

Came in in hope it might have been implemented directly with the laravel debug bar! No luck!

**Comment by barryvdh** [comment]
https://github.com/barryvdh/laravel-debugbar/pull/1859
