### ISSUE TITLE
Debugbar not display on Laravel Version 8.48.1

### ISSUE THREAD

**Issue by farhaanabdulla** [barryvdh/laravel-debugbar#1202]
Dear All,

I've install the laravel-debugbar package on laravel v8.48.1, i've follow all the steps but it is not showing the bar neither the debug log.

Please can you assist me?

**Comment by pl38** [comment]
Same for me, I get errors:

`GEThttps://abcdef.lan/_debugbar/assets/stylesheets?v=1623680966&theme=auto
[HTTP/1.1 404 Not Found 2ms]

GEThttps://abcdef.lan/_debugbar/assets/javascript?v=1623680966
[HTTP/1.1 404 Not Found 7ms]

Uncaught ReferenceError: jQuery is not defined

 Uncaught ReferenceError: PhpDebugBar is not defined
`
"laravel/framework": "^8.48.1"
"barryvdh/laravel-debugbar": "^3.6.2",
"tailwindcss": "^2.2.2",
"laravel-mix": "^6.0.24",

build was fine before 8.48.1 but that might be a red-herring as the site versioning of css is also flaky, a dev build doesn't help either.

**Comment by barryvdh** [comment]
Do you get an error when openening the stylesheet url?

**Comment by pl38** [comment]
> Do you get an error when opening the stylesheet URL?

Hi, yes, I did, but then I deleted the vendor folder, composer.lock, upgraded to laravel-mix 6.0.25 - composer installed, and everything is back to normal.

I should have broken down the process to see what helped, but I needed to get it working - thanks for a brilliant helper btw 😀

**Comment by barryvdh** [comment]
Ok, if anyone else has this problem, please open the asset url (`_debugbar/assets/javascript`) in the browser and check if there is an error there.

**Comment by farhaanabdulla** [comment]
Hi, In my case its a fresh installation, I've delete the vendor folder and composer install but the bar still not showing. I've try to open console for _debugar/assets/javascript but no errors. Please help
<img width="1426" alt="Screenshot 2021-06-27 at 23 24 19" src="https://user-images.githubusercontent.com/35699210/123556934-02b32980-d79f-11eb-8f03-47a5b55a1e1f.png">

**Comment by farhaanabdulla** [comment]
Please can anyone help?

**Comment by minhchu** [comment]
@farhaanabdulla please check `laravel.log`. It may show some exceptions from debugbar

**Comment by maicol07** [comment]
I have this error in the log file:
```
#0 /home/maicol07.it/bd.account.maicol07.it/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->find()
#1 /home/maicol07.it/bd.account.maicol07.it/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#2 /home/maicol07.it/bd.account.maicol07.it/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#3 /home/maicol07.it/bd.account.maicol07.it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#4 /home/maicol07.it/bd.account.maicol07.it/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#5 {main}
"}
[2021-07-06 18:38:00] local.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.
```

**Comment by barryvdh** [comment]
Maybe flush your routes? And disable the route caching.

**Comment by maicol07** [comment]
@barryvdh yeah, you're right

**Comment by farhaanabdulla** [comment]
@minhchu Thank a lot for your help.

After I've gone through laravel.log i found this error. [2021-07-08 08:16:46] local.ERROR: Debugbar exception: mkdir(): Permission denied  

What I've done I've create a folder inside storage and now its working fine :)
