### ISSUE TITLE
Debug bar error

### ISSUE THREAD

**Issue by kvinkinamoto** [barryvdh/laravel-debugbar#1210]
Symfony\Component\VarDumper\Dumper\HtmlDumper::setDumpHeader(): Argument #1 ($header) must be of type string, null given, called in D:\OSPanel\domains\brilara\vendor\maximebf\debugbar\src\DebugBar\DataFormatter\DebugBarVarDumper.php on line 288

    "require": {
        "php": "^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.3",
        "laravel/framework": "^8.51",
        "laravel/tinker": "^2.6"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^v3.6.2",
        "barryvdh/laravel-ide-helper": "^v2.10.0",
        "facade/ignition": "^2.11.2",
        "fakerphp/faker": "^1.15",
        "laravel/sail": "^v1.8.6",
        "mockery/mockery": "^1.4.3",
        "nunomaduro/collision": "^5.6",
        "phpunit/phpunit": "^9.5.7"
    },

**Comment by SignetPlanet** [comment]
I am just leaving work so didn't dive into this further but it seems this is an issue from an update to Symfony about 5 days ago. The code looks right at first glance. I'll look into it more tomorrow if I get the chance. 
https://github.com/symfony/var-dumper/commit/56d2cd7b5f49e309ee48ff7df891db0bf3c5143f

**Comment by prazny** [comment]
Temporarily you can comment the line in **vendor\maximebf\debugbar\src\DebugBar\DataFormatter\DebugBarVarDumper.php:288**
`public function getAssets() {
        $dumper = $this->getDumper();
        //$dumper->setDumpHeader(null); // here
        return array(
            'inline_head' => array(
                'html_var_dumper' => $dumper->getDumpHeaderByDebugBar(),
            ),
        );
    }`

**Comment by kvinkinamoto** [comment]
thenks

**Comment by barryvdh** [comment]
Should be fixed with maximebf/php-debugbar#475 after running composer upgrade. If not, please report back.

**Comment by SignetPlanet** [comment]
Ran composer update and issue is gone. That was super fast. Thanks.
