### ISSUE TITLE
Argument 1 passed to Barryvdh\Debugbar\DataCollector\CacheCollector::subscribe() must be an instance of Illuminate\Events\Dispatcher, instance of October\Rain\Events\Dispatcher given

### ISSUE THREAD

**Issue by pgarnek** [barryvdh/laravel-debugbar#1225]
Hello,

problem showed up when i've made a first step to create new plugin with rainlab/page-builder plugin. I had one plugin made the same way few days ago, now i wanted to make new one.... so after filling basic information to create plugin form and after click on "Create" button thix exception shows:

![image](https://user-images.githubusercontent.com/6490500/132571133-a4efc037-9f26-49d1-a138-42820a7e9143.png)
same error shows on every page, both frontend and backend.

after searching for a problem, i've decidec to delete all *.json files in storage/debugbar, couse i've found they got > 600MB.
Not knowing the business logic of debugbar, i thought it will help me force trought this issue. But it won't :/

when APP_DEBUG is set to FALSE, everythings goes and works fine. Enabling APP_DEBUG shows exception again.

how to make it work's again? i've got no ideas...

**Comment by pgarnek** [comment]
temporary made a modification in laravel-debugbar\src\DataCollector\CacheCollector.php
adding line `use October\Rain\Events\Dispatcher as Dispatcher2;`

and changing line #62 from `public function subscribe(Dispatcher $dispatcher)` to 'public function subscribe(Dispatcher2 $dispatcher)'

page works, exception dissapeared.

what to do now? leave at it is? or should i made sth. else with this issue ?

**Comment by barryvdh** [comment]
I should probably typehint a contract there.
