### ISSUE TITLE
The Content-Length is changed when no content

### ISSUE THREAD

**Issue by AlexMcowkin** [barryvdh/laravel-debugbar#1231]
I have some endpoints that use no content response. I this case I have a problem with Content-Length.

`
    protected function noContentResponse(): Response
    {
        return response('', 204);
    }
`

also, I have the middleware to count the content length:

`public function handle(Request $request, Closure $next)`
`    {`
       ` /** @var Response $response */`
`        $response = $next($request);`

`        return $response->header('Content-Length', (string)strlen((string)$response->getContent()));`
 `   }`

When I call my endpoint I have to see the **Content-Length: 0**
but instead, I see the huge value.

after the debugging, I found out that the LaravelDebugbar changes this value.

Could you please check this issue?
Thank you

**Comment by barryvdh** [comment]
When the debugbar is injected, the content length changes. But I guess it wouldn't make sense to inject it in the 204 calls probably. Is that an ajax call or what is calling the 204?

**Comment by AlexMcowkin** [comment]
No. This is API (laravel)
I have a controller with method:

`    public function destroy(int $userId): Response
    {
        $user = User::findOrFail($userId);

       /*some logic*/

        return return response('', 204);
    }`
