### ISSUE TITLE
Debugbar on production server

### ISSUE THREAD

**Issue by Stehos** [barryvdh/laravel-debugbar#1241]
Hello, is there any way how can I start showing debug bar on the production live server? I install it as nondev dependency, tried to use \Debugbar::enable(), updated the env file in the following way:

APP_ENV=local
APP_DEBUG=true

but everything without result.

composer:
"barryvdh/laravel-debugbar": "^3.6",
"laravel/framework": "^8.54",

thank you.

**Comment by AbdullahFaqeir** [comment]
try deleting the vendor folder then install it while allowing dev dependancies to be installed.

**Comment by ismaail** [comment]
move `barryvdh/laravel-debugbar` to `require` section in `composer.json` and run `composer update`.

add this lines in `routes/web.php`:

```php
if (class_exists(\Debugbar::class) && in_array(request()->ip(), ['127.0.0.1'], true)) {
    \Debugbar::enable();
}
```

in the array `[127.0.0.1]` put any ip address allowed to see the **Debugbar**
