### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by Maks1988** [barryvdh/laravel-debugbar#1244]
Hello! 
I tried to install the package: 
composer require barryvdh/laravel-debugbar --dev
and got this error:

1. I cleared the cash and updated the composer.
2. I removed the vendor package and updated the composer.
3. Nothing from above helped me.

Problem 1
    - barryvdh/laravel-debugbar[v3.6.0, ..., v3.6.2] require maximebf/debugbar ^1.16.3 -> satisfiable by maximebf/debugbar[v1.16.3, ..., 1.17.x-dev (alias of dev-master)].
    - maximebf/debugbar 1.17.x-dev is an alias of maximebf/debugbar dev-master and thus requires it to be installed too.
    - maximebf/debugbar[dev-master, v1.16.4, ..., v1.17.1] require psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - maximebf/debugbar v1.16.3 requires php ^7.1 -> your php version (8.0.11) does not satisfy that requirement.
    - Root composer.json requires barryvdh/laravel-debugbar ^3.6 -> satisfiable by barryvdh/laravel-debugbar[v3.6.0, v3.6.1, v3.6.2].

**Comment by Aydcoder** [comment]
I'm also having the same problem. Please help

**Comment by nicotravassos** [comment]
Same problem here cannot install debugbar in new application @barryvdh .

**Comment by arminlinzbauer** [comment]
+1 - worked last week, now it's broken!

**Comment by scorpion2763** [comment]
Plase this try;

composer require barryvdh/laravel-debugbar --dev -W
