### ISSUE TITLE
RAM increase when use laravel octane

### ISSUE THREAD

**Issue by mcolominas** [barryvdh/laravel-debugbar#1247]
From what I have indicated in the title, the ram increases as requests are made.
```
wrk -t4 -d30s -c200 http://127.0.0.1:8000
```

I have followed the instructions and I have made the following configuration:

Make sure to add LaravelDebugbar to your flush list in config/octane.php.
```php
    'flush' => [
        \Barryvdh\Debugbar\LaravelDebugbar::class,
    ],
```

I also have to add, that the RAM only increases when APP_DEBUG=true, when set to false, RAM does not increment.

**Comment by henriquebremenkanp** [comment]
I can also confirm the same issue, don't know the cause.

**Comment by anibalealvarezs** [comment]
Maybe this? https://github.com/barryvdh/laravel-debugbar#enablingdisabling-on-run-time

**Comment by henriquebremenkanp** [comment]
@anibalealvarezs Thank you for your help.

As far as I checked, the memory leak only happens when debugbar is enabled as @mcolominas reported. (`APP_DEBUG=false` also disables the debugbar)

Disabling debugbar won’t fix, but avoid triggering the issue.
No debugbar, no issue.

It seems like he reported the wrk command as a way for us to reproduce it.

**Comment by anibalealvarezs** [comment]
@henriquebremenkanp Yes, I just noticed that you could disable the collectors in runtime with ```\Debugbar::disable();```, so you wouldn't have to alter the ``APP_DEBUG``` variable value. Don't know if it prevents the memory issue, but it's worth a try.

**Comment by dvlpr91** [comment]
is it solved?

If I activate only the debugbar, memory usage increases.

**Comment by lazerg** [comment]
@mcolominas @henriquebremenkanp 

For future readers, try [this](https://github.com/barryvdh/laravel-debugbar#laravel-with-octane) configuration

>### Laravel with Octane:
>Make sure to add LaravelDebugbar to your flush list in config/octane.php.
>
>```php
>'flush' => [
>    \Barryvdh\Debugbar\LaravelDebugbar::class,
>],
>```

**Comment by parallels999** [comment]
Try #1467
