### ISSUE TITLE
Feature Request: Allow Debugbar in PHPUnit (environment "testing")

### ISSUE THREAD

**Issue by camya** [barryvdh/laravel-debugbar#1248]
I create an API based Laravel application. 

To debug / optimise it, I use **laravel-debugbar**'s `Debugbar::getData()`method. It outputs an array with SQL queries, measurements, etc.

**This works great** if I access my API over HTTP with tools like Postman, Insomnia, the Webbrowser, Curl.

# The problem: It's skipped in PHPUnit Tests (env "testing")

I write integration tests for all my API routes. (PHPUnit or Pest)

In PHPUnit/Pest the `Debugbar::getData()` contains the same data including SQL queries ... (Which is really useful here.) ... if it's enabled.

**Unfortunately the data collection it's disabled by default** for env "testing" (see `LaravelDebugbar ->isEnabled()`)

This is **easily fixed by enabling** the laravel-debugbar for the testing environment. Now all data is available. (See code example)

# Feature request

Please activate laravel-debugbar collection also for the "testing" environment. (See implementation below)

Thoughts
- **Only collect data** in env testing - Don't inject the debugbar into the markup.

# Implementation idea
```
// vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php
public function isEnabled()
{
    if ($this->enabled === null) {
        
        // ... 

        // Old implementation does not allow environment "testing"
        // $this->enabled = $configEnabled && ! $this->app->runningInConsole() && ! $this->app->environment('testing');
    
        // New implementation: Allows environment "testing"
        if ($this->app->runningInConsole()) {
            $configEnabled = $this->app->environment('testing');
        }
        $this->enabled = $configEnabled;

    }

    return $this->enabled;
}
```

**Comment by akalongman** [comment]
I think debugbar should be enabled everywhere, if APP_DEBUG is true
