### ISSUE TITLE
Debugbar is shown in production

### ISSUE THREAD

**Issue by aeq-dev** [barryvdh/laravel-debugbar#1259]
Hello,
I've a project on production where I set app_debug=false but it still appears !
what's the matter here ?
Thanks

**Comment by barryvdh** [comment]
Config cached? You should instell debugbar only on dev.

**Comment by aeq-dev** [comment]
Yes I did cache clear, optimize clear and it's installed on dev
I'm using Laravel 6.

**Comment by amirsarfar** [comment]
You should add  `DEBUGBAR_ENABLED=false` in your .env file, too.

**Comment by zippos** [comment]
> Config cached? You should instell debugbar only on dev.
> Yes I did cache clear, optimize clear and it's installed on dev I'm using Laravel 6.

And also you should not install dev dependencies on production
`composer install --no-dev`
