### ISSUE TITLE
Loading page very slow when i am using graph with Laravel-debuggger ?

### ISSUE THREAD

**Issue by pankajToday** [barryvdh/laravel-debugbar#1277]
I  have been facing an issue for a long time. The issue is when I log in and come to the dashboard then that page takes a long time to load.  i am doing long calculations and showing graph 📊. but the whole calculation is being done in less than in 2sec. but after that, my blade view takes a long time or sometimes crashes the page. can you tell me how I can i fix it? I am developing the project on the WAMP server. it is running well without a debugger.
please check my images.

![Screenshot 2022-01-21 112505](https://user-images.githubusercontent.com/26523290/150474752-7f2c1acc-1fcf-4ca4-a0b7-b53154b54daa.png)
![Screenshot 2022-01-21 112544](https://user-images.githubusercontent.com/26523290/150474779-725d73cc-e2ff-447b-8238-a08b0ade0972.png)
![Screenshot 2022-01-21 112657](https://user-images.githubusercontent.com/26523290/150474831-0f2e1082-2573-4661-9234-b0eeb86ba915.png)

**Comment by MarcinStefaniak** [comment]
Hi,
i have a similar problem. The site works very slowly and everything takes a long time to load when debugging is with the debugbar option turned on.
When I turn off the debugbar itself, the page starts to work quickly.

I'm developing a project on a computer locally on homestead.
I use:
- AlpineJS 3.10
- Livewire 2.10
- Laravel 9.43
- Debug bar 3.7
