### ISSUE TITLE
Error in lumen

### ISSUE THREAD

**Issue by renayanti** [barryvdh/laravel-debugbar#1279]
Barryvdh\Debugbar\ServiceProvider::Barryvdh\Debugbar\{closure}(): Argument #2 ($application) must be of type Illuminate\Foundation\Application, Laravel\Lumen\Application given

**Comment by dudecussi** [comment]
Same problem 😿
```
"laravel/lumen-framework": "^8.3"
"barryvdh/laravel-debugbar": "^3.6"
```

**Comment by iamBunny** [comment]
@renayanti @dudecussi Temporary, quick fix, until it's patched (if you're gonna use the vendor in Lumen app):

In `vendor/barryvdh/laravel-debugbar/src/ServiceProvider.php` replace line 10:

`use Illuminate\Foundation\Application;`

with

`use Laravel\Lumen\Application;`

**Comment by PascalHuijsmans** [comment]
I got the same issue. 

`        
"php": "^8.1",
"laravel/lumen-framework": "^9.0.2",
"barryvdh/laravel-debugbar": "^3.6.7",
`

@iamBunny I can confirm it is working with your fix.
