### ISSUE TITLE
Laravel 9.0

### ISSUE THREAD

**Issue by gofish543** [barryvdh/laravel-debugbar#1280]
With the release of Laravel 9.0 coming within a week or two; what is the release schedule looking like for this package? Would you like any help?

**Comment by barryvdh** [comment]
What is the problem with Laravel 9? It should have been added in https://github.com/barryvdh/laravel-debugbar/pull/1271 already. Please try the latest dev version with v9 and create an issue if you encounter some issue.

**Comment by gofish543** [comment]
Didn't check the latest dev version. Thank you!

**Comment by GrytsenkoAndrey** [comment]
Hello,

composer.json:
```
"require": {
        "php": "^8.0",
        "ext-curl": "*",
        "ext-fileinfo": "*",
        "ext-json": "*",
        "ext-zip": "*",
        "predis/predis": "^1.1",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5"
    },
"require-dev": {
        "spatie/laravel-ignition": "^1.0",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.0",
        "phpstan/phpstan": "^1.4",
        "phpunit/phpunit": "^9.5.10",
        "squizlabs/php_codesniffer": "*"
    },
```
I try to install the package:
`composer require barryvdh/laravel-debugbar:^3.6.6 --dev`

and the result is:
![image](https://user-images.githubusercontent.com/63291871/152673268-a383ba39-f198-4174-92cb-81bcbe44b2f1.png)

Is there really support Laravel 9?

**Comment by GrytsenkoAndrey** [comment]
DONE! I install the package (also the IDE-Helper)
