### ISSUE TITLE
Memory exhaustion due to large sql queries

### ISSUE THREAD

**Issue by akulmehta** [barryvdh/laravel-debugbar#1287]
I am getting an error similar to https://github.com/barryvdh/laravel-debugbar/issues/726#issue-257661417 for memory exhaustion. This is for a route with a large number of SQL queries being performed in the service as batched jobs. So the route basically creates a batch of jobs to import data from a large json file. 

The error I am getting is 

```
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 2700264 bytes) in 
C:\...\vendor\barryvdh\laravel-debugbar\src\DataCollector\QueryCollector.php on line 172
```

I think it is the `preg_replace` on the following line which causes this issue:

```
vendor\barryvdh\laravel-debugbar\src\DataCollector\QueryCollector.php

                $query = preg_replace($regex, addcslashes($binding, '$'), $query, 1); 

```

What is weird is that even if I use `\Debugbar::disabled()` in the route like below, it still gives the error.

```
    public function importData()
    {
        \Debugbar::disable();
        $batch = (new ImportDataService())->importDataFromJSON();
        return view('import')->with(['batch' => $batch]);
    }
```
Shouldn't Debugbar not gather the information if it is disabled for the route?

I also tried `DB::disableQueryLog()` but didn't change anything.

**Comment by akulmehta** [comment]
Just to update - I wonder if this issue of disable not working is caused due to livewire?

**Comment by sawirricardo** [comment]
Hi, any update with this? I'm encountering issues with importing and creating model.
