### ISSUE TITLE
Debugbar with tunnel

### ISSUE THREAD

**Issue by ossigeno** [barryvdh/laravel-debugbar#1293]
When using a tunnel service like ngrok the toolbar is trying to load resources over https to my localhost . So requires self-cert installing locally. Everything else accepts SSL offloading. Not really a bug but a real pain to setup.

Access to CSS stylesheet at 'http://[localhost domain]/_debugbar/assets/stylesheets?v=1644393152&theme=auto' from origin 'http://[subdomain].ngrok.io' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `local`.

This only occurs in Chrome since they now enforce [CORS-RFC1918](https://wicg.github.io/private-network-access/). Using Firefox the debugbar loads.

**Comment by bretto36** [comment]
Thanks for the tip on firefox still working.... for now anyway
