### ISSUE TITLE
A simple incompability with php 8.1

### ISSUE THREAD

**Issue by PaolaRuby** [barryvdh/laravel-debugbar#1296]
Hello, i've found an error here :

**message:** `htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated`
**exception:** `ErrorException`
**file:** `/var/www/vendor/barryvdh/laravel-debugbar/src/DataFormatter/QueryFormatter.php`
**line:** `58`
https://github.com/barryvdh/laravel-debugbar/blob/b96f9820aaf1ff9afe945207883149e1c7afb298/src/DataFormatter/QueryFormatter.php#L57-L59
Works adding `(string)` or checking null
```php
foreach ($bindings as &$binding) {
     $binding = htmlentities((string) $binding, ENT_QUOTES, 'UTF-8', false); 
} 
// OR
foreach ($bindings as &$binding) {
     if (!is_null($binding)) {
         $binding = htmlentities($binding, ENT_QUOTES, 'UTF-8', false); 
     }
} 
// OR
foreach ($bindings as &$binding) {
     $binding = htmlentities($binding ?: '', ENT_QUOTES, 'UTF-8', false); 
}  
```
----
**Environment:**
"Package": "v3.6.7"
"PHP": "8.1.2"
"Laravel": "v8.83.1"

Maybe related https://github.com/barryvdh/laravel-debugbar/issues/1284#issuecomment-1032527507

**Comment by angeljqv** [comment]
[barryvdh](https://github.com/barryvdh) +1

sometimes i get that exception too

**Comment by erikn69** [comment]
+1

**Comment by PaolaRuby** [comment]
Fixed on https://github.com/barryvdh/laravel-debugbar/commit/29d7d90678f968d279eb083fccfea1824132c976

**Comment by barryvdh** [comment]
Tagged
