### ISSUE TITLE
Ignore AJAX on HTTP 204

### ISSUE THREAD

**Issue by GarryLai** [barryvdh/laravel-debugbar#1299]
I have a ping which return HTTP 204 (no content).
I fetch it every 30 second.
Every time I fetch it, it well be recordrd.
I think this is annoying and useless on HTTP 204 AJAX.

**Comment by wizzymore** [comment]
I don't think this is useless as people use the laravel debug bar for exceptions, queries done, models loaded etc, even if it returns no content it doesn't mean that a 204 route doesn't have side effects that needs to be tracked
