### ISSUE TITLE
[Feature] Dashboard like telescope

### ISSUE THREAD

**Issue by pionl** [barryvdh/laravel-debugbar#1300]
Hi,

I do like the Debugbar and I'm using it since Laravel 5.5. But there are some use cases where Debugbar can't be used - like JSON API. We have used some work arounds, but I do not like it (like rendering a view with the json data).

Not sure how hard it would be, but it would be great to make a dashboard to see last request (we could reuse the same UI) or latest requests (probably needs some refactoring - could similar to telescope).

This would be great because Telescope is not interested in tracking "profiling" metrics (https://github.com/laravel/telescope/pull/698) which I use to find places that can be optimized.

How hard would be to integrate this feature?

Thank you for your time,
Martin

**Comment by Forsakenrox** [comment]
> Hi,
> 
> I do like the Debugbar and I'm using it since Laravel 5.5. But there are some use cases where Debugbar can't be used - like JSON API. We have used some work arounds, but I do not like it (like rendering a view with the json data).
> 
> Not sure how hard it would be, but it would be great to make a dashboard to see last request (we could reuse the same UI) or latest requests (probably needs some refactoring - could similar to telescope).
> 
> This would be great because Telescope is not interested in tracking "profiling" metrics ([laravel/telescope#698](https://github.com/laravel/telescope/pull/698)) which I use to find places that can be optimized.
> 
> How hard would be to integrate this feature?
> 
> Thank you for your time, Martin

try to look at clockwork
