### ISSUE TITLE
After install not woking show Queries, Model and ... - Laravel 9

### ISSUE THREAD

**Issue by phuochoit** [barryvdh/laravel-debugbar#1301]
Hi Sir. 
I always and forever have used barryvdh/laravel-debugbar with no issues ever and now my use Laravel 9. But  this time the debug bar does not display all not showing except View and Timeline

I Using 
```
"php": "^8.0.2",
"laravel/framework": "^9.2",
 "laravel/jetstream": "^2.6",
```
and last releases 
![image](https://user-images.githubusercontent.com/8032723/155445744-becf8200-bc3d-437a-a562-7643459a08b6.png)
![image](https://user-images.githubusercontent.com/8032723/155445887-6c6879db-ddbd-40ec-8d4d-66518dfc0c62.png)
![image](https://user-images.githubusercontent.com/8032723/155445932-7bbd7680-2f93-455d-ae1b-e18d005fbe50.png)

Please help me - Thank you.

**Comment by kylescousin** [comment]
I'm having the same problem with L9.
Views show, but no models and no queries.
