### ISSUE TITLE
Bar not showing and class not found

### ISSUE THREAD

**Issue by PierreFontaineCS** [barryvdh/laravel-debugbar#1316]
Hi, 

I am using a clean laravel 9 installation, 

I installed the debugbar with : 

`composer require barryvdh/laravel-debugbar`

But it is now showing. 

I have already cleared cache of config, routes etc... 

Trying to figure out the problem I put this in the route file : 

`\Barryvdh\Debugbar\Facades\Debugbar::info("test");` 

And I have this error : 

`[Class "Barryvdh\Debugbar\Facades\Debugbar" not found]`

It seems the autoloader is not working properly. 

I have already tried to make `composer dumpautoload`

Thank's for the help !

**Comment by kanich** [comment]
Docker container fresh created from Bitnami Laravel Docker Image.
barryvdh/laravel-debugbar installed with composer, included in config/app.php and published. The debugbar was not shown on pages in browser.

After closer check was found that current copy of php.ini is copy of php.ini-production.
Here error messaging is partially suppresed. 

Solution:
copy php.ini-development to php.ini or change following parameters to new values:
error_reporting = E_ALL
display_errors = On
display_startup_errors = On

Apply: php artisan optimize
Result: laravel-debugbar is shown on pages in browser.
