### ISSUE TITLE
octane(swoole) memory leak

### ISSUE THREAD

**Issue by dvlpr91** [barryvdh/laravel-debugbar#1324]
1. Create a new project.

2. Install octane(swoole) and debugbar.

3. Each time the page is refreshed, the memory increases.

4. Set the enabled value to false in config/debugbar.php

5. Each time the page is refreshed, memory is maintained.

**Comment by ankurk91** [comment]
You are not going to use debug bar in production.

**Comment by ariaieboy** [comment]
@ankurk91 the memory leak will prevent developers from detecting actual memory leaks in the app.

and in some cases my 16GB ram gonna overflow because of this memory leak

**Comment by lazerg** [comment]
@dvlpr91 @ariaieboy 

Have you tried [this](https://github.com/barryvdh/laravel-debugbar#laravel-with-octane) configuration?

>### Laravel with Octane:
>Make sure to add LaravelDebugbar to your flush list in config/octane.php.
>
>```php
>'flush' => [
>    \Barryvdh\Debugbar\LaravelDebugbar::class,
>],
>```

**Comment by dvlpr91** [comment]
> @dvlpr91 @ariaieboy
> 
> Have you tried [this](https://github.com/barryvdh/laravel-debugbar#laravel-with-octane) configuration?
> 
> > ### Laravel with Octane:
> > Make sure to add LaravelDebugbar to your flush list in config/octane.php.
> > ```
> > 'flush' => [
> >    \Barryvdh\Debugbar\LaravelDebugbar::class,
> > ],
> > ```

Yes

**Comment by lazerg** [comment]
> > @dvlpr91 @ariaieboy
> > Have you tried [this](https://github.com/barryvdh/laravel-debugbar#laravel-with-octane) configuration?
> > > ### Laravel with Octane:
> > > Make sure to add LaravelDebugbar to your flush list in config/octane.php.
> > > ```
> > > 'flush' => [
> > >    \Barryvdh\Debugbar\LaravelDebugbar::class,
> > > ],
> > > ```
> 
> Yes

Is that solved your issue?

**Comment by dvlpr91** [comment]
> > > @dvlpr91 @ariaieboy
> > > Have you tried [this](https://github.com/barryvdh/laravel-debugbar#laravel-with-octane) configuration?
> > > > ### Laravel with Octane:
> > > > Make sure to add LaravelDebugbar to your flush list in config/octane.php.
> > > > ```
> > > > 'flush' => [
> > > >    \Barryvdh\Debugbar\LaravelDebugbar::class,
> > > > ],
> > > > ```
> > 
> > 
> > Yes
> 
> Is that solved your issue?

No, So I dumped the deguhbar in the trash.

**Comment by ariaieboy** [comment]
> @dvlpr91 @ariaieboy
> 
> Have you tried [this](https://github.com/barryvdh/laravel-debugbar#laravel-with-octane) configuration?
> 
> > ### Laravel with Octane:
> > Make sure to add LaravelDebugbar to your flush list in config/octane.php.
> > ```
> > 'flush' => [
> >    \Barryvdh\Debugbar\LaravelDebugbar::class,
> > ],
> > ```

yes I added this config but it's not helping

**Comment by mehrab-wj** [comment]
Same issue when using Debugbar, Laravel 10, and Swoole.
I've added the `\Barryvdh\Debugbar\LaravelDebugbar::class` to the `flush` configuration but still at every refresh of a fresh project, the ram will go up.

**Comment by aran112000** [comment]
Same issue here

**Comment by louisjeck** [comment]
Same here, Laravel 10, Octane + Swoole, on Laravel Sail, added the config but same leak.

**Comment by marianoarga** [comment]
Same problem here, flush debugbar does not help. Increasing memory on every request

![image](https://github.com/barryvdh/laravel-debugbar/assets/1138627/4a1e6ebb-c149-4cc6-ba46-5857e4ccf521)

**Comment by victorbetini** [comment]
Same here, but it seems like it's a "visual bug". I'm not seeing an actual increase in memory usage. Not really sure...
![image](https://github.com/barryvdh/laravel-debugbar/assets/42259632/0218357a-ea67-4cc8-a5eb-8e395b9857cc)

**Comment by barryvdh** [comment]
Sorry not really familiar with Swoole. Maybe something needs to be flushed/reset with the RAM. Do other people increase actually increasing ram, or just the visual?

Can anyone try with settings realUsage to true in https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/DataCollector/MemoryCollector.php
Or by calling https://www.php.net/manual/en/function.memory-reset-peak-usage.php in the flush / event when restarted (not sure how that works with Octane)

**Comment by victorbetini** [comment]
> Sorry not really familiar with Swoole. Maybe something needs to be flushed/reset with the RAM. Do other people increase actually increasing ram, or just the visual?
> 
> Can anyone try with settings realUsage to true in https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/DataCollector/MemoryCollector.php Or by calling https://www.php.net/manual/en/function.memory-reset-peak-usage.php in the flush / event when restarted (not sure how that works with Octane)

Thanks for the reply! I've tried both suggestions, but none of them fixed the issue :(
I'm considering not using Octane anymore... It is giving me more problems than solutions...

**Comment by dvlpr91** [comment]
This problem will not be easily resolved. When faced with a problem, giving up now will be the quickest solution.

**Comment by borys-p** [comment]
I **do not** confirm the issue. Just tested on Laravel 10.13, Octane 2.0, Swoole 5.0.3 and Debugbar 3.8.1. Single Blade view, debug mode enabled, reported memory usage stays at 19MB no matter how many times I refresh the page. Seems that _something_ got fixed along the way.

**Comment by aran112000** [comment]
We're still seeing this within Laraval apps running on Octane - Even a default Laravel install adds +~2mb per page load and compounds with every page you view until memory exhausted, or Octane restarts the worker

**Comment by parallels999** [comment]
It seems to me that the problem is that they use only a "main" preloaded script for many requests, debugbar obtains the peak of the request, that would be the memory value of the entire process on this case

**Comment by erikn69** [comment]
Hi, try https://github.com/maximebf/php-debugbar/pull/559 and let your review

**Comment by barryvdh** [comment]
For Octane, can Laravel just call `memory_reset_peak_usage` when PHP8.2+ is used?

**Comment by erikn69** [comment]
@barryvdh , still, octane handles an running process with "preload" on memory instances, so the peak is always really big, also on other OS like windows, the instance is up 19mb, https://github.com/maximebf/php-debugbar/pull/559 normalizes with a baseline before execution, 
That will normalize the memory calculation, what do you think of that solution? What would be the cons?

**Comment by mehrab-wj** [comment]
I still have this issue but I found a quick fix and thought to share it here.

The easiest fix is, when you are starting your Octane server, specify [Max Request Count](https://laravel.com/docs/10.x/octane#specifying-the-max-request-count) to something low like 1, or 2.

For example, this is how I'm running my server in development:
```sh
php artisan octane:start --watch --host=0.0.0.0 --port=8000 --max-requests=1
```

**Comment by erikn69** [comment]
@mehrab-wj hi, for the records, did you set `true` on `reset_peak` and `with_baseline`?
https://github.com/barryvdh/laravel-debugbar/blob/276892c32bd71d6cc073e39a6e6c1a341ea128c0/config/debugbar.php#L202-L204

**Comment by mehrab-wj** [comment]
Hi @erikn69, Now I was following the based on the readme, I will test this, Thanks.

**Comment by mehrab-wj** [comment]
Hi @erikn69, No I was following the based on the readme, I will test this, Thanks.

**Comment by borys-p** [comment]
@mehrab-wj this will result in restarting the workers after each request, so you will lose all the benefits of using Octane and might even get worse performance than without it.

**Comment by bigfootcreative** [comment]
With frankenphp leave debugbar to null for DEBUGBAR_ENABLED, and 
'flush' => [
        Barryvdh\Debugbar\LaravelDebugbar::class,
    ],
This did work for me.

**Comment by CheesyTech** [comment]
Still a pressing issue. It also eats up 2-3 mb after page reloading.

**Comment by parallels999** [comment]
Maybe the listeners remain active even if flush is performed, that would cause the listeners to duplicate each page load.

I'm not familiar with Swoole, Many have the problem but it seems that no one wants to contribute with more information or a PR.

**Comment by neokofg** [comment]
config/debugbar.php 
options.memory
set both reset_peak and with_baseline to true
```
'options' => [
  'memory' => [
      'reset_peak' => env('DEBUGBAR_OPTIONS_MEMORY_RESET_PEAK', true),       // run memory_reset_peak_usage before collecting
      'with_baseline' => env('DEBUGBAR_OPTIONS_MEMORY_WITH_BASELINE', true), // Set boot memory usage as memory peak baseline
      'precision' => (int) env('DEBUGBAR_OPTIONS_MEMORY_PRECISION', 0),       // Memory rounding precision
  ],
```
