### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by cverster** [barryvdh/laravel-debugbar#1326]
I'm having an issue with Debugbar on my remote server. It works fine locally, but on my remote server, the Debugbar messages and information appears briefly, and then dissapear and I get the following error in console:

`javascript?v=1644364352:2243 Uncaught TypeError: Cannot read properties of undefined (reading 'length')`

I don't know why this only happens remotely. I get what looks like normal 200 responses on /_debugbar requests.

Any idea as to why this could be happening?

**Comment by Husky110** [comment]
@cverster - got the same problem. Did you fix it? If so: how?
