### ISSUE TITLE
Queries Tab Always empty.

### ISSUE THREAD

**Issue by muhsinzyne** [barryvdh/laravel-debugbar#1343]
![Screen Shot 2022-09-20 at 1 08 59 PM](https://user-images.githubusercontent.com/24736242/191217820-4704b3b3-8d72-4a4b-9f6c-24cd734fc00e.png)

I have added a few queries to my controller. but the queries tab always remains empty. even not displaying the standard authentication queries or user auth queries.

**Comment by muhsinzyne** [comment]
I am closing this as it was fixed by #1260 



anyone who faces the same can try injecting just the js file in order to see the queries tab with expected data.


 #1260

**Comment by kylescousin** [comment]
Having the same issue with L9. No models or queries showing:

![image](https://user-images.githubusercontent.com/5787966/208882643-63b856dd-748a-40fb-8244-eb3fc40a0929.png)

**Comment by Johnefsh** [comment]
Same here
