### ISSUE TITLE
"Views" tab not finding rendered views

### ISSUE THREAD

**Issue by browner12** [barryvdh/laravel-debugbar#1354]
With the release of Laravel v9.36.0, the "View" tab is no longer showing any rendered views.

Haven't nailed down *why* yet, but most likely due to [PR 44487](https://github.com/laravel/framework/pull/44487).

![Screen Shot 2022-10-18 at 11 10 38 AM](https://user-images.githubusercontent.com/5232313/196485092-cfd711e4-42da-46a3-a4a9-8a9b825a8c4e.png)

**Comment by nunomaduro** [comment]
Fixed on Laravel `v9.36.3`.
