### ISSUE TITLE
PHP 8.2 DateFormatter, Creation of dynamic property deprecated

### ISSUE THREAD

**Issue by hopkins385** [barryvdh/laravel-debugbar#1367]
Hi guys, 

with php 8.2 I get the following warnings.
Haven't found an already existing thread about this particular issue. 

````
Creation of dynamic property Barryvdh\Debugbar\DataFormatter\SimpleFormatter::$cloner is deprecated in /var/www/html/vendor/maximebf/debugbar/src/DebugBar/DataFormatter/DataFormatter.php on line 23
````

````
Creation of dynamic property Barryvdh\Debugbar\DataFormatter\SimpleFormatter::$dumper is deprecated in /var/www/html/vendor/maximebf/debugbar/src/DebugBar/DataFormatter/DataFormatter.php on line 24
````

### How to Reproduce

1. Install Debugbar in local environment
2. Visit an endpoint where debugbar is enabled (e.g. home)
3. Check logs

### Environment

PHP Version: 8.2.0
Laravel Version: 9.43.0
Debugbar Version: 3.7.0

**Comment by Alphaws** [comment]
`composer require maximebf/debugbar:^1.18.1`

**Comment by aneesdev** [comment]
@barryvdh

**Comment by CraniumAdamantium** [comment]
https://github.com/barryvdh/laravel-debugbar/pull/1370

**Comment by hopkins385** [comment]
Hi, any update?

**Comment by hopkins385** [comment]
Fixed with latest release.
