### ISSUE TITLE
Debugbar showing but my object information not showing anything

### ISSUE THREAD

**Issue by info-emastersindia** [barryvdh/laravel-debugbar#1379]
Possibly a bug here.

When I am to display my object's info using Debugbar, its showing blank if the page has error. Means no data in case there's an error on page. See screenshots below:

My Code:
<code>
$str = "test string";
$obj = $CheckUrlExist;
\Debugbar::info($str); // This is a sting variable and it shows the string
\Debugbar::info($obj); // This an object. It won't show if there's any error
var_dump($obj); //var_dump is showing data for on the object, even with error. So there's no question of object being null
</code>

Pages where's there no error:
![image](https://user-images.githubusercontent.com/120705703/212070512-491cc3fc-882a-4fad-acf5-bee56e85518a.png)
See, we have the string and the database model object.

Pages with errors on page is showing as:
![image](https://user-images.githubusercontent.com/120705703/212070926-d9c3b410-0a1a-4401-8d78-91cc7d1f93a1.png)
See the yellow marked one is showing blank.  And it is because of the error underlined in red.

var_dump() method output for object, even though there's error on page.
![image](https://user-images.githubusercontent.com/120705703/212072639-c4b76ec9-c20e-40c9-8531-cf79e8437053.png)
var_dump details marked.

It would be beneficial if we can use Debugbar instead of var_dump in case of errors too.

Thank you

**Comment by info-emastersindia** [comment]
What, seems nobody interested on the issue above or don't see it as a issue at all.

**Comment by crysix** [comment]
I also see this error. Very bad, especially for development, if you output some objects if debug set to true.
If you use _debug(print_r($obj, true));_ the Debugbar will show the object (but unformatted). So why is a string displayed on error and not an object?

**Comment by crysix** [comment]
As a workaround you could use `\Debugbar::info("<pre>".print_r($obj, true)."</pre>");` but thats not how it should work.

**Comment by crysix** [comment]
I found out, that the reason for all this is the following code, which is added to laravel debug error page:
`
    <style>
        pre.sf-dump {
            display: none !important;
        }
    </style>`
So output is there but only hidden.

**Comment by info-emastersindia** [comment]
> Thanks @crysix for the valuable insights. I hope to see solution for this on next version of Debugbar. Indeed its hidden. I didn't checked that earlier.
Debugbar, however, is a wonderful project for Laravel that really really saves lots of time in debugging.

**Comment by crysix** [comment]
I already made a "fix" for that, there is only a little problem then, the debug info is shown, but also background and colors are overwritten, so styling is not fully readable. But this styling is not from laravel-debugbar, it is from the php debugbar (which is the base for this project) or laravel itself. We could of course overwrite this in laravel-debugbar too, but I need to test a bit more for sideeffects. And also there are multiple other color values overwritten for the formatted text (but if we change one color and one bg and the display:none it is at least fully readable again).
The display none is part of the ignition package for laravel (the error page package). And chaning this has no side effects.

**Comment by crysix** [comment]
I made a fix for this, please approve #1399

**Comment by crysix** [comment]
Please approve #1399 to fix this problem. Than this thread could be closed.

**Comment by info-emastersindia** [comment]
I believe this is good to go as of the fix. Thanks
