### ISSUE TITLE
Incompatibility between debugbar dev-master and Laravel 4.1?

### ISSUE THREAD

**Issue by fogelfish** [barryvdh/laravel-debugbar#138]
I added

```
"require": {
        "barryvdh/laravel-debugbar": "dev-master"
    },
```

to composer.json and then ran composer update, with this result:

```
[Composer\DependencyResolver\SolverProblemsException]                                                   

    Problem 1                                                                                             
      - The requested package laravel/framework 4.2.* could not be found.
```

And after that, when I ran php artisan config:publish barryvdh/laravel-debugbar, it gave me:

```
PHP Fatal error:  Class 'Barryvdh\Debugbar\ServiceProvider' not found … Illuminate/Foundation/ProviderRepository.php on line 158
```

I'm in Laravel 4.1.  What adjustments should I make so Laravel and debugbar will work together?  Thanks very much!

**Comment by assoft** [comment]
@barryvdh

> [InvalidArgumentException]
> Could not find package barryvdh/laravel/debugbar at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 

Laravel Version: 5.2.23.
