### ISSUE TITLE
Debugbar icon

### ISSUE THREAD

**Issue by liamseys** [barryvdh/laravel-debugbar#1397]
Hi

Since updating to the new version of Laravel Debugbar I am seeing a UI glitch. When you expand the bar it now shows the Laravel icon twice. Is this intended behaviour?

![Screenshot 2023-02-22 at 11 22 57](https://user-images.githubusercontent.com/10025985/220592482-8e1a0f0a-73bc-48ff-9fc0-94d5ceee4d88.png)

**Comment by barryvdh** [comment]
Do you have the latest version? From yesterday? Should be fixed already (yesterday)

**Comment by liamseys** [comment]
Did ```composer update``` and this fixed the issue, thanks

**Comment by hamzaakbar15** [comment]
@barryvdh I just install it and still can see the double icon.

**Comment by jtouza** [comment]
@parallels999 I haven't looked too much into the topic and the error can probably be fixed without a css fix. May be someone has a more elegant solution. 
Also the problem, in my projects, doesn't seem to happen in v3.8 and php8.2

**Comment by parallels999** [comment]
Fixed on latest version
