### ISSUE TITLE
Problem with ajax requests

### ISSUE THREAD

**Issue by spib** [barryvdh/laravel-debugbar#14]
Hi,

When using the debugbar with ajax requests I always get an error where the browser returns a 'Request Failed' error. I found that if I comment out the following line in ServiceProvider.php it works again.

``` php
...
}elseif( $request->isXmlHttpRequest() ){
    $debugbar->sendDataInHeaders();
}elseif(
...
```

Would it be possible to make it optional whether or not to apply the debug data in the http headers for ajax requests?

Thanks

**Comment by mizanur-rahman** [comment]
@barryvdh 
I have disabled capture_ajax from config
`'capture_ajax' => false,`

after done this if i click any ajax link I got redirect to this page-
http://prntscr.com/cwldme

could you please suggest me what should i do?
