### ISSUE TITLE
Any way to pass in where query was called?

### ISSUE THREAD

**Issue by Icehawg** [barryvdh/laravel-debugbar#140]
I have been mucking with the source but haven't been able to figure out a way to pass in _ _ FILE _ _ and _ _ LINE _ _ for the queries so I can see where the duplication is coming from. Ideally, I want to click on each query and along with PARAMS, I would like to see where the query was made. Any thoughts on how I can get this to work?

Thanks for your time.

**Comment by davejamesmiller** [comment]
I just wanted to say this was really useful for tracking down duplicated queries in someone else's code. I think it would be great if it was on by default. (It was only after I came to make a request for this feature that I realised it already existed - it's not mentioned in the readme, and I never needed to run `php artisan vendor:publish` so I never read the config file comments or even realised there was a config file available. Anyway, good job, thanks!

**Comment by jonnywilliamson** [comment]
Just used this today. Brilliant help.
