### ISSUE TITLE
Lumen bug

### ISSUE THREAD

**Issue by 158672319** [barryvdh/laravel-debugbar#1416]
"message": "Argument 2 passed to Barryvdh\\Debugbar\\ServiceProvider::Barryvdh\\Debugbar\\{closure}() must be an instance of Illuminate\\Foundation\\Application, instance of Laravel\\Lumen\\Application given, called in ...\\vendor\\illuminate\\container\\Container.php on line 767",
    "exception": "TypeError",
    "file": "..\\vendor\\barryvdh\\laravel-debugbar\\src\\ServiceProvider.php",
    "line": 57,

**Comment by parallels999** [comment]
Seems like you can't follow installation instructions
https://github.com/barryvdh/laravel-debugbar#lumen

**Comment by 158672319** [comment]
No, I have already done it. If I change Illuminate\Foundation\Application to Laravel\Lumen\Application , it will succeed
