### ISSUE TITLE
Php v 8.0 unsupported

### ISSUE THREAD

**Issue by dav245** [barryvdh/laravel-debugbar#1418]
I have updated dependencies and came across this exception:

hash(): Argument #1 ($algo) must be a valid hashing algorithm

Thrown from file: /DataCollector/QueryCollector.php:396
That line is: if (hash('xxh128', 'v2' . $path) == $hash || sha1('v2' . $path) == $hash)

Did a fast google search and it looks like xxh128 hash was added in php 8.1
https://php.watch/versions/8.1/xxHash

Same results are from tinker
![image](https://github.com/barryvdh/laravel-debugbar/assets/32794932/4f99d701-8840-441e-bec9-944eb040f4a9)

I checked composer.json and it looks that php 8.0 should be supported. So i suppose this is a bug?

Thank you in advance for looking into this.

**Comment by dav245** [comment]
Just to fill in info from out composer.lock:

"name": "barryvdh/laravel-debugbar",
"version": "dev-master",

latest and greatest.

**Comment by dav245** [comment]
And last speedup. Reported change is from this commit:
https://github.com/barryvdh/laravel-debugbar/compare/v3.8.0...master#diff-edb5bfd4c9a2327c5da4a7529b29b426893fa4441dee5353d109bbda2c760333

**Comment by parallels999** [comment]
Wich laravel version are you using??
