### ISSUE TITLE
Internal Error 500 JavaScript

### ISSUE THREAD

**Issue by climentjoan** [barryvdh/laravel-debugbar#1420]
Hi there, 

I'm trying to have the debugbar working, after a lot of trouble to make it work in Laravel 7 and php 7.4, I managed to install it, but when I try to load, I get these errors at "Console":

GET http://localhost:8000/_debugbar/open?op=get&id=X3dd1e943f3a47f4d357f5af3acea82ff 500 (Internal Server Error) 

I get 3 of them. If I click on the error, it shows that the problem is:
    try {
                        s.send(t.hasContent && t.data || null)
                    } catch (e) {
                        if (n)
                            throw e
                    }

I've assured that the directory and contents belongs to www-data, and I've done route:clear.

My app information:
Laravel: ^7.0"
Php: ^7.2.5
Debugbar: ^3.7

I've looked for other issues, but I haven't found this error

Thanks!

**Comment by parallels999** [comment]
Laravel 7.x and PHP 7.4 have no support, try PHP 8.0 and Laravel 9.x, is the minimum requirement
https://github.com/barryvdh/laravel-debugbar/blob/bdfe99cbbfaa880a5126732a2806a82380be0a89/composer.json#L12-L13
https://github.com/barryvdh/laravel-debugbar/blob/bdfe99cbbfaa880a5126732a2806a82380be0a89/composer.json#L17

**Comment by climentjoan** [comment]
I understand last version doesn't support Laravel 7 and php 7.4, but 3.7 has (the one I've installed).

I can't upgrade for know to Laravel 9.

**Comment by parallels999** [comment]
Sorry 3.7 is old and impossible to update

**Comment by climentjoan** [comment]
I understand, I'm not asking for an upgrade, It could be something I'm missing, something I'm not doing right.

**Comment by parallels999** [comment]
Try it on a laravel 7.x fresh installation, i did test it v3.7.0 on laravel 8.x and everything works

**Comment by climentjoan** [comment]
Thank you, I did that and get it working by accessing to 127.0.0.1:8000 instead of localhost:8000. It's also running on my project.
