### ISSUE TITLE
Debugbar with Vapor results in a File Not Found exception

### ISSUE THREAD

**Issue by pooley182** [barryvdh/laravel-debugbar#1422]
When using Laravel Vapor it's possible that requests get routed to a different Lambda function. This means that looking at the `/tmp/storage/debugbar/` directory is likely to not contain the file requested.
If this was a traditional deployment then we'd enable sticky sessions on the load balancer, but this isn't possible with API Gateway / Lambda.

![image](https://github.com/barryvdh/laravel-debugbar/assets/5040011/09aa6e15-886f-49ad-ba22-c8945a969f79)

Is this a known issue with a workaround? I couldn't see any other issues raised for it here, or any others reporting the same issue on Google.

**Comment by parallels999** [comment]
You could change 
https://github.com/barryvdh/laravel-debugbar/blob/b7362410434d7f1155e0729e3a75c83384d3b699/config/debugbar.php#L42

**Comment by pooley182** [comment]
Thanks, I think you've pointed me in the right direction, `path` isn't quite what I need, but I should be able to change `driver` to use redis so it doesn't rely on the lambda temp storage.

**Comment by pooley182** [comment]
Setting the storage driver to redis does resolve this problem. Closing this issue.
```php
'storage' => [
    ...
    'driver'     => 'redis'
    ...
]
