### ISSUE TITLE
Old jquery, please update

### ISSUE THREAD

**Issue by mahdyfo** [barryvdh/laravel-debugbar#1432]
### Error:
After moving to laravel vite, I got this error:
![image](https://github.com/barryvdh/laravel-debugbar/assets/15161574/774e86f2-c207-4999-922f-5e02157166b5)
```
Uncaught SyntaxError: missing ) after argument list (at ?v=1689852031:2:80845)
Uncaught ReferenceError: jQuery is not defined at (index):184:2249
Uncaught ReferenceError: PhpDebugBar is not defined at (index):187:19
```

### Info:
Windows localhost
WAMP
php8.1.0
Chrome browser (Version 115.0.5790.99 (Official Build) (64-bit)), latest version till now
This error was not appearing for other users with non-windows os.

### Fix:
I updated `jQuery v3.3.1` located in `src/DebugBar/Resources/vendor/jquery/dist/jquery.min.js` to `jQuery v3.6.1` and the issue was fixed.

**Comment by parallels999** [comment]
that package does not handle jquery here, inherits it from the parent package
https://github.com/maximebf/php-debugbar/blob/293d02c78fd74d97e740772b079c33d61b9e90a7/bower.json#L4
