### ISSUE TITLE
debug bar showing 19-21mb memory usage on clean install laravel (welcome page)

### ISSUE THREAD

**Issue by Yogeshwar-Barai** [barryvdh/laravel-debugbar#1434]
I have tested it on laravel 8 , 9 and 10. all of them showing 19-21mb usage on welcome page while having fresh installation.
Is this normal or something is wrong with package. I have php v8.1.17 installed. i did composer update as well. but issue remains same. I have watched few installation tutorials. They have less memory usage than mine for same laravel version.

**Comment by parallels999** [comment]
![image](https://github.com/barryvdh/laravel-debugbar/assets/109294935/c1a2dc7c-e6c3-4c5f-bd65-40ab6406aa5a)

**Comment by Yogeshwar-Barai** [comment]
> ![image](https://user-images.githubusercontent.com/109294935/256009379-c1a2dc7c-e6c3-4c5f-bd65-40ab6406aa5a.png)

Are you a mac user ?

Also What do you mean by that image?

**Comment by Yogeshwar-Barai** [comment]
https://laraveldaily.com/post/default-laravel-20-mb-ram-memory-usage-windows

I found a comment regarding this issue.

**Comment by jaber-mtl** [comment]
it's not an issue, it's normal.

**Comment by erikn69** [comment]
@Yogeshwar-Barai hi, try https://github.com/maximebf/php-debugbar/pull/559, and if it works for you leave your review

**Comment by Yogeshwar-Barai** [comment]
> @Yogeshwar-Barai hi, try [maximebf/php-debugbar#559](https://github.com/maximebf/php-debugbar/pull/559), and if it works for you leave your review

Doesnt seem to work for me. I did the composer update as well. 

```
 "barryvdh/laravel-debugbar",
  "version": "v3.7.0",
```

**Comment by erikn69** [comment]
@Yogeshwar-Barai hi, There was a change, it is no longer automatic, look at https://github.com/barryvdh/laravel-debugbar/pull/1467, must be enabled by `$debugbar['memory']->resetMemoryBaseline();`, If you don't enable it, it maintains the previous functionality.

**Comment by Yogeshwar-Barai** [comment]
> @Yogeshwar-Barai hi, There was a change, it is no longer automatic, look at #1467, must be enabled by `$debugbar['memory']->resetMemoryBaseline();`, If you don't enable it, it maintains the previous functionality.
> 
> > "maximebf/debugbar": "^1.17.2"
> > "maximebf/debugbar": "^1.18.2",
> 
> ???, you have to upgrade to [maximebf/php-debugbar/releases/v1.19.0](https://github.com/maximebf/php-debugbar/releases/tag/v1.19.0)
> 
> `composer update`
> 
> Also Laravel 8 is no longer supported, i manually copied `barryvdh/laravel-debugbar, maximebf/debugbar` to vendor, and it works too, no errors

i didnt tried using that specific version. I was installing using default command. I will try and let you know.

**Comment by erikn69** [comment]
> Also your patch is yet to be merged

We have to wait for he to have a little time, and hopefully it will be merged into the package.


>I had to manually make it true or there is a command line which will be easier for users to use it rather than manual method

With my patch, on `config/debugbar.php`
```php
'options' => [
    'memory' => [
        'with_baseline' => true,  // Set boot memory usage as memory peak baseline
    ],
    ///
```
Or on a service provider 
```php
public function register()
{
    $debugbar = $this->app->make(\Barryvdh\Debugbar\LaravelDebugbar::class);
    if ($debugbar->shouldCollect('memory', true)) {
        $debugbar['memory']->resetMemoryBaseline();
    }
}
```
