### ISSUE TITLE
addDataset Error

### ISSUE THREAD

**Issue by choiks141** [barryvdh/laravel-debugbar#144]
phpdebugbar.restoreState();
phpdebugbar.ajaxHandler = new PhpDebugBar.AjaxHandler(phpdebugbar);
if (jQuery) phpdebugbar.ajaxHandler.bindToJquery(jQuery);
phpdebugbar.setOpenHandler(new PhpDebugBar.OpenHandler({"url":"http:\/\/localhost\/dailylook\/public\/_debugbar\/open"}));

phpdebugbar.addDataSet(, "f1dc193cefc66396d187502889cc138d");

**Comment by ARehmanMahi** [comment]
@barryvdh Hi, I just had the same error as above, I found one cause which is reproducible.

Laravel 11 fresh install.
using jetstream
ubuntu 24.04
php8.4.1
nginx

```php
Route::group(['group' => RouteGroupEnum::ADMINISTRATION], function (): void {
    Route::resource('users', UserController::class);
});
```

**RouteGroupEnum**
```php
declare(strict_types=1);

namespace App\Enums;

enum RouteGroupEnum
{
    case ADMINISTRATION;
}
```

using RouteGroupEnum::ADMINISTRATION as group attribute messes up debugbar: 
`phpdebugbar.addDataSet(, "X9e9f63880c3a1639bbcd79e4c852fa02"); `

if I use string type eneum it works, even if I use any other object/model class even new stdClass() it works.


```php
Route::group(['group' => new stdClass()], function (): void {
    Route::resource('users', UserController::class);
});
```
