### ISSUE TITLE
3.9.x throwing console error

### ISSUE THREAD

**Issue by archilex** [barryvdh/laravel-debugbar#1446]
Hi! Just wanted you to know that I pulled down the latest version and I'm now getting a `TypeError: Cannot read properties of undefined (reading 'length')` error when loading a page with a Livewire component. This is happening in the  "Search for duplicate statements" section and prevents debugbar from loading queries or subsequent LW calls.

I tested all the way back to LW beta 7 and still get the error. 

3.8.2 is working fine with all the latest versions of LW.

Thanks!

**Comment by browner12** [comment]
Can confirm. I am getting the exact same issue.

**Comment by orumad** [comment]
Yes, me too. I'm running Vue 2 with Laravel Mix and Laravel-debugbar v.3.9.1. And can confirm version 3.8.2 is running fine.

Thanks!

**Comment by Gawdl3y** [comment]
This is happening for me as well, although I am not using Livewire. It appears to happen on any type of AJAX request.

**Comment by angeljqv** [comment]
Maybe related https://github.com/barryvdh/laravel-debugbar/pull/1436
Feel fre to make a PR fixing that

**Comment by barryvdh** [comment]
I think I should only make the browser disabled by default. Will make a fix.

**Comment by barryvdh** [comment]
Fixed in https://github.com/barryvdh/laravel-debugbar/pull/1447 and tagged v3.9.2
Can you check if it works now?

Sorry for the delay, missed the issue.

**Comment by archilex** [comment]
Fixed. Thanks!

**Comment by orumad** [comment]
Yeah! Fixed. Thanks!!
