### ISSUE TITLE
DEBUGBAR can be ABUSED to obtain USER Credentials!

### ISSUE THREAD

**Issue by whipsterCZ** [barryvdh/laravel-debugbar#1452]
**WARNING: using debugbar at TEST or PRODUCTION environment will lead to SECURITY BREACH...**

im using (i was using) DEBUGBAR at several pages.
But we were recently hacked - Debugbar has log of all requests INCLUDING LOGIN REQUESTS with PASSWORDS!!!!

Can you share this as ATTENTION 
Or at least add some warning to README.MD , i have not clue that it can be ABUSED like this.. 

DETAILS: 
attacker found debugbar enabled on our TEST environment, but we are using same credentials on PROD
so attacker had access to our ADMIN account .

```
(/_debugbar/open?method=POST&uri=*%2Flogin&max=20&offset=0)

I found this:

"password" => {plaintext-password!}
"email" =>  {adminEmail}
```

**Comment by parallels999** [comment]
- https://github.com/barryvdh/laravel-debugbar/pull/1442
- https://github.com/barryvdh/laravel-debugbar/pull/1443

**Comment by parallels999** [comment]
> Debugbar has log of all requests INCLUDING LOGIN REQUESTS

Disable debugbar on login, just enable it whe you need, i did add a debugbar enabler button

**Comment by barryvdh** [comment]
This should already be fixed in the latest version. Browsing is disabled by default.
Note that you should still not show it on public sites, which was already mentioned in the config.
