### ISSUE TITLE
502 bad gateway when debugbar is active

### ISSUE THREAD

**Issue by ronnievisser** [barryvdh/laravel-debugbar#146]
Hi,
When setting the debug to true and when debugbar is installed my app is throwing a 502 bad gateway. When turning debug off so that debugbar isn't active everything works fine.

This issue only occurs when submitting forms.

Ronnie

**Comment by AntonioPrimera** [comment]
Hey,

all of a sudden (after no specific upgrade or anything), I get this 502 Bad Gateway if the DebugBar is enabled (when I comment out the service registration, everything works well).

Here's my nginx log for this issue:
`PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /Users/Antonio/Documents/workspace/dev/sef/vendor/symfony/debug/ExceptionHandler.php on line 405
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /Users/Antonio/.composer/vendor/laravel/valet/server.php:0
PHP message: PHP   2. require() /Users/Antonio/.composer/vendor/laravel/valet/server.php:133
PHP message: PHP   3. Illuminate\Foundation\Http\Kernel->handle() /Users/Antonio/Documents/workspace/dev/sef/public/index.php:53
PHP message: PHP   4. Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() /Users/Antonio/Documents/workspace/dev/sef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
PHP message: PHP   5. Illuminate\Pipeline\Pipeline->then() /Users/Antonio/Documents/workspace/dev/sef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
PHP message: PHP
2017/10/09 11:19:04 [error] 3149#0: *16 FastCGI sent in stderr: "pace/dev/sef/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP message: PHP  17. Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() /Users/Antonio/Documents/workspace/dev/sef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
PHP message: PHP  18. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /Users/Antonio/Documents/workspace/dev/sef/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
PHP message: PHP  19. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() /Users/Antonio/Documents/workspace/dev/sef/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP message: PHP  20. Barryvdh\Debugbar\Middleware\Debugbar->handle() /Users/Antonio/Documents/workspace/dev/sef/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
PHP message: PHP  21. Barryvdh\Debugbar\LaravelDebugbar->modifyResponse() /Users/Antonio/Documents/workspace/dev/sef/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php:60
PHP message: PHP  22. Barryvdh\Debugbar\LaravelDebugbar->injectDebugbar() /Users/Antonio/Documents/workspace/dev/sef/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php:717
PHP message: PHP  23. DebugBar\JavascriptRenderer->render() /Users/Antonio/Documents/workspace/dev/sef/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php:825
PHP message: PHP  24. DebugBar\DebugBar->getStackedData() /Users/Antonio/Documents/workspace/dev/sef/vendor/maximebf/debugbar/src/DebugBar/JavascriptRenderer.php:866
PHP message: PHP  25. Barryvdh\Debugbar\Storage\FilesystemStorage->get() /Users/Antonio/Documents/workspace/dev/sef/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php:364
PHP message: PHP  26. Illuminate\Filesystem\Filesystem->get() /Users/Antonio/Documents/workspace/dev/sef/vendor/barryvdh/laravel-debugbar/src/Storage/FilesystemStorage.php:82
PHP message: PHP  27. file_get_contents() /Users/Antonio/Documents/workspace/dev/sef/v
2017/10/09 11:19:04 [error] 3149#0: *16 FastCGI sent in stderr: "uments/workspace/dev/sef/vendor/composer/ClassLoader.php:322" while reading response header from upstream, client: 127.0.0.1, server: sef.dev, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/Users/Antonio/.valet/valet.sock:", host: "sef.dev"
`

Any ideas why this might happen?
