### ISSUE TITLE
Debugbar isn't displaying session arrays in Session-tab

### ISSUE THREAD

**Issue by NitroxydeX** [barryvdh/laravel-debugbar#1480]
This could be a super stupid question but shouldn't I see view injected array-data in the sessions-tab or somewhere else?

This works absolutely fine on livewire array data in the livewire-tab but it doesn't work on anything else.

Is this really no feature or some strange bug?

**Comment by parallels999** [comment]
Did you try `CTRL` + `SHIFT` + `R`? 
Look in the console, maybe there is some js error

**Comment by NitroxydeX** [comment]
There are absolutely no errors. Cleared browser cache.

![image](https://github.com/barryvdh/laravel-debugbar/assets/9305576/ab51c18a-3552-4408-9385-5a37669c4e7c)

**Comment by parallels999** [comment]
I don't seem to understand what you expect to see, there is the session data
![image](https://github.com/barryvdh/laravel-debugbar/assets/109294935/7ea83e8d-2da9-4d35-8ccf-73edc7c65d25)

**Comment by NitroxydeX** [comment]
@parallels999 I'm feeding the view with an array through the controller.

` return view('dashboard', $arr);`

This array is never empty. The array at least contains a state. `$arr = ['state' => 1]`

The datetime behind the "start" in my picture above is passed to the view in that same array.

So going back to my initial question: Aren't I able to see my array passed to that view through the controller inside the "Session"-Tab?

**Comment by parallels999** [comment]
Ok, I think I already understood your problem, you are looking for views data on Sessions Tab 😄
If you want to see views data, you have to look Views Tab, I don't understand why you look for it in Sessions Tab
```
views data    => Views Tab
session data  => Session Tab
queries data  => Queries Tab
etc
```

**Comment by NitroxydeX** [comment]
So it was just me confusing this as I thought.

But:
![image](https://github.com/barryvdh/laravel-debugbar/assets/9305576/08b12a26-76c0-40de-b65d-f3f4d414b673)

I'm only seeing the params here but not the actual array itself.

Is there no way to see the array-data itself in the debugbar like how it's displayed in the livewire tab?
![image](https://github.com/barryvdh/laravel-debugbar/assets/9305576/e3ee5c43-d20d-4014-b310-79bd9feb74ec)

**Comment by parallels999** [comment]
If you read the documentation you will discover that by default it only shows the keys to improve performance, but it can be configured, there are many things that are disabled to improve performance

**Comment by NitroxydeX** [comment]
I knew it was something dumb...

Well. The Note on that is a little bit misleading but I got it now. Thanks for both hints! :)

**Comment by parallels999** [comment]
`'data' => true,`
https://github.com/barryvdh/laravel-debugbar/blob/6931d7a4f2b5466ed0636fb3b0ded81ce422c63d/config/debugbar.php#L213-L217
