### ISSUE TITLE
debuge bae not showing all thbe data 

### ISSUE THREAD

**Issue by ibrahimalkhalafalnimer** [barryvdh/laravel-debugbar#1481]
I create new Laravel project with livewire and filament everything with the 
latest version
install debug bar with steps 
composer require barryvdh/laravel-debugbar --dev
and i published assets 
php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"
and now showing all the data just showing 
message, timeline ,exception
![Screenshot (7)](https://github.com/barryvdh/laravel-debugbar/assets/93493711/3c174574-b4db-4843-8e1b-8ab098ba79e8)

**Comment by parallels999** [comment]
Did you try `CTRL` + `SHIFT` + `R`? 
Look in the console, maybe there is some js error

**Comment by ibrahimalkhalafalnimer** [comment]
it worked with me after clearing browser cache
