### ISSUE TITLE
When capturing AJAX, leave the debug view on the selected request. 

### ISSUE THREAD

**Issue by adampatterson** [barryvdh/laravel-debugbar#1490]
Because the data tables have polling It's impossible to view any the data in debug bar unless I go into the code and disable polling or disable `capture_ajax` 

I think a good UX approach would be to disable the reloading once you choose one of the items leaving the focus on the selected item.

https://d.pr/i/Hy3jgX

**Comment by parallels999** [comment]
https://github.com/barryvdh/laravel-debugbar/issues/1413#issuecomment-1560484959
Always read other issues/discussions before opening a new one

**Comment by adampatterson** [comment]
@parallels999 thanks, I didn't really read "Stop auto drop down switch" as the same thing. 

It's still open so I'm not sure if it's a solution but I'll give it a try.

**Comment by parallels999** [comment]
> It's still open so I'm not sure if it's a solution

It's still open because people open an issue and never close it after getting a solution, nor do they give any feedback.

**Comment by adampatterson** [comment]
The [solution here](https://github.com/barryvdh/laravel-debugbar/issues/1413#issuecomment-1560484959) worked perfectly.
