### ISSUE TITLE
Can't select or copy SQL query from debug bar.

### ISSUE THREAD

**Issue by pronode** [barryvdh/laravel-debugbar#1495]
Hello - I would like to copy SQL query from debug bar so I can work with it elsewhere. 
However, I can't select it (debug bar just toggles query details). 
There is no "copy to clipboard" icon either. Am I missing something?

**Comment by parallels999** [comment]
> Am I missing something?

Just the basics, read
https://github.com/barryvdh/laravel-debugbar/blob/6931d7a4f2b5466ed0636fb3b0ded81ce422c63d/config/debugbar.php#L206

**Comment by angeljqv** [comment]
If it was already solved, it should be closed
