### ISSUE TITLE
Debugbar text is not visible on timeline when theme was set to dark mode.

### ISSUE THREAD

**Issue by lady-yanagi** [barryvdh/laravel-debugbar#1500]
![debugbar-text-is-not-visible-on-timeline-when-theme-was-set-dark-mode](https://github.com/barryvdh/laravel-debugbar/assets/72491828/74879f7c-4cf1-46ce-b1fb-bf57109f46a2)

I can see the text when i highlighted them.

**Comment by parallels999** [comment]
>I can see the text when i highlighted them.

How do you "highlighted them"?
![image](https://github.com/barryvdh/laravel-debugbar/assets/109294935/9a141d25-3d5e-43fa-af9a-0300ccc81bc1)

**Comment by lady-yanagi** [comment]
Like what you did,

**Comment by parallels999** [comment]
maybe you have css conflicts, if so this only happens to you

**Comment by lady-yanagi** [comment]
`vendor\barryvdh\laravel-debugbar\src\Resources\laravel-debugbar-dark-mode.css`

i guess you're right anyway I added some style. 

```
table.phpdebugbar-widgets-params td.phpdebugbar-widgets-name, td.phpdebugbar-widgets-value {
    background: var(--color-gray-900);
    color: var(--color-gray-200);
}

ul.phpdebugbar-widgets-timeline table.phpdebugbar-widgets-params td {
    border: 1px solid var(--color-gray-600);
}
```

![working-debugbar-text-is-visible-on-timeline-when-theme-was-set-dark-mode](https://github.com/barryvdh/laravel-debugbar/assets/72491828/7afb7f7e-3af9-4010-a4e1-cca5c4791875)
