### ISSUE TITLE
Debugbar stopped working with Livewire 3

### ISSUE THREAD

**Issue by PostScripton** [barryvdh/laravel-debugbar#1501]
After upgrading Livewire from V2 to V3, this tab stopped displaying any useful information:

<img width="129" alt="image" src="https://github.com/barryvdh/laravel-debugbar/assets/68855126/a56e50dc-aea9-41b9-ae15-cc4fc098204e">

**Comment by PostScripton** [comment]
Had updated up to 3.9.1 before I opened this issue, the same problem

**Comment by parallels999** [comment]
Current is [v3.9.2](https://github.com/barryvdh/laravel-debugbar/releases/tag/v3.9.2)
but feel free to open a PR with a fix.

**Comment by PostScripton** [comment]
@parallels999 oops, my bad. It was 3.9.2:

<img width="305" alt="image" src="https://github.com/barryvdh/laravel-debugbar/assets/68855126/5a88b57d-2f46-44f5-895e-86ad3b164149">

**Comment by parallels999** [comment]
Also, after upgrade `laravel-debugbar` you must reload browser cache(`Ctrl + Shift + R` shortcut)
>but feel free to open a PR with a fix.

**Comment by PostScripton** [comment]
Well, it worked after recreated Docker containers. Thanks for attention!
