### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by hassanazimi** [barryvdh/laravel-debugbar#1502]
I recently upgraded to the recent version of Laravel and i saw this error attached screenshot below

<img width="823" alt="Screenshot 2024-02-05 at 15 01 21" src="https://github.com/barryvdh/laravel-debugbar/assets/4809004/069f565a-bc96-4581-949a-41a5fb4a68fe">

```
exception: "Symfony\\Component\\ErrorHandler\\Error\\FatalErIor"
file: "/Users/hass/Sites/medialake/vendor/barryvdh/laravel-debugbar/src/DataCollector/LogsCollector.php"
line: 82
message: "Maximum execution time of 30 seconds exceeded"
trace: []
```

Don't ask for stack trace as i wasn't given

**Comment by parallels999** [comment]
Maybe too much logs

**Comment by hassanazimi** [comment]
I cleared the log but still the same but when I downgraded to 3.9.1 issue was fixed

**Comment by parallels999** [comment]
These are the differences 
https://github.com/barryvdh/laravel-debugbar/compare/v3.9.1...v3.9.2

**Comment by hassanazimi** [comment]
its probably not related to the package i assume so I'm gonna close this.
