### ISSUE TITLE
Unable to disable debugbar when app.debug is true

### ISSUE THREAD

**Issue by nuernbergerA** [barryvdh/laravel-debugbar#1514]
Hey @barryvdh 

before the latest release this combination was valid in my `.env`
![image](https://github.com/barryvdh/laravel-debugbar/assets/13331388/61324bea-e32c-4b04-857c-2510271d3468)

so my app is in debug-mode but the debubar was disabled

since v3.10.0 i get this error:
![image](https://github.com/barryvdh/laravel-debugbar/assets/13331388/11abc481-1e57-40e3-b209-2e3df9f399f3)

Cheers Adrian

**Comment by barryvdh** [comment]
Are you using a framework/cms?

Can you update to the latest version (just tagged v3.10.1)

**Comment by nuernbergerA** [comment]
@barryvdh v3.10.1 fixed it

> Are you using a framework/cms?
just Laravel 10
