### ISSUE TITLE
Undefined array key "file"

### ISSUE THREAD

**Issue by agape26** [barryvdh/laravel-debugbar#1529]
Encountered issue after the recent update v3.10.0 Performance Improvements + Better IDE Support
> Undefined array key "file" 

![v3 10 issue](https://github.com/barryvdh/laravel-debugbar/assets/130942119/253c5391-aec2-4364-b2ac-60b97e63f9e0)
](url)

**Comment by barryvdh** [comment]
How are you debugging this message? Is ths a closure?

**Comment by barryvdh** [comment]
Fixed with https://github.com/barryvdh/laravel-debugbar/issues/1529
Try to update with composer

**Comment by barryvdh** [comment]
I mean https://github.com/maximebf/php-debugbar/pull/599
