### ISSUE TITLE
 Is FilesCollector still needed?

### ISSUE THREAD

**Issue by erikn69** [barryvdh/laravel-debugbar#1539]
In the past, Laravel allowed compiling files, to improve performance, but since Laravel 5.4, the functionality was removed(https://github.com/laravel/framework/pull/17003)
>Since Laravel 5.5 will be PHP 7.0+ it makes sense to remove this feature, since the best way to optimize performance in PHP 7 is just to correctly configure opcache to what's best for your server and websites.
>>I plan to remove this on 5.4.

`FilesCollector` was used to check which files were not compiled, and decide if they should be added for compilation

https://github.com/barryvdh/laravel-debugbar/blob/6727dad59d7135deb7ada07e0f6f475a86cc1b35/src/DataCollector/FilesCollector.php#L83-L96
this collector was designed to copy and paste into the config file
https://github.com/barryvdh/laravel-debugbar/blob/6727dad59d7135deb7ada07e0f6f475a86cc1b35/src/DataCollector/FilesCollector.php#L46-L47

So my question would be, **Is FilesCollector still needed? Should it be updated to the current version?**

**Comment by barryvdh** [comment]
I dont think its needed anymore indeed.
