### ISSUE TITLE
Auth::check() return false if Debugbar enable

### ISSUE THREAD

**Issue by Nishchit14** [barryvdh/laravel-debugbar#156]
Hi friend,

 This is awesome package for debugger , Thank you very much. I am getting one problem , I did lots of googling but it all west, 

I have two userType(1 & 2). When i configure debugbar user1 already loggedin, But when i logout it and try to login with user2 , It Auth::check() return false.

My login logic is:

First i send login api it gives me true flag, So i reload same page with angular,
Then Index function check Auth::check(), if it gives true then load index.php otherwise login.php

 While login with user2 login api gives flag true means Auth::attempt successfully,
But when reload Auth::check() fails; 

Also i set session data on login, I can see this data successfully on debugbar.
But page always render login page.

When i try to login with user1 its working properly.

Here is session data:

![image](https://cloud.githubusercontent.com/assets/5078921/3560860/94ec9c32-0993-11e4-97ce-8a132669b96e.png)

But Auth gives:

![image](https://cloud.githubusercontent.com/assets/5078921/3560862/a6eda656-0993-11e4-83be-30289a992cdb.png)

Thanks in advance. 

-ND

**Comment by aghidayat** [comment]
i also have a same problem
