### ISSUE TITLE
DebugBarException "'mail' is not a registered collector" on 3.11.0

### ISSUE THREAD

**Issue by jnoordsij** [barryvdh/laravel-debugbar#1568]
When sending mails within my Laravel application with debugbar active, the following `DebugBarException` is shown: `'mail' is not a registered collector`.

My assumption is this is a regression introduced in #1521, which assumes the collector added in the mail scope to be `'mail'`. However, the current name of this collector is `'symfonymailer_mails'` (see https://github.com/maximebf/php-debugbar/blob/a8694a4e0ee2291d13de5ff1d700d94393366511/src/DebugBar/Bridge/Symfony/SymfonyMailCollector.php#L66).

Possible solutions:
- rename at one of the two places
- partially revert changes from #1521

This issue is not present on 3.10.6.

**Comment by erikn69** [comment]
would just have to change `mail` to `symfonymailer_mails`?

**Comment by barryvdh** [comment]
Fixed with #1570
