### ISSUE TITLE
Question about the dataset switcher

### ISSUE THREAD

**Issue by theupriser** [barryvdh/laravel-debugbar#1592]
Hello!

I've found that the dataset switcher won't enable by itself. 
In Laravel 10 I could force it to show by adding the StartSession and ShareErrorsFromSession middleware to the global middleware stack.

However.. Laravel 11 does not like this and will not forward flashed session data anymore.

Is there any way to enable this without tampering with middleware placement?

![image](https://github.com/barryvdh/laravel-debugbar/assets/5661837/7d6e5dca-10fa-4308-95ad-3280630bff6c)

Edit:
I solved it by doing this for now.. but I think it's not really meant to be done like this.
![image](https://github.com/barryvdh/laravel-debugbar/assets/5661837/66d6b31d-3e5a-41a3-a095-d0d755418ce1)

With kind regards,

Rick

**Comment by barryvdh** [comment]
Can you try https://github.com/barryvdh/laravel-debugbar/pull/1591 ?

**Comment by barryvdh** [comment]
Please try dev-master for now

**Comment by theupriser** [comment]
This fixes my issue once and for all! Thanks Barry!
