### ISSUE TITLE
TypeError: data.__meta is undefined

### ISSUE THREAD

**Issue by darkons** [barryvdh/laravel-debugbar#1614]
I just did a clean install of Laravel 11 and found this javascript error in the browser console.

After some research, I have found that the package `maximebf/php-debugbar` has suffered a change in its version 1.22 which is used by `barryvdh/laravel-debugbar` since version 3.13.

The problem seems to be that now the `addDataSet` method expects the `__meta` property, however, it is not receiving it.
https://github.com/maximebf/php-debugbar/blob/v1.22.0/src/DebugBar/Resources/debugbar.js#L944

I hope this information will help to solve the problem.

**Comment by barryvdh** [comment]
Are you using a custom configuration?

**Comment by parallels999** [comment]
Did you reload browser cache?

**Comment by darkons** [comment]
> Are you using a custom configuration?
Nope, just default one.


> Did you reload browser cache?
Yeah, tried on Firefox and Chrome. In both with cache disabled, private tabs and forcing with CTRL+F5.

Laravel 11 + Breeze Inertia/Vue stack.

**Comment by parallels999** [comment]
Maybe a validation is needed in case no data comes, sometimes an exception json may come, and there is not `__meta`
![image](https://github.com/barryvdh/laravel-debugbar/assets/109294935/9e379656-08e5-42c8-9409-1fc930cbd1e1)
![image](https://github.com/barryvdh/laravel-debugbar/assets/109294935/4f95528e-f108-4190-af1e-f3e1725914e9)
