### ISSUE TITLE
Debugbar non stop ajax requests

### ISSUE THREAD

**Issue by rnleal** [barryvdh/laravel-debugbar#1619]
Debugbar sends non stop ajax get request to the custom Route prefix set (v2/_debugbar)

https://github.com/barryvdh/laravel-debugbar/assets/60339084/27a00447-6a82-4428-9d13-3406fa271c00

**Comment by barryvdh** [comment]
Can you check if https://github.com/barryvdh/laravel-debugbar/pull/1616 works for you? I'll tag a new release then.

**Comment by barryvdh** [comment]
Should be fixed with latest release.

**Comment by rnleal** [comment]
Thank you @barryvdh. Confirming that fixed the issue.
