### ISSUE TITLE
filter networks history to ignore useless networks 

### ISSUE THREAD

**Issue by fredimitchel** [barryvdh/laravel-debugbar#1635]
In our app, we have a keep alive polling which interact with the server to keep the session alive.

But Debugbar is logging this network ping which doesn't make sense and avoid us to use the auto select feature.

Feature request: be able to set a rule to ignore specific routes.

**Comment by erikn69** [comment]
https://github.com/barryvdh/laravel-debugbar/blob/bd8edca124f84d14203b29698f8f204c8eabc960/config/debugbar.php#L13-L21
