### ISSUE TITLE
Change path to quickly open vscode files / Can't open vscode://file with WSL

### ISSUE THREAD

**Issue by WebCimes** [barryvdh/laravel-debugbar#1643]
Hi,

When I use Laravel Debugbar on Windows 11, if I run my local server directly from PowerShell with php artisan serve, everything works, and I can use the shortcut `vscode://file/N:\sites\myproject\test.php:5`, for example, and VS Code opens the file directly from the browser shortcut in Laravel Debugbar.

However, if I use WSL with Debian and run the server directly from Debian with php artisan serve, the route can't open with the shortcut `vscode://file//mnt/n/sites/myproject/test.php:5`. VS Code says, "The path doesn't exist."

My project is on a NAS (letter N), and everything works well directly inside VS Code (with or without WSL). I also have the WSL extension for VS Code, so I can open files directly in VS Code using WSL with `code myfile.php`, for example.

I think the problem is that the browser is running on Windows and the server is on WSL Debian, so the link to access files quickly doesn't work.

Is there a way to configure Debugbar to always use `N:\sites\myproject instead of //mnt/n/sites/myproject` instead of `//mnt/n/sites/myproject` for the `vscode://file/... shortcut`?

Thanks for your help.

**Comment by parallels999** [comment]
https://github.com/barryvdh/laravel-debugbar/blob/150ac5d7d238191cac44156e9a55c7309f4b7523/config/debugbar.php#L90

**Comment by WebCimes** [comment]
Thanks for your answer. When I set local_sites_path to `N:\sites\myproject`, it seems to work for shortcuts inside the bottom panel (Exception, View, Routes, Queries, Models, etc.), but not inside the exception panel.

In the screenshot below, the green-highlighted part works with local_sites_path, and I get `N:\sites\myproject`. However, in the red-highlighted part, I always get `//mnt/n/sites/myproject`.

I have also try to type `php artisan debugbar:clear` and remove the `storage/debugbar` folder for prevent caching issue.

![image](https://github.com/user-attachments/assets/83c8dab5-aa99-4866-861d-0a17f250bb51)

**Comment by parallels999** [comment]
> in the red-highlighted part, I always get //mnt/n/sites/myproject.

The red-highlighted part is not part of laravel-debugbar, it is [spatie/laravel-ignition](https://github.com/spatie/laravel-ignition)
They are two completely different packages.

That why I pointed out `IGNITION_LOCAL_SITES_PATH` as `.env` config

**Comment by WebCimes** [comment]
Thanks for your help, you are right sorry for my mistake
