### ISSUE TITLE
Vardump + xdebug link alignment issue

### ISSUE THREAD

**Issue by martijngastkemper** [barryvdh/laravel-debugbar#1644]
In the `HtmlVariableListWidget` widget the alignment breaks when you the vardumper output as value and a xdebug link:

![Screenshot 2024-08-26 at 09 54 15](https://github.com/user-attachments/assets/787b136c-aad3-41e4-baea-98d6301c02d9)

The links are pushed down by the vardumper element and disappear behind the gray rows.

I've tried to create a PR, but it's a bit harder then expected. The PHP debugbar styling works, but the vardumper, added by Laravel debugbar, breaks it. I've tried making the vardumper element float left, because the xdebug link floats right. But that breaks the row height. Hopefully someone with better CSS skills nows how to fix issue.

**Comment by parallels999** [comment]
Maybe related: https://github.com/barryvdh/laravel-debugbar/pull/1601#issuecomment-2031562905

**Comment by parallels999** [comment]
Which tab is it? doesn't it appear to me?

![image](https://github.com/user-attachments/assets/01874272-5404-46ac-a925-829299ccebac)

**Comment by erikn69** [comment]
Try https://github.com/maximebf/php-debugbar/pull/668, 
don't forget to reload the browser cache too

**Comment by martijngastkemper** [comment]
It's a custom collector I made with application specific debug information in it. 

That pull request looks like the same problem. Thanks for the tip. Hopefully it's getting merged soon. I'll test it tomorrow.
