### ISSUE TITLE
downloadable font: Glyph bbox was incorrect error

### ISSUE THREAD

**Issue by eznix86** [barryvdh/laravel-debugbar#1645]
Referenced here:

https://github.com/barryvdh/laravel-debugbar/issues/1614#issuecomment-2049816544
https://github.com/FortAwesome/Font-Awesome/issues/19925

Currently using:
barryvdh/laravel-debugbar 3.13.5
which depends on:
maximebf/debugbar 1.22.3

Currently on laravel 11.20.0

**Comment by parallels999** [comment]
Did you reload browser cache?

maybe FortAwesome/Font-Awesome will be removed in the future: https://github.com/maximebf/php-debugbar/issues/598
This already was reported here: https://github.com/maximebf/php-debugbar/issues/598#issuecomment-2214842226

Also, feel free to make a PR with a fix
