### ISSUE TITLE
Preserve SQL queries log

### ISSUE THREAD

**Issue by ahmadxgani** [barryvdh/laravel-debugbar#1671]
How to preserve SQL queries log when the page redirected or reloaded?

**Comment by barryvdh** [comment]
You can view the history using the browse button.

**Comment by ahmadxgani** [comment]
Could you please tell me where the "browser button" is? I can't seem to find it.

**Comment by barryvdh** [comment]
Top right, left from the down arrow.

**Comment by ahmadxgani** [comment]
I see..., thanks for the hint!
