### ISSUE TITLE
Uninitialized string offset 0 on V3.14 . works on lower version

### ISSUE THREAD

**Issue by anwarsendleads** [barryvdh/laravel-debugbar#1676]
[2024-09-22 21:24:55] local.ERROR: Uninitialized string offset 0 {"exception":"[object] (ErrorException(code: 0): Uninitialized string offset 0 at /var/www/html/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php:908)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Uninitialized s...', '/var/www/html/v...', 908)
#1 /var/www/html/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(908): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Uninitialized s...', '/var/www/html/v...', 908)
#2 /var/www/html/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(839): Barryvdh\\Debugbar\\LaravelDebugbar->isJsonRequest(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))
#3 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(72): Barryvdh\\Debugbar\\LaravelDebugbar->modifyResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#20 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#21 {main}
"}

**Comment by FdvTerje** [comment]
Can confirm this, we got the same error on our team and reverting back to v3.13 fixed it for us for now

**Comment by emilebourquin** [comment]
I am also experiencing this issue, can confirm reverting to v3.13 makes the issue go away.

**Comment by erikn69** [comment]
https://github.com/barryvdh/laravel-debugbar/pull/1677#discussion_r1772110619

**Comment by Jamesking56** [comment]
Managed to downgrade to v3.13.5 locally by:

1. Add conflict to `composer.json`:

```json
"conflict": {
    "barryvdh/laravel-debugbar": "=3.14.0"
},
```

2. Run `composer require --dev -W barryvdh/laravel-debugbar`

This should downgrade it to v3.13.5 and stop v3.14.0 from being able to be installed in the future. It should not stop updates past v3.14.0 from being installed.

**Comment by enikeishik** [comment]
Confirm the same error, in LaravelDebugbar.php on line 908 uses $content[0] without checking existing of this element.

**Comment by barryvdh** [comment]
Sorry all, should be fixed with https://github.com/barryvdh/laravel-debugbar/releases/tag/v3.14.1
