### ISSUE TITLE
Git Ignore 

### ISSUE THREAD

**Issue by lozadaOmr** [barryvdh/laravel-debugbar#168]
I have question which happens after setting laravel-debugbar.

when I did `git status`

It had the following as untracked files

app/storage/debugbar/
public/packages/barryvdh/
public/packages/maximebf/

I'm unsure as what is the best practice in this situation so,
Should I add them to the repository or just ignore them and put it the .gitignore?

**Comment by steven7mwesigwa** [comment]
> @barryvdh Dead link.

Live link here:
https://github.com/barryvdh/laravel-debugbar/blob/cae0a8d1cb89b0f0522f65e60465e16d738e069b/src/Storage/FilesystemStorage.php#L36
