### ISSUE TITLE
Uncaught TypeError: statements is not iterable

### ISSUE THREAD

**Issue by shankhadevpadam** [barryvdh/laravel-debugbar#1685]
https://github.com/barryvdh/laravel-debugbar/blob/c0bee7c08ae2429e4a9ed2bc75679b012db6e3bd/src/Resources/queries/widget.js#L113

**Comment by parallels999** [comment]
CC: @tpetry

**Comment by jonathan-bird** [comment]
+1 on this new bug

**Comment by tpetry** [comment]
Do you have some more informations? Because for statements not to be iterable it must be something else than an array. And I dont know currently how that should be possible.

**Comment by jonathan-bird** [comment]
@tpetry It's undefined for me. 

Probably unhelpful, but I run the latest version of everything (PHP, Laravel, Chrome etc)

**Comment by barryvdh** [comment]
Should there be any queries? Or are you not running them?

**Comment by jonathan-bird** [comment]
Yeah there's lots of queries being run, they're not showing up in the Queries tab and this is the console error. Let me know if there's anything specific you'd like me to check.

**Comment by barryvdh** [comment]
Can you see what 'statements' actually contains? Either in the json from storage or sourcecode?

**Comment by jonathan-bird** [comment]
@barryvdh I checked `this.identifyDuplicates(data.statements);` and data returned empty array, thus causing `data.statements` to be undefined when passed to the method.

**Comment by jonathan-bird** [comment]
Doesn't seem to be an error on all pages though, just some. I double checked that there are queries being run on that page that has the error occurring too.

**Comment by tpetry** [comment]
Can you try finding out which exact version broke this?

**Comment by barryvdh** [comment]
Or maybe disable the EXPLAIN options, or other options in the config for DB collector?

**Comment by tpetry** [comment]
> Or maybe disable the EXPLAIN options, or other options in the config for DB collector?

The EXPLAIN option is only for interactivity after loading it first. This seems to be a general issue with the query widget.

**Comment by jonathan-bird** [comment]
@tpetry Confirmed working in v3.13.5 but not working in v3.14.0

**Comment by bennettblack** [comment]
I'm seeing this error too with `v3.14`; I noticed it causes the "queries" tab to be empty. The error goes away when I disable `with_params` in the config.

**Comment by tpetry** [comment]
> I'm seeing this error too with `v3.14`; I noticed it causes the "queries" tab to be empty. The error goes away when I disable `with_params` in the config.

Thats more strange. Because that option changes how the SQL is rendered - and nothing about the list. 

Can you reduce your script to a single query that affects the issue? Or at least to as less as possible? And then `dd()` the `$data` in the `QueryCollector:: collect()` method at the end? Once with disabled and once with enabled? As we don't experience the issue we need to see the data whether something is off.

**Comment by bennettblack** [comment]
@tpetry After doing some digging, it looks like this is failing Laravel-side here:

```php
// QueryCollector.php @getSqlQueryToDisplay
DB::connection($query['connection'])->getQueryGrammar()->substituteBindingsIntoRawSql($sql, $query['bindings'] ?? []);
```

I'm using a custom DB driver that doesn't support escaping values. This worked with previous versions, I'm guessing some of the new collector changes might have affected this. In my case, I can handle this with my driver.

**Comment by barryvdh** [comment]
Any others also using a custom driver? Or just mysql?

**Comment by jonathan-bird** [comment]
Just MySQL for me.

**Comment by barryvdh** [comment]
I do have a feeling that it might be about the escaping of the params, or the encoding of it. Are there any specific object you put in those queries?

**Comment by barryvdh** [comment]
Is the issue same with the new v3.14.4?

**Comment by jonathan-bird** [comment]
@barryvdh Looks to have fixed it for me, thanks!

**Comment by shankhadevpadam** [comment]
Now it's fixed. Thanks

**Comment by bennettblack** [comment]
@barryvdh Me as well!

**Comment by mariomeyer** [comment]
Also getting this new bug.. +1

**Comment by tpetry** [comment]
> Also getting this new bug.. Also goes away if I set `with_params` to `false`... +1

Did the new version resolve the issue?

**Comment by cwdt** [comment]
> I'm having a similar JS issue [here](https://github.com/barryvdh/laravel-debugbar/blob/c0bee7c08ae2429e4a9ed2bc75679b012db6e3bd/src/Resources/queries/widget.js#L337):
> 
> ![image](https://private-user-images.githubusercontent.com/543690/385318683-1cd31e0b-f7fb-428f-9015-5b2550d41b2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTgxOTIsIm5iZiI6MTczMTQ5Nzg5MiwicGF0aCI6Ii81NDM2OTAvMzg1MzE4NjgzLTFjZDMxZTBiLWY3ZmItNDI4Zi05MDE1LTViMjU1MGQ0MWIyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMTM4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2QxODI4YzhjMWM0NGRjOTBlZjYzNmZmYWJiMGQyZmRiNjQ1MDg1MDVlYjczNDg5MDFiNmYxODk1NDJjMDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7cB4VX4LoJ9rhHGnmCGodSXRJ1TenK1AwgipPl9Xiag)
> 
> This causes the Models, Mails, Gate,Session and Request Tabs to be empty.
> 
> I'm using v3.14.6

I'm having the same issue as @maxxscho.
The bindings can either be an array or an object. If I understand correctly, the JS only expects an array.

**Comment by erikn69** [comment]
Hi @cwdt @maxxscho, please try #1701

**Comment by maxxscho** [comment]
@erikn69 works perfect. Thank you very much!

@barryvdh will there be a new release in the near future? 🙃

**Comment by barryvdh** [comment]
Yes new version is released. Let me know if there are any issues still.

**Comment by maxxscho** [comment]
Works perfect. Thank you 🙏🏻 !
