### ISSUE TITLE
GateCollector::addCheck errors when target is a model with no key

### ISSUE THREAD

**Issue by sparksp** [barryvdh/laravel-debugbar#1688]
I believe that #1653 introduced an undesirable bug when using a Model with no key as the target for a gate check.

It presents itself as `The attribute [id] either does not exist or was not retrieved for model [App\Models\ModelName].` and took me quite a while to realise it was a problem with debug bar, and not with my code, as the vendor trace is hidden by default.

I have a model `Attendance` which extends from `Illuminate\Database\Eloquent\Relations\Pivot`. Instances are unique by the `foreignKey` and `relatedKey`. [`AsPivot` handles this internally](https://github.com/laravel/framework/blob/3818c2adbb51219665641cf5a5d733bb8c84c3bb/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php#L92-L105) and makes an `isset` check for any primary key before setting keys for query manually.

In the case of a Pivot model, you could use the foreign and related keys in the description. But I can imagine a case where a model has been fetched without its `id` which would still break this feature, so it may be wise to include an `isset` check of your own and fall back to no description?

**Comment by barryvdh** [comment]
Hmm so what is `getKeyName()` then? It seems like default Laravel, so weird it would crash. Normally Models don't crash on not-existing properties, right?

**Comment by barryvdh** [comment]
Can you try to make a PR ?

**Comment by sparksp** [comment]
> Hmm so what is `getKeyName()` then? It seems like default Laravel, so weird it would crash. Normally Models don't crash on not-existing properties, right?

In this case `getKeyName()` is still `"id"` as that is the default set by Model. But the model has no `id`, and there is no other sensible attribute I can use here.

I use [`Model::shouldBeStrict()`](https://laravel-news.com/shouldbestrict) in all my projects, which will throw an exception when you try to access a missing attribute - this helps me to spot errors in development quickly from typos or overly restrictive queries.

> Can you try to make a PR ?

Yes, for sure. I might find some time next week, otherwise I'll have time in early November.

**Comment by barryvdh** [comment]
Can you test https://github.com/barryvdh/laravel-debugbar/pull/1691 ?

**Comment by niladam** [comment]
This for reason creates issues with https://github.com/bezhanSalleh/filament-shield who's using [spatie's permission](url) and outputs an error like `Call to undefined method App\Models\Role::hasAttribute()`;

In order for this to be confirmed, toggling the gate collector shows this.

**Comment by sparksp** [comment]
Happy to confirm this is working for my case also.
