### ISSUE TITLE
Error message flooding my laravel.log

### ISSUE THREAD

**Issue by avn-dev** [barryvdh/laravel-debugbar#1689]
In combination with laravel-pulse this is getting spammed in my logfile (when I'm viewing a /pulse resource):
=> most recent laravel, pulse & debugbar version installed
database: sqlite

[2024-10-17 03:32:52] Debugbar exception: Strings with null bytes cannot be escaped. Use the binary escape option.

**Comment by barryvdh** [comment]
Seems similar to https://github.com/laravel/telescope/issues/1489 so probably related to use also doing substituteBindingsIntoRawSql

I tried https://github.com/barryvdh/laravel-debugbar/pull/1690 as fix
