### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by barryvdh** [barryvdh/laravel-debugbar#170]
Just a list to keep track of things that may or may not be possible/useful:

QueryCollector:
- [ ] Show part of the results (#169)
- [x] Show the origin/source of the query (#140)
- [ ] Show EXPLAIN / performance tips on queries
- [ ] Look for the N+1 trap (instead of Eager Loading)

LogsCollector:
- [ ] Log Browser

ViewCollector:
- [ ] Seperate global/shared variables from template variables
- [ ] Show source filename

**Comment by aik099** [comment]
> Show EXPLAIN / performance tips on queries

We might use code from Phabricator, where it analyzes EXPLAIN results and show badness index that allows to determine if query is bad or good without looking into EXPLAIN results.

It looks like this (the color indicates badness level, but text shows meaning): 

<img width="995" alt="2017-08-16_1910" src="https://user-images.githubusercontent.com/1277526/29373360-a56d3162-82b6-11e7-9e96-e33fa967dfc4.png">

This could probably incorporated into EXPLAIN results or even Hints.

Actual code is here: https://secure.phabricator.com/source/phabricator/browse/master/src/applications/console/plugin/DarkConsoleServicesPlugin.php;7bbd26427f8c360e4c3796d2f5305518f3da4a9e$62-137

**Comment by JohnRoux** [comment]
This one is super ancient, But it was one of the only issues which mentioned further explain analysis.

Would be really nice to get some good index helper guides as optional flags.

I was playing around with adding a DB:listen and doing an explain analyze behind the scenes to track down queries which aren't using indexes well and instead are doing a lot of table scanes.

I don't know of any nice tools which can take something like a mysql explain analyze and clean it up a little.

Would this be something worth me sinking some time into?

For now I'm just doing something like this in my codebases:

```
                $explainAnalyze = DB::scalar("EXPLAIN ANALYZE " . $query->sql, $bindings);
                if(Str::contains($explainAnalyze, 'Table scan')) {
                    Log::info('SQL LOG: Found Slow Table Scan', ['sql' => $sql_with_bindings, 'analyze' => $explainAnalyze]);
                }
                elseif($query->time > $alwaysShowFullExplainAnalyzeIfItTakesLongerThan) {
                    Log::info('SQL LOG: Slow Query Explained:', ['time' => $query->time, 'sql' => $sql_with_bindings, 'analyze' => $explainAnalyze]);
                }
                ```

**Comment by parallels999** [comment]
It would be great to at least have the resulting records count per query, I mean count of CREATED/UPDATED/DELETED/FETCHED rows

- On  https://github.com/laravel/framework/pull/48643  was almost possible through the event `QueryExecuted`
