### ISSUE TITLE
Disable debugbar on some routes

### ISSUE THREAD

**Issue by Thijmen** [barryvdh/laravel-debugbar#172]
Hi,

I'd like to disable the debugbar on some routes. I am developing a REST API and each time, the API attaches the debugbar :) I'd like to disable this for some routes.

Is this possible?
Thanks in advance.

**Comment by lukepolo** [comment]
How do you do this in laravel 5 ?

**Comment by lukepolo** [comment]
look at #409

**Comment by kheme** [comment]
I called this within my control, and it worked for me:

`app('debugbar')->disable();```

**Comment by besrabasant** [comment]
I just use a handly middleware in my route group.

[https://gist.github.com/besrabasant/dd46023f2e09a9000db6db26099e0ae1](https://gist.github.com/besrabasant/dd46023f2e09a9000db6db26099e0ae1) 

Then, in your `web.php`

```php
Route::group(['middlware' => 'noDebugbar'], function() {
    
  Route::get('/', function() {
     return view('view');
  });
  
});
```
