### ISSUE TITLE
POSTed form redirest as GET with debugbar

### ISSUE THREAD

**Issue by ptim** [barryvdh/laravel-debugbar#176]
Hi! Thanks for debugbar!

Since installing debugbar: my form(method=GET, action=self) is being redirected, and so the page loads as GET instead.

If I disable debugbar completely, or adapt your suggestion above, then the form works as expected.

This SO question is similar to my scenario: http://stackoverflow.com/questions/17240767/form-submits-as-get-laravel-4

I think I've followed the install directions closely (got assets, config, calling db via `Debugbar::info($object);` facade works)
Am I missing something?

TIA, Tim

**Comment by amenk** [comment]
I have the same problem :-(

**Comment by amenk** [comment]
In my case I have a 

    <script>
        $('#email_quicklogin').change(function() {
            $('#email').val($(this).val());
            $('#password').val('dev');
            $('form').submit();
        });
    </script>

When I replace the last line with 

           $('form .btn-primary').click();

it works...

**Comment by emilv** [comment]
@amenk `$('form')` finds all `<form>` elements on the page. Try a more specific query. I don't think that is a problem with Debugbar.

**Comment by amenk** [comment]
The problem seems to be, that the debug bar itself has some form included. Still an unpretty side effect of the debug bar I think, but can probably not be easily fixed... Maybe it should just be noted in the readme?

**Comment by barryvdh** [comment]
Just restrict your submit to the parent form, not just any form. That will lead to problems later on anyway..

**Comment by amenk** [comment]
Yes, sure -- never said that code is good :-)
Just I feel that a debug tool should document it's side effects.

2017-01-27 14:09 GMT+01:00 Barry vd. Heuvel <notifications@github.com>:
