### ISSUE TITLE
There are no commands defined in the "debugbar" namespace if ServiceProvider is in {environment}/app.php

### ISSUE THREAD

**Issue by jonwhittlestone** [barryvdh/laravel-debugbar#18]
Hi

After installing the service provider in the configured environment `config/local/app.php` , after running `php artisan debugbar:publish` I get:

`There are no commands defined in the "debugbar" namespace`

Inserting just in `config/app.php` is OK however.

Not sure if this is intentional.

**Comment by xadim** [comment]
Hey I'm having the same issue, what's the matter please?

**Comment by barryvdh** [comment]
You don't need to publish anymore.

**Comment by xadim** [comment]
what do you mean?

**Comment by xadim** [comment]
I just can't get the debuger running in Laravel 5 local env.

**Comment by barryvdh** [comment]
Okay then open your own issue with more information

**Comment by xadim** [comment]
Alright, Thanks!
