### ISSUE TITLE
Cannot add MailCollector to Laravel Debugbar: array_replace_recursive(): Argument #2 is not an array

### ISSUE THREAD

**Issue by DrudgeRajen** [barryvdh/laravel-debugbar#181]
Debugbar is working fine in my localhost.But in production server it is giving this error .
Cannot add MailCollector to Laravel Debugbar: array_replace_recursive(): Argument #2 is not an array
Due to which javascript is not working.What is the problem can any body help me out here?

**Comment by mehrang13** [comment]
hi
im using laravel 9
this is exceptios:
Cannot add MailCollector to Laravel Debugbar: Method Illuminate\Mail\Mailer::getSwiftMailer does not exist.
and
Method Illuminate\Mail\Mailer::getSwiftMailer does not exist.
![Screenshot 2022-02-09 001126](https://user-images.githubusercontent.com/36799592/153072080-77c58ef1-2e16-4bdc-8bd1-e53fff377b6c.png)

**Comment by rrpadilla** [comment]
> hi im using laravel 9 this is exceptios: Cannot add MailCollector to Laravel Debugbar: Method Illuminate\Mail\Mailer::getSwiftMailer does not exist. and Method Illuminate\Mail\Mailer::getSwiftMailer does not exist. ![Screenshot 2022-02-09 001126](https://user-images.githubusercontent.com/36799592/153072080-77c58ef1-2e16-4bdc-8bd1-e53fff377b6c.png)

I'm having the same issue.
- Laravel 9.0
- PHP 8.1.2
Ping @barryvdh
