### ISSUE TITLE
app.url

### ISSUE THREAD

**Issue by raulp** [barryvdh/laravel-debugbar#185]
Hey guys

Question: i'm trying to do App::before() ... and if request is secure, to change the app.url to https.
Problem is, the assets are still loaded from app.url which is http.

``` php
App::before( function( $request )
{
    Request::setTrustedProxies( Config::get('app.proxies') );
    if(Request::secure())
    {
        $app_url = Config::get('app.url');
        Config::set('app.url', str_replace("http://","https://",$app_url));
    }
});
```

Then, to test, i have:

``` php
Route::get("/test", function() {
    echo Config::get('app.url');
}
```

That outputs the correct SSL url ... but the package resources ( js/css)  are still loaded from the original http url.
Also, very strange, that on my local machine, where i don't have nginx in front as a proxy, it works. But on the staging server it does not. And i checked that the resource can be loaded via https, just to exclude a rewrite rule from somewhere.

Any ideas will be appreciated. 

Thanks

**Comment by marceux** [comment]
@raulp Hey, what did you do to fix the issue?  I'm having a similar one in my application hosted on AWS.  Everything is getting routed via an .htaccess file right now.

**Comment by mln-mln-mln** [comment]
hi, I am still having this issue. Can anyone tell me how to fix this?

**Comment by raulp** [comment]
hey guys, long time ago ... but as far as i remember i did a location block in nginx 
Also, as @barryvdh mentioned, i had to upgrade to a different version

Sorry guys, but can't remember what i did almost 2 years ago, considering i am no longer maintaining that specific project.
