### ISSUE TITLE
assets.css and assets.js not found

### ISSUE THREAD

**Issue by anthonywkchan** [barryvdh/laravel-debugbar#187]
Hi, I just updated to the latest laravel-debugbar and now I'm getting 404 Not Found errors when loading 

/_debugbar/assets.css?xxxxx
/_debugbar/assets.js?xxxxx

I can see that the routes are properly registered, but for some reason Nginx is not routing it correct. Could it be my Nginx config? Here is my config taken from the Server section below:

```
    location / {

        # URLs to attempt, including pretty ones.
        try_files   $uri $uri/ /index.php?$query_string;

    }

    # Remove trailing slash to please routing system.
    if (!-d $request_filename) {
        rewrite     ^/(.+)/$ /$1 permanent;
    }

    # PHP FPM configuration.
    location ~ \.php$ {
            fastcgi_pass                    unix:/var/run/php-fcgi.sock;
            fastcgi_index                   index.php;
            fastcgi_split_path_info         ^(.+\.php)(/.+)$;
            include                         /etc/nginx/fcgi.conf;
            fastcgi_param                   SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # We don't need .ht files with nginx.
    location ~ /\.ht {
            deny all;
    }

    # Set header expirations on per-project basis
    location ~* \.(?:ico|css|js|jpe?g|JPG|png|svg|woff)$ {
            expires 365d;

    }
```

**Comment by epileftro85** [comment]
hi i know that it is old but, i have the same very issue, then i realize that my route was working with controller, instead of get, for example
```php
Route::controller('/', 'MainController');
```
in this case i get a notFoundExeptiont, so, i have to move my routes to Route::get to get it work, but maybe it would be nice if it could work with controllers routes, because i don't like many route for my application instead of one file content the main routes, cheers

**Comment by ashdownadvisorygroup** [comment]
Hi, 
I have thesame problem , i my case i resolve by activiting the apache rewrite module so that i would not need to type index.php after /public .

**Comment by nosun** [comment]
@ashdownadvisorygroup  maybe your nginx setting is wrong,i met the same issue,but its my fault

**Comment by MakeApps** [comment]
After updating composer, add the ServiceProvider to the providers array in config/app.php

> **If you use a catch-all/fallback route, make sure you load the Debugbar ServiceProvider before your own App ServiceProviders.**

**Comment by eduardoarandah** [comment]
I fixed it with 

`php artisan cache:clear`
