### ISSUE TITLE
Allowed memory size exhausted after installation

### ISSUE THREAD

**Issue by jonwhittlestone** [barryvdh/laravel-debugbar#19]
Hi

At installation, after having published the assets successfully with `php artisan debugbar:publish`

I then try to refresh any page on my site and get

```
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 679477248 bytes exhausted (tried to allocate 669253632 bytes)' 
```

I had increased my memory limit in `php.ini` from 512M to 648M to no avail.

Thanks.

Jon.

**Comment by kevnk** [comment]
> Publish the config file: `php artisan config:publish barryvdh/laravel-debugbar` and edit app/config/packages/barryvdh/laravel-debugbar/config.php, to comment out some of the collectors.
> You can also disable the service providers to see what package is not working well with the debugbar.

The command now is `php artisan vendor:publish --provider=barryvdh/laravel-debugbar`
