### ISSUE TITLE
FatalErrorException: Call to undefined method Barryvdh\Debugbar\Facade::warning()

### ISSUE THREAD

**Issue by jonwhittlestone** [barryvdh/laravel-debugbar#20]
Hi

After adding `'Debugbar' => 'Barryvdh\Debugbar\Facade'` to the `aliases` array in `app.php`

I then try to execute one of my controller actions containing the following:

```
public function getIndex(){
Debugbar::warning('Watch out..');
}
```

But I receive the following error:

```
 Symfony \ Component \ Debug \ Exception \ FatalErrorException
Call to undefined method Barryvdh\Debugbar\Facade::warning()
```

Have I included the facade incorrectly?

Thanks a lot for you help.

**Comment by godfreykori** [comment]
@jonwhittlestone instead of 

use DebugBar\DebugBar;

do this

use Debugbar;

That will work

**Comment by lawsonjt** [comment]
I was getting the same issue.  Adding `use Debugbar;` like godfreymakori mentioned worked, but it is strange because normally it should be `use Debugbar\Debugbar;`

**Comment by vihangarajalingam** [comment]
> Are you in a namespace? If so, you can do \Debugbar::warning('Watch out..');

This works

**Comment by iwasherefirst2** [comment]
> @jonwhittlestone instead of
> 
> use DebugBar\DebugBar;
> 
> do this
> 
> use Debugbar;
> 
> That will work

I had the same issue. When I use autoimport from PHPStorm I get `use DebugBar\DebugBar;`
