### ISSUE TITLE
Reflection Exception Class debugbar does not exist

### ISSUE THREAD

**Issue by dluague** [barryvdh/laravel-debugbar#228]
When I access http://localhost:8000/_debugbar/assets/javascript?1416837064

I got an error Reflection Exception Class debugbar does not exist.
open: D:\Dropbox\Web-stuff\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Container\Container.php
        // hand back the results of the functions, which allows functions to be
        // used as resolvers for more fine-tuned resolution of these objects.
        if ($concrete instanceof Closure)
        {
            return $concrete($this, $parameters);
        }

```
    $reflector = new ReflectionClass($concrete);

    // If the type is not instantiable, the developer is attempting to resolve
```

Note:
I already add 'Barryvdh\Debugbar\ServiceProvider' in my app settings under providers and 'Debugbar'        => 'Barryvdh\Debugbar\Facade' under aliases

**Comment by lucasmezencio** [comment]
I am having the same issue on Laravel 4.2. :(
