### ISSUE TITLE
In local, debugbar show queries but not when in production (live)

### ISSUE THREAD

**Issue by muhdazrain** [barryvdh/laravel-debugbar#230]
Hi,

I'm using Laravel 4 with your debugbar installed. I have weird issue and i don't know what's the caused of the problem. when i tried in local, the debugbar shows all the information including queries but when i tried in my live website (environment production), it shows the debugbar but no information in it. only has 3 tabs shown in the debugbar which are messages, timeline and exceptions. plus, i have chmod the folder in app/storage/debugbar to 757

as far as i remember, i don't have this kind of problem before. just recently i wanted to debug something, i came across this problem and have no idea what's the issue.

thanks.

**Comment by tomzx** [comment]
@muhdazrain Is this still relevant?

If so, do you have a custom `config.php` in your `app/config/packages/barryvdh/laravel-debugbar`?

**Comment by muhdazrain** [comment]
actually, it already solved which I don't know what the caused of the problem. I put aside this issue and continue with the development. When I checked it back, it just fine and shows all the results. thanks for reply :+1:
