### ISSUE TITLE
Debugbar not working with Dingo API package

### ISSUE THREAD

**Issue by prolio** [barryvdh/laravel-debugbar#235]
Not sure why, but when the dingo/api package is enabled, the Debugbar won't show up on any pages. As soon as I disable the API ServiceProvider, the bar shows up again. Possibly it's because of the way Dingo returns all responses as JSON? Is there anything that I can do to go about fixing this? Thanks in advance.

**Comment by refear99** [comment]
@barryvdh I have the same problem.
I am using l5 and dingo 1.x
Put `Barryvdh\Debugbar\ServiceProvider` after or before dingo is not work for me.

**Comment by williamoliveira** [comment]
Not working, is there any workaround or fix for this?
