### ISSUE TITLE
Config at app/config/packages/barryvdh/laravel-debugbar/config.php being ignored

### ISSUE THREAD

**Issue by mhughes** [barryvdh/laravel-debugbar#236]
For Version 1.7.7
Laravel version 4.2.11
I've published the config with

> php artisan config:publish barryvdh/laravel-debugbar

Then overriden the collectors array to include a bare minimum. (Specifically remove views, but i have tried with any permutation of collectors)

There is no effect on the rendering of the debugbar.  regardless of collectors defined.

Please let me know if you need any more information.

**Comment by tomzx** [comment]
@mhughes Do you need any further help? Can this issue be closed?
