### ISSUE TITLE
Can't find MemoryCollector data for each measurement

### ISSUE THREAD

**Issue by pepijnolivier** [barryvdh/laravel-debugbar#246]
Hi,

I'm currently profiling a site like this:

```
\Debugbar::startMeasure('HIERARCHY', '..some info here...');
//some long-running operation here
\Debugbar::stopMeasure('HIERARCHY');
```

I do see the debugbar with information much like the image below, but don't see any memory information for each measurement

**Where can I see memory information about each measurement, or how do I add this collector?**

![Image of debugbar](https://cloud.githubusercontent.com/assets/973269/4270452/740c8c8c-3ccb-11e4-8d9a-5a9e64f19351.png)

**Where can I see memory information about each measurement, or how do I add this collector?**

Thanks

**Comment by user11001** [comment]
Hey @barryvdh, nice!

That is exactly what I mean. I'm going to use this with my local set-up and will report any bugs or thoughts in your pull request.
