### ISSUE TITLE
No Debugbar Storage found.. when php artisan debugbar:clear

### ISSUE THREAD

**Issue by sergiodebcn** [barryvdh/laravel-debugbar#247]
When I execute the command 'php artisan debugbar:clear' I get an error, No Debugbar Storage found..

If I hardcode the class ClearCommand to set the storage manually it works perfect.

public function fire()
    {
/* Added Code
        $storage = new FilesystemStorage($this->debugbar->app['files'], storage_path() . '/debugbar');
        $this->debugbar->setStorage($storage);
*/
        if ($storage = $this->debugbar->getStorage()) {
            $storage->clear();
            $this->info('Debugbar Storage cleared!');
        } else {
            $this->error('No Debugbar Storage found..');
        }
    }

Thanks

**Comment by tonglil** [comment]
Yes, I also have this issue, even though the /storage/debugbar folder exists with `.json` files inside.

I only stumbled upon this because I'm getting a 500 when the debugbar tries to load something like this: `https://example.com/_debugbar/open?op=get&id=1ea0b33b6eaf429b32829943a030b9da`

**Comment by totalpeople** [comment]
I'm also getting this error when I run the artisan command. My env is local. I don't have any storage/debugbar folder. It's an app that I've just migrated to Laravel 5 from v4. Any ideas?

**Comment by goyote** [comment]
I found the issue, in the service provider in line 62 you have this:

        if ($app->runningInConsole()) {
            $this->app['config']->set('debugbar.enabled', false);
        }

So when the following check happens `debugbar.enabled` is set to `false` and not `null`.

        // If enabled is null, set from the app.debug value
        if (is_null($enabled)) {
            $enabled = $this->app['config']->get('app.debug');
            $this->app['config']->set('debugbar.enabled', $enabled);
        }

**Comment by furey** [comment]
@barryvdh I'm experiencing the same error.

-----

**Published package config**

[/config/debugbar.php](https://github.com/barryvdh/laravel-debugbar/files/33600/debugbar.php.txt)

![storage-settings](https://cloud.githubusercontent.com/assets/1914481/11138342/0bfdaf0c-8a15-11e5-8140-69a3bf871b70.png)

**Project directory (storage folder exists)**

![root](https://cloud.githubusercontent.com/assets/1914481/11138312/b89d4458-8a14-11e5-8670-621bf485b13b.png)

**Artisan output**

![artisan](https://cloud.githubusercontent.com/assets/1914481/11138405/f6c560c0-8a15-11e5-8578-eaa48803025e.gif)

-----

Any ideas?

**Comment by spajz** [comment]
Same for me.

**Comment by wink-** [comment]
I have the same issue when migrating to my live Forge server. The .json files are there in the debugbar directory in storage, the APP_ENV=local, and APP_DEBUG=true. Works great on my local machine. When I hit f12 it tells me that the resources will not load. But if I view the source, it shows the typical debugbar mumbo jumbo on the bottom.

**Comment by neylsongularte** [comment]
`php artisan debugbar:clear`

```
// in console enabled is defined as false
if ($app->runningInConsole()) {
      $this->app['config']->set('debugbar.enabled', false);
}
...
// here
if ( ! $enabled) {
            return;
        }
// debugbar not is booted
        /** @var LaravelDebugbar $debugbar */
        $debugbar = $this->app['debugbar'];
        $debugbar->boot();
```

**Comment by barryvdh** [comment]
Fixed by booting the storage before clearing.
