### ISSUE TITLE
Undefined Offset 0

### ISSUE THREAD

**Issue by yelqandili1** [barryvdh/laravel-debugbar#249]
I'm using laravel 4.2 and I was trying to display a variable that I'm getting from my Cache. As you can see my variable is an object that I want to see in the DebugBar :
$var = Cache::get('data');
$var = json_decode($var);
Debugbar::info($var);

The error this gives is : 
Undefined offset: 0 (in line 73 : vendor/symfony/var-dumper/Symfony/Component/VarDumper/Cloner/VarCloner.php)

but the exception was raised from :  Debugbar::info($var);

Do you have any idea where this is coming from ? knowing that it was working properly before, and I haven't made any updates to the packages

**Comment by luckyzid** [comment]
ERROR - 2015-01-22T15:37:23+09:00 - exception 'ErrorException' with message 'Undefined offset: 0' in /vendor/symfony/var-dumper/Symfony/Component/VarDumper/Cloner/VarCloner.php:73

u can try

VarCloner.php:73
if ($zval['zval_isref'] = $queue[$i][$k] === $cookie) {

to

VarCloner.php:73
if ($zval['zval_isref'] = (isset($queue[$i][$k])) ? ($queue[$i][$k] === $cookie) : false) {

**Comment by barryvdh** [comment]
Probably an issue in the VarDumper component. Can you open an issue there?
Op 22 jan. 2015 07:54 schreef "luckyzid" <notifications@github.com>:

**Comment by tomzx** [comment]
@luckyzid Any update on this? Can this issue be closed?

**Comment by kasparsklavins** [comment]
Noticed the same issue. Traced it down to this https://github.com/barryvdh/laravel-debugbar/blob/master/src/DataCollector/MultiAuthCollector.php#L65

`$recaller` consists of only one element after exploding - the token.

**Comment by barryvdh** [comment]
Can you create A PR?
