### ISSUE TITLE
Loading fonts take 4s

### ISSUE THREAD

**Issue by ddeath** [barryvdh/laravel-debugbar#250]
Hi there,
I recently found that m app is really slow. It looks like laravel debugbar is loading x-font-woff file, which is font. The problem is, that it takes 4s to load.
My app is rendered nicely, but after it renders site, it immediately freeze for that 4s and after that I can work with my site.

If I turn laravel-debugbar off, my site is working perfectly without freezing.

On my site I have a big table containing a lot of rows (hundreds).
I use dev-master version of debugbar with reference 1015c5d23e01ae6025990dd501f8d921451e5927

**Comment by ddeath** [comment]
Well i looked into it a little bit again, with debug turned on it take additional 8 seconds while I can do something on page. The page has a big DOM and also there was a lot of queries (cca 1000) if I turned off logging queries it takes only 4 additional seconds.... So the debug bar is quite useless if it take 8 seconds to load...

**Comment by barryvdh** [comment]
Well, you probably shouldn't be doing 1000 queries, debugbar could help with that ;)

**Comment by ddeath** [comment]
Yeah I`m aware of that, I`m just saying that debugbar is taking so much time even when I haven`t it opened...

**Comment by barryvdh** [comment]
Is it the time to execute or the time to render? or the time to load the assets?

**Comment by ddeath** [comment]
It looks like loading font or sth. not sure, but when I turn debugbar off, the things on bottom disapear...
![screenshot from 2015-01-27 20 20 10](https://cloud.githubusercontent.com/assets/2537379/5925252/7e884c68-a662-11e4-9ee1-89f0e3f18ed9.png)

**Comment by barryvdh** [comment]
Can you try turning of the vendor files?

**Comment by ddeath** [comment]
Ok  in LaravelDebugBar.php I set:

    $renderer->setIncludeVendors($this->app['config']->get('laravel-debugbar::config.include_vendors', false));

**Comment by barryvdh** [comment]
You have to set it in the config file.

**Comment by ddeath** [comment]
The vendor files are not loading but the page take same time to load...:
With debugbar on:
![with](https://cloud.githubusercontent.com/assets/2537379/5927012/00555e22-a670-11e4-8e0b-cab74272dd54.png)

and without:
![without](https://cloud.githubusercontent.com/assets/2537379/5927015/06615082-a670-11e4-9357-cefe60a3fbce.png)

**Comment by headersalreadysent** [comment]
Yes first screenshot shows that font load s 8 second but mostly they cached by browser

All network activities show that your page html load on about 4 second. I think debugbar cant do anything on that. Maybe you can optimize your queries or load data with ajax after page load.
.

**Comment by ddeath** [comment]
@headersalreadysent yeah but look at the second picture where vendor files are disabled, and still it is taking quite a time to finish whatever the debugbar is doing.

**Comment by ddeath** [comment]
So problem is not with any font. Problem is that debugbar creates elements for each sql query and each generated view, so that way it has to load it somehow even if the debugbar is not open... what is sad but prob. can`t do anything about it...

**Comment by barryvdh** [comment]
No but you could disable the query collector and still use the rest.

**Comment by headersalreadysent** [comment]
I think you can close db collector from config.

**Comment by ddeath** [comment]
Yes, I can and it works, but It is impractical though

**Comment by muba00** [comment]
I still have this issue, in my case it takes 9s - 12s to load the font.
