### ISSUE TITLE
Ajax calls 502 bad gateway

### ISSUE THREAD

**Issue by sergiodebcn** [barryvdh/laravel-debugbar#251]
With version 1.8.1 no problem.

In version 1.8.2 and later if capture_ajax is enabled, Every ajax call finish with a 502 bad gateway. 
Any solution?

In localhost there is no problem, only server.

**Comment by barryvdh** [comment]
I don't really have an idea. It's only when the debugbar is enabled right?
Any logs or error messages?

**Comment by sergiodebcn** [comment]
Only with debugbar enabled, Only shows a 502 bad gateway

**Comment by ryan953** [comment]
@sergiodebcn I had the same `502` problem and after some debugging discovered that I was hitting a limit inside nginx, not a problem in PHP.
I added the following to my site conf and things seem to be working now:

```
fastcgi_temp_file_write_size 10m;
fastcgi_busy_buffers_size 512k;
fastcgi_buffer_size 512k;
fastcgi_buffers 16 512k;
```

Idk if you have nginx on your localhost, but look into your server config.

**Comment by sergiodebcn** [comment]
thanks @ryan953 , I'll try this config.

**Comment by scheMeZa** [comment]
I can confirm that disabling capture_ajax fixes the 502 problem.

**Comment by scheMeZa** [comment]
@ryan953 Adding these
```
fastcgi_temp_file_write_size 10m;
fastcgi_busy_buffers_size 512k;
fastcgi_buffer_size 512k;
fastcgi_buffers 16 512k;
```
Also fixed my problem, I can now enable capture_ajax.

**Comment by AstroBoy269** [comment]
Goggled into this thread to solve this same problem for our development environments.  However, after a lot of testing we determined that only the `fastcgi_buffer_size` and `fastcgi_buffer` settings needed to be updated.  There's a very interesting article that you could use to help zero in on the appropriate buffer sizes [here](https://gist.github.com/magnetikonline/11312172#determine-fastcgi-response-sizes).  For our environment here are the settings we used.  
```
fastcgi_buffer_size         64K;
fastcgi_buffers          16 64K;
```

**Comment by chaiwei** [comment]
Encounter the same issue when using the debugbar for an Inertiajs based application in laravel valet.

Checked the error log
```
tail -5 ~/.config/valet/Log/nginx-error.log
[error] 272#0: *22475 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, ...
```

So I edit the valet.conf with cli
```
nano /usr/local/etc/nginx/valet/valet.conf 
```

Added the fastcgi params provided above.
```
   location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass "unix:/Users/chaiwei/.config/valet/valet.sock";
        fastcgi_index "/Users/chaiwei/.composer/vendor/laravel/valet/server.php";
        include fastcgi_params;
fastcgi_buffer_size         64K;
fastcgi_buffers          16 64K;
        fastcgi_param SCRIPT_FILENAME "/Users/chaiwei/.composer/vendor/laravel/valet/server.php";
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
```

then restart valet

```
valet restart
```

**Comment by mattkingshott** [comment]
I've added a PR to fix this on the Valet repo - https://github.com/laravel/valet/pull/1079
