### ISSUE TITLE
REST API profiling

### ISSUE THREAD

**Issue by qstyler** [barryvdh/laravel-debugbar#252]
Hi! I'm having an API built with laravel. And I need to do some profiling on it.
It's the classic REST API that returns json.
How can I profile it with debugbar?

**Comment by barryvdh** [comment]
I'm not sure if you can profile real-time, unless you also send the API requests with the same app.

You could use the browse button to view previous requests, which should include the API requests.

**Comment by barryvdh** [comment]
That is at least, assuming your app is the one that returns the JSON. Or is your app making the API requests and you want to log Guzzle or something?

**Comment by jonagoldman** [comment]
@barryvdh I see this kind of issue all over the repo. Would also like to see a way to profile apis bould with Laravel. Exactly how Debug Bar works now, just a way to pull the data so it can be attached to a JSOn response.

**Comment by plasticbrain** [comment]
+1

**Comment by zakiaziz** [comment]
+1 Lots of people would find this helpful

**Comment by Xplouder** [comment]
+1

**Comment by abellion** [comment]
+ 1

Do you have any workaround for now ?

**Comment by ElfSundae** [comment]
Same here. I am googling a built-in way which can send the profiling data to the RESTful API response, and it seems no that way.

My current solution is attaching a middleware that adding the profiling data to the response, then enable this middleware for the Api routes group.

For example:

```php
<?php

namespace App\Http\Middleware;

use App\Http\ApiResponse;
use Closure;

class ProfileApiResponse
{
    /**
     * Indicate if the Debugbar is enabled.
     *
     * @var bool
     */
    protected $debugbarEnabled;

    /**
     * Create a new middleware instance.
     */
    public function __construct()
    {
        $this->debugbarEnabled = function_exists('debugbar') && debugbar()->isEnabled();
    }

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        if ($this->debugbarEnabled && $response instanceof ApiResponse) {
            $response->setData($response->getData(true) + [
                '_debugbar' => array_only(debugbar()->getData(), ['__meta', 'messages', 'memory', 'queries']),
            ]);
        }

        return $response;
    }
}

```

The `ApiResponse` is just a subclass of `Illuminate\Http\JsonResponse`, you may change it to `JsonResponse` or your own custom API response class.

**Comment by dirkpostma** [comment]
+1

**Comment by ElfSundae** [comment]
I have updated the [previous example code](https://github.com/barryvdh/laravel-debugbar/issues/252#issuecomment-248343762).

**Comment by thinkstylestudio** [comment]
The middleware solution works PERFECTLY. would be nice though if this was integrated in.

**Comment by vijaythecoder** [comment]
Is there a way to generate the debugbar on SPA? @ElfSundae solution returns all the json the data with `_debugbar` attached, but how do we add the debugbar on the front end that is entirely in different folder(SPA using Vuejs) ?

**Comment by kishanmd** [comment]
I have adjusted @ElfSundae solution to also work when using [dingo/api](https://github.com/dingo/api) to handle your API responses (using the Dingo [response builders](https://github.com/dingo/api/wiki/Responses#response-builder)):

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Dingo\Api\Http\Response;

class ProfileJsonResponse
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        if (
            $response instanceof Response &&
            app()->bound('debugbar') &&
            app('debugbar')->isEnabled()
        ) {
            $response->setContent(json_decode($response->getContent(), true) + [
                '_debugbar' => app('debugbar')->getData(),
            ]);
        }

        return $response;
    }
}

**Comment by anorgan** [comment]
@kishanmd Sometimes output of `getContent()` can not be decoded. I have modified it to be:
```php
...
$content = json_decode($response->morph()->getContent(), true) ?? [];
$response->setContent($content + [
    '_debugbar' => app('debugbar')->getData(),
]);
...
```

**Comment by yangliuyu** [comment]
this works out of box on laravel-debugbar version 2.4.0 

```
Route::get('/abc', function () {
    User::whereName('abc')->get();
    return json_encode(['a'=>1]);
});
```

![screen shot 2017-07-06 at 3 33 03 pm](https://user-images.githubusercontent.com/1361821/27900316-75c71426-6260-11e7-9dbd-e06552af84c7.png)

**Comment by blue7wings** [comment]
if you use **Postman** to test your api, add `X-Requested-With: XMLHttpRequest` in your request's header. otherwise, configure option `'capture_ajax' => true` will never work.

**Comment by jpleveille-mv** [comment]
Maybe that's unrelated, but I'm developing an API using Laravel and we have another team working on a second Laravel application that happens to consume the API served by the former. When they want to profile their application as well as our underlying API they consume, they simply have both applications storing their JSON dumps in the same folder. Both application have `config/debugbar.php`:
```
<?php
return [
    'storage' => [
        'enabled' => (bool)env('DEBUGBAR_STORAGE_ENABLED'),
        'path' => env('DEBUGBAR_STORAGE_PATH')
    ]
];
```
Pretty straight forward from there. The bar in the Web application prompts dumps from both the Web and the API applications. If your environment doesn't define DEBUGBAR_STORAGE_ENABLED and DEBUGBAR_STORAGE_PATH, debugbar simply defaults to the regular storage.

**Comment by giovannipds** [comment]
@yangliuyu indeed, though it'd be nice and easier to let Laravel handle the return:

    Route::get('/abc', function () {
        $user = User::whereName('abc')->get();
        return $user;
    });

**Comment by zlanich** [comment]
This seems to work very well with Postman for me. I just turn Debug Bar on, make the API call with Postman, then go to the Folder icon and choose the latest request: http://zsl.io/pwIN9o. You'll need at least one web route so you can view Debug Bar, but no need to refresh that page or anything between requests. Clicking the Folder icon pulls the requests from the storage folder via. ajax.

**Comment by acepsaepudin** [comment]
nice info! thanks @zlanich .

**Comment by PaddyLock** [comment]
I can't get the debug toolbar to display in Postman app. The json files are written to storage/debugtoolbar but postman I think does not allow javascript in preview. So the question remains - how to profile API requests, when they have header info or post params that needs to be sent, and therefore can't be tested in a normal browser. My workaround is to use the history feature on a normal web page in same project.

**Comment by giovannipds** [comment]
@PaddyLock see @blue7wings's answer above.

**Comment by mkrell** [comment]
There's an alternative specifically for monitoring APIs which our company is using now: [itsgoingd/clockwork](https://github.com/itsgoingd/clockwork)

**Comment by barryvdh** [comment]
Yeah and https://github.com/laravel/telescope ofcourse now.

**Comment by PaddyLock** [comment]
> @PaddyLock see @blue7wings's answer above.

I tried that but postman does still not show it

**Comment by PaddyLock** [comment]
> Yeah and https://github.com/laravel/telescope ofcourse now.

Trying telescope now. Works a treat. Same as debug toolbar history really though for requests, and the way it is used on a  separate web page, rather than at the bottom of the response.

**Comment by vntrungld** [comment]
```
<?php

namespace App\Http\Middleware;

use Closure;
use Dingo\Api\Http\Response;

class ProfileJsonHttpResponse
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        if (
            $response instanceof Response &&
            app()->bound('debugbar') &&
            app('debugbar')->isEnabled()
        ) {
            $response->setContent(json_decode($response->morph()->getContent(), true) + [
                '_debugbar' => $this->sqlParser(app('debugbar')->getData()),
            ]);
        }

        return $response;
    }

    /**
     * Get only sql and each duration
     *
     * @param $debugbar_data
     * @return array
     */
    protected function sqlParser($debugbar_data) {
        $result = array_get($debugbar_data, 'queries.statements');

        return array_map(function ($item) {
            return [
                'sql' => array_get($item, 'sql'),
                'duration' => array_get($item, 'duration_str'),
            ];
        }, $result);
    }
}
```

**Comment by mgolshan** [comment]
> Yeah and https://github.com/laravel/telescope ofcourse now.

Whereas Telescope is a useful tool, it does not provide performance information.

**Comment by kirkbushell** [comment]
+1

**Comment by Yuriy-Svetlov** [comment]
+1
I don't want to offend Laravel, but in Yii2 everything is much easier and better. But maybe I haven't gotten used to Laravel yet.

**Comment by akalongman** [comment]
+1 for SPA

**Comment by jhormantasayco** [comment]
### I just have updated middleware for php 8

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;

class ProfileJsonHttpResponse
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure(\Illuminate\Http\Request): (\Illuminate\Http\Response|\Illuminate\Http\RedirectResponse)  $next
     * @return \Illuminate\Http\Response|\Illuminate\Http\RedirectResponse
     */
    public function handle(Request $request, Closure $next)
    {
        $response = $next($request);

        if (
            $response instanceof JsonResponse &&
            app()->bound('debugbar') &&
            app('debugbar')->isEnabled() &&
            env('API_DEBUG', false)
        ) {
            $queriesData = $this->sqlFilter(app('debugbar')->getData());

            $responseData = json_decode($response->getContent(), true) + [
                '_debugbar' => [
                    'total_queries' => count($queriesData),
                    'duplicates' => collect($queriesData)
                        ->groupBy('sql')
                        ->map(fn ($rows) => $rows->count())
                        ->map(fn ($value, $index) => [
                            'sql'   => $index,
                            'total' => $value
                        ])
                        ->sortByDesc('total')
                        ->values()
                        ->toArray(),
                    'queries' => $queriesData,
                ]
            ];

            $response = $response->setContent(json_encode($responseData));
        }

        return $response;
    }

    /**
     * Get sql queries information.
     *
     * @param array $debugbarData
     * @return array
     */
    protected function sqlFilter(array $debugbarData): array
    {
        $result = Arr::get($debugbarData, 'queries.statements');

        return array_map(fn ($item) => [
            'sql' => Arr::get($item, 'sql'),
            'duration' => Arr::get($item, 'duration_str'),
            'stmt_id' => Arr::get($item, 'stmt_id'),
            'backtrace' => collect(Arr::get($item, 'backtrace'))->mapWithKeys(fn ($item) => [
                $item->index => "{$item->name}:{$item->line}"
            ]),
        ], $result);
    }
}

```

**Comment by annelbco** [comment]
For anyone else still struggling, I was able to make it work out of the box following @zlanich's [post](https://github.com/barryvdh/laravel-debugbar/issues/252#issuecomment-390324355)
_(sry for the crappy gif due to size limit here, but hope everyone can get the gist of it)_


![debugbar](https://user-images.githubusercontent.com/1003597/159914342-5a1c3594-1d80-4b2b-9ac6-b9f75acf4bb1.gif)
