### ISSUE TITLE
Debugbar not showing

### ISSUE THREAD

**Issue by markeilander** [barryvdh/laravel-debugbar#253]
Debugbar is generating the css and js files correctly i get some 404's.

[domain]/laravel/public/_debugbar/assets/stylesheets?1419408007
[domain]/laravel/public/_debugbar/assets/javascript?1418805579

Does someone have any idea how to fix this?

**Comment by barryvdh** [comment]
Did you fix this or why did you close it? what was the problem?

**Comment by markeilander** [comment]
Heb het afgesloten omdat ik zelf en typo had gemaakt.
De vhost stond verkeerd ingesteld waardoor de css en js bestanden niet goed werden geladen.
Thnx voor het navragen.
Mvg,

 
Mark Eilander


Date: Wed, 7 Jan 2015 11:47:27 -0800
