### ISSUE TITLE
Unable to view AJAX requests results

### ISSUE THREAD

**Issue by tomzx** [barryvdh/laravel-debugbar#256]
Hi,

I'm unable to get AJAX queries to properly report on 1.8.3.

I have the following settings of interest in my `config.php`

```php
'include_vendors' => false,
'capture_ajax' => true,
```

Some information that is probably of interest to debugging this issue:

- Provided `jquery` is `1.11.0`
- The request returns a `phpdebugbar-id` in the response header
- A breakpoint in the `bindToXHR` method of the extended `AjaxHandler.prototype` will only trigger on setup.  `XMLHttpRequest.prototype.open` never appears to be called when `$.ajax` is called (by a third-party library).
- Browser is `chrome 39.0.2171.95 (64-bit)`

The application using `laravel-debugbar` also makes use of angular, for which we use the ng-phpdebugbar module in order to track $http requests. This works properly. I've also verified that it doesn't interfere with `php-debugbar` by disabling it completely.

Let me know if any other information might be useful to debug this.

Thanks!

**Comment by Dukeman330** [comment]
I made a possible workaround, if you're interested:

https://github.com/barryvdh/laravel-debugbar/issues/142#issuecomment-69693966

**Comment by barryvdh** [comment]
So shouldn't need ng-debugbar actually. But you say that works properly? If so, what is the problem exactly?

**Comment by cryoutsolutions** [comment]
I have the same issue... it was working fine before updating composer

**Comment by barryvdh** [comment]
What version was working? And are you using regular ajax calls or angular?

**Comment by cryoutsolutions** [comment]
I don't know witch version... it was before I updated last week through composer. 
I am using regular calls.
This is a sample header:

Host: host.dev
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:34.0) Gecko/20100101 Firefox/34.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Referer: http://flashoncam.dev/model
Cookie: laravel_session=eyJpdiI6Im5qYXFuUGx1S1ZvMmhIQ2NYVGtrOXc9PS
Connection: keep-alive

**Comment by barryvdh** [comment]
And the response header?

**Comment by cryoutsolutions** [comment]
application/json

**Comment by barryvdh** [comment]
And the rest of the headers?

**Comment by cryoutsolutions** [comment]
![screen shot 2015-01-13 at 12 55 39](https://cloud.githubusercontent.com/assets/5873018/5719716/97ab3a74-9b23-11e4-992d-83eec0db79be.png)

**Comment by cryoutsolutions** [comment]
the ajax calls are not showing in history either

**Comment by barryvdh** [comment]
And you are using the latest version? Did you composer-update before trying?

**Comment by cryoutsolutions** [comment]
yup... just did it again now... still the same

**Comment by barryvdh** [comment]
How are you generating the json response exactly? Can you provide a snippet?

**Comment by cryoutsolutions** [comment]
here's a basic example

the function in controller
public function ajaxAddPost() {
        $post = new Post();
        $post->post = Input::get('post');
        $post->user_id = Auth::user()->id;
        $post->save();
        return Response::json(array(
                    'success' => TRUE,
                    'message' => array("message" => 'Post', 'modal' => View::make('model.partials_ajax.post')
                                ->with('post', $post)
                                ->render())
        ));
    }

**Comment by tomzx** [comment]
@cryoutsolutions In your case the response headers aren't generating the `phpdebugbar-id` headers, while in mine they do.

**Comment by barryvdh** [comment]
@tomzx What library is that?

I've added some tweaks to https://github.com/barryvdh/laravel-debugbar/commit/d4ebe58f0be834bda4383491948587a28d1be03a but don't think that's the issue.

Is there anything in the laravel logs?

**Comment by tomzx** [comment]
@barryvdh It is [Chumper's Datatable](https://github.com/Chumper/Datatable]. It uses [DataTables 1.9](http://legacy.datatables.net/) javascript library.

**Comment by barryvdh** [comment]
Hmm, datatables work fine with me, haven't tried chumpers library, but it does seem to return a normal json response on collection->make(), so that seems correct..

**Comment by cryoutsolutions** [comment]
I reproduced the ajax call in a different laravel project and it seems that the ajax requests are ok... I have the phpdebugbar-id in the response header.
Could you tell me where id phpdebugbar-id injected so I can try to find out where's the issue in the main project?
Thanks a lot!

**Comment by barryvdh** [comment]
This determines what the debugbar should do: https://github.com/barryvdh/laravel-debugbar/blob/master/src/LaravelDebugBar.php#L504-L536

with SendDataInHeaders, the header id is added. (That is here: https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/DebugBar.php#L291-L305 )

**Comment by cryoutsolutions** [comment]
Thanks

**Comment by cryoutsolutions** [comment]
I now see that I have in the log this error 
[2015-01-13 14:14:04] local.ERROR: Debugbar exception: Method StudioController::myAccount() does not exist [] []
But my function is called *ajax*AddMyAccount() for ajax requests...
Until last week it worked like this...
Do you have any idea why wouldn't now see it. 
I'm working on this project with a team and this is how the project was build. 
in the route the code is 
Route::post('my-account', array('as' => 'studio.my-account','uses' => 'StudioController@myAccount'));
and if it is an ajax request it calls *ajax*AddMyAccount()

**Comment by tomzx** [comment]
@barryvdh Take a look at [tomzx/256-laravel-debugbar](https://github.com/tomzx/256-laravel-debugbar)

**Comment by barryvdh** [comment]
I've looked. When I'm on index.php and run `$.getJSON('index.php/ajax');` in the JS console, the /ajax request is intercepted correctly.
When I visit /ajax directly and then go back to the index, I can see the /ajax request in the browse window.
Can you provide an example of what is giving a problem?

**Comment by tomzx** [comment]
Thanks for the help!

After further investigation, it seems the issue was related to [PACE](http://github.hubspot.com/pace/docs/welcome/). It breaks the `XMLHttpRequest.prototype`

`XMLHttpRequest.prototype` with php-debugbar
![](http://fkcd.ca/U2s.png)

`XMLHttpRequest.prototype` with php-debugbar AND pace
![](http://fkcd.ca/Iyp.png)

You can close this, I'll follow up with the PACE developer.

Thanks again

**Comment by react-nativeevan** [comment]
> application/json





https://preprocessor.space/questions/utilizing-php-to-send-arrays-through-ajax-and-json
