### ISSUE TITLE
always shown

### ISSUE THREAD

**Issue by doriansavage** [barryvdh/laravel-debugbar#257]
I have debug=>false both local and production config.
On local, it doens't shows but on production it shows...
Even if I put "'enabled' => 'false'," on the packages/barry.../config.php

don't understand :x 

thx

**Comment by barryvdh** [comment]
l4 or l5?

**Comment by doriansavage** [comment]
4

**Comment by barryvdh** [comment]
Are you using quotes or are you actually using true or false?

**Comment by doriansavage** [comment]
with 
'debug' => 'false',

**Comment by barryvdh** [comment]
The string false is true ;) put false without quotes.

**Comment by doriansavage** [comment]
ups... thanks ! quick <3
