### ISSUE TITLE
Add views compile time.

### ISSUE THREAD

**Issue by j-a-p-dev** [barryvdh/laravel-debugbar#258]
Now we can't see how many time a view take to be compiled.

**Comment by barryvdh** [comment]
I don't have that information.

**Comment by crosma** [comment]
Would it be possible to log the total time views take to the timeline? Would be very helpful.

**Comment by emilv** [comment]
Are you after the compile time or the render time? The view is usually compiled once into PHP code, cached as a file on disk and then that file is used every time the view is rendered.

To measure the render time I believe you have to overload the view engine resolver and both the PhpEngine and the CompilerEngine. Then you can hijack their render() methods and add start/stopMeasure calls. You should probably do this in your application.

**Comment by crosma** [comment]
I would really only be interested in render time, since compiling only happens once.

**Comment by progsmile** [comment]
It's also interesting to see blade render speed, - may be it has to be optimized, and we are not aware of that
