### ISSUE TITLE
Highlighting / grouping duplicate queries

### ISSUE THREAD

**Issue by beneverard** [barryvdh/laravel-debugbar#260]
When using Debugbar it tells me I have `n` duplicate queries, however it's not clear unless I look through all queries which ones are duplicate.

It'd be great if there was a way of highlighting this, or perhaps filtering by only duplicate queries with a count and perhaps the sum of all query time for each query.

**Comment by barryvdh** [comment]
It should have a slightly different background (more grey) if it's a duplicated query. But I agree it could be more clear.

**Comment by Nossnevs** [comment]
In Django debug toolbar you will see the number of duplicates under every row. [https://i.stack.imgur.com/0O9Uz.png](https://i.stack.imgur.com/0O9Uz.png)

The slight color difference is not good because it is no way the user understands that it is a duplicate and if you are color blind it is impossible. 

Now the duplicate calculation is done in js, i think it should be in php but i don't know the whole picture.

**Comment by ajcastro** [comment]
You could do this trick... 
```
 <script type="text/javascript">
    window.toggleSqlDuplicate = function () {
        $('div.phpdebugbar-widgets-sqlqueries li').not('.phpdebugbar-widgets-sql-duplicate').toggleClass('hidden');
    }
</script>
```
and for more visible highilighting 
```
<style type="text/css">
    .hidden {
        display: none !important;
    }
    
    div.phpdebugbar-widgets-sqlqueries li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate {
        background-color: yellow !important;
    }
</style>
````

**Comment by steveheinsch** [comment]
I made a js bookmarklet for this. Just create a bookmark and use this for the `location`. Then just click the bookmark to toggle the dupes on/off.
```
javascript:(function(){ if (typeof toggleSqlDuplicate !== 'function') { window.toggleSqlDuplicate=function (){$('div.phpdebugbar-widgets-sqlqueries li').not('.phpdebugbar-widgets-sql-duplicate').toggleClass('hidden');} } toggleSqlDuplicate(); })(); 
```

**Comment by philcgilbert** [comment]
I have to tweak @steveheinsch bookmark slightly to the following for it to work for me:

`javascript:(function(){ if (typeof toggleSqlDuplicate !== 'function') { window.toggleSqlDuplicate=function (){$('.phpdebugbar-widgets-list > li').not('.phpdebugbar-widgets-sql-duplicate').toggle();} } toggleSqlDuplicate(); })();`

**Comment by moisish** [comment]
I have added the following snippet at the end of my master blade.

` @if (debugbar()->isEnabled())
            <style>div.phpdebugbar-widgets-sqlqueries li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate {background-color: #FFAC4694 !important;}</style>
            <script>
                window.toggleSqlDuplicate = function () {
                    $('<a>')
                        .text(' | Toggle Duplicates |')
                        .on('click', function () {
                            $('div.phpdebugbar-widgets-sqlqueries li').not('.phpdebugbar-widgets-sql-duplicate').toggle();
                        })
                        .appendTo($('.phpdebugbar-widgets-sqlqueries .phpdebugbar-widgets-status'));
                };
                setTimeout(function(){
                    toggleSqlDuplicate();
                    $('.phpdebugbar-datasets-switcher').change(function(){
                        toggleSqlDuplicate()
                    });
                },1000);
            </script>
        @endif
`
![image](https://user-images.githubusercontent.com/15047879/146568349-5c68c309-840c-48ed-8bbc-d31c48b991c0.png)

**Comment by moisish** [comment]
I have added the following snippet at the end of my master blade.

``` 
@if (app()->has('debugbar') && app('debugbar')->isEnabled())
            <style>div.phpdebugbar-widgets-sqlqueries li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate {background-color: #FFAC4694 !important;}</style>
            <script>
                window.toggleSqlDuplicate = function () {
                    $('<a>')
                        .text(' | Toggle Duplicates |')
                        .on('click', function () {
                            $('div.phpdebugbar-widgets-sqlqueries li').not('.phpdebugbar-widgets-sql-duplicate').toggle();
                        })
                        .appendTo($('.phpdebugbar-widgets-sqlqueries .phpdebugbar-widgets-status'));
                };
                setTimeout(function(){
                    toggleSqlDuplicate();
                    $('.phpdebugbar-datasets-switcher').change(function(){
                        toggleSqlDuplicate()
                    });
                },1000);
            </script>
        @endif
```
![image](https://user-images.githubusercontent.com/15047879/146568349-5c68c309-840c-48ed-8bbc-d31c48b991c0.png)

**Comment by jakedowns** [comment]
i tweaked it slightly to not use jquery:
```
window.toggleSqlDuplicate = function () {
            let a = document.createElement('a');
            a.textContent = ' | Toggle Duplicates |';
            a.onclick = function() {
                let els = document.querySelectorAll(
                    'div.phpdebugbar-widgets-sqlqueries \
                    li:not(.phpdebugbar-widgets-table-list-item)\
                    :not(.phpdebugbar-widgets-sql-duplicate)'
                );
                for(let el of els){
                    // toggle visibility
                    if(el.style.display === 'none'){
                        el.style.display = null;
                    }else{
                        el.style.display = 'none';
                    }
                }
            }
            let target = document.querySelector('.phpdebugbar-widgets-sqlqueries .phpdebugbar-widgets-status');
            target.appendChild(a);
        };
        ```
