### ISSUE TITLE
PhpDebugBar is not defined

### ISSUE THREAD

**Issue by joshbenham** [barryvdh/laravel-debugbar#261]
Now on all my sites when I run debugbar it does not seem to work.

The CSS and JS files are not loading correctly and they are firing a 500 error.

I went to the page directly and I get:
Call to undefined method Symfony\Component\HttpFoundation\Response::header()

**Comment by barryvdh** [comment]
What laravel version? And what debugbar version?

**Comment by barryvdh** [comment]
And what kind of response? can you try with latest stable and with dev version?

**Comment by joshbenham** [comment]
Sorry for the delay.

Laravel Framework version 4.2.16

Then when it comes to debugbar I was using `master` as well as `"barryvdh/laravel-debugbar": "~1.8"`

It errored on both instances.

**Comment by jasonvarga** [comment]
I had the same issue where I was seeing `PhpDebugBar is not defined` and was getting 404s on the assets. I have a catch-all route and didn't follow the installation instructions regarding that.

> Note for Laravel 5: If you use a catch-all/fallback route, make sure you load the Debugbar ServiceProvider before your own App ServiceProviders.

When I moved the service provider earlier, it started to work.

Hopefully this helps you.

**Comment by joshbenham** [comment]
@jasonvarga My original script which always worked was

`
    'providers' => append_config(array_merge([
        'Barryvdh\Debugbar\ServiceProvider',
        'Intervention\Image\ImageServiceProvider',
        'Greggilbert\Recaptcha\RecaptchaServiceProvider',
        'Way\Generators\GeneratorsServiceProvider',
        'Hugofirth\Mailchimp\MailchimpServiceProvider',
        'Pingpong\Shortcode\ShortcodeServiceProvider',
        'Roumen\Sitemap\SitemapServiceProvider',
        'Maatwebsite\Excel\ExcelServiceProvider',
    ], Fdw\Core\Libraries\Helpage\Packager::providers())),
`

Which always worked until recently. I need to run the php providers method first because that is how I handle package injection into my system.

**Comment by joshbenham** [comment]
Ok I found out what the error was.

I originally had in my filters

```
App::after(function ($request, $response) {

    if (App::environment() != 'production') {
        $response->header('X-Robots-Tag', 'noindex, nofollow');
    }

});
```

Which was working at the start but then I started getting header errors in the css/js includes so I just changed it to 

```
App::after(function ($request, $response) {

    if (App::environment() != 'production' && strpos(Request::url(), 'debugbar') === false) {
        $response->header('X-Robots-Tag', 'noindex, nofollow');
    }

});
```

No idea what started making this error appear but this seemed to have fixed it :)

**Comment by barryvdh** [comment]
Ah well, the response is a plain Symfony response. That doesn't have the header method.
I'll change it to a illuminate response (which extends the symfony one), so you can still apply your filters.

**Comment by machmum** [comment]
I'm develop my sites with laravel 4.2 and use debugbar but, it seem does not work,
In console:
> Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost/kidnesia-frontend/public/_debugbar/assets/stylesheets?1445286912".

> Uncaught ReferenceError: PhpDebugBar is not defined

> var phpdebugbar = new PhpDebugBar.DebugBar();

Any idea how to track the error? I already tried to copy the debugbar folder in other site where my debugbar works, still come the same error
