### ISSUE TITLE
Overwrites font-awesome CSS

### ISSUE THREAD

**Issue by securit** [barryvdh/laravel-debugbar#264]
Hi Barry,

your /Resources/vendor/font-awesome/style.css (version 4.2.0)is overwriting the css of our version of font-awesome (v 4.3.0)... 

What is the best way of approaching this so that it doesnt?

Thanks in advance

**Comment by barryvdh** [comment]
You can disable the vendor css in the config.

**Comment by barryvdh** [comment]
You could also disable a specific vendor, with `disableVendor('fontawesome')` on the JavascriptRenderer. Something like this:

`app('debugbar')->getJavascriptRenderer()->disableVendor('fontawesome');`

**Comment by barryvdh** [comment]
Also update FontAwesome to 4.3.0
