### ISSUE TITLE
Artisan Memory Problem

### ISSUE THREAD

**Issue by bryceray1121** [barryvdh/laravel-debugbar#266]
In my app I have laravel-debugbar enabled but capture_console disabled.  Despite having artisan command debugging disabled my php larger php artisan commands do not work with debugbar.  If I execute one of my larger seeders than the memory slowly climbs until it runs out of memory.  It would seem to me that laravel-debugbar should be hands off on console if capture_console is set to false.

I verified this by setting capture_console to false, running a test, and then setting enabled to false and running the same test.  Disabling debugbar drastically improves my seeder performance.

**Comment by bryceray1121** [comment]
Now that I take a second look capture_console is an option in the config for laravel-debugbar but appears to not be used any where in the src.  So of course it acts like the option does nothing, it is doing nothing.

**Comment by barryvdh** [comment]
It Should be used in the fifth line of the boot method in the service provider.
What laravel version?

**Comment by bryceray1121** [comment]
I'm using the latest build of L5.  It would appear that the command is not in debugbar branch 2.0:
https://github.com/barryvdh/laravel-debugbar/blob/2.0/src/ServiceProvider.php

But I do see it on master, so somewhere it did not make it in to 2.0 ServiceProvider.

**Comment by barryvdh** [comment]
Okay, it should be disabled on the console anyways, because the after /shutdown function isn't possible. Can you make a PR to disable the debugbar on console, similar to the master branch (but just always, regardless of the config), if that works for you?

**Comment by barryvdh** [comment]
Pushed a fix, does that work for you?
