### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by bipinu** [barryvdh/laravel-debugbar#267]
Hi,
Appreciate your work on the tool. For quite some time, we've been seeing a very weird layout issue. The entire content area has the height of a single line.
As you can see in the screenshot, the Firebug console doesn't throw any error. Chrome isn't any different either.

We are using Laravel 4.2.* and debugbar 1.*

![screen shot 2015-02-02 at 12 08 22](https://cloud.githubusercontent.com/assets/78911/5999728/fd3dd08e-aad4-11e4-9377-c5d858e550d4.png)

**Comment by barryvdh** [comment]
Do you have some default styling for your page? Can you try it on a page without any css?

Perhaps some global ul/li styles?

**Comment by bipinu** [comment]
I tried with another of our projects, and it works fine. Looks like it is some sort of CSS clash.

**Comment by barryvdh** [comment]
Can you try with this commit? https://github.com/maximebf/php-debugbar/commit/db6dda22af1a938db61a2f93fc24a3e7373942fc

Or can you tell me what styles are overriden? Propbably the global ul/li styles.

**Comment by bipinu** [comment]
I had issue downloading the specific commit mentioned (attached in screenshot), so I replaced the content of debugbar.css. Doesn't help!
I can have a look at the CSS conflicts after work in the evening, and update the issue. Let me know if I can help with anything else in the meanwhile.

![screen shot 2015-02-02 at 14 27 30](https://cloud.githubusercontent.com/assets/78911/6001257/e4c45fc4-aae7-11e4-84a4-7e4a25de2fcc.jpg)

**Comment by barryvdh** [comment]
Okay sorry probably changed the commit. 
Should be good with https://github.com/maximebf/php-debugbar/commit/df23eae5b6bf67d1d4dd3d571be0e42f1c7810da
Resetted the clear and the width of links.

**Comment by bipinu** [comment]
It sure seems to fix the issue. Thanks a lot.
However, our composer is marked to download stable packages only; I'll be able to confirm for sure once the commit is tagged.

**Comment by bipinu** [comment]
@barryvdh I'm closing this, since it does seem fixed. Any ETA on when it'll be tagged?

**Comment by barryvdh** [comment]
I'll see if I can tag soon.
You could also require the 1.x@dev version for php-debugbar, next to the laravel debugbar to get the latest changes.
