### ISSUE TITLE
Route debugbar:openhandler not defined

### ISSUE THREAD

**Issue by subdesign** [barryvdh/laravel-debugbar#270]
I have the following error in the logs and Debugbar doesnt show up:
```php
[2015-02-05 12:02:22] local.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  
```
I have a fresh new L5 install, only laravel-debugbar (v2.0) package added, and published the config file.
Package is enabled, env is local
Am I missing something?

EDIT: in the prev version it was a debugbar folder in the storage folder. Now in L5 there isn't, is it OK?

**Comment by barryvdh** [comment]
I'm not sure, it's working for me. Don't know why the route wouln't show up. It should just register it here: https://github.com/barryvdh/laravel-debugbar/blob/master/src/ServiceProvider.php#L36

**Comment by subdesign** [comment]
If you guide me I can debug it, of course if you're interested in.

**Comment by barryvdh** [comment]
Eh, it's a bit hard to guide because I don't know what causing it :P 

I would use `dd()` driven debugging ;) Put a `dd('in boot')` in the start of the boot, and see if it boots and get's to the router part (https://github.com/barryvdh/laravel-debugbar/blob/master/src/ServiceProvider.php#L36)

You could also disable the storage, see if that helps (`storage.enabled`)

**Comment by subdesign** [comment]
- the package boots up well
- disabling storage option doesn't make it work
The $this->app['route'] content is:
```php
Router {#22 ▼
  #events: Dispatcher {#5 ▶}
  #container: Application {#2 ▶}
  #routes: RouteCollection {#24 ▼
    #routes: array:2 [▶]
    #allRoutes: array:3 [▼
      "HEAD_debugbar/open" => Route {#94 ▶}
      "HEAD_debugbar/assets/stylesheets" => Route {#95 ▶}
      "HEAD_debugbar/assets/javascript" => Route {#96 ▶}
    ]
    #nameList: array:3 [▶]
    #actionList: array:3 [▼
      "Barryvdh\Debugbar\Controllers\OpenHandlerController@handle" => Route {#94 ▶}
      "Barryvdh\Debugbar\Controllers\AssetController@css" => Route {#95 ▶}
      "Barryvdh\Debugbar\Controllers\AssetController@js" => Route {#96 ▶}
    ]
  }
  #current: null
  #currentRequest: null
  #middleware: array:3 [▶]
  #patternFilters: []
  #regexFilters: []
  #binders: []
  #patterns: []
  #groupStack: []
}
```
so the routes are added , too.
Np Barry, time solves lot of things :)

**Comment by barryvdh** [comment]
Can you clear the storage folders? Perhaps the routes are cached, or the service provider manifests or something.

**Comment by subdesign** [comment]
Cleared storage folders/subfolders but nothing new

**Comment by subdesign** [comment]
Ok, so the guy installed successfully. I changed APP_DEBUG in .env to false, refreshed screen, changed to back to true, and at the end set inject option again to true, now WORKS. I can't find any reason what happened..
sorry for that Barry, thank you for your time

**Comment by barryvdh** [comment]
Probably something being cached or something

**Comment by subdesign** [comment]
I don't know if .env is cached but will investigate

**Comment by subdesign** [comment]
Last comment, i forget to say meantime i fired a composer update, and it was a change:
```php
barna@barna:/var/www/laravel5⟫ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing maximebf/debugbar (v1.10.3)
  - Installing maximebf/debugbar (v1.10.4)
    Downloading: 100%  
```
could be the reason? who knows..

**Comment by barryvdh** [comment]
Shouldn't have anything to do with it, as far I know.

**Comment by EdwinvanDessel** [comment]
Strange, I am having the exact same problem. Nothing appearing in the browser and the same error message in the log. Tried it now in the latest version of Firefox, Chrome and IE but none of the browsers displays the debugbar. Also repeated the steps that resolved the issue for subdesign but to no avail. Any suggestions?

**Comment by basudz** [comment]
I had the same issue and none of the mentioned solutions were working.  What did the trick for me was to run `php artisan clear-compiled`

**Comment by EdwinvanDessel** [comment]
Does not seem to work for me. In my case it seems to have more to do with the browser. I created a new project, started from scratch and now the debugbar does appear, but only for this app. In the old app the debugbar stays hidden. Clearing the browser history completely did not help.

**Comment by bgarrison25** [comment]
I am also having this issue. I have my routes cached but i cleared it and recached and debugbar.openhandler is STILL not showing up in the route list....doesn't show up on the page ... APP_DEBUG=true....error shows up in logs

**Comment by Spir** [comment]
Same issue here. clearing all the cache is fixing the issue for me:
php artisan clear-compiled; php artisan cache:clear; php artisan route:clear

**Comment by teamexpertois** [comment]
My S/W: DebugBar 2.2 & Laravel 5.2 I'm still getting "Route [debugbar.openhandler] not defined" and file_get_contents(/var/www/mvp.example.com/laravel/../../public_html/build/rev-manifest.json): failed to open stream:
I've deployed the site on a subdomain; if that helps!
No amount of clearing cache, config, routes etc. is helping! Please help! I'm stuck at this first and last point before even starting with my project work!

**Comment by shaizar** [comment]
Just experienced the same problem. Clearing the route cache fixed it for me.

**Comment by TresErres** [comment]
I can confirm that using cached routes generated the issue.

**Comment by svkmedia** [comment]
Same happened to me... I think this problem shows up when you have APP_DEBUG=false and run php artisan route:cache. Then you switch APP_DEBUG to true and there is this error. When I run route:cache with APP_DEBUG=true everything works fine...
