### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by xeno010** [barryvdh/laravel-debugbar#271]
Hello,

I have found a XSS vulnerability in the event viewer

The Code:
```php
User::whereId('<script>alert(1)</script>')->get();
```

Result:
![3](https://cloud.githubusercontent.com/assets/5448179/6061590/466d6302-ad49-11e4-8ece-77af0fc8a964.png)

![1](https://cloud.githubusercontent.com/assets/5448179/6061561/1cd27dc0-ad49-11e4-8609-106458f272f6.png)

HTML Source:
![2](https://cloud.githubusercontent.com/assets/5448179/6061560/1cd25e8a-ad49-11e4-8084-7e68be516d9e.png)

**Comment by barryvdh** [comment]
Should be fixed with commit above.

**Comment by GrahamCampbell** [comment]
Fast response @barryvdh. :)
