### ISSUE TITLE
Double Inserts using Query Builder's insert() with debugbar enabled

### ISSUE THREAD

**Issue by tylercubell** [barryvdh/laravel-debugbar#272]
When debugbar is enabled, inserts are getting repeated twice.

```php
DB::table('records')->insert(array("foo" => "bar"));
```

I'm using Laravel 4.2 with MySQL.

**Comment by barryvdh** [comment]
Hmm, You don't accidentally have the explain option enabled for inserts do you?

**Comment by tylercubell** [comment]
I never knowingly enabled an explain option. Where would that be located?

**Comment by barryvdh** [comment]
In the config file, if you have it published.
Can you publish the config and disable the query collector or just disable some of the options there.
I haven't seen this before though.

**Comment by tylercubell** [comment]
I published the config file and when I turn 'inject' to false, the insert acts as it should. But when I enable 'inject' it inserts the same thing 3 times.

**Comment by tylercubell** [comment]
Here's my db config if it makes any difference: https://gist.github.com/tylercubell/2daf5abda0f5c6b36f85

**Comment by barryvdh** [comment]
And how /what are you inserting? Not something on each request or something right?

**Comment by tylercubell** [comment]
For testing: in my routes file I have a dummy insert (like snippet above) and then die(). It will be called for any request.

**Comment by barryvdh** [comment]
Okay well debugbar makes multiple requests, 1 for js, 1 for css. And for every javascript call / open handler call, another one.. So make sure you run your test snippet on real routes, not just on every request.

**Comment by tylercubell** [comment]
For production I want to do an insert inside App::error to record some information.

So for my real world case, if someone is accessing my app directly by IP instead of by the domain name, App::error is called and inside that I have my insert. In the local environment, debugbar is enabled. So you're saying it goes like this:

1. Initial request is made -> goes to App::error -> triggers insert().
2. Debugbar makes CSS request -> goes automatically to App::error -> triggers insert().
3. Debugbar makes JS request -> goes automatically to App::error -> triggers insert().

Why does debugbar have to make these extra requests? Couldn't the CSS/JS be inline?

**Comment by barryvdh** [comment]
Yeah it could be but that also gave trouble (with updating assets, merging them etc). Might revisit that sometime.
But not sure why App::error() is always triggered?

**Comment by tylercubell** [comment]
In app/start/local.php I'm looking at the HTTP Request header for _every_ request. If my app doesn't like it, it triggers an App::abort(). That then goes to App::error().

**Comment by barryvdh** [comment]
I guess you could check if the request starts with _debugbar and your in local env or something.

**Comment by tylercubell** [comment]
That worked.

```php
if (Request::is('_debugbar/assets/*')) {
    // Don't abort
}
```
