### ISSUE TITLE
DebugBar must have a storage backend to use OpenHandler

### ISSUE THREAD

**Issue by ekittell** [barryvdh/laravel-debugbar#273]
I keep getting this when I run composer install

**Comment by barryvdh** [comment]
What error exactly?

**Comment by ekittell** [comment]
[RuntimeException]                                           
  Error Output:                                                
                                                               
    [DebugBar\DebugBarException]                               
    DebugBar must have a storage backend to use OpenHandler

**Comment by barryvdh** [comment]
What version of Laravel and debugbar? Are you running any commands or something?

**Comment by ekittell** [comment]
laravel 4.2, debugbar 1.*

**Comment by ekittell** [comment]
puttling $this->enable(); in __construct seems to fix it

is there something else I was supposed to do to enable Debug bar during theme compilation?

**Comment by barryvdh** [comment]
In which construct?

**Comment by ekittell** [comment]
LaravelDebugbar
