### ISSUE TITLE
In Laravel 5 debugbar's route collector causing output to browser before debugbar can inject into HTML

### ISSUE THREAD

**Issue by ItsTobias** [barryvdh/laravel-debugbar#274]
Upgrading a Laravel 4 site to Laravel 5 and debugbar was not showing, tracked it down to a foreach over the collectors on Line 589 of LaravelDebugBar.php.
One of the collectors was causing Laravel to dump the view output to the browser before Debugbar was injecting its HTML.
Disabling the route collector fixed the issue and the debugbar then appeared correctly before the body tag.

**Comment by barryvdh** [comment]
What kind of route was it? And what was the output?
Can't reproduce it here.

Did you have any special routes/controllers or anything?

**Comment by ItsTobias** [comment]
I shall do some more testing this evening (UK time).
From memory:
Once the route collector was called, the full output of the rendered views was being sent to the browser. Setting route to false in the debugbar config file fixed the issue.

Two things off the top of my head that I think could have affected it.
1) I have re-added the setupLayout functionality from Laravel 4 into Laravel 5 by adding the Laravel 4 callAction into my base controller. As described here https://laracasts.com/discuss/channels/general-discussion/laravel-5-this-layout-content-not-working
2) I have an afterFilter in my base controller which takes the rendered HTML, runs it through some regex replacements and then puts it back into the response object using setContent (I know this after filter is working sub-optimally currently as I am using $this->layout->render() to retrieve the rendered HTML, I should be using $response->getContent() I believe, however this was not working when I upgraded to Laravel 5, however that was likely because of the new Laravel 5 callAction which I have since replaced.)

The way my routes are stored is a little weird, but from Laravel's point of view they are pretty standard.
All my routes call controller actions in this manner, I didn't find a route that the issue didn't affect:
```php
Route::get('user/profile', [
    'as' => 'profile', 'uses' => 'UserController@showProfile'
]);
```

The Laravel 4 project is my first Laravel project and it was not complete when I started the upgrade to 5. I come from a CodeIgniter background, so forgive me if I am doing things in the wrong way.

**Comment by ItsTobias** [comment]
After doing some further testing and re-working my afterFilter to use the $response->getcontent() correctly rather than re-rendering the layout, the issue appears to have gone away.
So I am closing this issue as it seems it was just me doing stupid things rather than an actual issue.
