### ISSUE TITLE
laravel-debugbar 2.0 not compatible with laravel 4.1.x

### ISSUE THREAD

**Issue by ddeath** [barryvdh/laravel-debugbar#275]
Hi there,
when I run composer update it requires illuminate/support: 5.0.* however laravel 4.1.x requires illuminate/support: 4.0.* so there is a problem.

It would be nice to say something about this in release 2.0

**Comment by barryvdh** [comment]
It says in the readme on the top:
> ### For Laravel 4, please use the [1.8 branch](https://github.com/barryvdh/laravel-debugbar/tree/1.8)!

**Comment by ddeath** [comment]
Sorry my fault then, I was reading https://packagist.org/packages/barryvdh/laravel-debugbar and there was nothing there about it

**Comment by GrahamCampbell** [comment]
> when I run composer update it requires illuminate/support: 5.0.* however laravel 4.1.x requires illuminate/support: 4.0.* so there is a problem.

Is that not self-explanatory?
