### ISSUE TITLE
L5 Route cache

### ISSUE THREAD

**Issue by subdesign** [barryvdh/laravel-debugbar#276]
```php
php artisan route:cache
```
Debugbar doesn't appear
```php
php artisan route:clear
```
Debugbar appears and works well

Maybe it has a correct answer I just recognized this behaviour.

**Comment by barryvdh** [comment]
Yeah the routes are probably cached. Are you in local environment? It shouldn't cache in local..

**Comment by subdesign** [comment]
Oh, right, of course.

**Comment by Jan-J** [comment]
I don't know if this is Laravel issue or your package, but debugbar should work also with routes cached. I looked at this issue and with routes cached, event 'router.after' is not fired, so no scripts are inserted to response. Can other event be listened instead? Or should this be consulted with Laravel maintainers as a potential bug?

**Comment by barryvdh** [comment]
Does that package not working when routes are cached? Or only if they are cached before the debugbar is added?

Seems weird that the router.after event is not called.

**Comment by Jan-J** [comment]
I was wrong and this event is fired. But there is an issue with debugbar routes being not cached. Method `injectDebugbar` throws an exception, because route `debugbar.openhandler` is not defined. When calling `route:list` command, debugbar routes aren't there, event with not cached routes.

**Comment by Jan-J** [comment]
Ok this was my mistake I made, so routes were not generated correctly. Seems to be working fine with cached routes.
