### ISSUE TITLE
Errors from composer require

### ISSUE THREAD

**Issue by bl4ckdu5t** [barryvdh/laravel-debugbar#279]
After running the:
```
composer require barryvdh/laravel-debugbar
```
based on the Readme, it fails with the following error:
Your requirements could not be resolved to an installable set of packages. 
Problem 1
- don't install laravel/framework v4.2.16|don't install illuminate/support v5.0.0 
- don't install illuminate/support v5.0.0|remove laravel/framework v4.2.16 
- barryvdh/laravel-debugbar v2.0.0 requires illuminate/support 5.0.* -> satisfiable by illuminate/support[v5.0.0].
- Installation request for barryvdh/laravel-debugbar ~2.0 -> satisfiable by barryvdh/laravel-debugbar[v2.0.0].
- Installation request for laravel/framework == 4.2.16.0 -> satisfiable by laravel/framework[v4.2.16]. 

Installation failed, reverting ./composer.json to its original content.

**Comment by barryvdh** [comment]
For laravel 4, Use 1.x

**Comment by GrahamCampbell** [comment]
This is why composer's require command is crap, and I recommend adding the version you want yourself.

**Comment by GrahamCampbell** [comment]
// cc @frankdejonge

I think you mentioned this command to me at somepoint?

**Comment by bl4ckdu5t** [comment]
Thanks. That worked

**Comment by barryvdh** [comment]
It actually already said that in the 1.8 docs.
