### ISSUE TITLE
Debugbar causing havoc with my javascript

### ISSUE THREAD

**Issue by grafikkaos** [barryvdh/laravel-debugbar#281]
For some reason, having Debugbar active is causing problems on my applications.  

This is result of the log in Chrome:

http://test-l5.eo/_debugbar/assets/stylesheets?1423642083 Failed to load resource: the server responded with a status of 404 (Not Found)
http://test-l5.eo/_debugbar/assets/javascript?1423154427 Failed to load resource: the server responded with a status of 404 (Not Found)
settings:371 Uncaught ReferenceError: PhpDebugBar is not defined
main.js:9 Uncaught TypeError: undefined is not a function
http://test-l5.eo/_debugbar/assets/stylesheets?1423642083 Failed to load resource: the server responded with a status of 404 (Not Found)

When PhpDebugBar crashes, a lot of my site's javascript ends up crashing as well.  I am using Laravel 5.  Any ideas?

Thanks

**Comment by barryvdh** [comment]
Try moving the service provider up. do you have any catchall routes?

**Comment by grafikkaos** [comment]
Ah yeah...  I do have a catch all route... commenting that line out loads up the debugbar without any issues
Looks like i may need to revise that particular line of my routes file...

**Comment by barryvdh** [comment]
So did you try moving the provider up? Above your routes provider?

**Comment by grafikkaos** [comment]
Yes, that has fixed the issue as well..

**Comment by grafikkaos** [comment]
Thanks for the assistance :+1:

**Comment by barryvdh** [comment]
Only good, cause that's what the readme says about this ;)

**Comment by namenyi** [comment]
I had the same issue, and moving the provider up solved it for me too :) thanks @barryvdh!

**Comment by GTCrais** [comment]
same as @namenyi , thanks @barryvdh !

**Comment by ixperiencenl** [comment]
Also fixes problems when using VueJS frontend! Thanks!
