### ISSUE TITLE
How can I disable exception logging?

### ISSUE THREAD

**Issue by zeckdude** [barryvdh/laravel-debugbar#282]
I'm using the [Laravel Debugbar 1.8 Package](https://github.com/barryvdh/laravel-debugbar/tree/1.8) to display debug information. I'm noticing that the debug bar is logging errors to the log whenever an exception occurs. I would rather this doesn't happen, since I am running my own custom exception handler which collects information in the format I prefer and I have it logging to the log file as well.

So for example when I mistype a route name, I get the message saved twice to the log file:

> [2015-02-11 16:21:02] local.ERROR: Method [fdfdgfd] does not exist.
> 
> [2015-02-11 16:21:04] local.ERROR: Debugbar exception: Method
> UserController::fdfdgfd() does not exist [] []

How can I disable exception logging with the Debugbar?

**Comment by barryvdh** [comment]
Not really sure, I guess that error occurs when the Debugbar is collecting it's data, but that should only happen on the end of of the request (router after), so usually you app would have been thrown out already.
I think it happens here: https://github.com/barryvdh/laravel-debugbar/blob/1.8/src/LaravelDebugBar.php#L504-L536

Maybe you can try to narrow down which of the 4 try/catches is cathing them?

**Comment by skalero01** [comment]
Hi, i am getting `max_allowed_packet` error, but dont have access to the mysql configuration, so, its there a way to config the package for not debugging the errors?

I would appreciate it :D 

The exactly log i got its `Debugbar exception: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes`
