### ISSUE TITLE
Problem with vendor:publish in Laravel 5

### ISSUE THREAD

**Issue by mehrdd** [barryvdh/laravel-debugbar#283]
Hi,
Thanks for your excellent Package, but i have a problem in Laravel 5.
When i use `vendor:publish` nothing will happen. (no config/migration etc..)
it might be Laravel's problem though ...

**Comment by herlon214** [comment]
Mee to :+1:

**Comment by ghkdev** [comment]
─$ php artisan vendor:publish                                                                                                                                                                                                                            
exception 'ReflectionException' with message 'Class files does not exist' in /Users/.../vendor/laravel/framework/src/Illuminate/Container/Container.php:776

**Comment by GrahamCampbell** [comment]
You need `~2.0` on laravel 5. That is very clearly documented.
