### ISSUE TITLE
but did you think that about using enabled=> env('APP_DEBUG'). 

### ISSUE THREAD

**Issue by birtanyildiz** [barryvdh/laravel-debugbar#285]
my app can not load debug bar. but when i use like this in config  
enabled=> env('APP_DEBUG')
thats perfectly works. shall we change the config to this one?

**Comment by barryvdh** [comment]
No. That should have the same result

**Comment by alextyrey** [comment]
@barryvdh I think this is connected with a bug, actually.
I had the same problem where debugbar wouldn't load despite app.debug being set to true.

I'm thinking config/app.php is being loaded AFTER config/debugbar.php because
```
dd(config('app.debug'));
```
in config/debugbar.php returns null.

If you can't reproduce this, let me know. I just resorted to doing what @birtanyildiz did and left it alone.

**Comment by barryvdh** [comment]
Sorry can't reproduce this.

**Comment by barryvdh** [comment]
Can you switch the order or the service providers or something?

**Comment by bart** [comment]
Having the exact same problem here. This is the order of my service providers:

```
/*
 * Application Service Providers...
 */
'App\Providers\AppServiceProvider',
'App\Providers\BusServiceProvider',
'App\Providers\ConfigServiceProvider',
'App\Providers\EventServiceProvider',
'App\Providers\RouteServiceProvider',

/*
 * Third party Service Providers...
 */
'Barryvdh\Debugbar\ServiceProvider',
```

When I change <code>'enabled' => config('app.debug')</code> to <code>'enabled' => true,</code> it's working. Any idea about this issue?

**Comment by barryvdh** [comment]
Okay probably because app.php is not loaded before debugbar.php

https://github.com/laravel/framework/blob/1b205ae8ac897470f501b7d781057701eeb01ac1/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L66-L76

Not sure how to fix that, because we can't know the order for sure..

**Comment by barryvdh** [comment]
We could however try to load Laravels core alphabetically, but not sure if that is a proper fix.

**Comment by bart** [comment]
Maybe setting enabled to env('APP_DEBUG') could be a temporary solution, so that it doesn't depend on app.php. But I know the more elegant way is depending on the app debug setting.

**Comment by barryvdh** [comment]
I'll add a check to see if the enabled key === null. If null, set it to the app.debug value then.

**Comment by barryvdh** [comment]
See above, does that fix it?

**Comment by bart** [comment]
That works well @barryvdh. Thanks a lot!
