### ISSUE TITLE
'enabled' setting in configdebug file doesn't work

### ISSUE THREAD

**Issue by gputignano** [barryvdh/laravel-debugbar#288]
Hi,
I user the command:

php artisan vendor:publish to copy debugbar config file to the local config directory but Debug Bar doesn't appear. When I modify:

'enabled' => config('app.debug') to 'enabled' => true

it works again.

**Comment by barryvdh** [comment]
And your app.debug is true?

**Comment by gputignano** [comment]
Yes, it is true. I see the issue before has the same problem and this is a duplicate. Sorry.

**Comment by barryvdh** [comment]
Ok, continues in #285
