### ISSUE TITLE
Works perfectly but is not visible on the Laravel 5 'Whoops' page

### ISSUE THREAD

**Issue by olimorris** [barryvdh/laravel-debugbar#289]
Works perfectly, as described, and I love it except it does not appear on the Laravel 5 'whoops' error page which means I have to make do with its horrible and un-descriptive errors. It's as if it is not being injected on that page.

**Comment by GrahamCampbell** [comment]
Yes, that's the expected behaviour. You will need to change your http kernel to use the debugbar midleware yourself if you want that.

**Comment by GrahamCampbell** [comment]
NB, I'm not talking about the middleware array here.

**Comment by barryvdh** [comment]
Well there is a L5 middleware but can't inject it automatically. You could try to add it to your middleware array but haven't fully tested it yet.

**Comment by GrahamCampbell** [comment]
> You could try to add it to your middleware array but haven't fully tested it yet.

That won't work. Laravel doesn't go through the same response cycle for error handling.

**Comment by sestolk** [comment]
It took me some tinkering but eventually I got this working in the Exceptions\Handler.php file:

```
public function render( $request, Exception $e )
{
$whoops = new Run;
$whoops->allowQuit( false );
$whoops->writeToOutput( false );
$whoops->pushHandler( new PrettyPageHandler() );

$status = $e instanceof HttpExceptionInterface ? $e->getStatusCode() : 500;
$headers = $e instanceof HttpExceptionInterface ? $e->getHeaders() : [ ];

$debugbar = App::make( 'debugbar' );
$debugbar->boot();

return $debugbar->modifyResponse( $request, Response::make( $whoops->handleException( $e ), $status, $headers ) );
}
```

**Comment by barryvdh** [comment]
I have another solution. Will push soon.

**Comment by barryvdh** [comment]
This would make more exceptions caught by the Debugbar: https://github.com/barryvdh/laravel-debugbar/commit/007534bf62f1415e9ddf9aba5d38ccdfc17180dc

Can you test with `2.x@dev`?

**Comment by olimorris** [comment]
Just tested now. Appears on the whoops page but does not capture exceptions itself. Is this expected behaviour?
![screen shot 2015-03-19 at 00 52 22](https://cloud.githubusercontent.com/assets/9512444/6722488/4736a83a-cdd2-11e4-899f-77f974849ef2.png)

**Comment by barryvdh** [comment]
I think you can add Debugbar::addException to your report function in your aerror handler.

**Comment by amenk** [comment]
Cool, would be nice if it works also in ` \GrahamCampbell\Exceptions\ExceptionHandler`
