### ISSUE TITLE
Using Debugbar with dingo/api throws errors

### ISSUE THREAD

**Issue by EspadaV8** [barryvdh/laravel-debugbar#290]
I've just installed the debugbar into a project that uses the dingo/api package. Attempting to load up a route that has been defined within a API group throws a 'Route not defined' exception.

I've submitted this big to both packages (https://github.com/dingo/api/issues/363) since I'm not sure which one has the problem.

**Comment by barryvdh** [comment]
Does dingo have a catch all route? If so, put my package before Dingo in the providers list.

**Comment by EspadaV8** [comment]
Unsure, however, I'm only adding Debugbar in dev configs using `append_config` so it will always appear after the Dingo provider.

I'll add it before Dingo to see if that helps but would there be a way to have it added after Dingo and still work?

**Comment by EspadaV8** [comment]
So adding it directly into the global app.php file before Dingo didn't help, the same error is still thrown.

**Comment by EspadaV8** [comment]
So, through a bit of random commenting/deleting lines it seems that it has something to do with the JavascriptRenderer, although I have no idea why that would be causing anything like this (commenting out lines 366-368 in LaravelDebugbar.php stops the error from being thrown).

**Comment by EspadaV8** [comment]
I've created a minimal test case laravel install that shows the issue

https://github.com/EspadaV8/dingo-debugbar/tree/develop
