### ISSUE TITLE
Invalid URI's redirect to a javascript file

### ISSUE THREAD

**Issue by nblackburn** [barryvdh/laravel-debugbar#291]
Invalid URI's seem to be intercepted and redirected to something along the lines of:

```
example.com/_debugbar/assets/javascript?1424249195
```

Or possibly i messed up somewhere.

**Comment by jaroslawziolkowski** [comment]
This url is ok. If you use own redirects, for example to set language identifier, you should set function to exclude it.

For example. I use Middleware Language to language id control. I added in config/app.php variable with excluded  pattern and in Middleware check function. When in url is excluded string, is not redirect.

**Comment by epileftro85** [comment]
hi @jaroslawziolkowski , How exactly did you build the exclude pattern? i have the same issue if i use Controller for routing, tks.
