### ISSUE TITLE
Font awesome global collision

### ISSUE THREAD

**Issue by nickcolley** [barryvdh/laravel-debugbar#295]
The version of font-awesome that is included leaks to the application which has a different version.

In our example it breaks the rendering of our icons which is frustrating when debugging.

I'm thinking we could namespace the version used in this debug bar, willing to help if that sounds good.

Are you doing anything fancy importing your resources? If not I can put a PR together to fix. 

Cheers :+1:

**Comment by barryvdh** [comment]
Any ideas how to best handle this? Use different font name and override the font for icons in debugbar namespace?

**Comment by nickcolley** [comment]
I'm thinking we could wrap like so:
```css
.phpdebugbar .fa {}
```

That way the font-awesome we load in with this library only applies to the debug bar.

So it's easy to update we could build from FA's pre-processor files so it's easy to update.

Otherwise we could manually wrap all of the font-awesome classes if you wanted to keep it simple without a build step, it'd just mean more work to update FA

**Comment by barryvdh** [comment]
I guess 1 would be best, but also have to update the core (php-debugbar). And laravel-debugbar uses an inline version.

But what is the conflict exactly? Should be on the latest version now.

**Comment by nickcolley** [comment]
We use an older version at the moment.

**Comment by MichealMi** [comment]
Has this problem been solved? I use the latest debug bar, but still have this problem. Font awesome icons are rendered when debugbar is enabled. But when it is disabled, I miss some icons.

**Comment by barryvdh** [comment]
You mean the other way around? What version of Font Awesome are you using?

**Comment by MichealMi** [comment]
I have to apologize for this error. I thought I had 4.3 but I did a "git pull" operation on my new development machine and didn't noticed it had an older version of FA installed. Problem solved.

**Comment by BlueManLine** [comment]
Bump

I want to use Font Awesome 4.4, but the debugbar have 4.3.

The problem will flow once again if debugbar will not use their own "css namespace".

**Comment by nickcolley** [comment]
Yeah this is still a problem, we need to namespace the font-awesome used in the debug bar.

**Comment by barryvdh** [comment]
Indeed, but not sure what the easiest way to do this is, with preserving the option to update easily.

**Comment by BlueManLine** [comment]
I do not know the CSS structure/options so if the css namespacing isnt available, than I have other idea:

How many font icons the debugbar use? I count 10.
So maybe the easiest thing is to copy just the X font declarations to new css file with different selector names?

**Comment by nickcolley** [comment]
I'd change https://github.com/maximebf/php-debugbar/blob/e5d9c677175d147b72a05087b916dfd103e1df74/src/DebugBar/Resources/debugbar.js#L263 to php-debugbar-icon-

Then have a build script in the base project that builds font-awesome from source. with the variables set to that https://github.com/FortAwesome/Font-Awesome/tree/master/less

**Comment by barryvdh** [comment]
That could be a good idea. Another idea I was thinking about was using base64-encoded icons in the CSS (or php), instead of using a font.

**Comment by nickcolley** [comment]
I think this is a problem with the other vendor files as well, with jQuery being injected. Maybe a higher level approach would be better. Maybe an iframe?

**Comment by barryvdh** [comment]
Also thinkin about that, ideally we would have minimal dependancy in the 'first stage' (plain javascript/css) that could inject the debugbar, similar to Zend Z-Ray. But that's a pretty big rewrite.. (see http://serverdemo.zend.com/laravel/ )

**Comment by nickcolley** [comment]
I've raised a PR here: https://github.com/maximebf/php-debugbar/pull/225

Font Awesome upgrade progress with this is just, copy paste new font-awesome. Run the replace script.

**Comment by BlueManLine** [comment]
+1 - if that help to push the PR, even if it will be just temporary solution.

**Comment by arcanedev-maroc** [comment]
@barryvdh Please update the font awesome to 4.5.0

I've an issue with the new google plus icon.

**Comment by nickcolley** [comment]
@arcanedev-maroc again, this is a temporary fix, we should make sure the debug bar does not use the same global classes rather than racing the current version.

**Comment by barryvdh** [comment]
The PR was merged and tested. Also updated this repo (and bumped to FA 4.5)
Can you guys check v2.2@dev?

**Comment by bluemanos** [comment]
Updated. Works for me, thanks!

**Comment by nickcolley** [comment]
Thanks all :+1:
