### ISSUE TITLE
helps

### ISSUE THREAD

**Issue by intrepidtr** [barryvdh/laravel-debugbar#296]
Problem 1
   - Installation request for barryvdh/laravel-debugbar ~2.0@dev -> satisfiable by barryvdh/laravel-debugbar[2.0.x-dev, v2.0.0, v2.0.1].
   - Conclusion: remove laravel/framework dev-master
   - Can only install one of: psy/psysh[v0.4.0, 0.3.x-dev].
   - Can only install one of: psy/psysh[v0.4.0, 0.3.x-dev].
   - laravel/framework dev-master requires psy/psysh 0.4.* -> satisfiable by psy/psysh[v0.4.0].
   - Installation request for laravel/framework dev-master#700bbf22bb325a3ddd10e2fc839feb9b4958387a -> satisfiable by laravel/framework[dev-master].
   - Installation request for psy/psysh == 0.3.9999999.9999999-dev -> satisfiable by psy/psysh[0.3.x-dev].

	"laravel/framework": "dev-master#700bbf22bb325a3ddd10e2fc839feb9b4958387a",
		"illuminate/html": "5.0.*@dev",
		 "bllim/datatables": "*",
    		"mitchellvanw/laravel-doctrine": "0.4.*",
    		"intervention/image": "dev-master",
    		"thujohn/analytics": "dev-master"

**Comment by barryvdh** [comment]
Never require dev-master, use laravel/framework 5.0.x
