### ISSUE TITLE
Using laravel-debugbar with rcrowe/Raven

### ISSUE THREAD

**Issue by tremby** [barryvdh/laravel-debugbar#297]
I'm using [rcrowe/Raven](https://github.com/rcrowe/Raven) and its Laravel service provider to have exceptions logged to a Sentry server.

It seems that it and Laravel Debugbar conflict.

My test case is this: is in a route I do

```
Log::info("test info");
Log::error(new Exception("test error/exception"));
```

With only the Debugbar service provider enabled, both of these appear nicely in the Messages tab, and they're both in the log file. Great.

With only the Raven service provider enabled, both are in the log file (though interestingly this time the exception doesn't have a stack trace -- is that something Debugbar adds?) and the exception is sent to Sentry. This is good too. But I want both.

With both service providers enabled, Debugbar and then Raven, both messages are in the log file (again with no stack trace), and the exception is sent to Sentry, but there is nothing in the Messages tab (or in Exceptions).

With the service providers the other way around (Raven and then Debugbar), both messages are in the log file (again with no stack trace), and the exception is sent to Sentry. There is nothing in the Messages tab, but in the Exceptions tab there are two entries:

```
Cannot add LogsCollector to Laravel Debugbar: Events dispatcher has not been set. /vagrant/vendor/barryvdh/laravel-debugbar/src/LaravelDebugBar.php#258 Exception
Events dispatcher has not been set. /vagrant/vendor/laravel/framework/src/Illuminate/Log/Writer.php#192 RuntimeException
```

Any idea what the problem is? Is there anything I can do to have Raven handle the Log::error call, but have it also handled by Debugbar and put in the Messages tab?

**Comment by tomzx** [comment]
My guess is that something is wrong with the `Log` class provided by rcrowe/Raven. See rcrowe/Raven#22.
