### ISSUE TITLE
debugbar not showing. Env is local, storage is ok

### ISSUE THREAD

**Issue by e4rthdog** [barryvdh/laravel-debugbar#298]
Just installed it on my L5 (latest 5.0.13) application.

Storage directory has files and i have no log errors.

Also environment is ok. debug=1

any ideas?

**Comment by barryvdh** [comment]
Can you try with latest version (2.0.2)?

**Comment by e4rthdog** [comment]
just made composer update but i have 2.0.1. How do i pull 2.0.2?

**Comment by barryvdh** [comment]
Try again after few minutes (now)

**Comment by e4rthdog** [comment]
Just did a composer update again and it is ok now. composer.json as normal ~2.0.

Thanks
