### ISSUE TITLE
Debugbar doesn't work in Laravel 5

### ISSUE THREAD

**Issue by tadejongithub** [barryvdh/laravel-debugbar#305]
I have a local environment with a subdomain defined for my app and when I set to use the debugbar I get errors: 
1. the css and js files are not loaded (404)
2. the phpdebugbar is not defined;

I followed all the install instructons but without a succcess. Any suggestions?

**Comment by GrahamCampbell** [comment]
What have you put in the require block?

**Comment by tadejongithub** [comment]
"require": {
		"laravel/framework": "5.0.*",
		"barryvdh/laravel-debugbar": "~2.0"
	},

Here is also a screenshot of the console output if it helps...

![2015-03-12 08_08_24-developer tools - http___neda localhost com_](https://cloud.githubusercontent.com/assets/7260332/6613543/046085e6-c88f-11e4-8081-b660ab6b0f30.jpg)

**Comment by barryvdh** [comment]
Yeah those assets should be loaded. Do you have a catch all route or something?

**Comment by tadejongithub** [comment]
I had wrong apache configuration for the folder where the app exists. It works now like a charm. Thx for the help.

**Comment by OzanKurt** [comment]
@tadejongithub Can you please provide your solution?

**Comment by tadejongithub** [comment]
It was just a typo in apache config but I don't remember anymore what was it. Sorry..
