### ISSUE TITLE
Jquery is eaten when using debugbar with pjax

### ISSUE THREAD

**Issue by tremby** [barryvdh/laravel-debugbar#309]
The latest version of [jquery-pjax](https://github.com/defunkt/jquery-pjax) (1.9.5, commit https://github.com/defunkt/jquery-pjax/commit/00191366fae68a188286ebb65ec342cb3f6ff37b in particular) introduces an issue with debugbar.

When switching to a different page via pjax and then hitting the "back" button, external scripts are not run again, but now in the new version inline ones are run again. Therefore the `jQuery.noConflict(true)` line is running, and the instance of Jquery the site developer put on the site is eaten. JS running on the page then breaks since the reference to `$` is gone. (You could argue that my code is broken for not having captured that reference. True. But this could still be a problem for other scripts pulled in later.)

I've mentioned this at https://github.com/defunkt/jquery-pjax/issues/502 but I think perhaps this would be better fixed in debugbar. Could the noConflict line simply be in the external script? Or can there be an option added to include the other vendor scripts but _not_ jquery (since I know my page will already provide it)?

**Comment by barryvdh** [comment]
Yeah you can exclude vendors in the config.

**Comment by tremby** [comment]
As I said, I still want to include the other vendor scripts. Just not jquery, since the site already includes it.

And you didn't touch on the other suggestion, of including the `noConflict` line in the external script. Perhaps that's simpler.

**Comment by barryvdh** [comment]
Okay I see it's not in the config but you can do something like this:

    $renderer = Debugbar::getJavascriptRenderer();
    $renderer->disableVendor('jquery');
    $renderer->setEnableJqueryNoConflict(false);
