### ISSUE TITLE
Session/_token problems

### ISSUE THREAD

**Issue by nickbr5** [barryvdh/laravel-debugbar#310]
Hi all, 

I'm experiencing some session problems when the debugbar is activated.
It looks like sometimes the debugbar causes a new session and also a new token. When i submit my form i get an exeption of the verifyCRSFToken middleware because somehow the session token and the hidden field _token are not the same anymore.
When i disable the debugbar all problems are gone.

**Comment by GrahamCampbell** [comment]
This is actually a laravel bug caused by using the file driver by sessions. Switch to a different driver, and you're sorted.

**Comment by kerwitz** [comment]
It seems like the issue persists when using the database driver. I receive the `TokenMismatchException` on a form request and after that the complete session is outdated.
The form has fields that utilize autocompletion through a local API.

**Comment by nickbr5** [comment]
Yes, i also keep having the problem when choosing another driver.
I've disabled the plugin for now, i hope we can resolve this problem soon.

**Comment by thstarshine** [comment]
I've experienced the same issue. At the first time I thought that was related to some settings in `config/session.php`. But apparently it's not. I then created a new project with just a simple welcome page displaying two session variables `test` and `test2`:

```
   if ($request->session()->has('test'){
      $request->session()->put('test2', 'test2');
   } else {
      $request->session()->put('test', 'test');
   }
```

I expected to see `test` when I first loaded the page and see both `test` and `test2` after I refreshed the page (no matter how many times I reloaded it, of course!). Everything works fine, however if Debugbar is enabled, sometimes randomly the page just showed `test`, and the Session tab of Debugbar also showed that `_token` had been changed.

Good news is that now I know it's not related to anything of my program and I don't need to worry about it will happen when the site goes live. But I do hope this issue could be fixed ASAP.

**Comment by barryvdh** [comment]
Hmm, does anyone have any clues? Haven't experienced it yet.

**Comment by barryvdh** [comment]
@thstarshine Was this always, or since recent updates from either Laravel or Debugbar?

**Comment by thstarshine** [comment]
Hi @barryvdh I just started to use Laravel last month so I'm not sure since which version this has happened. I'm using Laravel 5.1 and Debugbar 2.0.5 with [WNMP](https://www.getwnmp.org/) 2.1.9 under Windows. 

I guess it may be OS dependent If there're just few people experiencing this. I'm going to deploy my site to Ubuntu next week and I'll come back if I find anything new.

**Comment by tarikgan** [comment]
I get same problem, but the problem only exist on my test server which is a shared hosting server, so I don't have full access to look and change the configuration in it. I don't get this problem on my localhost.

This problem disabling me to use session and cookies because it change the session id (and _token) everytime I go to other route.
When I delete laravel-debugbar from my composer, the problem suddeny gone.

I use Laravel 4.2.17, debugbar 1.8.7.

**Comment by dvispo** [comment]
During 2 weeks I had problems with the session. Some data stored in session were randomly deleted. I tried everything and finally after I disabled DebugBar it works perfectly.

**Comment by w1n78** [comment]
i'm also experiencing this with laravel 5.2. i noticed debugbar has _token as well. also noticed in the query analyzer that it's returning 2 records. this is happening on both mysql and mssql. when i go into the config debugbar file and set 'enabled' => false - it goes away and everything is working. this is when i use session driver as database.

**Comment by stefkes** [comment]
Fresh install of debugbar + Laravel 5.4 kills the sessions.

**Comment by ilumos** [comment]
I have this issue too, but only when using the `database` session driver - using the `file` driver works fine.

Disabling debugbar also allows session data to be saved.

Laravel 5.7 on Ubuntu Server 18.04 and WSL 18.04

**Comment by hafissafwan** [comment]
kjnlnl
