### ISSUE TITLE
debugbar doesn't collect output from global after middleware

### ISSUE THREAD

**Issue by peerrabe** [barryvdh/laravel-debugbar#311]
Register this following middleware in Kernel.php global HTTP middleware stack and only 1 will be displayed under "Messages". Is there some explanation for this behavior?

``` php
class AfterMiddleware implements Middleware {

    public function handle($request, Closure $next)
    {
        debug('1');
        $response = $next($request);

        debug('2');

        return $response;
    }
}
```

in use:
- current laravel 5.0.x-dev
- current debugbar master

**Comment by ammont** [comment]
I'm using laravel 4.1 and none of the displays.

**Comment by ShuaiyiWu** [comment]
+1

**Comment by ShuaiyiWu** [comment]
solution: in your /app/Http/Kernal.php, manual add "\Barryvdh\Debugbar\Middleware\Debugbar::class" to $middleware[] will work for me
