### ISSUE TITLE
Laravel 5 and debugbar

### ISSUE THREAD

**Issue by xadim** [barryvdh/laravel-debugbar#312]
Hi,

I'm having some issue getting the debugger working.
I just installed a fresh Laravel 5 and follow step by step the debugbar installation process. But cannot have it run.

**Comment by barryvdh** [comment]
Is there any output in the source code? Any error in the laravel log of the browser console?
if there is anything in the source code, can the assets be loaded?

Is app.debug true:

**Comment by xadim** [comment]
I've just the initial whooops basic error page.

**Comment by xadim** [comment]
This is what I've in app.php 'debug' => env('APP_DEBUG'),

**Comment by barryvdh** [comment]
And what is APP_DEBUG?

**Comment by xadim** [comment]
That's just the default Laravel config i did make any change

**Comment by barryvdh** [comment]
no in you .env file, is it set to true?

**Comment by xadim** [comment]
this is my env

APP_ENV=local
APP_DEBUG=true
APP_KEY=key

DB_HOST=localhost
DB_DATABASE=my_db
DB_USERNAME=db_user
DB_PASSWORD=pass

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null

**Comment by jasonbourne501** [comment]
ok

**Comment by barryvdh** [comment]
But you say Whoops error page? Did you try on a page without any errors?

And can you answer the questions?

> Is there any output in the source code? Any error in the laravel log of the browser console?
if there is anything in the source code, can the assets be loaded?

**Comment by xadim** [comment]
The only error I'm having is that the form cannot be send and i get the Whoops

**Comment by barryvdh** [comment]
Sorry, I have no idea what you mean. Please try to be a bit clearer in what you are actually doing and what the problem is. I don't know what 'form' you are talking about. And debugbar doesn't work on error pages, only proper responses.

**Comment by xadim** [comment]
Ok,

I'm trying to send a form to populate my db, but the form cannot find the route I specified and send me the Whoops error page (with any helpful info for debugging). After guessing, I fixed that and have now a db connexion failed. I would like to have the debugbar working for a better understanding of my errors.

**Comment by xadim** [comment]
![screen shot 2015-03-18 at 10 14 25 am](https://cloud.githubusercontent.com/assets/3090152/6710509/9f686fd2-cd57-11e4-9ffa-a2399a2ffea8.png)
This is what I'm having.

**Comment by barryvdh** [comment]
Debugbar doesn't work on error pages yet. It will soon.

**Comment by barryvdh** [comment]
It should handle errors better on the latest dev version (`2.x@dev`).

For this error, you should probably just add a hidden `_token` input field with `csrf_token()` as value. See http://barryvdh.nl/laravel/2015/02/21/csrf-protection-in-laravel-explained/

**Comment by xadim** [comment]
Hi Barryvdh, I just found out that the problem was with Opera which is obviously not compatible with the plugin.
Thanks!
