### ISSUE TITLE
no debugbar when json data is returned.

### ISSUE THREAD

**Issue by pavankumarkatakam** [barryvdh/laravel-debugbar#314]
im just creating a API with json data output. i observed that when json data is returned to browser there is no laravel-debug bar. but when a string is returned then there is debugbar

**Comment by barryvdh** [comment]
That is correct. Adding html to a json response would break the json.
It would be waves though in the history of the debugbar. Also, if you make Ajax request from a page with the debugbar, it should show the info.

**Comment by pavankumarkatakam** [comment]
Is there any way to

**Comment by hootlex** [comment]
However it would be nice if we could easily enable/disable it.

**Comment by pavankumarkatakam** [comment]
But always enabling and disabling it time consuming?

**Comment by hootlex** [comment]
If it is something simple I dont think it would be time consuming.

For example:
```php
if (env('APP_DEBUG')) {
 Debugbar::debugJSON();
}
```

**Comment by LucaColombi** [comment]
does exists a chrome plugin for this case? So I can see the debugbar even for json
