### ISSUE TITLE
L5, ::enable() - no show, no error

### ISSUE THREAD

**Issue by hulkur** [barryvdh/laravel-debugbar#315]
L 5.0.18, D 2.0.3

If debug is true in .env everything is working fine.
If debug is false in .env and i call enable() then debugbar is not showing up.
Called it from several places with no result. Nothing in log or console.

Question: where is the correct place from where to call enable()?

**Comment by Stricted** [comment]
same problem here, i wanted to dynamically enable it over a flag in "production" environment (just over an admin permission)
as soon as APP_DEBUG is false and/or enabled in config/debugbar.php is false i can not enable it
unfortunately nothing happens aber calling `\Debugbar::enable();`
