### ISSUE TITLE
Debugbar with language identifier wrong url to assets.

### ISSUE THREAD

**Issue by Bananamoon** [barryvdh/laravel-debugbar#317]
I'm using debugbar together with mcamara/laravel-localization. Since I wanted my languages in the url I had to add it in the middleware. When I do this the url to the assets of debugbar are the following:

http://test.local/en/_debugbar/assets/stylesheets?1427286728
http://test.local/en/_debugbar/assets/javascript?1427286728

and leads to the assets not being found.
I checked both issues in here and on the git of the laravel-localization but can not find a clear solution.

**Comment by barryvdh** [comment]
Is this fixed?

**Comment by Bananamoon** [comment]
Think the issue is more for the Laravel-localization than the debugbar since the session is misbehaving. When I turn off the LocaleSessionRedirect in my kernel.php everything works fine.  Thanks for the help though!
