### ISSUE TITLE
Debug Bar Not Displaying?

### ISSUE THREAD

**Issue by chood531** [barryvdh/laravel-debugbar#319]
I've been using this package for a while now and it has been working great!

As of this morning, the bar is no longer loading, however.

Couple of things:

APP_DEBUG=true in my .env file
Package has been added as both a Service Provider and a Facade
I have published the config file debugbar.php for the package

Is there anything else that would have changed that I need to update on my end?

I suspect this may be related to the latest Laravel 5.0.22 release, as the debug bar was working just fine with 5.0.16.

**Comment by SachinAgarwal1337** [comment]
@chood531 Its working fine for me for Laravel 5.0.22 also.<br>
did you change the 'enabled' property to 'true' in config/debugbar.php?

**Comment by chood531** [comment]
@SachinAgarwal1337  - yes APP_DEBUG is set to true, which is how to the value in config/debugbar is set.  I am scratching my head here - not sure what the issue could be.

**Comment by chood531** [comment]
@SachinAgarwal1337  - I figured it out.  It was related to this resolved issue:

https://github.com/barryvdh/laravel-debugbar/pull/287

**Comment by beststrelok** [comment]
I figured out 2 common reasons for this issue:
1. you need to clear cached view files or restart server
2. (my case) you declared catch all route like:

Route::any('{any}', function(Request $request) {
	$cart = session('cart');
	Log::warning('404 - Missing page at: '.$request->url());
    return response(view('errors.404', compact('cart')), 404, []);
})->where('any', '.*');

So any third-party routes are disabled. 
Hope that helps...

**Comment by ahmedash95** [comment]
@beststrelok What if i need the ``` Route::any({'any'}) ```?

**Comment by CindyBoy** [comment]
> I figured out 2 common reasons for this issue:
> 
> 1. you need to clear cached view files or restart server
> 2. (my case) you declared catch all route like:
> 
> Route::any('{any}', function(Request $request) {})->where('any', '.*');
> 
> So any third-party routes are disabled.
> Hope that helps...

Enviroment: Lumen 5.5.2  barryvdh/laravel-debugbar@3.2
It not works!!!

**Comment by CindyBoy** [comment]
$debugbar = new LaravelDebugbar();
$renderer = $debugbar->getJavascriptRenderer();
$debugHtml    = $renderer->renderHead().$renderer->render();


Add this code to the end, Hope that helps you !
