### ISSUE TITLE
DB queries won't show if DB config was changed programatically 

### ISSUE THREAD

**Issue by hubail** [barryvdh/laravel-debugbar#320]
Somehow related to #22 

When you overwrite database info using Config::set(), two exceptions are thrown:

`Cannot add listen to Queries for Laravel Debugbar: SQLSTATE[HY000] [1049] Unknown database 'xyz'
vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#295
Exception`

and

`SQLSTATE[HY000] [1049] Unknown database 'xyz'
vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php#47
PDOException`

laravel-debugbar always reverts to what's on the config files despite the dynamic change, this is probably related to the request lifecycle I guess (collector being loaded before the controller dispatch)?

**Comment by lukasoppermann** [comment]
I am having the same problem (I think). In my app, I am using different db connections but only the default connection is show. Is there any way I can fix this? @barryvdh any idea?

The new db connection is added at runtime depending on the info from the database.

**Comment by jcalonso** [comment]
Having the same problem here, is there a way to handle dynamic connections?

**Comment by londoh** [comment]
...and the same problem and question from me.

This is in a multi tenant app where db is switched early depending on url. No queries are shown in debugbar.

l.

**Comment by LasseRafn** [comment]
This doesn't seem to be an issue for us :) Issue must've been resolved.
