### ISSUE TITLE
debugbar is not showing up after 'config:cache' command

### ISSUE THREAD

**Issue by gholol** [barryvdh/laravel-debugbar#328]
Hello,

Laraver debugbar is not injected into my page if i execute artisan's config:cache command.

It's just not showing up. When i do 'artisan config:clear' everything is back to normal.

I'm using Laravel 5.0.27

**Comment by constb** [comment]
This happens because Debugbar disables itself for console commands. 'artisan config:cache' is a console command so while it's running ``'debugbar.enabled'=false`` and this is the value that gets cached.

**Comment by gholol** [comment]
Oh, i see. Thanks for explaination

**Comment by Tantacula** [comment]
Ou, very useful information. Thank you very much.

**Comment by jaketoolson** [comment]
This was useful to me as well -- not sure if its well known.
