### ISSUE TITLE
Disabling auto-navigation to most recent AJAX request

### ISSUE THREAD

**Issue by benjaminkohl** [barryvdh/laravel-debugbar#330]
Forgive me if this is in the docs, but I couldn't find it--is there a way to disable the auto-refresh of the debug bar when AJAX calls occur? Sometimes I want to examine some queries from the original page load request but each time an AJAX call is made on a set interval, the debug bar automatically navigates to that request's data. I'd like it to stay on the currently selected request until I click over to a different one.

Thanks.

**Comment by barryvdh** [comment]
This currently isn't possible. It is in the to do list.

**Comment by benjaminkohl** [comment]
Thanks. Are there any known forks where someone might be working on this feature already?

**Comment by aliazizi** [comment]
I disable it by editing source file

in `JavascriptRenderer` Put `protected $ajaxHandlerAutoShow = false;`

**Comment by thbighead** [comment]
Is it still impossible?

**Comment by eness** [comment]
Add below line as one of last key defined at config/debugbar.php :

`'ajax_handler_auto_show' => false`
