### ISSUE TITLE
Debugbar doesnt work for Route::controller('/', 'IndexController');

### ISSUE THREAD

**Issue by BlueManLine** [barryvdh/laravel-debugbar#333]
When I have a root route set as controller() than the debugbar isnt working.
The http://sportforcharity.local.host/_debugbar/assets/stylesheets?1425741323 is returning `Controller method not found` exception.
The JS function responsible of runing the debugbar `var phpdebugbar = new PhpDebugBar.DebugBar();` is also throwing an exception `ReferenceError: PhpDebugBar is not defined` which prevent runing other JS functions/libraries :/

**Comment by BlueManLine** [comment]
I need it for catching missing method for root controller.

Right now I fix it by this routes:
```php
Route::get('/', 'IndexController@getIndex');

Route::any('{catchall}', 'IndexController@missingMethod')
    ->where('catchall', '^((?!_debugbar/assets/stylesheets|_debugbar/assets/javascript).)*$');
```

But I dont think that this is the best way to do this ;)

**Comment by paolooo** [comment]
+1 @BlueManLine 

As for me, what I did is...

```
Route::any('{path?}', function() {
    // ....
})->where('path', '(?!_debugbar\/).+');
```
