### ISSUE TITLE
Feature Request: Easily Selectable File Paths

### ISSUE THREAD

**Issue by astorm** [barryvdh/laravel-debugbar#340]
There's numerous places where the debugger's UI will display a file path

Views
    home (app/views/home.blade.php)
    layouts.scaffold (app/views/layouts/scaffold.blade.php)    

Routes

```
file    app/path/to/Controller.php
```

It would be nice if, application wide, it was possible to easily select any file path for pasting into text editors, file open dialogs, the terminal, etc.

For example: Right now, if you triple click a path in the Views tab (`app/views/layouts/scaffold.blade.php`), the **entire** line is selected, and not just the file path.

Or on the Route tab there's some weirdness when you try to select the file path, and the weirdness prevents selection entirely.  If there was a standard way of handling the display of the file path within the application that made it easier for developers to copy file paths (the most commonly copied piece of information, I'd bet), it'd make an already great extension even better.     

Is this something the project would be open to?

**Comment by barryvdh** [comment]
I was thinking about a copy button (see https://github.com/maximebf/php-debugbar/issues/130) is that what you mean, or do you have a different proposal?

We could perhaps make filepaths a link and when clicked, the full path is copied.

**Comment by astorm** [comment]
A copy button would work, or just some desktop UX work to make sure the text is isolated and easily selectable.
