### ISSUE TITLE
FileViewFinder won't work with namespaces.

### ISSUE THREAD

**Issue by apps4u** [barryvdh/laravel-debugbar#341]
HI Ive been trying to work out a problem for three days now and Ive been posting issue on other packages as they have not been working . But after three days of that Ive worked out it was this packages 

When using this package I was not able to send emails as I could not load views that were from other packages. The FileViewFinder in laravel would not have the views name space in its hints array. 

I ended doing a few new installs and they work so I then added all the packages that I had in my project to the new site and it stopped working . So I knew it was one of the packages so one by one I uninstalled and reinstalled each package and service provider and as this package would loaded from the app/providers/AppServiceProvider.php class so i could check env it was the last package I tested.
Once I removed this packages service provider I could and send emails .. 

The emails were in a view namespace e.g.:

```
platform/media::emails.email
```

or 

```
apps4u/users::emails.welcome_user
```

both of these package are in the FileViewFinder $hints array only when this package is not installed.

I can send a stack trace if you like.

**Comment by barryvdh** [comment]
Does it work when you disable the view collector (in the config)? And/or the mail collector?
Are there any errors in the log? Perhaps an exception occurs when trying to send an email.

It's strange that the paths aren't found, because I don't think I actually do anything with it.

**Comment by apps4u** [comment]
I just tried your idea and Turned off mail collection in the config file . And Emails are now being sent.  So it looks like its the mail collector.  
Now that I know I'll try to debug and get a idea on how to fix but Im don't know the internals of this package so don't know if I'll be much help.
