### ISSUE TITLE
Compatibility issues with "cartalyst/composite-config"

### ISSUE THREAD

**Issue by Omranic** [barryvdh/laravel-debugbar#344]
Just noticed that This package isn't compatible with "cartalyst/composite-config", when used through "cartalyst/platform2". After digging deep I've noticed that whenever the following line is executed the problem happens, while before that line everything seems to be OK. When commented out cartalyst's platform works just fine, but of course the debugbar is distributed.
https://github.com/barryvdh/laravel-debugbar/blob/813c5a9c39186b0a84613035824d9929a5467fc9/src/LaravelDebugbar.php#L425
This happens actually once the "$this->app['url']" is called!! Any suggestions?

**Comment by maherelgamil** [comment]
+1

**Comment by barryvdh** [comment]
Do they override/extend/change the url instance in the all container? Otherwise I wouldn't really know..
what error do you get?

**Comment by Omranic** [comment]
Yes, the 'url' service is being overridden, and the 'config' service is being extended somehow (didn't dig in it yet) to fetch the custom platform configurations & merge with the core config values..

Basically there's no error messages, I actually get null for all custom (aka. cartalyst/platform2) config values.. But I'm still confused what's the relation between both services 'url' & 'config' to cause such conflict.

I'll be happy to provide any further details..

**Comment by barryvdh** [comment]
Where can I found cartalyst/platform2? Is it paid?

You could try switching around the order of the service providers.

If they register the `url` instance during the `register()` method, I don't really understand why it doesn't work. These conflicts usually appear when one of the providers replaces an instance during boot, so the app uses 1 instance for the first half, the other instance for the last half.

**Comment by Omranic** [comment]
Yes, Cartalyst Platform is a paid package: https://github.com/cartalyst/platform
The issue appears with version 2 (Laravel 4) by the way, not 3 (Laravel5)

Already tried switching service providers with no effects at all.

The 'url' service is being overridden in the register() method, not in the boot():
```
		$this->app->bindShared('url', function($app)
		{
			$routes = $app['router']->getRoutes();

			$request = $app->rebinding('request', function($app, $request)
			{
				$app['url']->setRequest($request);
			});

			$urlGenerator = new UrlGenerator($routes, $request);
			$urlGenerator->setAdminUri(admin_uri());

			return $urlGenerator;
		});
```

Side Notes:
- The following services are all being overridden/extended: 'request', 'url', 'router', 'translator', 'redirector' :smile: 
- Once I've disabled the 'url' service override everything works fine, so we've two clues now, this one & the other one mentioned in previous comment.

Any suggestions?

**Comment by Omranic** [comment]
Any suggestions?

**Comment by Omranic** [comment]
@barryvdh Sorry to bother you, but do you've any recommendations to solve this issue?
