### ISSUE TITLE
SSL Problem...

### ISSUE THREAD

**Issue by googled** [barryvdh/laravel-debugbar#347]
Mixed Content: 
The page at 'https://some.domain.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://some.domain.com/_debugbar/assets/stylesheets?1432136693'. This request has been blocked; the content must be served over HTTPS.

Same goes for the JS script.

You should probably start your links with // instead of forcing a protocol.

**Comment by GrahamCampbell** [comment]
I can't replicate this issue.

**Comment by GrahamCampbell** [comment]
Are you proxying requests? Did you set your trusted proxies on the symfony request correcty?

**Comment by googled** [comment]
Nope.

Site is behind cloudflare.

**Comment by googled** [comment]
but nothing is cached for the dev. environment.

**Comment by googled** [comment]
Chrome doesnt want to load an unsecure resource on an HTTPS site.

**Comment by googled** [comment]
I am using lavarel 4.2 therefore the 1.8 version of this lib.

**Comment by barryvdh** [comment]
Cloudflare needs trusted proxies to be configured probably

**Comment by GrahamCampbell** [comment]
> Site is behind cloudflare.

So you are proxying requests...

**Comment by GrahamCampbell** [comment]
If you're using apache as a webserver, cloudflare have a module for it so you can get the correct stuff set in the request before you get to your php app, if that helps.

**Comment by googled** [comment]
using nginx not apache.

**Comment by GrahamCampbell** [comment]
I don't know of any module for nginx, so I'd recommend setting the trusted proxies in your app.

**Comment by GrahamCampbell** [comment]
https://github.com/fideloper/TrustedProxy

**Comment by googled** [comment]
Why not just set it protocol agnostic with //

Pretty much all scripts / new sites nowadays use that.

**Comment by GrahamCampbell** [comment]
Because laravel is generating the paths, not us. We can't change that stuff.

**Comment by harrisoftware** [comment]
with El Capitan update, Chrome Version 45.0.2454.101 (64-bit) on OSX is now throwing 

    Mixed Content: The page at 'https://dev.local/desktop' was loaded over HTTPS, but requested an insecure stylesheet 'http://dev.local/_debugbar/assets/stylesheets?1436453519'. This content should also be served over HTTPS.

    Mixed Content: The page at 'https://dev.local/desktop' was loaded over HTTPS, but requested an insecure script 'http://dev.local/_debugbar/assets/javascript?1423122680'. This content should also be served over HTTPS.

My Environment: localhost development on Mac OSX El Capitan / Server / apache/ php 5.5.27 / mysql 

Seems the browsers are really getting pickier and pickier.

Anything more to add here? as a solution? I'm guessing everyone is going to be having this issue on their Mac dev boxes.

**Comment by flyingcoder** [comment]
What if you really want to load and external api request but the request is only available for http and don't have https?

I have read about mixed application like this kind and they are saying about load balancer and I can't comprehend with it means I don't know if that is what I need or not. But considering this kind of mixed up that needs to load an http request to https environment in laravel what would be the best solution for this?
