### ISSUE TITLE
Not logging ajax requests from Postman

### ISSUE THREAD

**Issue by newtonianb** [barryvdh/laravel-debugbar#355]
We are developing an API in Laravel and trying to get the debugbar output from the API requests. We are using Postman to generate and test the routes using GET/POST etc...

How can we get the output for this? We created a controller that shows us the DebugBar but it's not showing in the history any of the ajax requests made with Postman.

Any input?

**Comment by cbakker** [comment]
If I remember correctly, the latest Postman does not share the sessions from your normal Chrome windows. So the server sees them as 2 different clients, and does not give information about one client to the debugbar from the other client.

Maybe you can find a way to share your Chrome sessions with your Postman and maybe it will be fixed that way.

**Comment by barryvdh** [comment]
I think it shoud log the requests made with Postman in the history browser. It shouldn't matter if it's from the same client or not, it should just save the data in the using the [FilesystemStorage](https://github.com/barryvdh/laravel-debugbar/blob/master/src/Storage/FilesystemStorage.php).

**Comment by alfredobarron** [comment]
@barryvdh Yes, the file is saved in the storage/debugbar/ succefully but is not showing in preview the Postman... any idea?
