### ISSUE TITLE
EN query or Collection query

### ISSUE THREAD

**Issue by blomdahldaniel** [barryvdh/laravel-debugbar#359]
I might be just a bit slow, but how do i filter between my actual DB queries and the queris made on Collections?

**Comment by philcross** [comment]
This caught me out as well. Debugbar was showing 165 queries to the database made (select statements), and I spent an hour trying to work out why my Support Collections were querying the database when I ran the `where()` method on them. 

Collection queries need to be differentiated between Database queries.

**Comment by barryvdh** [comment]
How do you suppose I make that distinction? Can you submit a PR?

You could enable the backtrace option, see if that gives you more info.

**Comment by GrCOTE7** [comment]
Hi, barryvdh :-)

Big congratulations for your excellent tools (This Debugbar (but _ide-helper too :-)

(Someone else think so too... (https://github.com/snowair/phalcon-debugbar)... Lol)

I done as you show that in README.md, a collector 'My messages'...

Well ! But, how to put in the final tab in the bar, data here ?

Again tanks for your good job :-)

To soon, I hope.

**Comment by barryvdh** [comment]
You know it is meant to be Cross framework Right? :) http://phpdebugbar.com/
And Sorry,

**Comment by barryvdh** [comment]
Sorry, I don't understand your issue. Dan you create your own issue?

**Comment by GrCOTE7** [comment]
Here: https://github.com/GrCOTE7/OctoberCMS000

:-)

Wahoo ! What for your reactivity (y) !!!

**Comment by GrCOTE7** [comment]
Yessss: I found:

$debugbar['messages']->addMessage("foobar");

Tanks again. :-)
