### ISSUE TITLE
Debugbar really slow if db collector is set to true (laravel 5.1)

### ISSUE THREAD

**Issue by karev** [barryvdh/laravel-debugbar#361]
Hello, when the DB collector is set to true the page load take 3 seconds but when i set it to false everything is ok like 83ms.

**Comment by cbakker** [comment]
How many queries are being fired in that request? 

It is not a secret that logging debug information messes with your performance. That is why you should not run it in production.

**Comment by karev** [comment]
the debug bar is activated only in local web server and there is 0 query running in my page itried it with a fresh laravel 5.1 installation

**Comment by boynet** [comment]
+1 when turn on the Booting step take 30s+

**Comment by eschmid72** [comment]
The browser becomes really overwhelmed when a lot of queries are fired.
It would be good if there was a max limit for query collecting.
