### ISSUE TITLE
Enabling at runtime

### ISSUE THREAD

**Issue by jasonvarga** [barryvdh/laravel-debugbar#366]
Hi, I'm sure I'm missing something obvious here.

If I've set `debug => false` in `debugbar.php`, where is a good place to enable it using `debugbar->enable()` in my code?

Adding it to my controller doesn't seem to make it show up.

**Comment by furey** [comment]
Same! @barryvdh, are you able to clarify?

**Comment by risingphoenix** [comment]
Same here, also the old trick to assign in the config
`
'enabled' => function(){ return false; }
`
and enable in a controller with `debugbar()->enable();` doesn't work anymore
