### ISSUE TITLE
Debugbar in maintaince mode?

### ISSUE THREAD

**Issue by htien** [barryvdh/laravel-debugbar#367]
How can I disable debugbar in maintaince mode? (note: my APP_DEBUG is set to 'true')

**Comment by GrahamCampbell** [comment]
It should already not be showing in maintaince mode?

**Comment by GrahamCampbell** [comment]
What laravel version?

**Comment by htien** [comment]
I'm using Laravel 5.1. Debugbar cannot reference to js and css files.

**Comment by GrahamCampbell** [comment]
I guess you could register your own custom middleware to replace https://github.com/barryvdh/laravel-debugbar/blob/master/src/Middleware/Debugbar.php.

**Comment by GrahamCampbell** [comment]
Actually, a better hack might be to just throw an exception in your maintainance middleware, then render the maintaince page in your exception handler. That way we're bailing before the debug bar middleware can do anything.

**Comment by htien** [comment]
I'm new in Laravel. I'll try to follow your suggestion. Thank you!

**Comment by jnbn** [comment]
@GrahamCampbell I Think it's probably ServiceProvider related issue.

As the sp boots Debugbar is already decided if it's going to be used or not. So probably a change on the sp would be required.

I'm trying few alternatives and update if I can get anything about it
