### ISSUE TITLE
Debug Bar Interface Problem at Session

### ISSUE THREAD

**Issue by iget-master** [barryvdh/laravel-debugbar#369]
Hi,

It's a very small problem:

Browser Chrome, OS Ubuntu 14.04

When clicking at Session section, if you try to select any session value to copy to clipboard, it's impossible.

You can fix it just by allowing selection at CSS, or creating a button to copy value to clipboard!

Thanks in advance,
Elias Soares

**Comment by barryvdh** [comment]
Good idea, can you submit a PR to https://github.com/maximebf/php-debugbar ?
