### ISSUE TITLE
Assets doesn't load.

### ISSUE THREAD

**Issue by Leandro-b-03** [barryvdh/laravel-debugbar#371]
Hi, I'm trying to use the debugbar with L5, and the assets doesn't load...

I've read all threads but no one resolve my issue.

So let me explain, when I enter in the route the debugbar assets doesn't load and the console throws me the error:
>The stylesheet http://localhost:8000/_debugbar/assets/stylesheets?1436634280 was not loaded because its MIME type, "text/html", is not "text/css".

I refresh the page and the debugbar is there, and load the all assets correctly.

I'm using like that on app.php
```
    'providers' => [

        /*
         * Development Service Providers...
         */
        Barryvdh\Debugbar\ServiceProvider::class,

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Foundation\Providers\ArtisanServiceProvider::class,
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Routing\ControllerServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        Illuminate\Html\HtmlServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        /*
         * Custom Services Providers...
         */
        Collective\Html\HtmlServiceProvider::class,
        Cviebrock\EloquentSluggable\SluggableServiceProvider::class,
        // Vinkla\Pusher\PusherServiceProvider::class,
        Zizaco\Entrust\EntrustServiceProvider::class,

    ],
```
I appreciate any help.

**Comment by vigneshgurusamy** [comment]
+1

**Comment by lindstrm** [comment]
+1

**Comment by HarryBosh** [comment]
+1

**Comment by Leandro-b-03** [comment]
On my homologation environment (that's online), I'm using the vhost to set the app online and there isn't any problem with the assets, on local environment I start the serve by:
> php artisan serve

and it start on localhost:8000, but the address is "::1" here's the console output:

>Laravel development server started on http://localhost:8000/
[Tue Aug 25 09:47:29 2015] ::1:52867 [200]: /library/adminLTE/bootstrap/css/bootstrap.min.css
[Tue Aug 25 09:47:29 2015] ::1:52869 [200]: /library/adminLTE/dist/css/AdminLTE.min.css
[Tue Aug 25 09:47:29 2015] ::1:52871 [200]: /library/adminLTE/dist/css/skins/skin-yellow-light.min.css
[Tue Aug 25 09:47:29 2015] ::1:52872 [200]: /library/adminLTE/plugins/iCheck/square/yellow.css
[Tue Aug 25 09:47:29 2015] ::1:52874 [200]: /library/adminLTE/plugins/jQuery/jQuery-2.1.4.min.js
[Tue Aug 25 09:47:29 2015] ::1:52876 [200]: /library/adminLTE/plugins/iCheck/icheck.min.js
[Tue Aug 25 09:47:29 2015] ::1:52875 [200]: /library/adminLTE/bootstrap/js/bootstrap.min.js
[Tue Aug 25 09:47:30 2015] ::1:52877 [200]: /library/adminLTE/bootstrap/fonts/glyphicons-halflings-regular.woff2
[Tue Aug 25 09:47:30 2015] ::1:52879 [200]: /library/adminLTE/plugins/iCheck/square/yellow.png
[Tue Aug 25 09:47:30 2015] ::1:52880 [200]: /favicon.ico

So I've tried to change the host and had no success

>Laravel development server started on http://timesheet.localhost.com:80/
[Tue Aug 25 10:13:43 2015] 127.0.0.1:53775 [200]: /library/adminLTE/bootstrap/css/bootstrap.min.css
[Tue Aug 25 10:13:43 2015] 127.0.0.1:53778 [200]: /library/adminLTE/dist/css/AdminLTE.min.css
[Tue Aug 25 10:13:44 2015] 127.0.0.1:53784 [200]: /library/adminLTE/plugins/iCheck/square/yellow.css
[Tue Aug 25 10:13:46 2015] 127.0.0.1:53780 [200]: /library/adminLTE/plugins/iCheck/icheck.min.js
[Tue Aug 25 10:13:46 2015] 127.0.0.1:53781 [200]: /library/adminLTE/bootstrap/js/bootstrap.min.js
[Tue Aug 25 10:13:46 2015] 127.0.0.1:53782 [200]: /library/adminLTE/plugins/jQuery/jQuery-2.1.4.min.js
[Tue Aug 25 10:13:46 2015] 127.0.0.1:53783 [200]: /library/adminLTE/dist/css/skins/skin-yellow-light.min.css
[Tue Aug 25 10:13:52 2015] 127.0.0.1:53791 [200]: /library/adminLTE/bootstrap/fonts/glyphicons-halflings-regular.woff2
[Tue Aug 25 10:13:52 2015] 127.0.0.1:53790 Invalid request (Unexpected EOF)
[Tue Aug 25 10:13:52 2015] 127.0.0.1:53794 [200]: /library/adminLTE/plugins/iCheck/square/yellow.png
[Tue Aug 25 10:13:52 2015] 127.0.0.1:53795 [200]: /favicon.ico

So at last I tried the vhosts on my machine:
```
<VirtualHost *:80>
    ServerName timesheet.localhost.com
    DocumentRoot "C:\Users\user\Projetos\Controle-de-Horas/public"
    <Directory "C:\Users\user\Projetos\Controle-de-Horas/public">
        AllowOverride all
    </Directory>
</VirtualHost>
```
And curiously, worked, but I'm not like using vhosts on local environment, because I'm don't like to apache start together with windows.

After some tries, look like the the php artisan serve --host=timesheet.localhost.com --port=80 worked, but I don't know how it worked, if someone could try to make us understand that behavior on the server I'll be eternally grateful!

PS: I've notice that may it worked after I put the ip and the alias on the hosts like:
>127.0.0.1    timesheet.localhost.com

That may make a lot of sense!

**Comment by days85** [comment]
Did you check your apache config and changed the Directory www to AllowOverride all?

**Comment by Leandro-b-03** [comment]
Well I'm on windows and the vhosts has the AllowOverride all on the directory, but I'm not using apache.

**Comment by mathieutu** [comment]
+1, and I've nginx, so no AllowOverride possible..
Any solution ?

**Comment by Leandro-b-03** [comment]
@mathieutu Man, I even forgot about this topic, but I think I may have a solution.

When I run 
> php artisan config:cache

The problem disappears until the next view created, may this could help you, is a temporally solution, but works for me.

**Comment by mathieutu** [comment]
Thank's @Leandro-b-03!
It seems to work now, I'll repost here if I've something new.

**Comment by Neomaltine** [comment]
+1 Everything was fine today until I created a new view. Now I have the same error and you fix is not working :(

**Comment by Leandro-b-03** [comment]
@Neomaltine,

Man, go to bootstrap/cache and see if you have a config.php, if you do delete it and see if works. it's a long shot, but could work.

**Comment by Neomaltine** [comment]
@Leandro-b-03 
Thank you for the anwer but I started a fresh install and now it's working fine.

**Comment by Briareos17** [comment]
I changed route_prefix to "-debugbar" and all starts working fine.
