### ISSUE TITLE
New cache error after last composer update

### ISSUE THREAD

**Issue by soluxima-erik** [barryvdh/laravel-debugbar#372]
Updating composer on a Laravel 5.1 install (that previously worked fine) returns an error in the console:

`[ErrorException]
  file_put_contents(/home/public_html/bootstrap/cache/services.json): failed to open stream: No such file or directory`

`Script php artisan clear-compiled handling the post-update-cmd event returned with an error`    

and in the browser:

`Whoops, looks like something went wrong.` 

`1/1 ErrorException in Filesystem.php line 81: file_put_contents(/home/public_html/bootstrap/cache/services.json): failed to open stream: No such file or directory`

I tried composer dumpautoload, but it did not help.

**Comment by barryvdh** [comment]
Is bootstrap/cache writable? Why do you think this is a debugbar problem?

**Comment by soluxima-erik** [comment]
I am so sorry, I didn't realize I posted it here.. Ill move it.
Your DBB is awesome btw!
