### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by chrisharrison** [barryvdh/laravel-debugbar#376]
I followed the instructions for adding Lumen support according to the readme but the debugbar is not being rendered in any of my responses.

**Comment by barryvdh** [comment]
APP_DEBUG is true? Is any output appended on your html? Any errors on your log? What Lumen version?

**Comment by chrisharrison** [comment]
Sorry @barryvdh I've worked out what the problem was. Your sentence "appended on your *html*" gave me the hint. I was outputting JSON, not HTML. I assumed the response would still get modified regardless of its type.

**Comment by nnnikolay** [comment]
For me it is still a problem, I see output in my json responses but I see them as injected <script> ... 
which ruin my json response... Maybe I miss some settings ?

**Comment by barryvdh** [comment]
did you set a proper content-type?

**Comment by nnnikolay** [comment]
Yes, sure. Or I would not see it at all

**Comment by nnnikolay** [comment]
I've set both accept and content type in json, and it became visible, but as injected js script content

**Comment by Zyles** [comment]
I want to show the debug bar on a JSON response in Lumen. Is it possible?

I even tried this:
return response($response)->header('Content-Type', 'text/html');

The content-type is set according to Chrome developer tools but still no bar is shown.

**Comment by boianmihailov** [comment]
any hint how to use json with debug bar?

**Comment by barryvdh** [comment]
You can't add HTML to a json response, but xhr should be shown. Json can be viewed with the browser button for previous requests.
