### ISSUE TITLE
Exception after install debug plugin phpdebugbar 

### ISSUE THREAD

**Issue by Valonix** [barryvdh/laravel-debugbar#378]
Hello, i am new in Laravel. I install ur plugin and found this error in debug panel
Cannot add listen to Queries for Laravel Debugbar: Unsupported driver [localhost]
/home/admin/web/default.domain/public_html/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#316
Exception
Unsupported driver [localhost]
/home/admin/web/default.domain/public_html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php#189
InvalidArgumentException
                return new SqlServerConnector;
        }

        throw new InvalidArgumentException("Unsupported driver [{$config['driver']}]");
    }

    /**

**Comment by barryvdh** [comment]
Why is your driver `localhost`? Use `mysql` or something.

**Comment by Valonix** [comment]
where ? in database.php?

**Comment by barryvdh** [comment]
yes

**Comment by Valonix** [comment]
yeah! its my fault, in another string wrote ip of database (but i don`t know in digital ocean droplet i must write localhost or my ip )  :) 
right now i try to change config.
ty

**Comment by Valonix** [comment]
Cannot add listen to Queries for Laravel Debugbar: SQLSTATE[28000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)
/home/admin/web/default.domain/public_html/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#316
Exception
SQLSTATE[28000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)
/home/admin/web/default.domain/public_html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php#50
PDOException



new errors. my site not in homestead

that is my config file
![image](https://cloud.githubusercontent.com/assets/8511169/8763035/137355f8-2d94-11e5-8c35-21cc51e264c9.png)

**Comment by barryvdh** [comment]
Yeah configure your database properly, or disable the database collector (in config/debugbar.php).

**Comment by Valonix** [comment]
but in the future i want to see database queries :)

**Comment by barryvdh** [comment]
Yeah so make sure it works first ;)

**Comment by Valonix** [comment]
u mean database connect?
ok, right now i try create some model and some method to get some posts(for example) from database to check  work it or not :)

**Comment by Valonix** [comment]
I just do not understand why the error is related to the Homestead is because if you put a framework in their environment

**Comment by Valonix** [comment]
i created model and one method to find all and my data from table was in view file, but debug panel wrote errors about homestead.
Can you explain me, i must edit database connect in config/database.php or in .env? if my site in not local, he is on digital ocean droplet :)
