### ISSUE TITLE
"Serialization of 'Closure' is not allowed" when using "route" collector

### ISSUE THREAD

**Issue by tremby** [barryvdh/laravel-debugbar#380]
When using the "route" collector I'm getting no debugbar and the message "Debugbar exception: Serialization of 'Closure' is not allowed" of level "error" in my log on each request to particular routes.

The way I'm defining these routes is somewhat nasty, due to SEO requirements from the client, and so I'm not sure if it's a bug in the collector or I'm doing something wrong. The code for the relevant routes looks like this:

``` php
// [switch locale based on domain in HTTP request]

$urls = [
    'home' => [
        'en_CA' => '',
        'fr_CA' => '',
    ],
    'about' => [
        'en_CA' => 'about',
        'fr_CA' => 'apropos',
    ],
    'tour' => [
        'en_CA' => 'tour',
        'fr_CA' => 'tournee',
    ],
    'rules' => [
        'en_CA' => 'rules',
        'fr_CA' => 'reglement',
    ],
];
$otherLocale = App::getLocale() == 'en_CA' ? 'fr_CA' : 'en_CA';
View::share('other_locale', $otherLocale);

// Public views
foreach ($urls as $route => $names) {
    Route::get($names[App::getLocale()], ['as' => $route, function () use ($route) {
        return view('public.' . $route);
    }]);
    if ($names[App::getLocale()] != $names[$otherLocale]) {
        Route::get($names[$otherLocale], function () use ($route) {
            return Redirect::route($route, [], 301);
        });
    }
}
```

The actual routes work just fine.

Any idea what's wrong?

**Comment by AntonCooper** [comment]
I'm having the same issue here when using `->missing()` on a route.

```php
Route::get('/test', fn() => 'test')
    ->missing(fn(Request $request) => 'not working');
```

Debugbar will not show on this route, even when the missing action is never triggered. Removing the missing method will allow the bar to show on the route. As a work around I have disabled the 'collectors.route' collector in the config, but would be nice to have this paradigm handled by the debug bar.

**Comment by azgooon** [comment]
I am experiencing exactly the same issue and only thanks to @AntonCooper I was able to find the cause of not appearing debugbar.
