### ISSUE TITLE
adding link

### ISSUE THREAD

**Issue by krowinski** [barryvdh/laravel-debugbar#381]
Hi, 

Im using xslt  template engine and I added new tab to debugbar. But big xml like this is loading very slow. IMO best its to display on other page also selecting parts of xml is expanding accidentally.

If there is a way do add custom link to tab  ??

![xml](https://cloud.githubusercontent.com/assets/1478555/8885598/81dfadb2-3261-11e5-89c8-0619a2b169ee.png)

**Comment by barryvdh** [comment]
You could write your own custom collector to load XML upon clicking or similar.

**Comment by krowinski** [comment]
tx
