### ISSUE TITLE
Refused to get unsafe header "phpdebugbar"

### ISSUE THREAD

**Issue by boywijnmaalen** [barryvdh/laravel-debugbar#384]
Hi,

I'm currently in Chrome latest version (just checked it) 

As of this morning I'm getting two error in my console.
- Refused to get unsafe header "phpdebugbar-id"
- Refused to get unsafe header "phpdebugbar"

I'm thinking this is not a specific debugbar notification so I tried Googling for it but no luck. 

I disabled the debugbar for testing purposes which results in no errors at all (obviously). 

Does anyone have a clue wat is going on?

**Comment by boywijnmaalen** [comment]
Issue resolved. 

Fix is to remove non-mandatory JavaScript from loading before the debugbar

**Comment by edbentinck** [comment]
> Fix is to remove **non-mandatory JavaScript** from loading before the debugbar

Could you clarify? I too have this issue but I can't seem to fix it.

**Comment by dancraioveanu** [comment]
+1

**Comment by boywijnmaalen** [comment]
Debugbar assets are loaded after all the application JS (eg. Google Analytics, Metrika, VWO, etc) If you remove these kind of JS from the template (even for testing purposes) the error disappears. Why the error is shown in the first place is a mystery to me but this seems to fix it. On my development environment I excluded these JS because on my dev I don't need them and the debugbar is a dev dependency so that's why this specific solution it works for me.

I tried if it maybe was a specific JS that was casing this but I couldn't find a common denominator.

**Comment by edbentinck** [comment]
Interesting, @boywijnmaalen, thanks. Removing internal javascript for Mixpanel worked for me (I don't use GA). Not really an ideal solution since most of us use analytics/tracking libraries but it'll do for now. Guess we'll have to wait for a more permanent solution.

**Comment by boywijnmaalen** [comment]
In my opinion this solution is permanent because the JS you removed should only be removed within your development environment. Debugbar is a dev dependency (if you installed it correctly) so if you disable your specific JS on develop environment only than you should be good (Debugbar is not loaded on any other environment than your dev environment so on other environments you shouldn't have any conflicts ). 
In my projects (and when I'm working on development environment) I usually disable not mandatory JS anyway because many scripts muddle my console with (on development) unnecessary events/logs/messages/etc.

**Comment by JTallis** [comment]
I've only recently noticed that I too get this issue but there are minimal things I can remove. The only thing I can ideally remove is just the Google Analytics code in which I tried to no avail.

One strange thing I did notice is that if I were do a normal refresh (CTRL+R, Refresh button) then I will not get any errors but if I were to hit enter on the URL bar or opening a page via clicking a link then I will get those errors.

**Comment by boywijnmaalen** [comment]
@JTallis There is indeed a difference between the two; I found a good explanation on stackoverflow; http://stackoverflow.com/a/20569464/4929221

**Comment by JTallis** [comment]
Yes but wouldn't that suggest the issue here is potentially related to a cached file's header? So there could be something particularly unsafe about that, that might be avoidable.

**Comment by boywijnmaalen** [comment]
The issue is not relared to what you are refering. you are describing browser related issues. this specific issue is related to a clash between the different javascripts. if you are right you would still het the issue even when you disable the debugbar but that will not be the case.

**Comment by SimonJ** [comment]
I have the problem too

**Comment by Francismori7** [comment]
Same issue here. Debug bar loads fine still.

**Comment by stuba** [comment]
For me this is caused by datatables language plugins. Language plugins are loaded using cdn. I do understand that ga etc are disabled on development environment, but cdn content is there for purpose.

So any other ideas how to solve this?  Only thing I have found out is to disable ajax. This makes debugging ajax calls a bit more difficult..

**Comment by boywijnmaalen** [comment]
As I mentioned earlier, Are you loading assets over SSL? The only thing I can come up with right is that maybe you're running into cross protocol errors. meaning you including an asset over SSL but your site/development environment is non-SSL loading? Always try to start you asset URL with; '//', eg. '//cdn-url/vendor/packacge/version.js'

**Comment by stuba** [comment]
Hi, im using SSL on development. If i remember non-ssl requests gives a bit different error.

I can live without Ajax debug so it is not a big deal. Hope this helps you to debug this problem. I might not be only one stuck with this error. I have not had any look how datatables works. Problem can be related some issues with datatables or its plugins. Anyway this error does happen only when debugbar is in use.

$('.DataTable').DataTable({
	"language": {
		url: '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Finnish.json'
	},
	"lengthMenu": [ 10, 25, 50, 75, 100, "200", "500" ],
	"pageLength": 25,
});

**Comment by barryvdh** [comment]
I think I misunderstood, this happens when you load javascript from other domains, and debugbar tries to access those headers, right?
Should probably add a check to compare the host or something..

**Comment by boywijnmaalen** [comment]
Hi Barry,

I'm not sure about the headers part but it most certainly has something to do with third-party javascript. The scripts I mentioned are all third-party software, I tried disabling them one by one but I still got the error until I disabled them all and then it worked perfectly fine (turning all the third party JS off is not a problem since this is a dev related problem and I don't necessarily need these third party JS on my dev env anyway).

**Comment by Francismori7** [comment]
This started happening to me when referencing socket.io's JS from my socket server (localhost:8000).

**Comment by ozanhazer** [comment]
Getting this when I add social buttons:

![screen shot 2015-09-17 at 11 30 14](https://cloud.githubusercontent.com/assets/1287658/9928530/8ee2aec6-5d2f-11e5-860d-7618be43e26f.png)

Comparing the host might do it but it won't capture ajax if developer wants to use a separate domain for API calls even the CORS headers are configured correctly in the development environment... I'd say simply catch the exception and ignore it but seems like it's not catchable...

Compare the host and add a configuration option to whitelist hostnames maybe...

**Comment by tonioriol** [comment]
+1 same here

**Comment by canfiax** [comment]
Same here

**Comment by XaviArnaus** [comment]
Happened the same when trying to implement a socket.io websockets feature.

Searching the internet I find maybe I should expose the phpdebugbar and phpdebugbar-id headers so that CORS allows them, but I've been trying this for some time with no luck

**Comment by driesvints** [comment]
Getting this error also since a couple of weeks.

**Comment by acacha** [comment]
Same error here. I'm using socket.io sockets too

**Comment by matriphe** [comment]
same here. adding socket.io produced the error.

**Comment by Xplouder** [comment]
+1 for socket.io

**Comment by gbaumeister** [comment]
Problem can also be related to certain chrome-extensions (which probably use a socket(?))

**Comment by navagroup** [comment]
+ 1 for socket.io too

**Comment by FutureKode** [comment]
Any update on this?

**Comment by barryvdh** [comment]
Still accepting pull requests

**Comment by JeramyNS** [comment]
+1 for socket.io

**Comment by Donny5300** [comment]
Socket.io is still conflicting, any solutions for this yet?

**Comment by DmacMcgreg** [comment]
+1 without using socket.io

**Comment by blackfyre** [comment]
After disabling the `capture_ajax` option in the config, the error messages went away.
Simply use the browser console to track network requests...

**Comment by sebdesign** [comment]
As per @blackfyre's suggestion, If you don't want to disable the `capture_ajax` globally in the config, you can trigger it on runtime using:
```php
Debugbar::getJavascriptRenderer()->setBindAjaxHandlerToXHR(false);
```

**Comment by gabor-nagy-stylers** [comment]
just faced the issue, with ajax requests to different domains.
with cors package installed I have configured cors in config/cors.php:
'exposedHeaders' => ['phpdebugbar', 'phpdebugbar-id'],

and it works. console errors gone, and debugbar shows ajax requests too.

**Comment by mnpenner** [comment]
@gabor-nagy-stylers What CORs package are you using?

**Comment by gabor-nagy-stylers** [comment]
@mnpenner yes, Barry's.
My full cors.php config looks like this:
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT', 'DELETE'],
    'exposedHeaders' => ['phpdebugbar', 'phpdebugbar-id'],
    'maxAge' => 0,
    'hosts' => [],

**Comment by JeramyNS** [comment]
Barry's cors method didn't work for me.
Got sick of the issue and just manually changed the httpd.conf to have:
```
Header set Access-Control-Allow-Headers "phpdebugbar, phpdebugbar-id"
Header set Access-Control-Allow-Methods "*"
Header set Access-Control-Allow-Origin "*"
```

**Comment by JeramyNS** [comment]
The Barry's cors method and manually setting the headers in httpd.conf didn't help.
I have no idea why it worked for a while then stopped, maybe I'm going crazy.

Anyway, have just added it to the node side
```
var app = require('express')();
app.use(function(req, res, next) {
    res.setHeader("Access-Control-Allow-Headers", "phpdebugbar, phpdebugbar-id");
    res.setHeader("Access-Control-Allow-Methods", "*");
    res.setHeader("Access-Control-Allow-Origin", "*");
    next();
});
var server = require('http').Server(app);
var io = require('socket.io')(server);
........................
```

**Comment by patobrien** [comment]
I'm still seeing this issue in development while using socket.io. Debugbar works, as people have posted above but it's a big annoyance.

I've added barryvdh/laravel-cors, and added it to my route. I've used the configuration above from @gabor-nagy-stylers 

@gabor-nagy-stylers did you take any additional steps to make the console errors go away?

**Comment by asvae** [comment]
> After disabling the capture_ajax option in the config, the error messages went away.
This is not a solution for single page applications.

@gabor-nagy-stylers, does your solution apply for same-domain ajax requests?

**Comment by D1kz** [comment]
Have a same issue. Removing scripts from page does not help me.

**Comment by acidjazz** [comment]
Hey guys, just started seeing this issue here, for me this started after I implemented cropperjs, which when given an <img> element, pulls the source in via AJAX, then writes it to a canvas.

I think the problem is somewhere around the area of JS doing allowed cross-domain calls or something? I'll do more research and try to contribute.

![image](https://cloud.githubusercontent.com/assets/967369/19597055/118006ba-9747-11e6-987f-9208105ab7dc.png)

If I remove cropperJS or not have it instantiate from an image element, I do not produce this error.

**Comment by barryvdh** [comment]
See this PR: https://github.com/maximebf/php-debugbar/pull/308

Crossdomain requests cannot be checked, but not sure what the best way to check this is.
I can check all headers (which only include those Chrome thinks are 'safe') to see of they match a debugbar header. Should fix it, not sure if most efficient though.

**Comment by joarobles** [comment]
+1 socket.io here

**Comment by MikhailRoot** [comment]
Thanks to @boywijnmaalen I've solved it. In my view i linked js scripts for Google Analytics and Yandex Webvisor, so the easiest solution is to wrap these declarations in 

`@if(config('app.env')=='production') <script><!-- GoogleAnalytics code --></script> @endif`

To load these scripts only in production environment. (in your `.env` file specify `APP_ENV=production`) by default in development environment it is set to `APP_ENV=local`

**Comment by curtisblackwell** [comment]
If environment conditionals aren't appropriate in your situation, see [sebdesign's response](https://github.com/barryvdh/laravel-debugbar/issues/384#issuecomment-211315821).
