### ISSUE TITLE
[Feature request] Debugbar in separate window for non-html requests

### ISSUE THREAD

**Issue by dirkpostma** [barryvdh/laravel-debugbar#389]
For non-html requests, .e.g. json output, debugbar doesn't work.

Dukeman330 has created a nice workaround for this by making a browser for debug files in a separate window:  https://github.com/Dukeman330/laravel-debugbar/

http://stackoverflow.com/questions/26999393/are-there-any-laravel-profilers-that-work-with-json-apis

Can this be integrated into the official debugbar? My suggestion would be to show debug information of the last (few) requests in a separate window.

**Comment by barryvdh** [comment]
Data should be stored, so you should be able to see the request when you click on the browse button.

Also, in the latest version, you can enable clockwork output, when used with the clockwork chrome extension.

**Comment by dirkpostma** [comment]
Oke cool! I just used it for first time and I didn't notice the browser before I saw the stackoverflow question. Sorry about that and bedankt for the great work! ;-)
