### ISSUE TITLE
Debugbar will not inject when routes points to magic method __call

### ISSUE THREAD

**Issue by markvaneijk** [barryvdh/laravel-debugbar#391]
When I use a magic method as endpoint for my route, Debugbar will not load. If I use a method I created then it loads correctly.

For example:

    <?php

    // routes.php

    get('/', ['uses' => 'TestController@test']);

    // controller

    class TestController extends Controller {

        public function __call()
        {
            return 'Test';
        }
    }

**Comment by barryvdh** [comment]
Do you get an error? Can you check your logs?

(Also not really sure why you would do this)

**Comment by markvaneijk** [comment]
I have no error in the server/php or Laravel logs. Is there any other way to find an error message?

I have a specific reason for this, I use the catch-all method for serving a default response when it should not be an 404, but a standard page.

**Comment by barryvdh** [comment]
You don't need a magic __call method for that, only a catch all route. You could try changing the order Od th service provider, move it all the way to the top or bottom.

**Comment by markvaneijk** [comment]
I don't like the concept of a catch-all route because that will definitely break the debugbar and possible other things :)

I did change the order of the service provider but it did not help..

Now I've solved it by not using a __call but manually check if a method exists and if not, I set the route to a "default" method.

But I find it strange that the debugbar does not work with a magic __call? Is there a reason for this?

**Comment by barryvdh** [comment]
I still don't understand why you need the `__call()` in your controller. I'm pretty sure you don't have to do that. Instead, something like `Route::any('{link}', 'PageController@default')->where('all', '.*');` as last route.

But anyways, I've fixed the bug in the Route collector, to check if the method exists.

**Comment by markvaneijk** [comment]
I don't like the catch-all route (I've used that before) because it breaks things like the original 404 error message in Laravel and also the loading of CSS and Javascript files from packages like Debugbar itself..

**Comment by barryvdh** [comment]
No but you said: 
> I have a specific reason for this, I use the catch-all method for serving a default response when it should not be an 404, but a standard page.

**Comment by markvaneijk** [comment]
Oh haha sorry for the confusion! With "catch-all method" I meant the __call magic method ;)

**Comment by markvaneijk** [comment]
But nice you fixed the bug in the route collector! Now it should work with the __call magic method?

**Comment by barryvdh** [comment]
Yes in the latest dev version. Try with `2.x@dev` and let me know if it's fixed!

**Comment by markvaneijk** [comment]
Yes it's fixed! :)
