### ISSUE TITLE
Debugbar not showing when config are cached

### ISSUE THREAD

**Issue by LucianoVandi** [barryvdh/laravel-debugbar#393]
When I run <code>php artisan config:cache</code> the debugbar is not showing. If I clear the cache with <code>php artisan config:clear</code> debugbar keeps showing again.

I'm on vagrant homestead (3.16.0-23-generic GNU/Linux), my composer.json file contains:
    <code>"laravel/framework": "5.1.10"</code>
    <code>"barryvdh/laravel-debugbar": "^2.0"</code>

In .env file APP_DEBUG is set to TRUE, same for "enabled" in config/debugbar.php. I've even tried to delete the whole /vendor directory and run <code>composer install</code>. Nothing changes...

**Comment by LucianoVandi** [comment]
Never mind, it's an expected behavior. After some research I've found the issue #328 marked as closed.

**Comment by LucianoVandi** [comment]
For other people in the same boat: if you need to enable config cache, but still want to see the debugbar you could simply enabling it on runtime.

In my case, in app/Providers/AppServiceProvider.php I'm conditionally loading some service provider based on the environment. Here is where I enable the debugbar too... something like:

```php
if ($this->app->environment() == 'local') {
     ...
     // This enable the debugbar
     $this->app['config']->push('debugbar.enabled', true);
} 
```

**Comment by Arrakeen** [comment]
Had the same issue, thanks for sharing.

**Comment by LucianoVandi** [comment]
I correct myself! This is not a solution because if you need to clear and re-cache the config with <code>php artisan config:cache</code> you will get an error:
```php
[ErrorException]                       
Cannot use a scalar value as an array
```
Temporarily i've fixed it adding to the if condition a check if running from CLI, something like 
```php
if ($this->app->environment() == 'local' && !php_sapi_name() == 'cli') {
    $this->app['config']->push('debugbar.enabled', true);
}
```
Hope someone could suggest a better solution. Thanks!

**Comment by wdmtech** [comment]
Thanks for this, I'm also having this problem.

**Comment by leek** [comment]
@LucianoVandi: Perfect! I was pulling my hair out trying to figure out why the DebugBar was not showing. Turned out I had a cached config as well. Thanks!

**Comment by robjbrain** [comment]
Attempted to do this based on showing the debug bar for admin only, but it seems the auth driver isn't available in AppServiceProvider. Is there a better place for it?

Attempted to put it in middleware, but no luck either

**Comment by goldenTabby** [comment]
LucianoVandi's solution didn't worked for me. It was adding array to config but not the key, so it was like this:

>'enabled' => [0 => true]

my solution that works (add to app/Providers/AppServiceProvider.php, register method) :

    if ($this->app->environment() === 'local' && php_sapi_name() !== 'cli') {
        $this->app['config']->set('debugbar.enabled', env('DEBUGBAR', false));
    }

In my case I added DEBUGBAR variable in .env, but you can pass true/false as you want.

**Comment by gildniy** [comment]
Thanks @goldenTabby This worked for me!

**Comment by barryvdh** [comment]
Is this fixed with above commit?

**Comment by gildniy** [comment]
For me it does.
