### ISSUE TITLE
Collect response also.

### ISSUE THREAD

**Issue by pavankumarkatakam** [barryvdh/laravel-debugbar#395]
Collecting response also will be nice, for creating api projects.

**Comment by barryvdh** [comment]
What exactly? The full html/json?

**Comment by pavankumarkatakam** [comment]
For normal project html and for api json, in both they are usefull. right?

**Comment by jonagoldman** [comment]
Would love to have a way to pull the debug data so I can attach it to a JSON response. Any news on this?

**Comment by pavankumarkatakam** [comment]
@jonagoldman , You can write a moddileware for that and get the debug data `app('debugbar')` and attach it to the response data.
