### ISSUE TITLE
Refused to get unsafe header "phpdebugbar" and "phpdebugbar-id" console errors in Chrome

### ISSUE THREAD

**Issue by zhuston** [barryvdh/laravel-debugbar#396]
We use a handful for of outside services on our site. I have noticed my console log filling up with the messages below and it seems to be tied to anytime a cross domain XHR request is made. 
> Refused to get unsafe header "phpdebugbar"
> Refused to get unsafe header "phpdebugbar-id"

The JS errors originate in the debugbar.js code when the headers are attempted to be extracted. 
```
extractIdFromHeaders: function(xhr) {
            return xhr.getResponseHeader(this.headerName + '-id');
        },
```
It seems to me the solution might be as simple as not trying to find the phpdebugbar headers for other domains or maybe a way to check without generating the error? I dug around for a little bit but thought someone out there might know an easy solution. 

I also thought it might be related to certain access control headers.

Some services I have seen to create these errors with debugbar are Intercom, Fullstory and Mixpanel.

**Comment by barryvdh** [comment]
See #384
