### ISSUE TITLE
Refused to get unsafe header "phpdebugbar-id"

### ISSUE THREAD

**Issue by simplenotezy** [barryvdh/laravel-debugbar#397]
I get a lot of these errors in console:

![image](https://cloud.githubusercontent.com/assets/3786627/9874179/dbf87d44-5ba4-11e5-82c2-b5205e59fbed.png)

Anyone knows why they appear?

**Comment by tonioriol** [comment]
1

**Comment by tonioriol** [comment]
dupe i think https://github.com/barryvdh/laravel-debugbar/issues/384

**Comment by D1kz** [comment]
duplicate of #384
