### ISSUE TITLE
Error 500 after upgrade to laravel 5.1.16

### ISSUE THREAD

**Issue by glukash** [barryvdh/laravel-debugbar#398]
After upgrade Laravel to 5.1.16 some routes ends with Internal Server Error 500, if debugbar config value: 'storage.enabled' is set to false.

**Comment by tormit** [comment]
+1
After upgrading to from Laravel 5.0.x to 5.1.x im getting 'Maximum function nesting level of '100' reached, aborting!' error. Trace tracks down to this Debugbar. I tried to disable debugbar and problem was gone.

local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum function nesting level of '100' reached, aborting!' in /Library/WebServer/Documents/projectxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:50
Stack trace:
#0 /Library/WebServer/Documents/projectxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /Library/WebServer/Documents/projectxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /Library/WebServer/Documents/projectxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /Library/WebServer/Documents/projectxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120): app()
#4 /Library/WebServer/Documents/projectxxxxx/vendor/barryvdh/laravel-debugbar/src/DataCollector/ViewCollector.php(58): base_path()
#5 /Library/WebServer/Documents/projectxxxxx/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(214): Barryvdh\Debugbar\DataCollector\ViewCollector->addView()
#6 /Library/WebServer/Documents/projectxxxxx/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): Barryvdh\Debugbar\LaravelDebugbar->Barryvdh\Debugbar\{closure}()
#7 /Library/WebServer/Documents/projectxxxxx/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array:{/Library/WebServer/Documents/projectxxxxx/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:221}()
#8 /Library/WebServer/Documents/projectxxxxx/vendor/laravel/framework/src/Illuminate/View/Factory.php(496): Illuminate\Events\Dispatcher->fire()
 ... more lines.

**Comment by tormit** [comment]
Update: Looks like it is not Debugbar problem. Seems Laravel/composer problem instead. I increased nesting limit to 200 and everything works again.

**Comment by barryvdh** [comment]
Or increase the limit in xdebug
