### ISSUE TITLE
Documentation Bug?

### ISSUE THREAD

**Issue by jsm9153** [barryvdh/laravel-debugbar#400]
In the installation docs it states this:

Laravel 5.x:

Barryvdh\Debugbar\ServiceProvider::class,
If you want to use the facade to log messages, add this to your facades in app.php:

'Debugbar' => Barryvdh\Debugbar\Facade::class,
The profiler is enabled by default, if you have app.debug=true. You can override that in the config (debugbar.enabled). See more options in config/debugbar.php You can also set in your config if you want to include/exclude the vendor files also (FontAwesome, Highlight.js and jQuery). If you already use them in your site, set it to false. You can also only display the js of css vendors, by setting it to 'js' or 'css'. (Highlight.js requires both css + js, so set to true for syntax highlighting)

Copy the package config to your local config with the publish command:

php artisan vendor:publish

//

However if (at least in my case) if you copy and paste:
Barryvdh\Debugbar\ServiceProvider::class,
and
'Debugbar' => Barryvdh\Debugbar\Facade::class,

into config/app.php, it results in this error when doing composer update:

> php artisan clear-compiled
> PHP Fatal error:  Class 'Barryvdh\Laravel-Debugbar\ServiceProvider::class' not found in /www/artistry/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Barryvdh\Laravel-Debugbar\ServiceProvider::class' not found  

Script php artisan clear-compiled handling the post-update-cmd event returned with an error

  [RuntimeException]  
  Error Output: PHP Fatal error:  Class 'Barryvdh\Laravel-Debugbar\ServiceProvider::class' not found in /www/artistry/vendor/larave  
  l/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146                      

//

I had to change those values to:
'Barryvdh\Debugbar\ServiceProvider',
and
'Debugbar' => 'Barryvdh\Debugbar\Facade',

It seems for whatever reason Laravel 5.1 doesn't like the ::class at the end.

**Comment by eviweb** [comment]
Hi

::class must not be used quoted.
Use Barryvdh\Debugbar\Facade::class unquoted since PHP 5.5 or 'Barryvdh\Debugbar\Facade' quoted

**Comment by arleslie** [comment]
This is fixed by removing pre-update-cmd commands from composer.json.

**Comment by gildniy** [comment]
Perhaps you downloaded the package manually and moved it in the vendor folder (you may have done and forgot you did this). If you did, for getting rid of this error, you might register it manually in autoload_psr4.php and autoload_classmap.php of vendor/composer folder
