### ISSUE TITLE
Inject assets into HTML

### ISSUE THREAD

**Issue by eusonlito** [barryvdh/laravel-debugbar#401]
I'm having problems with `PhpDebugBar is not defined` in one of my live servers.

I have configured debugbar to use in live server under certain conditions:

``` php
# app/Providers/DebugServiceProvider.php

public function register()
{
    if ((env('APP_DEBUG') === true) || ($this->user->admin && $this->user->debug)) {
        $this->app['config']->push('debugbar.enabled', true);
        $this->app->register('Barryvdh\Debugbar\ServiceProvider');
    }
}
```

I think that a `inject assets into html` option without external resources (current are responding 404, I haven't a catch all route, I have cleared caches) can be a good option to debug projects under certain conditions.

There are currently any option to enable this feature?

Thanks :)

**Comment by days85** [comment]
Did you check your apache config and changed the Directory www to AllowOverride all?

**Comment by eusonlito** [comment]
Yes, I'm using same config in live and development servers but in live doesn't work. But my issue is to add a feature to inject assets into HTML without need be file dependent.

**Comment by jrsalunga** [comment]
Did you check if the css/js on your html is loading correctly?
