### ISSUE TITLE
Loosing session flash data on ajax post request.

### ISSUE THREAD

**Issue by kaiserlos** [barryvdh/laravel-debugbar#403]
I have a form that is loaded by ajax, the controller giving back the form html is also saving some data as flash session data. If the form data is then send by ajax post request I can't retrieve the flashed data...

Disabling the debugbar plugin (dev-master) helps. Any idea?

**Comment by upwebdesign** [comment]
+1

**Comment by kaiserlos** [comment]
Just completely forgot about this issue and needed again hours to detect why my flashed session data is not there anymore. Seems like I am not alone...

**Comment by kaiserlos** [comment]
Seems like it is not depending und flashed data, even normal new set session data ist not "saved"

**Comment by upwebdesign** [comment]
My solution to this issue is to `Debugbar::disable();` on the AJAX route controller method.

**Comment by barryvdh** [comment]
What driver are you using for session? It could be that it makes 2 concurrent requests that try to write to the session.
It should reflash the data: https://github.com/barryvdh/laravel-debugbar/blob/866806cbd410e7d098642daa426fc0c131b9ee39/src/LaravelDebugbar.php#L110-L112

You could also try disabling the capture of ajax in the config; `debugbar.capture_ajax`

**Comment by upwebdesign** [comment]
Hmm, I am using memcached, but I like having debugbar capturing ajax calls. Disabling debugbar for just those requests seem the most logical at this time. @barryvdh I did notice your reflashing and am still confused why it is not working...

**Comment by kaiserlos** [comment]
Also noticed your reflashing. I am using the file driver at the moment.

Disabling  debugbar completely for ajax is not an option as it is so great :)

**Comment by bram1028** [comment]
@barryvdh I just saw your comment regarding the reflash after I submitted a PR. I'm not sure why the reflash in the boot is not working. I put it in the BaseController and it's working great for me.

**Comment by bram1028** [comment]
@barryvdh - Just so you know, I did some more digging on this. The session hasn't been started when the above mentioned boot is ran, and therefore has no data to reflash. So, this bit should probably be removed, too, as it effectively doesn't do anything.

```php
        if ($this->isDebugbarRequest()) {
            $this->app['session']->reflash();
        }
```

In an application's kernel, you'll see the StartSession middleware. This is where the session is started after the service providers have been booted.

**Comment by barryvdh** [comment]
Okay can you submit a PR for that also?
Can the rest confirm this solves it? Then I'll tag a release.

**Comment by barryvdh** [comment]
Changed it a bit to check for session (for Lumen 5.2) and removed the other reflash. https://github.com/barryvdh/laravel-debugbar/commit/515cb008b7f6c82667afe665c316966fa5c15714
