### ISSUE TITLE
Debug bar not rendering on Laravel 4.2

### ISSUE THREAD

**Issue by lucastaliberti** [barryvdh/laravel-debugbar#404]
Hi all,
Just installed debugbar for the first time version ~1.8 on composer.
I did the composer install, set the debug to true on config/app.php, published the configurations... well everything following the docs.

Even though not rendering the UI. I checked storage/debugbar and there is two json files there with something that seems to be the debugbar logs.

I don't know what else to do, neither how to debug the problem.

Hope you guys can help me.

**Comment by bagwaa** [comment]
Having the same problem sadly :(

**Comment by days85** [comment]
Did you check your apache config and changed the Directory www to AllowOverride all?

**Comment by mserralta** [comment]
Did you added 'Barryvdh\Debugbar\ServiceProvider', in the providers list of app/config/app.php ??
That was my problem...
