### ISSUE TITLE
Conflicts with route wild cards

### ISSUE THREAD

**Issue by nivv** [barryvdh/laravel-debugbar#406]
I've noticed that if I use a wild card routes with three parameters debugbar stops working. I guess I'm hijacking the ajax response route. 

**How to reproduce**
With a fresh install of Laravel and debugbar add this to the `app/Http/routes.php`:

``` php
Route::get('{slug}', function ($slug) {
    return $slug;
});

Route::get('{parent?}/{slug}', function ($slug) {
    return $slug;
});

Route::get('{grandParent?}/{parent?}/{slug}', function ($slug) {
    return $slug;
});
```

After adding above, debugbar stops working

No network errors in Chrome but I get these console messages:

![skarmklipp 2015-10-15 09 24 28](https://cloud.githubusercontent.com/assets/4033930/10507115/978cedc0-731e-11e5-8899-29836578e5ad.png)

**Comment by barryvdh** [comment]
Did you read this in the readme:
> If you use a catch-all/fallback route, make sure you load the Debugbar ServiceProvider before your own App ServiceProviders.

**Comment by nivv** [comment]
@barryvdh No I did not, sorry! :panda_face:
