### ISSUE TITLE
Doesn't show up in fresh installation

### ISSUE THREAD

**Issue by pdcmoreira** [barryvdh/laravel-debugbar#408]
I've just created a new L5.1 project and installed the debugbar.
The only modification I did was `composer require barryvdh/laravel-debugbar`.
Added the service provider and the alias, published the config, tried clearing everything related to cache but the bar still doesn't appear nor throws any error.

**Comment by Grummfy** [comment]
Have you added the the provider in app.php ?
In the html code produce (the browser content), is there a javascripti code like "var phpdebugbar = new PhpDebugBar.DebugBar();" ?
In your dev console of your browser (F12 key on windows & linux) did you have errror on javascript load)?

**Comment by adriandmitroca** [comment]
Same issue here. Developer console says that phpdebugbar.addDataSet line has illegal token.

`Uncaught SyntaxError: Unexpected token ILLEGAL`

By the way - none of DebugBar assets are being loaded.

**Comment by adriandmitroca** [comment]
It is highly possible that this issue is related to #405

**Comment by mstnorris** [comment]
Debugbar showed up the first time I opened my app, now it doesn't show at all.

**Comment by peterfoliant** [comment]
I have the same problem. It does not showup in Firefox, but it does in Safari.
@Grummfy The javascript is there, but in Firefox it gives the following error message in my Firebug error console: 
"TypeError: PhpDebugBar.DebugBar is not a constructor 
var phpdebugbar = new PhpDebugBar.DebugBar();

Hope this helps.

**Comment by Geczy** [comment]
I get `Uncaught ReferenceError: PhpDebugBar is not defined`

**Comment by peterfoliant** [comment]
Found out that in my situation the problem of DebugBar not showing was caused by Firefox Extension "Self-Destructing Cookies". After setting self-destruct to never DebugBar does show in Firefox.
