### ISSUE TITLE
CSS isn't sent properly when using php7.0

### ISSUE THREAD

**Issue by muihlinn** [barryvdh/laravel-debugbar#415]
Someone else experienced this?

Works like a charm under php5x, as long as I switch apache to use the 7x debugbar works its data but css not, it's there but chrome warns about being sent as text/html instead text/css.
Firefox/firebug also shows no rules in the css file.

**Comment by muihlinn** [comment]
still doesn't take the css properly in 7.0

**Comment by pierrestoffe** [comment]
Hey @muihlinn, were you able to fix this? I'm experiencing this now on my server (with another platform)

**Comment by muihlinn** [comment]
Sadly, @pierrestoffe I haven't had the chance. Too much work to do and all of it had to be working in 5.6 to pay attention to this by now.

**Comment by barryvdh** [comment]
Hm, so either the headers are not properly set, or not sent. Which seems weird, because it works in PHP5.6
Could be a difference in output buffering, or simply a left-over space/enter somewhere, which forces the headers to be sent (without output buffering)

**Comment by karneaud** [comment]
+1 for this issue. I'm also running **PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )** on staging which is giing me this same error, however, my developement runs PHP 7.2.5-1+ubuntu18.04.1+deb.sury.org+1  and displays as intended. This is weird and driving me nuts.
