### ISSUE TITLE
No message after returning redirect

### ISSUE THREAD

**Issue by Phylu** [barryvdh/laravel-debugbar#416]
I true to issue a warning using `Debugbar::warning("warn");`. Then the controller returns a redirect. I would expect the warning to be shown on this page, but it is not.

Am I missing something here?

**Comment by DinkDonk** [comment]
I am having the same issue. Seems like we are missing something, because persistent debugging is a must!

Hoping for a response on this issue soon :-)

**Comment by Phylu** [comment]
I have found it now. You need to choose the Stacked Request using the dropdown menu left to the folder icon on the right of the debugbar menu. The message shows up in the message tab then.

**Comment by LucaColombi** [comment]
Hello,

maybe you can put an icon on this stack call? It was a pain to find it even knowing that it exists
