### ISSUE TITLE
Installing in 5.2?

### ISSUE THREAD

**Issue by mstroeck** [barryvdh/laravel-debugbar#419]
Hi,

I tried to install debugbar in 5.2, but it fails. Is there any way to get this working? I tried to find info on it but failed. Thanks!

**Comment by noxify** [comment]
+1

**Comment by vesper8** [comment]
yes please.. having same issue

**Comment by barryvdh** [comment]
I've updated the composer.json to allow 5.2, try laravel-debugbar `2.2@dev`
Is that enough for you?

**Comment by GrahamCampbell** [comment]
@barryvdh Be careful with that. Taylor was thinking about making a fundamental change to middleware and exceptions. May come back and bite. Better to wait until there's a 5.2.0 tag so we can be sure stuff's not going to get broken.

**Comment by barryvdh** [comment]
Okay will take that into consideration.
For now I'll leave it in, but wait before tagging a new release. This way we can detect problems early on.
I'm guessing the 5.2 release should be pretty close, right? Cause Symfony 2.9/3.0 was released last month

**Comment by GrahamCampbell** [comment]
> I'm guessing the 5.2 release should be pretty close, right?

Not entirely sure. It seems to be sliding a bit, lol.
