### ISSUE TITLE
Unable to use 'return back()' while debugbar is enabled

### ISSUE THREAD

**Issue by jezzdk** [barryvdh/laravel-debugbar#424]
Subject says it all. When given the code below, I'm redirected to '/_debugbar/assets/stylesheets?1447949495' instead of the previous location.

``` php
if ($valid) {  
    // hooray!  
}  
else {  
    return back()->withInput();  
}  
```

**Comment by barryvdh** [comment]
What specific Laravel version?

**Comment by jezzdk** [comment]
I'm running version 5.1.24

**Comment by ddewit** [comment]
Is there by any chance an update on this?

Issue still exists on Laravel Framework version 5.1.29 (LTS) with laravel-debugbar v2.1.1.

**Comment by ddewit** [comment]
Does not seem to happen every time, but does occur for sure when trying to return back() in middleware...

**Comment by rommelandrea** [comment]
I've the same problem.
It's happend when i reload the same page (example with ctrl+F5) and i try to go back.
Laravel 5.1.31
debugbar 2.2.0
