### ISSUE TITLE
Cleanup request .json files

### ISSUE THREAD

**Issue by garygreen** [barryvdh/laravel-debugbar#426]
It might be a good idea to add a console command that you could call which will cleanup the debug .json stuff that gets put in storage. After a while that directory can get huge and would be nice to clear it out thru a scheduled task or something.

**Comment by arecaps** [comment]
:+1:

**Comment by joelcuevas** [comment]
Yes please. :)

**Comment by steveheinsch** [comment]
@joelcuevas Doesn't `artisan debugbar:clear` do this for you?

**Comment by joelcuevas** [comment]
Well... it does! Haha I should have read the command list first. Thank you, @steveheinsch!

**Comment by tquiroga** [comment]
I have got my production server out of disk space because of that, no idea that could create so many JSON files. 47% of my used disk space was from these... 🤦
