### ISSUE TITLE
Router no longer has before and after (in 5.2)

### ISSUE THREAD

**Issue by Francismori7** [barryvdh/laravel-debugbar#427]
We cannot use those:

In src/LaravelDebugbar.php

```
                if ($this->app->isBooted()) {
                    $debugbar->startMeasure('application', 'Application');
                } else {
                    // This line here.
                    $this->app['router']->before(
                      function () use ($debugbar) {
                          $debugbar->startMeasure('application', 'Application');
                      }
                    );
                }
                
                // And this line here.
                $this->app['router']->after(
                  function () use ($debugbar) {
                      $debugbar->stopMeasure('application');
                      $debugbar->startMeasure('after', 'After application');
                  }
                );
```

They prevent the framework from launching with those exceptions:

`BadMethodCallException in Macroable.php line 81: Method before does not exist.`
`BadMethodCallException in Macroable.php line 81: Method after does not exist.`

Of course this is for 5.2.

**Comment by michaeljhopkins** [comment]
@Francismori7 any idea how to resolve this?

**Comment by GrahamCampbell** [comment]
Laravel debugbar needs to use middlewares instead.

**Comment by GrahamCampbell** [comment]
The before/after stuff has been deprecated since L5.0, and I deleted it in 5.2.

**Comment by GrahamCampbell** [comment]
If you still need that stuff, I'd recommend sticking with L5.1 LTS.

**Comment by TommyC81** [comment]
Also experienced this. My know-how is unfortunately a bit short of being able to put a pull request in. I've barely used middleware at all.

**Comment by TommyC81** [comment]
Enough to merge this already existing pull request? #407

**Comment by barryvdh** [comment]
@TommyC81 That is to remove the information, this is about needing the filters at all.

**Comment by TommyC81** [comment]
Not sure I'm following, sorry. Thought it was the same issue. Did try the pull request and it seemed to have fixed the issue, however still some other item failing in that pull request. Missing argument in some view.

**Comment by michaeljhopkins** [comment]
@TommyC81 your PR may fix the issue that you are seeing. What @barryvdh is saying is that the issue currently being discussed isn't `Missing argument 2 for Barryvdh\Debugbar\LaravelDebugbar::Barryvdh\Debugbar{closure}()` but rather the `before()` and `after()` methods currently being used in the `LaravelDebugbar.php` class

**Comment by TommyC81** [comment]
Hmm, it's the before and after filters issue I've been trying to address.
Not my pull request, but it removes the before and after filters and moves
the code to middleware as explained/suggested by Graham. And it seems to
work.

Not sure if we are misunderstanding each other, I think a look at that pull
request will clear things up. Maybe it's just a matter of reviewing that
pull request, it seems it would still be compatible with all 5.* versions.

**Comment by barryvdh** [comment]
Fixed and tagged, let me know if you still have problems.
