### ISSUE TITLE
[RFC] Would it be possible to have a RedisCollector?

### ISSUE THREAD

**Issue by phoenixgao** [barryvdh/laravel-debugbar#429]
Would like to see redis commands in laravel debugbar, SncRedisBundle for symfony has a redis collector, but I'm not sure how to extend laravel's redis facade to a traceable one.

**Comment by richbradshaw** [comment]
Same here - would be nice to have something that hooks round the `Cache` facade.

**Comment by jpmurray** [comment]
I was coming just to ask if it was possible to integrate redis, so I guess I'll just add my voice to the lot!

**Comment by barryvdh** [comment]
Not sure, but I'm open for PR's :)

**Comment by webcodecs** [comment]
+1
