### ISSUE TITLE
Laravel 5.2 gives error

### ISSUE THREAD

**Issue by tdolph** [barryvdh/laravel-debugbar#434]
The error is:
ErrorException in LaravelDebugbar.php line 291:
Missing argument 2 for Barryvdh\Debugbar\LaravelDebugbar::Barryvdh\Debugbar{closure}()

This was shown when trying to login.

**Comment by barryvdh** [comment]
Can you check that #433 fixes it (`@dev` version)

**Comment by tdolph** [comment]
Thanks
