### ISSUE TITLE
Support for L5.2 multi auth

### ISSUE THREAD

**Issue by vadimsg** [barryvdh/laravel-debugbar#436]

**Comment by barryvdh** [comment]
What do you need exactly?

**Comment by vadimsg** [comment]
I have 2 auths. One for public users and one for admins. After I login in public and admin side I see in debugbar auth tab only the default guard, It doesn't switch to admin guard. 

Do you think this could be added?

**Comment by barryvdh** [comment]
Probably, PR is welcome :)
