### ISSUE TITLE
Storage logs in elastic search

### ISSUE THREAD

**Issue by pavankumarkatakam** [barryvdh/laravel-debugbar#438]
How to use this package to store logs in elasticsearch as JSON document.

**Comment by barryvdh** [comment]
This isn't meant for storing logs. Use a monolog subscriber or something.

**Comment by pavankumarkatakam** [comment]
But i want all the data collected by this package specifically for laravel.

**Comment by barryvdh** [comment]
It's currently stored in a Debugbar specific json file, so not sure if that's helpful for elasticsearch. How do you imagine this in elasticsearch?

**Comment by pavankumarkatakam** [comment]
i just manually send the .json file to elasticsearch and viewed with kibana it working fine, But i want to use some custom storage driver in this package it automatically send the data (which is writing to json file) elastic search. If so i can visualize the response codes, time taken for each route and how many exception i got in a day all those main analytics can be derived using kibana.

**Comment by pavankumarkatakam** [comment]
What is your thoughts @barryvdh . Actually Elastic and Kibana is really awesome.

**Comment by pavankumarkatakam** [comment]
Closing this issue, as now there is option for custom storage.
