### ISSUE TITLE
bug syntax error, unexpected 'class' (T_CLASS)

### ISSUE THREAD

**Issue by khaninejad** [barryvdh/laravel-debugbar#439]
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifi
er (T_STRING) or variable (T_VARIABLE) or '{' or '$' in ../vendor/barryvdh/laravel-debugbar/src/L
aravelDebugbar.php on line 372
laravel 5.0 
![bug-debuger](https://cloud.githubusercontent.com/assets/4404500/12052560/6e80ef4c-af25-11e5-9d26-1b8d9e26c6b7.jpg)

**Comment by barryvdh** [comment]
Does above commit fix it for you?

**Comment by khaninejad** [comment]
No, 
remote:   Error Output: PHP Parse error:  syntax error, unexpected 'class' (T_CL
ASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
../vendor/barryvd
h/laravel-debugbar/src/LaravelDebugbar.php on line 372
remote:

**Comment by khaninejad** [comment]
let me update my composer

**Comment by barryvdh** [comment]
Did you apply above commit?

**Comment by khaninejad** [comment]
[RuntimeException]
  Error Output: PHP Parse error:  syntax error, unexpected 'class' (T_CLASS),
   expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
  ../vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php on line 372

**Comment by barryvdh** [comment]
You need the `@dev`  version to test the commit (or manually change that 1 line from https://github.com/barryvdh/laravel-debugbar/commit/3bf871f2d70e0412379613b2a52d03f5a3d6a75e

**Comment by khaninejad** [comment]
I guess fixed, I face this error on app building so my options are limited.

**Comment by khaninejad** [comment]
Fixed!

**Comment by atwright147** [comment]
Will this be is a release soon? The `@dev` this doesn't seem to work for me...

**Comment by sandersjj** [comment]
@barryvdh I also have this problem. I get this error after php artisan clear-compiled

    PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/hypotheekbond/admin/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php on line 372


                                                                                                                      
  [Symfony\Component\Debug\Exception\FatalErrorException]                                                             
  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'  
                                                                                                                      


Script php artisan clear-compiled handling the post-update-cmd event returned with an error

                                                                                                                                                                                                                                             
  [RuntimeException]                                                                                                                                                                                                                         
  Error Output: PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/hypotheekbond/admin/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.p  
  hp on line 372

**Comment by meriemMat** [comment]
khaninejad how you fixed that ?

**Comment by ricardovigatti** [comment]
+1, i'm almost sure this is related to Laravel version. I'm using 5.0

**Comment by meriemMat** [comment]
the above commit fix it ... thx barryvdh
