### ISSUE TITLE
PhpDebugBar is not defined

### ISSUE THREAD

**Issue by vvmgev** [barryvdh/laravel-debugbar#440]
hi all ... I have a problem with the debugger (lamp-server^)
![2016-01-01 16-11-56](https://cloud.githubusercontent.com/assets/11613729/12070782/174701a0-b09a-11e5-97e7-b16a9497535d.png)

and when run as  php -S localhost:8000 -t public 
It works fine

**Comment by MECU** [comment]
Same as #418?

**Comment by vvmgev** [comment]
I do not see it making

**Comment by Donny5300** [comment]
Start with adding jQuery to your application cause its not defined.

**Comment by JackPot777** [comment]
By default, the server loads the index.html. You need to force the index.php in the browser row.
