### ISSUE TITLE
Access denied error for user homestead 

### ISSUE THREAD

**Issue by shinokada** [barryvdh/laravel-debugbar#442]
I am not using homestead. Using localhost mysql for my DB. 

Laravel version: 5.2.5

I get the following errors in the debugbar exceptions:

    Cannot add listen to Queries for Laravel Debugbar: SQLSTATE[HY000] [1045] Access denied for 
    user  'homestead'@'localhost' (using password: YES)
    /Users/sokada/Code/laravel52/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#310

    SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)
     /Users/sokada/Code/laravel52/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php#55

Is this a bug?

**Comment by barryvdh** [comment]
It seems it's not loading the correct config then. It does work in your application? Are you using multiple connections?

**Comment by josimar-lemos** [comment]
I think it's not a bug just set .env file with your database connection

```php
DB_HOST=localhost
DB_DATABASE=homestead //your database name
DB_USERNAME=homestead //your database user name
DB_PASSWORD=secret //your database password
```
