### ISSUE TITLE
debugbar is searching for a non existing file 'jquery.min.map'

### ISSUE THREAD

**Issue by kife-design** [barryvdh/laravel-debugbar#444]
Since the last update, there seems to be a problem where the following url '_debugbar/assets/jquery.min.map' seems to be called, which does not exist.

**Comment by kife-design** [comment]
my fault, has nothing to do with the debugbar

**Comment by barryvdh** [comment]
The min.map is tried when de Developer Tools are open. But there is probably a reference left in the files somewhere.

**Comment by kife-design** [comment]
There is, in maximebf/php-debugbar. I have created a pull request.
https://github.com/maximebf/php-debugbar/pull/247
