### ISSUE TITLE
DebugBar stops working when routs have many parameters

### ISSUE THREAD

**Issue by RollingTL** [barryvdh/laravel-debugbar#445]
After placing  following code uno routs.php DebugBar stops working:
Route::get('{p1}', ['uses' => 'PageController@index',]);
Route::get('{p1}/{p2}', ['uses' => 'PageController@index',]);
Route::get('{p1}/{p2}/{p3}', ['uses' => 'PageController@index',]);
Route::get('{p1}/{p2}/{p3}/{p4}', ['uses' => 'PageController@index',]);

Javascript errors:
[Error] Did not parse stylesheet at 'http://localhost:8000/_debugbar/assets/stylesheets?1436453519' because non CSS MIME types are not allowed in strict mode.
SyntaxError: Unexpected token '<'
(anonymous function)javascript:1
ReferenceError: Can't find variable: PhpDebugBar
(anonymous function)brokerage:170

After removing multiple parameters from routs,php all started to work.

Laravel 5.1, Mac Safari, PHPStorm

**Comment by barryvdh** [comment]
Did you see the note in the readme?
> If you use a catch-all/fallback route, make sure you load the Debugbar ServiceProvider before your own App ServiceProviders.

**Comment by RollingTL** [comment]
I didn't see, sorry.
Changed order, all is working now.
