### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by chadsterBAM** [barryvdh/laravel-debugbar#447]
Just updated through composer and now am getting the message below:

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/elements/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php on line 372

**Comment by hansek** [comment]
Probably you have an outdated version of PHP. On my localhost I get this error for PHP 5.4, if I use 5.6 then it works. :wink:
