### ISSUE TITLE
Missing queries?

### ISSUE THREAD

**Issue by lazytyper** [barryvdh/laravel-debugbar#449]
I've been using another eloquent query in a method of a model class, and discovered that it's not shown in the query list.

To make sure the debugbar is not disabled before the query is being executed, I've disabled the `disable()` method for test.

``` php
public function disable()
{
    //$this->app['config']->set('debugbar.enabled', false);
}
```

The query still didn't show.
I can help finding the reason, but then I'll need to study the code or I'll need tipps what to try/test/check.

**Comment by ricardokenji** [comment]
DebugBar uses Eloquent's DB::listen();  

can you use it manually and check if your query is there?

try something like:
```
DB::listen(
    function ($query) use($logDB){
        $logDB->addInfo("Query (".$query->time."ms): ".$query->sql." \n DATA: ".implode(" , ",$query->bindings));
    }
);

```
Where $logDB is my monolog instance. If it's not there then it's not DebugBar's fault.
