### ISSUE TITLE
Queries tab not obeying cached entries?

### ISSUE THREAD

**Issue by breenyoung** [barryvdh/laravel-debugbar#450]
Apologies if this is already been logged / addressed etc.  I looked around and didn't find anything similar.

**Platform (Dev env)**
- Windows 7
- PHP 5.6.14
- Laravel 5.1
- Debugbar 2.1.1

Here is the scenario.  I have a display only page which makes about 3 DB calls if not found in the cache (type: file).  It is then stored in cache.  Debugbar will display this correctly in the queries tab, on first page load showing the 3 DB queries and then on a page reload, showing 0 queries.  All is working as you would expect.  

The issue arises when an administrator of said display only page updates something on a unrelated edit page.  On successful update to the DB, I put the data **back** into the cache (overwriting the existing key with the new data).

When you go back to the display only page and reload it **should** continue to display 0 queries and retrieve (the now updated) entry from the cache.  Instead it again shows the 3 DB queries supposedly being executed.  Even on subsequent page reloads, it constantly says it's hitting the DB.

I've used the PhpMyAdmin SQL monitor to verify there is in fact no database calls being made and even went so far as the comment out the part of the code that **would** get it from the DB should it not be found in the cache (that code is never reached of course but I wanted to exhaust all options).

Is this a known issue or bug?

**Comment by boynet** [comment]
can't really understand what you are doing, but it looks like you also cached the debugbar data, so when you load the page it also load the old debugbar data that's why you see the queries
