### ISSUE TITLE
Debugbar Error with Laravel Tracker package (must implement interface Illuminate\Contracts\Debug\ExceptionHandler)

### ISSUE THREAD

**Issue by bachmay** [barryvdh/laravel-debugbar#451]
I installed antonioribeiro/tracker for Laravel (https://github.com/antonioribeiro/tracker). If the Debugbar is enabled, I get the following error:

```
ErrorException in Debugbar.php line 29:
Argument 2 passed to Barryvdh\Debugbar\Middleware\Debugbar::__construct() must implement interface Illuminate\Contracts\Debug\ExceptionHandler, instance of PragmaRX\Tracker\Support\Exceptions\Handler given
```

Screenshot:
![screenshot 2016-01-20 23 02 57](https://cloud.githubusercontent.com/assets/6717537/12471270/f7d56f02-bfc9-11e5-997b-61135f118706.png)

The problem is, I am okay with disabling debugbar for that part of my project. However, there is no way to disable Debugbar on only one route or URI.

Any type of help would be greatly appreciated.

Thanks.

**Comment by bachmay** [comment]
This problem actually occurs on all of the pages. I can only enable only one of the 2 packages at a time.

**Comment by NightZpy** [comment]
I have same problem!

**Comment by thecortex** [comment]
I have same problem :(
