### ISSUE TITLE
Class session does not exist

### ISSUE THREAD

**Issue by lly835** [barryvdh/laravel-debugbar#453]
for Lumen (5.2.4) (Laravel Components 5.2.*)

boostrap/app.php

```
$app->register(Barryvdh\Debugbar\LumenServiceProvider::class);
```

![qq20160124-0 2x](https://cloud.githubusercontent.com/assets/2225913/12532236/d786c796-c249-11e5-9cca-c6c0f89b63f8.png)

**Comment by lly835** [comment]
![qq20160124-0 2x](https://cloud.githubusercontent.com/assets/2225913/12532235/c75fe776-c249-11e5-99bc-94529b462e22.png)

**Comment by devboxr** [comment]
Can confirm, have exactly the same problem.

Problem seems to be this part of the code from `src/ServiceProvider.php`:

```php
        $this->app->singleton('debugbar', function ($app) {
                $debugbar = new LaravelDebugbar($app);

                $sessionManager = $app['session'];
                $httpDriver = new SymfonyHttpDriver($sessionManager);
                $debugbar->setHttpDriver($httpDriver);

                return $debugbar;
            }
        );
````

Reason for that being that Lumen 5.2+ removed Session support, on which laravel-debugbar is based.

> Lumen 5.2 represents a shift on slimming Lumen to focus solely on serving stateless, JSON APIs. As such, sessions and views are no longer included with the framework. If you need access to these features, you should use the full Laravel framework. Upgrading your Lumen application to the full Laravel framework mainly involves copying your routes and classes over into a fresh installation of Laravel. Since Laravel and Lumen share many of the same components, your classes should not require any modification.

Bad news!

@barryvdh Do you have any ideas how to fix this?

**Comment by barryvdh** [comment]
Can you try the latest dev version?

**Comment by devboxr** [comment]
I just did try the dev-master and it seems to be working, at least no exceptions are thrown.

However, the bar is not shown do to it being an API. I know that PHP Debug Bar can tunnel information through headers, is that something I could use with it? Probably completely unrelated problem, but in Laravel it is shown by default by using views. In Lumen, most of the time, there are none.

Thanks

**Comment by carbontwelve** [comment]
I liked Lumen because it was in my mind akin to Silex, a slimmer version of its bigger sibling. But now they have removed sessions and views, it makes it essentially a framework for one niche and not exactly a micro framework.
