### ISSUE TITLE
Queries tab is not displayed in the Lumen 5.1

### ISSUE THREAD

**Issue by newpdv** [barryvdh/laravel-debugbar#455]
In Lumen 5.1.6 Queries tab is not displayed, because `isset($this->app['db'])` return false in file
https://github.com/barryvdh/laravel-debugbar/blob/master/src/LaravelDebugbar.php#L258
If replace this with `$this->app['db']` tab works correctly

**Comment by barryvdh** [comment]
Related with #463 ?

**Comment by eslym** [comment]
call `$app->withEloquent();` before registering the service provider
