### ISSUE TITLE
DebugBar not rendering when returning response instead of view

### ISSUE THREAD

**Issue by mitchkramez** [barryvdh/laravel-debugbar#459]
When returning a view like this:

`return response()->view('front.listings.show', compact('listing'))->withCookie(cookie()->forever('recents', $recents));`

Debugbar isn't rendered on the page. returning a view normally:

`return view('front.listings.show')->with(compact('listing'));`

works fine. Am I missing something in here?

**Comment by mitchkramez** [comment]
FWIW, I've tried tracing back the classes, add adjusted to:

```$response = response()->view('front.listings.show', compact('listing'))->withCookie(cookie()->forever('recents', $recents));

        return Debugbar::modifyResponse($request, $response);```

Without sucess.

**Comment by groston** [comment]
Keeping fully in mind that I do not even qualify as a Laravel newbie: I installed DebugBar to help me understand what is going on with my site (which I did not build). What I am noticing is that the DebugBar renders on all pages other than those which use LazyLoad to display items from the database. Is there a chance that my issue is related to Mitch's?
