### ISSUE TITLE
Session flash message

### ISSUE THREAD

**Issue by TBestcz** [barryvdh/laravel-debugbar#472]
Hi,

after updating on version 2.2.0 from 2.0.6 I have a problem with flash messages on Laravel. When i set flash message, message has flashed to the page and after page reload message still flashes (and after next reloads, as long as session expires).

After downgrading to version 2.0.6 all works fine.

Thanks!

**Comment by Twinsen-** [comment]
I confirm the problem with 2.3 and 3.1.4
Session::flash act like Session::put
