### ISSUE TITLE
Composer update returns PHP syntax error in laravel-debugbar

### ISSUE THREAD

**Issue by Joe1992w** [barryvdh/laravel-debugbar#479]
shortly after > php artisan clear-compiled
I get the following error:

  [RuntimeException]
  Error Output: PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING
  ) or variable (T_VARIABLE) or '{' or '$' in F:\Development\workwear.needlers.co.uk\vendor\barryvdh\laravel
  -debugbar\src\LaravelDebugbar.php on line 368

I'm using Laravel 5.0.35 and removing ::class from the line in question fixes my issues.

**Comment by deep88** [comment]
same problem with me on laravel 5.0 on php 5.4.45

**Comment by odin88** [comment]
same problem with me .. using laravel 5.0 .. please fix this

**Comment by The-Hasanov** [comment]
change to 
` $gateCollector = $this->app->make('Barryvdh\Debugbar\DataCollector\GateCollector');`

**Comment by deep88** [comment]
thanks for reply hosanov pls..tell in detail..what should we change in which file

**Comment by amidevelopment** [comment]
Did anyone try the solution by @The-Hasanov?
