### ISSUE TITLE
Class 'Barryvdh\Debugbar\ServiceProvider' not found in \src\Illuminate\Foundation\ProviderRepository.php

### ISSUE THREAD

**Issue by aymeric75** [barryvdh/laravel-debugbar#480]
Hi,

 When trying to install the debugbar i faced this error running the command: `php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"`

> Class 'Barryvdh\Debugbar\ServiceProvider' not found in \src\Illuminate\Foundation\ProviderRepository.php

I tried to look for this error on google but none of the solutions i found worked, i'm stuck here, any help ?

Cheers

**Comment by marktopper** [comment]
Please show us your `composer.json` file and make sure that you have ran `composer update barryvdh/laravel-debugbar` and `composer dump-autoload`.

**Comment by meduprise** [comment]
i have the same problem and i did composer update 

> barryvdh/laravel-debugbar `and `composer dump-autoload.
but nothing changed

**Comment by barryvdh** [comment]
And did you add the service provider?

**Comment by meduprise** [comment]
yeah ! but okay the problem solved
**thanks**

**Comment by abahaudd** [comment]
I am getting this error on my publicly hosted server where I do not have a command line access. So I can't run composer update barryvdh/laravel-debugbar and composer dump-autoload.  

Is there any other way to fix this ?

**Comment by nhatdv** [comment]
I have already fix this problem.
You can fix by this command:
composer require barryvdh/laravel-debugbar --dev
this command execute in project folder via command line
After composer a barrybvh will generic C:\xampp\htdocs\am\vendor Folder

Thank

**Comment by ECloutier** [comment]
euh les gars

**Comment by rakesh350** [comment]
`composer update` solved my problem

**Comment by gbrits** [comment]
The error just stops the automatic eject button - so you gotta pull the manual lever instead:

delete bootstrap/cache/config.php
then run `php artisan config:cache`

**Comment by aashu122** [comment]
I have the following error:
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Barryvdh\Debugbar\ServiceProvider' not found


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```


None of the above solutions worked for me. Please help me out

**Comment by egorsmkv** [comment]
Enter the `boostrap/cache` folder and remove all the files it contains. After removing run the command:

```
php artisan package:discover
```

**Comment by bastiotutuama** [comment]
**It needs to be also removed in the providers: `app/config/app.php`**

After:
1.  `composer remove vendor/barryvdh/laravel-debugbar`
2.  `composer update`

**remove the line:**
`Barryvdh\Debugbar\ServiceProvider` in _app/config/app.php_.

Also these folders can be deleted:
- `app/config/packages/barryvdh/laravel-debugbar/config.php`
-  another Debugbar-related file somewhere under `app/storage/...`

**Comment by yahyaefendy** [comment]
> I have already fix this problem.
> You can fix by this command:
> composer require barryvdh/laravel-debugbar --dev
> this command execute in project folder via command line
> After composer a barrybvh will generic C:\xampp\htdocs\am\vendor Folder
> 
> Thank

Thanks. This resolved for my problem

**Comment by oggyoggy448** [comment]
None of the above solution worked for me. In the end, I'm getting this error, 

 The requested package maximebf/debugbar (locked at v1.16.1, required as ^1.16.3) is satisfiable by maximebf/debugbar[v1.16.1] but these conflict with your requirements or minimum-stability.

whenever I try to remove the barrayvdh it tell me two problem. One problem is solution recommendation is install barryvdh^3.5 and other is to install maximmebf/debugbar ^1.16.1.

What should I do now?

**Comment by camohub** [comment]
This problem also occurs if I run **composer dump-autoload --optimize --no-dev** The --no-dev removes all dev dependencies but it is still in the config/app.php in providers array.

**Comment by gajendrarahul** [comment]
you need to install composer package (composer install)

**Comment by HakerTag** [comment]
Barryvdh\Debugbar\ServiceProvider::class line

remove it from app/config/app.php

**Comment by fanti1** [comment]
> I have already fix this problem. You can fix by this command: composer require barryvdh/laravel-debugbar --dev this command execute in project folder via command line After composer a barrybvh will generic C:\xampp\htdocs\am\vendor Folder
> 
> Thank

Facing this problem with some new install of WinterCMS, the composer require with --dev arg solved to me, thanks <3

**Comment by VirajInsharp** [comment]
> Barryvdh\Debugbar\ServiceProvider::class line
> 
> remove it from app/config/app.php

This worked :+1:

**Comment by ThangPhanDuc** [comment]
> Please show us your `composer.json` file and make sure that you have ran `composer update barryvdh/laravel-debugbar` and `composer dump-autoload`.
I followed through and fixed the error

**Comment by ThangPhanDuc** [comment]
> Please show us your `composer.json` file and make sure that you have ran `composer update barryvdh/laravel-debugbar` and `composer dump-autoload`.

I followed through and fixed the error

**Comment by parthiops** [comment]
> Enter the `boostrap/cache` folder and remove all the files it contains. After removing run the command:
> 
> ```
> php artisan package:discover
> ```

this worked for me
