### ISSUE TITLE
System and PHP info

### ISSUE THREAD

**Issue by vedmant** [barryvdh/laravel-debugbar#481]
Hi, Debug Bar is really nice package, I use it for every project!

It would be helpful to have system and PHP info in debug bar in popup or separate page so full PHP info will not be loaded every time. And would be nice to show PHP and Laravel version somewhere in the bar itself. For example Symfony profiler has this page http://screencast.com/t/JvqrJGA4v9uV and it has short info in the bar http://screencast.com/t/ITjQsLeq.

**Comment by marktopper** [comment]
:+1:

**Comment by phoenixgao** [comment]
+1

**Comment by vaughany** [comment]
:+1:
