### ISSUE TITLE
How to work with Mongodb 

### ISSUE THREAD

**Issue by truongthaison** [barryvdh/laravel-debugbar#485]
I'm use https://github.com/jenssegers/laravel-mongodb
and use Laravel dedugbar, in queries tab not show list query database.

**Comment by ebisbe** [comment]
You need to do this:  \DB::connection('mongodb')->enableQueryLog(); 
I have multiple databases ( mysql + mongodb )

More information on https://github.com/jenssegers/laravel-mongodb/issues/600

**Comment by bram1028** [comment]
ebisbe is correct. However, Mongo ID and Date objects won't render correctly.

```
clients.find({"_id":{}})
activity.find({"date":{"$gte":{},"$lte":{}}})
```

The values are blank. Never tracked down the cause.

**Comment by orrd** [comment]
The same solution recommended by @ebisbe also works for Clockwork (a similar tool to Laravel Debugbar, but it uses a browser extension instead and also works with non-HTML responses).  But I would also mention that you probably only want to turn on the query log in debug mode with something like this (in your AppServiceProvider.php's boot() function:

`if (config('app.debug')) DB::connection('mongodb')->enableQueryLog();`
