### ISSUE TITLE
lumen 5.2.6 did't work with debugbar

### ISSUE THREAD

**Issue by EfraimChu** [barryvdh/laravel-debugbar#486]
some steps:
1.composer require barryvdh/laravel-debugbar
2. register a different Provider in bootstrap/app.php:

if (env('APP_DEBUG')) {
 $app->register(Barryvdh\Debugbar\LumenServiceProvider::class);
}
To change the configuration, copy the file to your config folder and enable it:

$app->configure('debugbar');

3.vist the url

but didn't appear the debugbar ？

Did I do  something wrong?

**Comment by aerojun** [comment]
I'm having the same issue.

**Comment by ProjektReaktor** [comment]
me too since update to lumen 5.2.6

**Comment by barryvdh** [comment]
Anything in the logs? Did you clear all caches? Does any html appear in the source:

**Comment by EfraimChu** [comment]
I fixed the problem.

- 1.I saw the chrome network ,and I found URL: http://www.xxx.com/_debugbar/assets/stylesheets?1455697941  is 404 NOT FOUNT 
- 2. I visited the URL :http://www.xxx.com/_debugbar/assets/stylesheets    I got the file
- 3.I thought whether my nginx's config is wrong ,and I changed my nginx config :
 
```
 location / {
    try_files $uri $uri/ /index.php?$query_string;
}

```

-  4. It's  work;
