### ISSUE TITLE
Not showing when routes are cached

### ISSUE THREAD

**Issue by aarondfrancis** [barryvdh/laravel-debugbar#488]
The debugbar does not show when routes are cached, because its routes do not get cached.

```
        if ($app->runningInConsole()) {
            return;
        }
```
prevents it from caching (or listing!) the routes

**Comment by NelinD** [comment]
#484

**Comment by NelinD** [comment]
#484 fix this problem

**Comment by aarondfrancis** [comment]
Awesome, thank you
