### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by JKair** [barryvdh/laravel-debugbar#493]
I update laravel today use composer,but all the commond lose.such as 

```
php artisan db:seed
php artisan make:......
```

when I get the artisan help,it become:

```
Laravel Framework version 5.1.35 (LTS)

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help     Displays help for a command
  inspire  Display an inspiring quote
  list     Lists commands
```

I tried other ways to solve it several time,but fail.I think I have installed this plugin recently,when i remove the barryvdh/laravel-debugbar and the problem is solved,but I can't be sure that the problem is caused by this plugin.Will you be sure that this problem is caused by this plugin?

I'm afraid you can't undestand my Chinglish,so I describe it by chinese one more time,maybe you can understand my mean with google.

我一开始尝试了其他方法去解决这个问题，但是都没有用，直到后来，我想起我最近安装过这个插件，然后我去除了，问题得到了解决，于是我来反馈一下这个问题，是不是开发的时候某些东西导致了插件更新冲突呢？

thanks.

**Comment by xewl** [comment]
"artisan list" displays all the commands you need. ;)

**Comment by JKair** [comment]
@xewl  = =
I use `php artisan`
It can display all the laravel commond,you also can try it.
It truly lose.
