### ISSUE TITLE
Debugbar stays visible even when debug=false

### ISSUE THREAD

**Issue by dgrigg** [barryvdh/laravel-debugbar#494]
I am having an issue in a Laravel 5.2 install where the debugbar is always visible even when the app.debug value is set to false. I have tried setting the enabled flag in the debugbar.php config to false but the bar still stays visible on page reload. 

I have tried removing and reinstalling the debugbar component, I checked the permissions on the storage directory, I have clear the config cache, all with no luck.

Any ideas?

**Comment by barryvdh** [comment]
Anything cached?

**Comment by dgrigg** [comment]
nothing outside of the standard Laravel config

**Comment by barryvdh** [comment]
I mean that configuration cache, did you clear it? Did you set debug to false in your .env?

**Comment by dgrigg** [comment]
yes, php artisan cache:clear and php artisan config:clear
APP_DEBUG=false in the .env file

**Comment by barryvdh** [comment]
What version of laravel-debugbar version are you using exactly?

**Comment by dgrigg** [comment]
2.2

**Comment by avataru** [comment]
If you are using `artisan serve` you need to restart it after changing something in .env. The environment file is loaded when the server starts and won't be read again until the next restart.
