### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by iwex** [barryvdh/laravel-debugbar#497]
I have such exception: 
`FatalThrowableError in ExceptionsCollector.php line 28:
Type error: Argument 1 passed to DebugBar\DataCollector\ExceptionsCollector::addException() must be an instance of Exception, instance of ParseError given, called in /home/iwex/vagrant/chicago/vendor/maximebf/debugbar/src/DebugBar/DataCollector/ExceptionsCollector.php on line 32`

**Comment by barryvdh** [comment]
We can't typehint the new Errors right? So no typehinting at all then?

**Comment by iwex** [comment]
Hmm, is it possible to create new branch for php7. For typehinting you can use Throwable interface.

**Comment by marktopper** [comment]
@iwex did you create an issue about this on [`maximebf/php-debugbar`](https://github.com/maximebf/php-debugbar)?

**Comment by iwex** [comment]
@marktopper no :)

**Comment by barryvdh** [comment]
So perhaps just like this; remove the typehint and Check at runtime.
https://github.com/Seldaek/monolog/commit/481fc4cfa17808581d113673e7dd002b06dcc100

**Comment by tje3d** [comment]
Works fine with: PHP 7.0.4

**Comment by vjoao** [comment]
@tje3d 
It's not working with PHP 7.0.5-2... should I downgrade?

**Comment by tje3d** [comment]
@vjoao 
hmm, didnt tried that, im not sure with 7.0.5

**Comment by marktopper** [comment]
It should work in PHP 7.x when exceptions are thrown, but not when errors are thrown.

**Comment by vjoao** [comment]
It was a mistake on my side. Exceptions are namespaced and I forgot to use them.

**Comment by alejandrozorita** [comment]
Hi!
I have the same fail with PHP 7.0.7...

**Comment by ThomasRalee** [comment]
@alejandrozorita 
Same am facing problems with PHP 7.0.8

**Comment by barryvdh** [comment]
Can you try disabling collectors until it doesn't happen, so we can narrow down which one it is?
Or if it's the debugbar itself (without collectors)

**Comment by Sly-Ripper** [comment]
Is there a reason this isn't fixed yet? Still the same error as OP, just line 28.

**Comment by siegerhansma** [comment]
@barryvdh Just tried this. It seems to be the Exceptions collector that is giving issues.

**Comment by DrudgeRajen** [comment]
Same problem with 7.0.9

**Comment by iget-master** [comment]
Same problem here... 

FatalThrowableError in ExceptionsCollector.php line 28:
Type error: Argument 1 passed to DebugBar\DataCollector\ExceptionsCollector::addException() must be an instance of Exception, instance of ParseError given, called in /home/esoares/Sandbox/cdtsys/vendor/maximebf/debugbar/src/DebugBar/DataCollector/ExceptionsCollector.php on line 32

**Comment by barryvdh** [comment]
Does the above commit fix it for you (Try `^2.3@dev`)

**Comment by iget-master** [comment]
Fixed! :) Thanks!
