### ISSUE TITLE
Lumen and Call to undefined method Laravel\Lumen\Application::runningUnitTests()

### ISSUE THREAD

**Issue by lasselehtinen** [barryvdh/laravel-debugbar#498]
Hi,

I have a Lumen application where I have used the package before. After upgrading all the packages through composer update, I started to get the following error:

```
FatalThrowableError in vendor/barryvdh/laravel-debugbar/src/ServiceProvider.php line 104:
Fatal error: Call to undefined method Laravel\Lumen\Application::runningUnitTests()

in ServiceProvider.php line 104
at ServiceProvider->boot() in Application.php line 172
at Application->register(object(LumenServiceProvider)) in app.php line 93
at require('/home/vagrant/Code/digital-distribution/bootstrap/app.php') in index.php line 14
```

**Comment by lasselehtinen** [comment]
Seems like it has been broken by [this commit](https://github.com/barryvdh/laravel-debugbar/commit/b7e40a5fdc65ef4e44819b81a2e048ec852b9f64).

**Comment by barryvdh** [comment]
The Lumen provider extends the Laravel one. I guess the UnitTest helper isn't there in Lumen.
ping @wiedem

**Comment by lasselehtinen** [comment]
Seems like the Illuminate\Foundation\Application.php in Lumen is missing this method which exists in Laravel. 

```
    /**
     * Determine if we are running unit tests.
     *
     * @return bool
     */
    public function runningUnitTests()
    {
        return $this['env'] == 'testing';
    }
```

**Comment by barryvdh** [comment]
Should we just replace it with `$app->environment('testing')`?

**Comment by barryvdh** [comment]
Can you test with https://github.com/barryvdh/laravel-debugbar/commit/c291e58d0a13953e0f68d99182ee77ebc693edc0 ?

**Comment by wiedem** [comment]
> Should we just replace it with $app->environment('testing')?

Your solution should be fine.
Dunno why this method is missing in Lumen, doesn't make any sense at all.
Someone should open an issue for this on the Lumen project.

**Comment by barryvdh** [comment]
2.2.2 is tagged with this fix :)

**Comment by lasselehtinen** [comment]
Awesome, seems to work just fine now. Thanks for the quick response.

**Comment by lasselehtinen** [comment]
I made a pull request to Lumen to add this method and it now merged. So up to you if you want to revert this change. Personally I don't see the need for this, because the current check is also very readable.

https://github.com/laravel/lumen-framework/pull/409/
