### ISSUE TITLE
how to add web middleware to route group?

### ISSUE THREAD

**Issue by lvqingan** [barryvdh/laravel-debugbar#501]
I'm using 5.2.31

routes of debugbar can't work without "web" middleware, the console shows error:

"Session store not set no request"

but $routeConfig in ServiceProvider.php only accept namespace and prefix, how to add web middleware to the route group?

**Comment by lvqingan** [comment]
I have a solution, maybe not the best one

add following code to map method in RouteServiceProvider just before mapWebRoutes call

        $vendorRouters = $router->getRoutes();

        foreach ($vendorRouters as $vendorRouter) {
            $vendorRouter->middleware('web');
        }

**Comment by barryvdh** [comment]
Why did you close this?

**Comment by lvqingan** [comment]
weird thing happened this morning I comment the workaround code to show how I fix this issue

**Comment by lvqingan** [comment]
weird thing happened this morning : )

I was showing my workaround to my colleague, then I comment the workaround code. But everything works fine. php artisan route:list shows web middleware already added to routes of debugbar.

I thought maybe it's my illusion, there is not andy issue about the web middleware.
