### ISSUE TITLE
Expand the details of a query in template file

### ISSUE THREAD

**Issue by ksdev-pl** [barryvdh/laravel-debugbar#504]
Hi

Related to discussion: https://mobile.twitter.com/laravelnews/status/732550470149902336
(I'm posting this to allow eventual further discussion, as twitter is not a good place for this, and to have an explanation of a future pull request).

Imagine that you must work with a code of another person. There is a view with multiple partials and you wish to check in which one of them and at what line a query is triggered. With Query Tracer it is simple, as you see the cached template file name and specific line. You cannot do this so fast when seeing only a "Template file" information:

![Screenshot](https://pbs.twimg.com/media/CirvG6lWgAA1Y7s.jpg:large)

Barry is not sure about the usefulness of showing a name of cached template, instead of a real name. But for debugging purpose it is enough to see the cached template name - it is the same in the stack trace. Certainly it is better than seeing nothing.

Thanks for the debugbar (and the "backtrace" option), I cannot live without it.

**Comment by barryvdh** [comment]
See https://github.com/barryvdh/laravel-debugbar/pull/503

**Comment by ksdev-pl** [comment]
#503 is great. Thank you.
