### ISSUE TITLE
Create a model in routes.php will create three database model records

### ISSUE THREAD

**Issue by leanplay** [barryvdh/laravel-debugbar#505]
When Laravel Debugbar is on.

Write the following code in `app\Http\routes.php`, will cause a bug:

```php
<?php
// app\Http\routes.php

$user = new App\User();
$user->name = 'Foo';
$user->save();
```

This would insert three records in database. I think it is a BUG.

**Comment by asvae** [comment]
@leanplay you should probably read the part of laravel manual about routing. Carefully.

**Comment by barryvdh** [comment]
Yeah you should do anything outside the routes.

**Comment by leanplay** [comment]
Thank you @asvae @barryvdh . You are very kind. 💌
