### ISSUE TITLE
remove debugbar

### ISSUE THREAD

**Issue by greatamir** [barryvdh/laravel-debugbar#513]
how can i remove it completely????
Debugbar::disable(); not working in laravel 5.2

**Comment by asvae** [comment]
@greatamir 
`'enabled' => null,` in `config/debugbar.php`

**Comment by ronrun** [comment]
I have the same problem in laravel 5.2. In config folder, there is no debugbar.php.
In config/app.php, I set 
`    'debug' => 'false',`
but the debugbar always shows at the bottom!!

**Comment by santigarcor** [comment]
if you don't have a debugbar.php maybe you should run `php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"`

**Comment by asvae** [comment]
@ronrun `'debug' => 'false'` that's because false is string in your case. :)

**Comment by dovietduc** [comment]
Because this one append to body tag. You can config onfig/debugbar.php
'inject' => false to 'inject' => true

**Comment by wturrell** [comment]
Once you've generated the debugbar.php config file (using `vendor:publish` in @santigarcor's  answer) you can just add a:

`DEBUGBAR_ENABLED=false` or
`DEBUGBAR_ENABLED=true` (default)

entry to your `.env` file.

**Comment by khemrajregmi** [comment]
just do APP_DEBUG=false in .env file its works fine

**Comment by vdeshan** [comment]
`app('debugbar')->disable();` use this on your `web.php `

**Comment by murilolivorato** [comment]
this debug bar , is the worth thing that I used on the last days

**Comment by boulangermario5** [comment]
vdeshan where do you put it into your web.php?

**Comment by nowendwell** [comment]
@boulangermario5 You should consider adding `Config::set('debugbar.enabled', false);` to your routes/web.php file.

**Comment by Dwood15** [comment]
Once you change your config file make sure to run `php artisan config:cache`

**Comment by dbehterev** [comment]
debugbar continue injecting JS code before closing body tag despite on:
- .env: DEBUGBAR_ENABLED=false
- web.php: Config::set('debugbar.enabled', false);
- config\debugbar.php: 'inject' => false
- php artisan config:cache

**Comment by nowendwell** [comment]
@dbehterev Did you run `php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"`?

**Comment by SebastianBotez** [comment]
My gosh this class is the worst experience of my coding life.
I try to get rid of it and it says Class 'Barryvdh\Debugbar\ServiceProvider' not found when accesing a page even if this class is not registered in providers or anywhere in the app.
This is the worst package ever and I still don;t know how to get rit of it!!!

**Comment by amit97911** [comment]
Even though you have installed the debugbar, kindly do **composer require --dev php-middleware/php-debug-bar --dev** and proceed with option **'y'**. Doing so will reinstall debugbar and change it to package to be enabled to the debug environment only.
Later on you can set the APP_DEBUG=true (for local machine) / false (for production machine) and the debugbar will show only where **APP_DEBUG=true**.

**Comment by deesynertz** [comment]
my project .env on production server the debugger is false while debug log still shown on the pages am tryin your solution nothing works

**Comment by amit97911** [comment]
> my project .env on production server the debugger is false while debug log still shown on the pages am tryin your solution nothing works

php artisan config:clear

Please run the above command. This will reload the updated .env in your project.

**Comment by deesynertz** [comment]
Thank you for your email
