### ISSUE TITLE
Can't install the bar

### ISSUE THREAD

**Issue by innerdev** [barryvdh/laravel-debugbar#514]
Hello. I'm taking errors while updating composer. Can you help me, please?

> C:\work\devilbros>composer require barryvdh/laravel-debugbar
> Using version ^2.2 for barryvdh/laravel-debugbar
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
>     - illuminate/support v5.2.25 requires illuminate/contracts 5.3.\* -> satisfiable by illuminate/contracts[5.3.x-dev] but these conflict with your requirements or minimum-stability.
>     - Conclusion: remove laravel/framework v5.0.35
>     - barryvdh/laravel-debugbar v2.2.0 requires illuminate/support 5.1._|5.2._ -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8, v5.2.0, v5.2.1
> 9, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.6, v5.2.7].
>     - barryvdh/laravel-debugbar v2.2.1 requires illuminate/support 5.1._|5.2._ -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8, v5.2.0, v5.2.1
> 9, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.6, v5.2.7].
>     - barryvdh/laravel-debugbar v2.2.2 requires illuminate/support 5.1._|5.2._ -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8, v5.2.0, v5.2.1
> 9, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.6, v5.2.7].
>     - don't install illuminate/support v5.1.1|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.13|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.16|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.2|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.20|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.22|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.25|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.28|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.30|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.31|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.6|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.1.8|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.0|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.19|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.21|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.24|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.26|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.27|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.28|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.31|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.32|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.37|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.6|don't install laravel/framework v5.0.35
>     - don't install illuminate/support v5.2.7|don't install laravel/framework v5.0.35
>     - Installation request for laravel/framework (installed at v5.0.35, required as 5.0.*) -> satisfiable by laravel/framework[v5.0.35].
>     - Installation request for barryvdh/laravel-debugbar ^2.2 -> satisfiable by barryvdh/laravel-debugbar[v2.2.0, v2.2.1, v2.2.2].
> Installation failed, reverting ./composer.json to its original content.

I'm just started to learn laravel, so feel free to ask me any other info, please.

**Comment by odin88** [comment]
which version of laravel are you using ?

**Comment by barryvdh** [comment]
I added 5.3 support: https://github.com/barryvdh/laravel-debugbar/commit/4e0e81e1b40616825556eeed6367cebe7e532622
Can you try with latest dev version?

**Comment by juanvillegas** [comment]
Same thing happening to me with Laravel 5.0.*

**Comment by RogueSheep-nl** [comment]
For anybody reading this:
I had the same issue with L5.0: "illuminate/support" should be on 5.0. By using version 2.1 of the debugbar this the right version is used:
"barryvdh/laravel-debugbar": "~2.1"
