### ISSUE TITLE
Responses selectbox auto-select

### ISSUE THREAD

**Issue by martin-heralecky** [barryvdh/laravel-debugbar#515]
Hi,

When there is a new response from the server, it's added to the selectbox and it's also autoselected. This may be a good idea but if I have an ajax request every 2 seconds, it's quite inconvenient, because I can't see the data for the response I want. Some button to disable the autoselecting would be great.

Thanks

**Comment by orosznyet** [comment]
I would love to disable this feature as well (on-demand). We have a request each 15 seconds and it's a complete nightmare switching back to the original request.

**Comment by barryvdh** [comment]
Please make a PR to https://github.com/maximebf/php-debugbar :)

**Comment by 4n70w4** [comment]
Hi! The same problem! Any news?
