### ISSUE TITLE
debugbar not showing in laravel module structure 

### ISSUE THREAD

**Issue by sachinvrg** [barryvdh/laravel-debugbar#516]
Can anyone please help me to find out , why debug bar is not showing in laravel module structure
please check the following screen shot, it is working only for root url -
![screen1](https://cloud.githubusercontent.com/assets/12329845/16034811/66711568-3231-11e6-8ee7-819319a5d7de.png)
However the same code is not working for below url-
![screen2](https://cloud.githubusercontent.com/assets/12329845/16034829/882a4f12-3231-11e6-8beb-c94d3b0e61ae.png)
'api' is nothing but a module created in '/var/www/html/demo/app/modules/Api' 

Please help
Thanks much.

**Comment by Bertuzb** [comment]
check firebug for errors. Additionally, the service provider is not being called apparently.

**Comment by marktopper** [comment]
Please share the source of the API Module and your routes to this.

**Comment by sidneycorreia** [comment]
I have the same problem using the Caffeinated Modules.

**Comment by barryvdh** [comment]
We cannot add the debugbar to json responses. Ajax requests are shown if you load them from an HTML page.
