### ISSUE TITLE
Debug false but true for some IP's

### ISSUE THREAD

**Issue by Sennik** [barryvdh/laravel-debugbar#523]
Is it possible to extend Debugbars configuration to create a possibility to hide the Debugbar for everyone except an array of IP's?

Sometime I have to debug on a new (live) server and I don't want anyone to see the debug bar. I know I can use the log, but I rather see the styled version of my error's and warnings... :-)

**Comment by asvae** [comment]
@Sennik At the very least you can extend `ServiceProvider.php` and override its `boot` method.

**Comment by wangta69** [comment]
coinfig/debugbar.php

$local_debug = isset($_SERVER['REMOTE_ADDR']) ?  in_array($_SERVER['REMOTE_ADDR'], array('xxx.xxx.xxx.xxx')): false;
return [
...........................
'enabled' =>$local_debug,
.........................
]

**Comment by reyezstef** [comment]
You don't want that kind of logic in a service provider or in a config. Besides the fact you need to load the request object in a service provider... How about a simple decorator where you can add your own logic to the component? 
https://pastebin.com/vBRFYkuQ
