### ISSUE TITLE
laravel add  Facades is not work

### ISSUE THREAD

**Issue by djoylove** [barryvdh/laravel-debugbar#525]
i install the debugbar follow the README guide, but i found that the Facades not work, I can not use the code such as 
 use Debugbar;
 Debugbar:error('Error!'); 
it tell me the Debugbar has not such static method,why is this happen?

also ,i found if the router is 
Route::get('/', function () {
    return view('welcome');
});
i can see the debugbar view;
but ,if the router like this
Route::get('/', function () {
    return redirect('/web');
});
the debugbar is no longer showing

**Comment by rogatec** [comment]
@djoylove is this just a typo from you? 

> use Debugbar;
Debugbar:error('Error!'); 

There is a colon missing
