### ISSUE TITLE
Using custom queue driver causes mail collector to throw exception.

### ISSUE THREAD

**Issue by cooperaj** [barryvdh/laravel-debugbar#526]
I've found that using a custom queue driver (https://github.com/cooperaj/laravel-redis-sentinel) causes the mail collector to throw an exception. 

I've narrowed it down to the fact that the queue driver is not added until `boot()` but debugbar boots on construction and so the queue driver isn't loaded then. 

For now I've disabled the mail collector. I'm not sure how this would be fixed.

**Comment by cooperaj** [comment]
Having just turned on the 'auth' collector it appears to suffer from the same issue (custom auth provider). Though in this case it stops DebugBar from working at all.

**Comment by barryvdh** [comment]
Perhaps change the order of the service providers?

**Comment by cooperaj** [comment]
Won't affect this as the library linked above does it's work in the boot() method which is called after all the providers register() methods. Since debugbar skips the queue as it were by doing it's work in the constructor it will always be before anything that uses boot().

I shall continue to fiddle around :)
