### ISSUE TITLE
CPU Overload on Ajax

### ISSUE THREAD

**Issue by Cracken6** [barryvdh/laravel-debugbar#527]
Some of my page contents are loaded through AJAX. And Debugbar is overloading CPU when calling multiple requests.

If I disable debugbar, its fine - no overloading at all, site is working very fast, and if I spam requests its maximum 50% CPU. But even with single AJAX call, if debugbar is enabled its about 70-80%. And multiple requests just hangs whole server and makes CPU 100%.

Without AJAX requests, there are no issues with debugbar.

Why is this happening? And how to prevent it?

I am using Laravel 5.2

**Comment by barryvdh** [comment]
You can change the config to disable ajax intercepting.

**Comment by jasperf** [comment]
Assume you meant using `false` here:

```
/*
     |--------------------------------------------------------------------------
     | Capture Ajax Requests
     |--------------------------------------------------------------------------
     |
     | The Debugbar can capture Ajax requests and display them. If you don't want this (ie. because of errors),
     | you can use this option to disable sending the data through the headers.
     |
     | Optionally, you can also send ServerTiming headers on ajax requests for the Chrome DevTools.
     */

    'capture_ajax' => false,
    'add_ajax_timing' => false,
```

and then reloading configuration using `php artisan config:clear` and `php artisan config:cache`?
