### ISSUE TITLE
Shouldn't debugbar view the ajax data after catching it?

### ISSUE THREAD

**Issue by OzanKurt** [barryvdh/laravel-debugbar#528]
I am confused, as I remember, after making an ajax request a select box was appearing letting me select the requests that has been made since the page load.

I am currently making an ajax request 3 seconds after loading the page.

``` js
        setTimeout(function() {
            $.ajax({
                url: '/dashboard',
                type: 'POST',
                success: function() {
                    alert('ajax done');
                }
            });
        }, 3000)
```

In this image, as you see in the console, the request has been made but there is no select box before the folder icon on the bar.
![the select box is not there](http://image.prntscr.com/image/9c4fbe3567a74b8991c6dfbe52a1f39d.png)

Then I click the folder icon and select the last request (the AJAX one) and here I have it;
![the box](http://image.prntscr.com/image/851ce72e47714ee39dff884051be3c2c.png)

Is there a way to make this select box appear and choose the latest ajax request automatically?

Best regards!

**Comment by OzanKurt** [comment]
@barryvdh ♥

**Comment by shahriar-b** [comment]
I'm having the same issue
