### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by cviebrock** [barryvdh/laravel-debugbar#529]
Current version of the package is 2.2.2, but it doesn't look like the changelog has been updated since version 1.8.4. 😞 

It's probably quite a chore to go back and note all the changes and update it, but it would be nice.

Unless this information is now kept somewhere else (website, wiki, etc.) ...?

**Comment by barryvdh** [comment]
No indeed, it is not kept. 2.x is mainly for Laravel 5 instead of 4, but not toooo much has changed, just some extra collectors/options.
