### ISSUE TITLE
MultiAuthCollector cause session token regeneration

### ISSUE THREAD

**Issue by vkartaviy** [barryvdh/laravel-debugbar#532]
When you have a couple of guards for example: 

``` php
 'guards' => [
        'user'   => [
            'driver'   => 'session',
            'provider' => 'users'
        ],
        'admin' => [
            'driver'   => 'session',
            'provider' => 'admins'
        ],
]
```

And then trying to refresh page on admin area with middleware `auth:admin` you will got session token regenerated due to `SessionGuard` trying to resolve user via recaller and then migrates session.

That also cause `TokenMismatchException` always be thrown on form submit.

**Comment by barryvdh** [comment]
ping @plapinski  for #456
