### ISSUE TITLE
Unable to install debugger on laravel 5.1.*

### ISSUE THREAD

**Issue by manojsharma20** [barryvdh/laravel-debugbar#533]
I have tried you step, but unable to install as i am getting following errors:
![image](https://cloud.githubusercontent.com/assets/9690516/17328631/5cc2ee34-58dc-11e6-8356-cb4f29264aec.png)

I have tried this multiple time, but did not get success.

**Comment by barryvdh** [comment]
Error doesn't say anything about debugbar, only about laravelcollective and laravel?

**Comment by manojsharma20** [comment]
What should i do next, as i am not able to install. I cannot upgrade to 5.2 version both laravel and laravelcollective.

**Comment by mikevrind** [comment]
How does your composer.json file looks like?

**Comment by emielmolenaar** [comment]
I guess this has nothing to do with the debugbar but with another package requiring Laravel 5.2.
