### ISSUE TITLE
New http request are automatically selected

### ISSUE THREAD

**Issue by grasmanek94** [barryvdh/laravel-debugbar#536]
When using the debugbar on a page that does ajax requests on a timer (e.g. 1 second) and you want to analyze a certain request (e.g. request number 1) you won't be able to - the debugbar will always jump to the newest request.

**Comment by CyrilMazur** [comment]
Same issue, this is pretty annoying. Any way to disable this behaviour?

**Comment by denjaland** [comment]
Hi,

On my local machine, debugbar works perfectly as I expect it, and I can manually select the request I'd like to consult.  however, the exact same code on a test server, loaded in my same browser results in this behaviour, which I agree is pretty annoying.  Does anyone have any idea what might be causing this?

Thanks a lot, not only for responding to this issue, but also for a great package!
