### ISSUE TITLE
Call to undefined method DebugBar\DebugBar::error()

### ISSUE THREAD

**Issue by xlkit456852** [barryvdh/laravel-debugbar#537]
Lavarel version:5.2.43
When trying to use the debugbar after finish installing by the way you give , I got this error . 
i'm sure that I have ran composer update barryvdh/laravel-debugbar and composer dump-autoload.
I was thinking if it can't find the 'Barryvdh\Debugbar'  ...or something..
composer.js:
`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "barryvdh/laravel-debugbar": "^2.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
`

Controller：
`
use Debug\DebugBar

function(){
Debugbar::error('Error!');
}
`

**Comment by barryvdh** [comment]
That only works with the facade, or app('debugbar')->error().
