### ISSUE TITLE
[Feature] In the view section show the variable content

### ISSUE THREAD

**Issue by sergiq** [barryvdh/laravel-debugbar#538]
Hi,

Could be interesting that the debug bar, in the view section, shows the content of all variables assigned to the view.

Best,

**Comment by barryvdh** [comment]
That is possible, set `debugbar.options.views.data` to `true` in your config: https://github.com/barryvdh/laravel-debugbar/blob/ecd1ce5c4a827e2f6a8fb41bcf67713beb1c1cbd/config/debugbar.php#L135

**Comment by sergiq** [comment]
thank you so much and sorry for waste your time :(

**Comment by barryvdh** [comment]
No problem :)
