### ISSUE TITLE
Laravel 5.3 ajax request 

### ISSUE THREAD

**Issue by milenv** [barryvdh/laravel-debugbar#544]
In Laravel 5.3 , on ajax request, debugbar crash with javascript error:  **Uncaught TypeError: Cannot read property 'length' of **undefined****   row 1875. 

Regards
Edit:
Fixed. The problem was nginx configuration, with result missing GET params.

**Comment by Decadence** [comment]
@milenv May you close it as resolved?

**Comment by mvelikoff** [comment]
Ensure that into location section has the next configuration:

try_files $uri $uri/ /index.php$is_args$args;
