### ISSUE TITLE
Hello,i found /vender/barryvdh/laravel-debugbar/src/Facade

### ISSUE THREAD

**Issue by mornone** [barryvdh/laravel-debugbar#555]

**Comment by mornone** [comment]
**First**

I'm a phper of China, 
My English is very bad, 
if you cannt understand me,
please put this into google translate.

My file config/app.php aliases setup above,

`'Debugbar'  => Barryvdh\Debugbar\Facade::class,`

But when i use Debugbar::info($articles),it's give me an error:
> Class 'debugbar' not found

so i searched the relate articles from baidu,
because google is fucked by GFW, 
i found this link,https://github.com/barryvdh/laravel-debugbar/issues/132,
but it's still didn't help me.

Finally,i found the file /vender/barryvdh/laravel-debugbar/src/Facade.php,the code 
`
protected static function getFacadeAccessor()
    {
        return 'debugbar';
    }
`
when it returned letter is a lowercase letter,
I can't be sure it's not a mistake,
please help me,thank you very much!

**Comment by barryvdh** [comment]
Also register the service provider.

**Comment by mornone** [comment]
@barryvdh ok,thank you very much！Good luck for you！
