### ISSUE TITLE
[Question] How only use clockwork?

### ISSUE THREAD

**Issue by a-h-abid** [barryvdh/laravel-debugbar#558]
I see that there is clockwork integration available. When enabled, I see data on clockwork panel, but phpdebugbar is still visible. 

How can I only use clockwork and hide the phpdebugbar? I don't want two things at same time.

**Comment by barryvdh** [comment]
Did you try setting the inject option to false?

**Comment by a-h-abid** [comment]
I just tried now... doesn't work. When setting inject option to **false**, after loading a page, no data added to the clockwork panel.

**Comment by barryvdh** [comment]
But if you don't use the debugbar,, why not use clockwork directly?

**Comment by a-h-abid** [comment]
Since the option was there, I expected to see data only on the clockwork when enabled. As it was showing data on both I thought maybe there are other options I have to enable, thats why asked. Not that I dont use debugbar, I use it always. Just asking because of that option.

**Comment by barryvdh** [comment]
I used it just for the ajax requests when the debug bar wasn't visible at all, but happy to accept or to fix this.
