### ISSUE TITLE
Lumen configuration problem

### ISSUE THREAD

**Issue by mohamedbelhassen** [barryvdh/laravel-debugbar#560]
When following the installation steps, it is said 
"To change the configuration, copy the file to your config folder and enable it:
$app->configure('debugbar');"

Which file I have to copy !! :app.php:: it is already one file with this name.

where to put ($app->configure('debugbar');")

**Comment by aerojun** [comment]
Inside bootstrap/app.php:

`if (env('APP_DEBUG'))
{
    $app->alias('Debugbar', 'Barryvdh\Debugbar\Facade');

	$app->register(Barryvdh\Debugbar\LumenServiceProvider::class);

	$app->configure('debugbar');
}`

**Comment by mohamedbelhassen** [comment]
Thank you very much :)

**Comment by maiconmva** [comment]
> Inside bootstrap/app.php:
> 
> ```
> if (env('APP_DEBUG'))
> {
>     $app->alias('Debugbar', 'Barryvdh\Debugbar\Facade'); //optional
>     $app->register(Barryvdh\Debugbar\LumenServiceProvider::class);
>     $app->configure('debugbar');
> }
> ```

the alias of Debugbar didnt work.. 

but if i put in this way, turn works:
 class_alias('Barryvdh\Debugbar\Facade', 'Debugbar');

**Comment by maiconmva** [comment]
> Inside bootstrap/app.php:
> 
> ```
> if (env('APP_DEBUG'))
> {
>     $app->alias('Debugbar', 'Barryvdh\Debugbar\Facade'); //optional
>     $app->register(Barryvdh\Debugbar\LumenServiceProvider::class);
>     $app->configure('debugbar');
> }
> ```

the alias of Debugbar didnt work.. 

but if i put in this way, turn works:
 class_alias('Barryvdh\Debugbar\Facade', 'Debugbar');

you have any idea to fix that?
