### ISSUE TITLE
Debug bar does not show

### ISSUE THREAD

**Issue by JC5** [barryvdh/laravel-debugbar#561]
My local vagrant / nginx machine will no longer show my debug bar. I have the same installation on a different machine, where it _does_ show. It must be something local, but for the life of me..

The error I get when I visit _debugbar/open is:

[2016-11-12 20:20:10] testing.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Undefined property: Barryvdh\\Debugbar\\Controllers\\OpenHandlerController::$app","time":"Sat, 12 Nov 2016 20:20:10 +0000","file":"\/sites\/firefly-iii\/vendor\/barryvdh\/laravel-debugbar\/src\/Controllers\/OpenHandlerController.php","line":15,"code":0}  

It's version 2.3.0 with laravel v5.3.18

I could use some pointers. I will update when I have news!

**Comment by JC5** [comment]
Fresh vagrant ubuntu 14.04. Installed nginx, php 7, the works. Still nothing.

**Comment by JC5** [comment]
No commands defined in the "ide-helper" namespace either. Trying an old version now.

**Comment by JC5** [comment]
And yes I enabled it.

**Comment by JC5** [comment]
It returned. I don't know why. Will investigate! Probably cache / version  related.

**Comment by JC5** [comment]
Oh and if anybody else ever runs into this: don't get into the habit of naming your local dev environment "testing". If you do, the debug bar simply won't work.

**Comment by barryvdh** [comment]
Or should look for app_debug, not app_env
