### ISSUE TITLE
How to show Apache SOLR queries in "Query" tab?

### ISSUE THREAD

**Issue by InternetMaster1** [barryvdh/laravel-debugbar#563]
Hi,
Congrats on the amazing library! 
We are currently using it to display all mysql queries running in our application.

Could you please help me as to how to display the **Apache SOLR queries too in the "Query" tab**?

For Apache SOLR, we have used the [apache-solr-client](https://github.com/reprovinci/solr-php-client). Please check the [usage example](https://github.com/PTCInc/solr-php-client/wiki/Example-Usage).

Could you please guide me as to what modification would be needed to the laravel-debugbar library to enable showing these queries too in the "Query" tab?

**Comment by InternetMaster1** [comment]
Some other wordpress based library has tried to print SOLR queries in their debugbar Query Tab, but frankly, that code is very different, and I didn't understand how to modify the "laravel-debugbar" plugin by looking at that code....

https://github.com/pantheon-systems/solr-power/pull/56/commits/6233adf6af5a45ae7c23132d465a581b988edbef

Any help would be appreciated!

**Comment by InternetMaster1** [comment]
Note: Added an issue in the [maximebf php-debugbar repository](https://github.com/maximebf/php-debugbar/issues/302) too

**Comment by barryvdh** [comment]
Closing this in favor of upsteram
