### ISSUE TITLE
Debugbar not showing - Laravel 5.3

### ISSUE THREAD

**Issue by kenold** [barryvdh/laravel-debugbar#568]
Debugbar is not showing for me in new Laravel 5.3 app. It used to work in v5.2. I updated Composer and added this line below in app.php but still didn't work.
`Barryvdh\Debugbar\ServiceProvider::class,`

**Comment by Alexicode** [comment]
Debugbar not working in L5.3?

**Comment by barryvdh** [comment]
Not sure, any errors? Problems with a catch-all route?

**Comment by marktopper** [comment]
Debugbar does not work when using `die` or `exit` in your script.

Be sure to `return` the response.

**Comment by Alexicode** [comment]
Yes, you right.

Thanks.

2016-11-25 14:45 GMT+01:00 Mark Topper <notifications@github.com>:

**Comment by Alexicode** [comment]
It working fine.

Great job.

2016-11-25 14:42 GMT+01:00 Barry vd. Heuvel <notifications@github.com>:

**Comment by kenold** [comment]
Not sure what happened but `php artisan config:cache` worked for me.
