### ISSUE TITLE
Not displaying correctly in Firefox

### ISSUE THREAD

**Issue by Rostom22** [barryvdh/laravel-debugbar#570]
Hi, when i open un project in firefox the debugbar height doesn't display correctly and it's hard to see the information inside. Thanks.

**Comment by apspan** [comment]
Are you on a mac or a pc?

**Comment by barryvdh** [comment]
Screenshot? Not dragged down by accident?

**Comment by apspan** [comment]
Works as expected on mac. FF version 50.0.1

**Comment by Rostom22** [comment]
![capture](https://cloud.githubusercontent.com/assets/21296052/20761275/be449bd6-b722-11e6-9288-4220d6d96dac.PNG)

I'm on pc using Windows 10

**Comment by barryvdh** [comment]
Can't you drag it higher?

**Comment by Rostom22** [comment]
No, i can only minimise.

**Comment by apspan** [comment]
@Rostom22 Can you confirm that you have the latest version of FF and the installation is clean from frontend altering plugins?

**Comment by Rostom22** [comment]
I just did a fresh installation with composer and it's the same :/

**Comment by ironteeth** [comment]
I got the same issue with ubuntu
Firefox Localstorage is readonly on your installation.
Type about:profiles in your address bar and then open the profile rootdir 
Locate webappsstore.* files and modify the write permissions to include your account
