### ISSUE TITLE
publish command not publishing anithing in Laravel 5.3

### ISSUE THREAD

**Issue by diazemiliano-zz** [barryvdh/laravel-debugbar#576]
When I run the command supplied in the `readme.md` nothing is published.

```
artisan vendor:publish --provider=\"Barryvdh\Debugbar\ServiceProvider\"
Nothing to publish for tag []
```

**Comment by AdnaneX** [comment]
try php artisan config:cache

**Comment by diazemiliano** [comment]
> @AdnaneX 
> first try php artisan config:cache

Nothing changed with `php artisan config:cache`. Thanks.

**Comment by adil-chbada** [comment]
in config/app.php
add in providers array
`Barryvdh\Debugbar\ServiceProvider::class,` 
and add aliases array
`'Debugbar' => Barryvdh\Debugbar\Facade::class,`

and run `php artisan config:cache`
and `php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"`

**Comment by diazemiliano** [comment]
I have no results @adil-chbada.  im on laravel 5.3
