### ISSUE TITLE
How to disable QueryCollector ?

### ISSUE THREAD

**Issue by karam12** [barryvdh/laravel-debugbar#579]
Hi !

When I execute a query (Eloquent) in production, it works.
But when I try it in debug, like this :
```php
// Disable debugbar
\Debugbar::disable();

$myQuery->get(); // Timeout
```  
I still get this error :
```php
Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in file xxx/vendor/barryvdh/laravel-debugbar/src/DataCollector/QueryCollector.php on line 109
Stack trace:
  1. Symfony\Component\Debug\Exception\FatalErrorException->() xxx/vendor/barryvdh/laravel-debugbar/src/DataCollector/QueryCollector.php:109
```

The function addQuery in the QueryCollector takes too long:

```php
public function addQuery($query, $bindings, $time, $connection)
```
Is there any way to disable it ?

**Comment by barryvdh** [comment]
Yeah set it to false in the config?

**Comment by karam12** [comment]
When I set false in the config it works, but I would like to have some pages that uses the debugbar and to disable it for some others.
