### ISSUE TITLE
Laravel 5.4 changes that break the debugbar

### ISSUE THREAD

**Issue by martindilling** [barryvdh/laravel-debugbar#582]
I stumbled into a few issues trying to get this working with the 5.4-dev (I know it's not released yet, but if I don't write them now, I wouldn't write them xD).
I don't really have time to work on a PR, but hopefully this can at least help find the right places to look :)

---

This commit broke the log listener:
https://github.com/laravel/framework/commit/57c82d095c356a0fe0f9381536afec768cdcc072?diff=split
What I could figure out was that this needs to accept the new `MessageLogged` class instead of the separate values:
https://github.com/barryvdh/laravel-debugbar/blob/master/src/LaravelDebugbar.php#L234

---

This commit broke the session collector:
https://github.com/laravel/framework/commit/66976ba3f559ee6ede4cc865ea995996cd42ee1b?diff=split
I see the interface/class is typehinted here:
https://github.com/barryvdh/laravel-debugbar/blob/master/src/DataCollector/SessionCollector.php
https://github.com/barryvdh/laravel-debugbar/blob/master/src/SymfonyHttpDriver.php#L51

---

Hope it can save at least a little bit of hunting around :)

**Comment by barryvdh** [comment]
Thanks, up for a PR? ;)

**Comment by martindilling** [comment]
#583
Don't know if it's good or not, but at least the application starts up in both 5.3 and 5.4 :)
