### ISSUE TITLE
Can't install  ~1.8 in Laravel4

### ISSUE THREAD

**Issue by zhangyongyu** [barryvdh/laravel-debugbar#585]
I got errors:

 
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: don't install barryvdh/laravel-debugbar v1.8.5
>     - Conclusion: don't install barryvdh/laravel-debugbar v1.8.4
>     - Conclusion: don't install barryvdh/laravel-debugbar v1.8.3
>     - Conclusion: don't install barryvdh/laravel-debugbar v1.8.2
>     - Conclusion: don't install barryvdh/laravel-debugbar v1.8.1
>     - Conclusion: don't install barryvdh/laravel-debugbar v1.8.0
>     - Installation request for maximebf/debugbar (locked at 1.13.1) -> satisfiable by maximebf/debugbar[1.13.1].
>     - Conclusion: don't install laravel/framework v4.2.22
>     - Installation request for illuminate/contracts (locked at v5.3.23) -> satisfiable by illuminate/contracts[v5.3.23].
>     - Conclusion: don't install barryvdh/laravel-debugbar v1.8.6|install laravel/framework v4.2.22
>     - Installation request for illuminate/support (locked at v5.3.23) -> satisfiable by illuminate/support[v5.3.23].
>     - Conclusion: don't install barryvdh/laravel-debugbar v1.8.7|install laravel/framework v4.2.22
>     - Installation request for barryvdh/laravel-debugbar ~1.8 -> satisfiable by barryvdh/laravel-debugbar[v1.8.0, v1.8.1, v1.8.2, v1.8.3, v1.8.4, v1.8.5, v1.8.6, v1.8.7].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by barryvdh** [comment]
Try the dev version

**Comment by zhed** [comment]
i've same issue too,
happened on laravel 5.4 PHP 7. 
i've already triend install latest version but it still didnt worked..
please help @barryvdh
