### ISSUE TITLE
Show active branch as indicator in debugbar

### ISSUE THREAD

**Issue by malamoet** [barryvdh/laravel-debugbar#587]
I think it would be handy to have some kind of notice in the browser of which repo branch is currently checked out. That said, I thought it may be useful to add the branch name as an extra indicator in the debugbar, something like [this](http://turl.ca/cyht) perhaps? If the Laravel project isn't a repo, then the indicator doesn't need to be rendered.

Just a suggestion off course...

Kind regards,
Thomas

**Comment by chrisbjr** [comment]
Couldn't find anything like this so I made a package for it:

https://github.com/CoreProc/laravel-debugbar-git-info
