### ISSUE TITLE
More 5.4 breakage?

### ISSUE THREAD

**Issue by jkudish** [barryvdh/laravel-debugbar#592]
Hey there,

I see that some updates were made in advance of Laravel 5.4. Unfortunately on a fresh Laravel 5.4-dev project with the latest debug bar, I am still getting a Fatal Error:

```
FatalThrowableError in Manager.php line 137:
Call to undefined method Illuminate\Session\EncryptedStore::set()
```

https://cl.ly/1P2F473N0g1E

Any ideas?

**Comment by jkudish** [comment]
I do have the `encrypt` setting in `config/session.php` set to `true`, but after changing it to `false`, it just changes the error to:

```FatalThrowableError in Manager.php line 137:
Call to undefined method Illuminate\Session\Store::set()```

**Comment by barryvdh** [comment]
Yeah session contract has changed. Can you submit a pr?

**Comment by jkudish** [comment]
Someone already has and it was merged into master. I didn't realize that 2.3.1 didn't include the latest fixes. I updated my composer to pull the latest master and now everything works as expected.
