### ISSUE TITLE
Dusk conflict

### ISSUE THREAD

**Issue by mizansyed** [barryvdh/laravel-debugbar#596]
An error occurs (message below) when Debugbar is enabled when Laravel Dusk is ran. Is there way to resolve this? I have tried at `\Debugbar::disable();` but it has no effect. Removing from config/app.php fixes the issue.

`Element is not clickable at point (118, 1043). Other element would receive the click ...<a class="phpdebugbar-tab">...</a>`

My current solution: I have added a `ENABLE_DEBUGBAR=false` on .env.dusk.local and `'enabled' => env('ENABLE_DEBUGBAR', 'null')` on debugbar.php

**Comment by barryvdh** [comment]
Can't you just set debug env to false on dusk?

**Comment by tyler36** [comment]
@barryvdh worked for me

Updated line in .env.dusk.local
```
APP_DEBUG=false
```

**Comment by minthemiddle** [comment]
I'm on Laravel 5.6.24, Debugbar v3.1.5
The only config that worked for me is:

```
# .env.dusk.local
DEBUGBAR_ENABLED=false
```

**Comment by driade** [comment]
Hi, another is to be sure you can "click" the element, by scrolling to it

```
$browser->script("$('html, body').animate({ scrollTop: $('.element').offset().top }, 0);");
```

**Comment by georaldc** [comment]
> I'm on Laravel 5.6.24, Debugbar v3.1.5
> The only config that worked for me is:
> 
> ```
> # .env.dusk.local
> DEBUGBAR_ENABLED=false
> ```

Setting APP_DEBUG to false should be enough. Did you make sure to initialize your test server environment with your dusk env file to populate your env variables? Something like the below if using artisan serve (if your env file is named .env.dusk.local):

```./artisan serve --env=dusk.local```

**Comment by jameswagoner** [comment]
Can confirm `APP_DEBUG=false` does not disable debugbar during Dusk tests.

Added `DEBUGBAR_ENABLED=false` to dusk env and finally got debugbar to not load.
