### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by coderdiaz** [barryvdh/laravel-debugbar#600]
Hello,

Have you thought about redesigning the package for a modern user interface?

**Comment by barryvdh** [comment]
You dont like it?

**Comment by zschuessler** [comment]
I think the current design and functionality is completely awesome, for what it's worth! Love the simplicity and readability.

**Comment by ideea** [comment]
check symfony's atleast. debug bar should be more beautiful and comfortable to work with. and its not so good :)
