### ISSUE TITLE
not support phpredis in Laravel 5.4

### ISSUE THREAD

**Issue by Except10n** [barryvdh/laravel-debugbar#602]
LaravelDebugbar.php
```
if (is_a($client, 'Illuminate\Redis\Connections\PredisConnection', false)) {
    $client = $client->client();
}
$storage = new RedisStorage($client);
```

When configuring redis.client = 'phpredis'

```
Argument 1 passed to DebugBar\Storage\RedisStorage::__construct() must be an instance of Predis\Client, instance of Illuminate\Redis\Connections\PhpRedisConnection given
```

**Comment by Except10n** [comment]
@barryvdh Can you help me to repair it ?

**Comment by barryvdh** [comment]
Can you make a PR that checks for the type of Redis?

**Comment by Except10n** [comment]
[RedisStorage (maximebf/debugbar) ](https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/Storage/RedisStorage.php#L28) need a instance of Predis\Client

If use phpredis of PHP extension ,  I can not fix it in laravel-debugbar

**Comment by barryvdh** [comment]
Ah I see. Can't you just use the filesystem?

We could otherwise make a Storage implementation based on phpredis, or adapt the other one.

**Comment by Except10n** [comment]
In a production environment We use the phpredis

Laravel5.4 already supports predis / phpredis,  if maximebf/debugbar is compatible with both ways. That's better  :)

**Comment by barryvdh** [comment]
Ok can you make a PR there? (And also, don't use this in production)

**Comment by Except10n** [comment]
#606 

[php-debugbar](https://github.com/maximebf/php-debugbar/pull/319)

**Comment by cjmaxik** [comment]
So, what is the status for now?

**Comment by Except10n** [comment]
@barryvdh now, Is there any intention to be compatible with phpredis ?
