### ISSUE TITLE
should show debugbar when APP_ENV = 'testing'

### ISSUE THREAD

**Issue by koolay** [barryvdh/laravel-debugbar#603]
Currently debugbar works only with APP_ENV='local'.  In my case, I want that debugbar should work also with APP_ENV=testing''.

**Comment by barryvdh** [comment]
Why? And it should look of APP_DEBUG

**Comment by koolay** [comment]
With setting `APP_DEBUG=true and APP_ENV='testing' ` , debugbar  still not work.
Only work when APP_ENV='local'.

**Comment by koolay** [comment]
in file `ServiceProvider.php`

```
if ($app->runningInConsole() || $app->environment('testing')) {
            return;
 }
```

**Comment by barryvdh** [comment]
But why would you want it in testing?

**Comment by koolay** [comment]
I want to see the debug info in my testing  environment,  since i have set `APP_DEBUG=true`.

**Comment by afraca** [comment]
The 'testing'  environment is for automatic testing through the CLI, typically phpunit. If you really want debug information in testing, use the log:
Log::debug(...)

**Comment by ramytamer** [comment]
This is my temp solution in the `AppServiceProvider`:

```php
    public function register()
    {
        if ($this->app->environment('development', 'local', 'testing')) {
            $this->app->register(\Barryvdh\Debugbar\ServiceProvider::class);
            
            $this->app->alias('Debugbar', \Barryvdh\Debugbar\Facade::class);
        }
    }
```

**Comment by lePig** [comment]
me too.
in my 'testing' environment not work

my configuration APP_ENV=testing and APP_DEBUG=true, the `config/debugbar.php`  ,`'enabled' => env('APP_DEBUG', false),`


**but**, if APP_ENV=test it work

**Comment by dfoxx** [comment]
I've found the culprit:

https://github.com/barryvdh/laravel-debugbar/blob/8da801b4783419ddac6fbee50f138a0aad8a77fc/src/LaravelDebugbar.php#L772

**Comment by cweiske** [comment]
"testing" is the environment when unit tests are running and should not be used for normal instances.

https://laravel.com/docs/6.x/testing#environment

**Comment by petermjr** [comment]
> But why would you want it in testing?

Because running tests uses different "testing" db from what I have in "local" and while im still developing I want to run automated tests, and if the test breaks, I might want to debug through my UI. That's why. And even if the environment is "testing" or "whatever", I would probably want to enable it in some way. Why do you ask stupid questions?
