### ISSUE TITLE
keep debugger on stacked mode

### ISSUE THREAD

**Issue by avifatal** [barryvdh/laravel-debugbar#605]
Hi,
Is it possible to have stacked selected by default? I want to see logs from my submits. I can't with out the stacked mode.
Thanks

**Comment by barryvdh** [comment]
What is stacked mode?

**Comment by avifatal** [comment]
https://snag.gy/4WKY3I.jpg

**Comment by PaulMenheere** [comment]
Any idea how/when this is controlled ?

**Comment by ilman** [comment]
It was enabled by default on some previous version, but dunno why its not available on latest version. I think this feature is really helpful, as we can know the debug data/query/error/message before redirection used

**Comment by kbasten** [comment]
Any news on this? Can we re-enable this?

**Comment by tannm2611** [comment]
me too. I need stack mode:(
