### ISSUE TITLE
Trying to run laravel-debugbar with PDO storage, cannot find migration

### ISSUE THREAD

**Issue by devnix** [barryvdh/laravel-debugbar#610]
I cannot find any documented way to run the laravel-debugbar migrations to use the PDO storage in Laravel 5. Is that feature missing?

**Comment by barryvdh** [comment]
It's this one, but it's not published by default
https://github.com/barryvdh/laravel-debugbar/blob/master/src/migrations/2014_12_01_120000_create_phpdebugbar_storage_table.php

**Comment by DevNIX** [comment]
The `vendor:publish` command does anything for this package :/

**Comment by golaod** [comment]
Looks like issue was closed, but the problem was never resolved. Service provider does not register migrations, so there is no way to use it except copy pasting probably
