### ISSUE TITLE
Guzzle requests

### ISSUE THREAD

**Issue by pjebs** [barryvdh/laravel-debugbar#613]
Is there any way to for debugbar to track requests made by Guzzle?

Is this a possible feature request?

**Comment by barryvdh** [comment]
https://github.com/hannesvdvreken/guzzle-debugbar

**Comment by pjebs** [comment]
Is there some way to get it to integrate with your debug bar instead of PHP debug bar?

**Comment by barryvdh** [comment]
Did you read the readme?
https://github.com/hannesvdvreken/guzzle-debugbar#laravel

**Comment by pjebs** [comment]
I read the readme section regarding Laravel...but when you look at the composer file, it loads the PHP debug bar aswell. That made me assume that perhaps it was bypassing your library.

**Comment by barryvdh** [comment]
My debugbar is based on php-debugbar. It also loads it, I just add some styling and collectors etc.

**Comment by pjebs** [comment]
Thank you.
