### ISSUE TITLE
Allow returning a value from ::measure closure

### ISSUE THREAD

**Issue by Cysioland** [barryvdh/laravel-debugbar#616]

**Comment by barryvdh** [comment]
?

**Comment by Cysioland** [comment]
Now construction like
```PHP
$var = Debugbar::measure('API', function()
{
    return $this->api->makeSomeNoise();
});
```

does not work.

**Comment by ahmes** [comment]
How it did it:
`protected function measure(string $function, array $arguments)
    {
        $output = null;

        $measuredCallback = function ($function, $arguments) use (&$output) {
            $output = $this->decoratedObject->{$function}(...$arguments);
        };

        Debugbar::measure(
            $this->makeMeasureName($function, $arguments),
            function () use (&$output, $measuredCallback, $function, $arguments) {
                $measuredCallback($function, $arguments);
            }
        );

        return $output;
    }`
