### ISSUE TITLE
Enable debugbar in AppServiceProvider

### ISSUE THREAD

**Issue by robindirksen1** [barryvdh/laravel-debugbar#617]
I cannot enable the debugbar in the AppServiceProvider when running `\Debugbar::enable();`. Is there another way to use this?

**Comment by cliftonscott** [comment]
Add this inside register() 
`$this->app->register( Debugbar::class );`

Add this at the top
`use Barryvdh\Debugbar\ServiceProvider as Debugbar;`

**Comment by potsky** [comment]
It does not work because in the package boot method, you call :

```
    public function boot()
    {
        ...

        // If enabled is null, set from the app.debug value
        $enabled = $this->app['config']->get('debugbar.enabled');

        if (is_null($enabled)) {
            $enabled = $this->checkAppDebug();
        }

        if (! $enabled) {
            return;
        }
```

So you need to trick in your register method :

```
                $this->app->register(\Barryvdh\Debugbar\ServiceProvider::class);
                $this->app['config']->set('debugbar.enabled',true);
```

**Comment by potsky** [comment]
My trick does not work if environment is `production`...

**Comment by gsabater** [comment]
Is this still true? Since L5.7 this trick is not working for me anymore

**Comment by MarcosBL** [comment]
I was able to get Database queries registered with just

```php
public function register()
{
	$this->app['config']->set('debugbar.enabled', true);
	$this->app->register(\Barryvdh\Debugbar\ServiceProvider::class);
	\Debugbar::enable();
}
```

with only this minor (for me) problem:

```php
Cannot add MailCollector to Laravel Debugbar: Class mailer does not exist
```

**Comment by ruziwang** [comment]
I still have this problem in laravel 6, and I have determined that the laravel debugbar introduces the debug console before routing

Still not displayed
