### ISSUE TITLE
Custom Skin

### ISSUE THREAD

**Issue by mdixon18** [barryvdh/laravel-debugbar#620]
I love this package, however im fairly new to packages and how they work. Is it possible from my own application to publish `laravel-debugbar.css` without having to edit your version in the vendor folder? So that updates wouldn't effect some of my custom styling?

**Comment by barryvdh** [comment]
It's possible to extend the debugbar and add/remove some styles, not guaranteed to keep working.

What do you want to change?

**Comment by martenkoetsier** [comment]
This is an old thread, but I am looking for the same.

The bar looks good in general, but I am looking to reduce the vertical space used by the bar. Especially the top and bottom padding of 15px for `phpdebugbar-widgets-list-item` is way too much for my taste, but also other vertical paddings.

> It's possible to extend the debugbar and add/remove some styles, not guaranteed to keep working.

What are your recommendations on changing the styles in a way that does not affect the application style sheet and lasts after package updates?

I can understand the lack of guarantee. I'll accept it as my own problem.
