### ISSUE TITLE
Error transaction event

### ISSUE THREAD

**Issue by WaterSpout** [barryvdh/laravel-debugbar#622]
Hello, i use Laravel 5.1.* and debugbar ~2.0. When i enable debug and use transaction(`\DB::beginTransaction()`) , i get exception
`Undefined property: Illuminate\\Database\\MySqlConnection::$connection`. After disabled dubug all fine. Help, please

**Comment by Bushikot** [comment]
Hey! I found workaroud for this. Replace `"barryvdh/laravel-debugbar": "dev-master",` with `"barryvdh/laravel-debugbar": "v2.3.0",` in your composer.json and run `composer update`. Seems like this version works fine with Laravel 5.1 transactions.

**Comment by WaterSpout** [comment]
Thanks, works =)

**Comment by barryvdh** [comment]
Never ever use dev-master. You could required the `@dev` version if needed.
