### ISSUE TITLE
Debugbar + Clockwork - FileNotFoundException on some routes

### ISSUE THREAD

**Issue by peppeocchi** [barryvdh/laravel-debugbar#626]
Hi,

the issue it's hard to describe but maybe you can point me to the right direction.

I have both Debugbar and Clockwork loaded into my app.
Something I noticed recently, in some routes clockwork doesn't log any data. Checking the logs, something interesting came up

```
Illuminate\Contracts\Filesystem\FileNotFoundException: File does not exist at path
/......./storage/debugbar/1491918605.5550.1454305797.json

Stack trace:
#0 /...../vendor/barryvdh/laravel-debugbar/src/Storage/FilesystemStorage.php(82): Illuminate\Filesystem\Filesystem->get('/...')
#1 /...../vendor/maximebf/debugbar/src/DebugBar/OpenHandler.php(96): Barryvdh\Debugbar\Storage\FilesystemStorage->get('1491918605.5550...')
#2 [internal function]: DebugBar\OpenHandler->get(Array)
....
```

That's correct, that file doesn't exist, at least not in that location. In fact, that file exists under
```
/......./storage/clockwork/1491918605.5550.1454305797.json
```

This issue **doesn't happen on every route**, until now I can see that happening **only on protected routes**.
If I comment out the `Barryvdh\Debugbar\ServiceProvider::class,` from my `config/app.php` clockwork works as usual.

Does it ring any bell? Do you see any reason why Debugbar is looking for a clockwork file (in the wrong directory)?

#### Info
`Laravel Framework version 5.1.46 (LTS)`
`barryvdh/laravel-debugbar v2.0.6`
`itsgoingd/clockwork v1.13.1`

**Comment by zugoripls** [comment]
I'm also facing that error too but I have no Clockwork in my project.
