### ISSUE TITLE
Just installed debugger and shows 40+ duplicate queries..

### ISSUE THREAD

**Issue by BirdyUK** [barryvdh/laravel-debugbar#627]
Could this be an issue with the latest release or am i lead to believe this is a code issue myside?

I cant see how i am sending 40+ queries to the databses as all i am doing is...

```model::where('id, '=', $id)->get()``` and there is only 1 record in the table?

```
select * from `project_details` where `project_details`.`project_id` = '2943875171' limit 1
280
select * from `project_details` where `project_details`.`project_id` = '2943875171' limit 1
270
select * from `project_details` where `project_details`.`project_id` = '2943875171' limit 1
240
select * from `project_details` where `project_details`.`project_id` = '2943875171' limit 1
260
```

Any advice greatly appreciated on this :)

**Comment by barryvdh** [comment]
Try enabling the back trace option to see if you can find it.
