### ISSUE TITLE
Uncaught TypeError: PhpDebugBar.Widgets.MailsWidget is not a constructor

### ISSUE THREAD

**Issue by thomthom** [barryvdh/laravel-debugbar#628]
Booted up my app on another partition, after installing everything fresh, got an unexpected error:

`Uncaught TypeError: PhpDebugBar.Widgets.MailsWidget is not a constructor`

DebugBar v2.1.1
Laravel v5.2.3
Chrome: 57.0.2987.133

![image](https://cloud.githubusercontent.com/assets/192418/25057067/30598eb6-216d-11e7-81a9-79f391e77e69.png)

I can workaround it by disabling its collector in config, but I was wondering what might cause this? I wasn't able to find any information on this error.

**Comment by devonblzx** [comment]
Seeing this error on Laravel 5.1.46, Debug Bar 2.4.0, on Chrome as well.

**Comment by nWidart** [comment]
Same here.

**Comment by aleksandrlat** [comment]
I had same issue. Browser cache clean worked for me.

**Comment by eaponiente** [comment]
delete cache worked for me as well thanks for that
