### ISSUE TITLE
debug bar is shown no matter what's the .env value

### ISSUE THREAD

**Issue by anddo88** [barryvdh/laravel-debugbar#630]
Not sure about this being debugbar specifically related. On shared host, .env files are not being read and putenv() is disabled with no possibility of enabling it. Replacing the default values of the config file with the $_ENV super global to read from .env files works fine. For example the debug mode instead of

`'debug' => env('APP_DEBUG', false),`

This is used

`'debug' => env('APP_DEBUG', $_ENV['APP_DEBUG']),`

This works fine with other values, and even though I confirmed that `$_ENV['APP_DEBUG']` value is the correct one as in the .env file, the debug bar shows no matter what it is. There is only two situations where debug bar could be turned off,

**1-** When the value of app debug is ZERO in the .env file instead of false. Example
`APP_DEBUG=0`

**2-** When
`'debug' => env('APP_DEBUG', false),`
is used and completely ignoring .env file value since the false is the default value anyway.

**Comment by barryvdh** [comment]
You can't use 'false' in actual environment vars. Those wil be parsed a string and the string 'false' evaluates to true. 0 evaluates to false.

**Comment by anddo88** [comment]
Perfect, thank you
