### ISSUE TITLE
Cannot turn Debugbar  Off with APP_DEBUG ='false'

### ISSUE THREAD

**Issue by dflow** [barryvdh/laravel-debugbar#635]
I cannot turn debugbar off on L5.4 production server
>>> return App::environment();
=> "production"
>>> return env('APP_DEBUG');
=> false
>>> return config('app.debug');
=> false
on config/debugbar.php
'enabled' => false,
I performed php artisan config:cache
nothing helped
thanks

**Comment by StGryphon** [comment]
I have the same problem, can't turn it off in production using the above settings. 
I was able to hide it by setting `'inject' => false,` in config/debugbar.php

**Comment by barryvdh** [comment]
'false' or just false?

**Comment by StGryphon** [comment]
I haven't been using quotes on true/false. None of the other Boolean settings in config/debugbar.php have quotes.

**Comment by barryvdh** [comment]
Ok good, you shouldn't.

Which version of debugbar have you installed?

**Comment by StGryphon** [comment]
v2.3.2 I haven't been playing with production until recently, so I don't know when it started.

**Comment by dflow** [comment]
'enabled' => false,

**Comment by Adroit11** [comment]
Also having the same problem

**Comment by steveheinsch** [comment]
In my AppServiceProvider register(), I just don't register them for production:
```
public function register()
{
    if ($this->app->environment() !== 'production') {
        $this->app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
        $this->app->register(\Barryvdh\Debugbar\ServiceProvider::class);
    }
}
```

**Comment by Mahdi-Sahib** [comment]
Also having the same problem

**Comment by jefferdo** [comment]
php artisan config:cache
