### ISSUE TITLE
Problem with instal 

### ISSUE THREAD

**Issue by SergeySerg** [barryvdh/laravel-debugbar#636]
Problem 1
    - Conclusion: remove laravel/framework v5.0.35
    - Conclusion: don't install laravel/framework v5.0.35
    - barryvdh/laravel-debugbar v2.3.0 requires illuminate/support 5.1.*|5.2.*|5.3.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - barryvdh/laravel-debugbar v2.3.1 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - barryvdh/laravel-debugbar v2.3.2 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.9].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.0.35
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.0.35
    - Installation request for laravel/framework (locked at v5.0.35, required as 5.0.*) -> satisfiable by laravel/framework[v5.0.35].
    - Installation request for barryvdh/laravel-debugbar ^2.3 -> satisfiable by barryvdh/laravel-debugbar[v2.3.0, v2.3.1, v2.3.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by SerafimArts** [comment]
Would you tried to read the error message before writing this issue?
...
