### ISSUE TITLE
php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider" now working

### ISSUE THREAD

**Issue by cristiron** [barryvdh/laravel-debugbar#637]
(used in PhpStorm, command line tool console);
without double quotes it works ok:
php artisan vendor:publish --provider=Barryvdh\Debugbar\ServiceProvider

**Comment by njdubois** [comment]
With vagrant in the CLI, ssh-ed in of course, neither work.

These commands:
php artisan vendor:publish --provider=Barryvdh\Debugbar\ServiceProvider
   -or-
php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"

Both output:
Nothing to publish for tag [].

**Comment by unarmedwombat** [comment]
Ditto. With or without double quotes, returns 'Nothing to publish for tag []'. Vanilla install of Laravel 5.3 on Ubuntu 14.04 / php 7.0
