### ISSUE TITLE
Install not working on Laravel 5.2.45

### ISSUE THREAD

**Issue by starcraft04** [barryvdh/laravel-debugbar#639]
Hi,

I just installed Laravel 5.2.45 with an old software I wrote. It was working fine with Debugbar.

I tried to reinstall everything and I put the folder /var/www/html in write for everyone, I got debugbar version 2.3.2 after composer update. My config file is like this:
    'providers' => [
	
        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
	Collective\Html\HtmlServiceProvider::class,
	Bestmomo\NiceArtisan\NiceArtisanServiceProvider::class,
	Barryvdh\Debugbar\ServiceProvider::class,
        Maatwebsite\Excel\ExcelServiceProvider::class,
        Yajra\Datatables\DatatablesServiceProvider::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Class Aliases
    |--------------------------------------------------------------------------
    |
    | This array of class aliases will be registered when this application
    | is started. However, feel free to register as many as you wish as
    | the aliases are "lazy" loaded so they don't hinder performance.
    |
    */

    'aliases' => [

        'App' => Illuminate\Support\Facades\App::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Config' => Illuminate\Support\Facades\Config::class,
        'Cookie' => Illuminate\Support\Facades\Cookie::class,
        'Crypt' => Illuminate\Support\Facades\Crypt::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
        'Event' => Illuminate\Support\Facades\Event::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Lang' => Illuminate\Support\Facades\Lang::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Password' => Illuminate\Support\Facades\Password::class,
        'Queue' => Illuminate\Support\Facades\Queue::class,
        'Redirect' => Illuminate\Support\Facades\Redirect::class,
        'Redis' => Illuminate\Support\Facades\Redis::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response' => Illuminate\Support\Facades\Response::class,
        'Route' => Illuminate\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,
	'Form'  => Collective\Html\FormFacade::class,
	'Html'  => Collective\Html\HtmlFacade::class,
        'Excel' => Maatwebsite\Excel\Facades\Excel::class,
        'Datatables' => Yajra\Datatables\Facades\Datatables::class,
	'Debugbar' => Barryvdh\Debugbar\Facade::class,
    ],

When I launch the website, I don't see any debugbar and also, by inspecting in chrome, I get the following errors:
GET http://192.168.0.101/public/_debugbar/assets/stylesheets?v=1484813989 
192.168.0.101/:173 
GET http://192.168.0.101/public/_debugbar/assets/javascript?v=1483605979 
(index):173 
GET http://192.168.0.101/public/_debugbar/assets/stylesheets?v=1484813989 
(index):173 
GET http://192.168.0.101/public/_debugbar/assets/javascript?v=1483605979 
(index):175 Uncaught ReferenceError: PhpDebugBar is not defined
    at (index):175
(anonymous) @ (index):175
app.min.js:13 Uncaught TypeError: $ is not a function
    at HTMLDocument.<anonymous> (app.min.js:13)
    at i (jQuery-2.2.0.min.js:2)
    at Object.fireWith [as resolveWith] (jQuery-2.2.0.min.js:2)
    at Function.ready (jQuery-2.2.0.min.js:2)
    at HTMLDocument.J (jQuery-2.2.0.min.js:2)

It is as if it is missing files because it cannot get them.

**Comment by a394867798as** [comment]
Problems can be solved by looking at the logs.

**Comment by bertalanimre** [comment]
Which logs and what is your solution? Laravel doesn't log this error to me.
