### ISSUE TITLE
Measuring memory usage is hard

### ISSUE THREAD

**Issue by fideloper** [barryvdh/laravel-debugbar#640]
I have a weird thing in debugbar where if I refresh a request over and over, the memory usage goes down each time - for a query returning large(ish) amounts of database, this means an original amount of memory used at about 130mb eventually went down to 12mb.

Using xDebug's function `xdebug_peak_memory_usage()` is consistent in it's memory usage (it agrees fairly closely with Debugbar's initial measurement, which was about 130mb, using PHP's `memory_get_peak_usage($real_usage = true);`.

**I'm wondering if:**

1. Anyone would know why the first thing would happen (can anyone replicate that?)
2. Would a PR be acceptable to use xdebug's function if the function exists (and maybe a config option to prefer it over php's built-in function).

From what I can find out, PHP's peak usage appears to multiply the # of memory "chunks" allocated by how large the chunk is, so it's about allocation - I'm wondering if that's related, maybe it does't allocate more chunks of memory in my use case of PHP-FPM only serving a single request at time (from me, in local dev). In that case, I think it's re-using a php-fpm worker process for quite a while before killing itself and creating a new one.

I can't really find good information on what xdebug is using behind the scenes for that function, but it seems more accurate!

**Comment by barryvdh** [comment]
Sorry dont know about 1, but I'm happy to accept a PR for 2. I guess when xdebug is better, there is no reason not to use it when xdebug is loaded, right?

**Comment by fideloper** [comment]
I still want to test this outside of local dev / Docker to see if it behaves the same too, seems like an odd behavior all around!

(I'd also love to find docs/info/anything on how xdebug decides on memory usage to know if it's actually better :P ).

Anyway, no updates here yet, just general thoughts I have on it 🍺

**Comment by edward101992** [comment]
Hello, my name is edward and I want to know how I could store the ram that my application uses in a field of a table in mysql, I would greatly appreciate your answer
