### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by browner12** [barryvdh/laravel-debugbar#644]
love the package, but I can't stand the tediousness of mousing to minimize and maximize the debugbar. (1st world problem, I know 😄 )

I would love to hook into the debugbar's `minimize`, `restore`, and `close` methods, so I can use [Moustrap](https://github.com/ccampbell/mousetrap) to bind some keyboard shortcuts to manipulating the debugbar.

Is it possible to access the javascript debugbar object in an external script?

Thanks!

**Comment by browner12** [comment]
woo hoo! i got it working.

here's the code for those interested.

obviously you can remove the `console.log()`s and use and key binding you'd like 😉 

```php
//debugbar minimize
Mousetrap.bind('d . m i n', function () {
    console.log('minimizing debugbar');
    phpdebugbar.minimize();
});

//debugbar maximize
Mousetrap.bind('d . m a x', function () {
    console.log('maximizing debugbar');
    phpdebugbar.restore();
});

//debugbar close
Mousetrap.bind('d . x', function () {
    console.log('closing debugbar');
    phpdebugbar.close();
});
```

**Comment by decadence** [comment]
Thanks for sharing! Maybe PR?

**Comment by browner12** [comment]
i'm hesitant to PR it, because we'd either have to require/include Mousetrap, or duplicate that functionality.

i'm hesitant to require/include it because it's not really essential to the project.

i'm hesitant to do it ourselves because its relatively complicated, and Mousetrap does such a good job of it already.

other people have thoughts on those options?

**Comment by browner12** [comment]
even cooler, arrow through the tabs

```php
//debugbar tab left
Mousetrap.bind('d left', function () {

    var tabs = [
        'messages',
        'timeline',
        'exceptions',
        'views',
        'route',
        'queries',
        'emails',
        'auth',
        'gate',
        'session',
        'request',
    ];

    var index = tabs.indexOf(localStorage.getItem('phpdebugbar-tab'));

    if (index === 0) {
        var previousTab = tabs.length - 1;
    }

    else {
        var previousTab = index - 1;
    }

    phpdebugbar.showTab(tabs[previousTab]);
});

//debugbar tab right
Mousetrap.bind('d right', function () {

    var tabs = [
        'messages',
        'timeline',
        'exceptions',
        'views',
        'route',
        'queries',
        'emails',
        'auth',
        'gate',
        'session',
        'request',
    ];

    var index = tabs.indexOf(localStorage.getItem('phpdebugbar-tab'));

    if (index + 1 >= tabs.length) {
        var nextTab = 0;
    }

    else {
        var nextTab = index + 1;
    }

    phpdebugbar.showTab(tabs[nextTab]);
});
```

**Comment by barryvdh** [comment]
How hard is this with plain javascript?

**Comment by browner12** [comment]
before I discovered Mousetrap, I did this with jQuery.  simple bindings (1 key) in jQuery are pretty easy, but the key combinations are more difficult. you also need to ensure that input fields don't interact with the key bindings.

```javascript
$(document).ready(function(){
	
	//key binding shortcuts
	$(document).on('keyup', function(e) {
	
		//get tag
		var tag = e.target.tagName.toLowerCase();
		
		//dont execute when focus is on certain elements
		if(tag == 'input' || tag == 'textarea' || tag == 'select' || tag == 'button'){
			return true;
		}
		
		//binding
		switch(e.which){
		
			//s key
			case 83:
                            phpdebugbar.minimize();
                            break;

                        //f key
                        case 70:
                            phpdebugbar.restore();
                            break;
                 }
       }
}
```

Without the key combo stuff, I think you would annoy some people by high-jacking certain keys.

I have no idea how you would do it with plain javascript.

Maybe someone better at javascript than me could help out with this.
