### ISSUE TITLE
Debugbar exception: Data missing

### ISSUE THREAD

**Issue by ale1981** [barryvdh/laravel-debugbar#645]
Laravel 5.4
PHP 7.1
Ubuntu 16.04 LTS

When viewing my login page the debugbar works fine, once I login and view a page I get this message in my laravel log file;

Debugbar exception: Data missing

Any idea?

**Comment by ale1981** [comment]
.. forgot to add that the bar does not load on any pages after logging in when this message is logged.

**Comment by barryvdh** [comment]
No when it encounters an exception in the debugbar itself, it swallows it and that breaks the rendering of debugbar (but continues for the app). Can you post the stacktrace?

**Comment by ale1981** [comment]
Apologies but how do I get a complete stacktrace, the only entry in my log file is;

[2017-06-08 10:28:15] local.ERROR: Debugbar exception: Data missing

**Comment by ale1981** [comment]
Can you let me know what you need to debug this?

**Comment by snapple42** [comment]
I can confirm I am having the exact same issues.. debug bar is present before login,and then after I get:

**local.ERROR: Debugbar exception: Data missing  **

after login.

I've cleared out all routes, caches, etc. I am using "php artisan serve".

**Comment by jthorpe-marco** [comment]
I'm having the same issue as well. I just created a fresh Laravel 5.5 application, added authentication and installed debugbar. It works on my login page but I get the same local.ERROR: Debugbar exception: Data missing as everyone else.

I'm using homestead rather than artisan serve.

**Comment by jthorpe-marco** [comment]
Has anyone had any luck fixing this yet? I've been disabling authentication temporarily to get around it for now, but that's obviously not a great solution.

**Comment by samloft** [comment]
As this issue is still open.... (I know it's old, but just has the same issue).

I'll assume you are using sqlsrv?

This is due to Carbon and SQLSRV date/time fields, data missing is the date/time not having enough data.

You can get around this by adding created_at and updated_at to the protected $hidden on the user model.
