### ISSUE TITLE
Laravel 5.1 - Undefined Property Exception

### ISSUE THREAD

**Issue by tylernathanreed** [barryvdh/laravel-debugbar#647]
For some reason, I keep getting the following error on various requests within my application:

    Undefined property: Illuminate\Database\SqlServerConnection::$connection

This comes from line 351:

    $queryCollector->collectTransactionEvent('Begin Transaction', $transaction->connection);

Where I believe the `$transaction->connection` piece is the problem.

This code was added by commit [506c1eb](https://github.com/barryvdh/laravel-debugbar/commit/506c1ebb9e344ee3f79c04ec30d42b5323671558). A comment for this commit even states that this breaks the 5.1 integration for debugbar.

Until this issue gets fixed, every application on Laravel 5.1 will be required to use 2.3.2.

**Comment by tylernathanreed** [comment]
I've created a [Pull Request](https://github.com/barryvdh/laravel-debugbar/pull/648) to fix this problem.

**Comment by barryvdh** [comment]
Should be fixed then
