### ISSUE TITLE
Undefined property: Illuminate\Database\MySqlConnection::$connection

### ISSUE THREAD

**Issue by neverlandzl** [barryvdh/laravel-debugbar#653]
Laravel 5.2  php 5.6
"barryvdh/laravel-debugbar": "^2.1@dev",
"barryvdh/laravel-ide-helper": "^2.1"

All query used transaction,"Undefined property: Illuminate\Database\MySqlConnection::$connection" appeared! Anyone can tell me how to solve it!

vendor\barryvdh\laravel-debugbar\src\LaravelDebugbar.php#365
 function ($transaction) use ($queryCollector) {
                    $queryCollector->collectTransactionEvent('Rollback Transaction', $transaction->connection);

**Comment by barryvdh** [comment]
Are you on the latest version? Do you have this fix? https://github.com/barryvdh/laravel-debugbar/pull/648/files

**Comment by neverlandzl** [comment]
Yeah,i'm on the latest version!
After i run command "composer update",it apprears! It works as https://github.com/barryvdh/laravel-debugbar/pull/648/files suggested.

**Comment by barryvdh** [comment]
So with the latest update it works?

**Comment by neverlandzl** [comment]
At that time , i was on the latest vesion! But i didn't change when i opened src/LaravelDebugbar.php.
At last , i fix the code as src/LaravelDebugbar.php suggested!

**Comment by MarksGui** [comment]
Thanks.

**Comment by pjrola** [comment]
Has this been fixed? This is still an issue for me. I've replaced 2.2 with 2.4 in my composer.json file and run a `composer update` and I am still receiving an error when trying to save a laravel model.

**Comment by danilosantosdev** [comment]
I'm with the latest version and the error continues. The weird is that the refered file don't have the PR changes.

**Comment by riddles8888** [comment]
This is still happening because the pull request with the fix is not part of a release yet. Using dev-master or version 2.3.2 fixes the issue until a new release is created.

**Comment by barryvdh** [comment]
Tagged v2.4.1,does that fix it?

**Comment by riddles8888** [comment]
That does fix it. Thank you 👍

**Comment by jeinnermarulanda** [comment]
**(2/2) ErrorException
Undefined property: Illuminate\Database\MySqlConnection::$id_catalogo (View: C:\erminventario\inventario\resources\views\bodega\producto\create.blade.php)**

They have some instruction to solve this mistake, I cannot find the solution

Thanks your collaborate
