### ISSUE TITLE
Class name improperly cased in 1.8 branch

### ISSUE THREAD

**Issue by cviebrock** [barryvdh/laravel-debugbar#654]
Debugging an old L4.2 project and I installed this package.  I also use `composer dump-autoload -a -o`, and get the error:

```
Class 'Barryvdh\Debugbar\LaravelDebugBar' not found
```

I think this has to do with the fact that the file is called `LaravelDebugBar.php` but the class is defined as

```php
class LaravelDebugbar extends DebugBar
                  ^
```
The `b` in `bar` should be capitalized, so the class name matches the file name's case.

Does that make sense?

**Comment by barryvdh** [comment]
Yes, can you submit a PR?

**Comment by cviebrock** [comment]
Thanks @barryvdh ! You'll tag a new release at some point (and then close this issue)?

**Comment by barryvdh** [comment]
Yes, tagged v1.8.9
