### ISSUE TITLE
phpinfo collector

### ISSUE THREAD

**Issue by decadence** [barryvdh/laravel-debugbar#658]
I see `phpinfo` collector in config but when it's enabled I don't see any difference as it's disabled.
Where can I see PHP version?

In page source code I see this:
![screenshot_2](https://user-images.githubusercontent.com/1434668/27187844-f3e049d0-51f4-11e7-938c-1655909643bf.png)

**Comment by barryvdh** [comment]
That's actually a good question, never did find that out myself.

**Comment by decadence** [comment]
So that is part of PHP Debug Bar?
But it is also in Laravel Debug Bar config so it should do something :)

**Comment by decadence** [comment]
Today I installed Laravel 5.5 with Debugbar from `master` and this collector shows PHP version.
I don't understand why it doesn't always work.
![screenshot_3](https://user-images.githubusercontent.com/1434668/28563735-829b071a-712f-11e7-9413-a9d2a012eec0.png)

**Comment by barryvdh** [comment]
Oh that is because I fixed it ;)

**Comment by decadence** [comment]
Haha, thanks :) I didn't know that.

**Comment by aik099** [comment]
@barryvdh , would the version with a fix be released?

**Comment by aik099** [comment]
I've found that it was fixed in https://github.com/maximebf/php-debugbar/commit/1fd5af226f2554819569d1dcebc6b8f1b60b09c5 commit of https://github.com/maximebf/php-debugbar project, but wasn't released yet.
