### ISSUE TITLE
Debugbar stopped appearing : complain of provider error

### ISSUE THREAD

**Issue by cwcrawley** [barryvdh/laravel-debugbar#659]
We've been using the debugbar in our application for the past few months - however, a few days ago - with no reason/evidence, the debugbar is now not loading and we've got the following error in our log file:

`local.ERROR: Debugbar exception: Authentication user provider [] is not defined`

Anyone able to point at what the solution could be? Nothing else appears not to be working on our application.

**Comment by barryvdh** [comment]
Can you disable the Auth collector?

**Comment by silencechow** [comment]
I have got the same error too.

**Comment by cwcrawley** [comment]
Sorry, for some reason I didn't get a notification of a comment! I've tried that and hasn't made any difference.
