### ISSUE TITLE
Command "debugbar:publish" is not defined 

### ISSUE THREAD

**Issue by dborovsky** [barryvdh/laravel-debugbar#664]
Hello

When run command **php artisan debugbar:publish** get error:

```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "debugbar:publish" is not defined.                      
  Did you mean one of these?                                      
      vendor:publish                                              
      debugbar:clea
```    

My env is local. I registered the debugbar serviceprovider in app.php.  

Laravel v. 5.3

**Comment by xaviermarchegay** [comment]
If you want to publish the config file, the correct command is : 

`php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"`
