### ISSUE TITLE
I can't enable Debugbar when I set DEBUGBAR_ENABLED as false in config.

### ISSUE THREAD

**Issue by codeh2o** [barryvdh/laravel-debugbar#668]
I want to disable the Debugbar by default.and enable it when I need it.
so I set  enabled  to false in **config/debugbar.php**.(Debugbar works properly when I set it as null or true);
`'enabled' => env('DEBUGBAR_ENABLED', false)`

and call **Debugbar::enable();** in a controller.but it seems DEBUGBAR didn't work.
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;


class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       \Debugbar::enable();
        var_dump("dsa");
    }

}

```

otherwise,If I set **DEBUGBAR_ENABLED** to **true**,and call **\Debugbar::disable();** in the controller.
it works good and the debugbar won't pop up.

but If I set **DEBUGBAR_ENABLED** to **false**,and call **\Debugbar::enable();** in the controller.
it works incorrectly.and I can't turn on debug bar.

```
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "barryvdh/laravel-debugbar": "^2.4"
    },
```

debugbar is really useful to me and I love it.
so I have to seeking for helping .
thank you for reading.

**Comment by dinhquochan** [comment]
Me too, but i use Laravel 5.5 dev. Try, auto discovery and manual, `DEBUG=true` in `.env`, `'debug' => true` in `app.php`, `'enabled' => true` in `debugbar.php` but still not working. Someone like me. Not show, not log, but Artisan has command: `debugbar:clear` but type it show error:

```
[ReflectionException]
  Method Barryvdh\Debugbar\Console\ClearCommand::handle() does not exist
```

cc @barryvdh

**Comment by dinhquochan** [comment]
Here, only show when whoops (I just delete encrypt key). Problem in Laravel 5.5 ?

![screen shot 2017-08-06 at 23 19 18](https://user-images.githubusercontent.com/9979458/29005085-d4777af0-7afd-11e7-9a0a-4f550e4d6509.png)
![screen shot 2017-08-06 at 23 19 27](https://user-images.githubusercontent.com/9979458/29005086-d47b6462-7afd-11e7-818c-7a3296ed1d15.png)

**Comment by nasirkhan** [comment]
facing same issue. did you find any workaround?

**Comment by alannaidon** [comment]
I'm also unable to use it.

**Comment by laurenceHR** [comment]
I have same problem on Laravel 5.2

**Comment by anibalealvarezs** [comment]
I haven't tested the "config / false" case but, if calling ```Debugbar::disable();``` works when setting the debug bar enabled in config, then move it to the "boot" method of your app's Service Provider to make sure that it stops before starting collecting, and prevent overheating (if that's the problem to want to prevent).

You can also put it in a middleware that wraps all the routes, so you make sure that it runs before any controller.

Then, you can re-enable it whenever you want.
