### ISSUE TITLE
ServiceProvider name

### ISSUE THREAD

**Issue by lk77** [barryvdh/laravel-debugbar#673]
Hello,

the class ServiceProvider is wrongly named, it should be DebugbarServiceProvider, the ServiceProvider class should always be Illuminate\Support\ServiceProvider.

Are you planning to fix this soon ?

i know i can do 
```use Barryvdh\Debugbar\ServiceProvider as DebugbarServiceProvider```
but it's not very elegant.

thanks

**Comment by barryvdh** [comment]
Nope and it is also not true
