### ISSUE TITLE
Problems with Axios?

### ISSUE THREAD

**Issue by 1e4** [barryvdh/laravel-debugbar#674]
I have been using Axios in a few projects and it doesn't seem that Debugbar picks up any of these requests. Switching to using $.ajax and the Debugbar captures the request.

Has anyone had this issue before (I searched and couldn't find an issue but still..)?

**Comment by jbbr** [comment]
I don't think debugbar hooks into axios. I would also be interested in a solution for Axios+Debugbar though.
Probably one would have to call some function of the global JS object `PhpDebugBar.AjaxHandler` from an axios interceptor.

**Comment by 1e4** [comment]
Hmm I see, I'll take a look later into it and get back to you if I get anywhere.

**Comment by barryvdh** [comment]
Yeah similar to how laravel echo does it.

**Comment by eblanshey** [comment]
Has anyone figured this out for axios? I remember playing with it a while back and not succeeding.

**Comment by sakibulalam** [comment]
any update on this? I can confirm that the axios requests are captured and logged. It correctly shows up in the dataset switcher modal (the folder icon on the far right) but the select dropdown is not triggered/shown for the latest request.

**Comment by frdteknikelektro** [comment]
I'm facing this problem to, and I use this.

```
axios.interceptors.response.use( (response) => { phpdebugbar.ajaxHandler.handle(response.request); return response; });
```

**Comment by tnorthcutt** [comment]
@frdteknikelektro I'm not familiar with axios interceptors - would you mind sharing where you use that code?
