### ISSUE TITLE
Laravel Horizon breaks if Debugbar is loaded first and collects mail

### ISSUE THREAD

**Issue by fredlahde** [barryvdh/laravel-debugbar#682]
If the debugbar service provider is loaded before the horizon package and the mail collector is set to true, horizon breaks.

In `Laravel\Horizon\WaitTimeCalculator@timeToClearFor()` Horizon tries to get a `Laravel\Horizon\RedisQueue` to call `readyNow()` on it. For some reasons, it get's a `Illuminate\Queue\RedisQueue` instead, which does not offer this method.

This leads to the following exception: `Call to undefined method Illuminate\Queue\RedisQueue::readyNow() `

Surprisingly, this only happens when:

a) The debugbar Service provider is loaded BEFORE horizon
b) The mail collector is activated

Versions:

Laravel dev-master @ 2876087527
Debugbar dev-master @ d2c6e2cb3c
Horizon 0.1.0 

If you need further assistance in debugging this, im happy to provide more info.

**Comment by barryvdh** [comment]
And I can debug this with a clean install op 5.5 with horizon and debugbar?

**Comment by fredlahde** [comment]
Yes

**Comment by barryvdh** [comment]
Submitted a PR upstream. Can you try it out?

**Comment by fredlahde** [comment]
Tried it.

Solves the issue completely for me. Good job!
