### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by belipero** [barryvdh/laravel-debugbar#685]
Hi! I'm running the installation with _**composer require barryvdh/laravel-debugbar**_ but I recieve the following error message:

Using version ^2.4 for barryvdh/laravel-debugbar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

  **[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found**

Script php artisan optimize handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

Does anyone recieved the same error message?

Regards

**Comment by barryvdh** [comment]
Seems to be an error about the ide helper, not debugbar?
