### ISSUE TITLE
Stop "request" dropdown from auto switching?

### ISSUE THREAD

**Issue by ben-shepherd** [barryvdh/laravel-debugbar#689]
On the top right of the debugbar, the dropdown that contain all the requests switches whenever there is a new ajax call. Is there anyway to prevent this?

It has made it very difficult to debug because it moves me away from where I am looking when there is a new request. 

Here is a screenshot of where I mean:
https://i.gyazo.com/ca8b4b28621620d1b12ea81304b31501.png

**Comment by decadence** [comment]
https://github.com/barryvdh/laravel-debugbar/issues/670

**Comment by ben-shepherd** [comment]
@decadence  Ah perfect. Thank you
