### ISSUE TITLE
Make backtrace on Queries tab more usable

### ISSUE THREAD

**Issue by aik099** [barryvdh/laravel-debugbar#692]
For every executed query I'm seeing this:

<img width="1435" alt="2017-08-15_0825" src="https://user-images.githubusercontent.com/1277526/29303175-88c575f2-8193-11e7-899f-8b3e2d79ba65.png">

Obviously this is 1st line in backtrace. What I think is best to gather line, that was first before any Eloquent code was executed (means who triggered db query call).

**Comment by decadence** [comment]
How can I enable backtrace?
Debugbar shows me only bindings.

![image](https://user-images.githubusercontent.com/1434668/29366213-12eb6322-82a2-11e7-8f00-cf893413e3f8.png)

**Comment by aik099** [comment]
I've debugged a bit and the issue comes from `QueryCollector` class (see https://github.com/barryvdh/laravel-debugbar/blob/2.4/src/DataCollector/QueryCollector.php#L223), where all code coming from `vendor/laravel/framework` is excluded.

This ends up badly for queries coming from framework itself, e.g. loading session or user record. Instead of excluding whole framework we should exclude folder where all DB-related code lives (e.g. Eloquent) so that framework calls to database would also be included.

**Comment by aik099** [comment]
> How can I enable backtrace? Debugbar shows me only bindings.

@decadence , it's enabled by default, but maybe you've disabled it in `/config/debugbar.php` file.

**Comment by decadence** [comment]
@aik099 Thanks!
That was disabled. I think I use old version when it was disabled by default.
