### ISSUE TITLE
Can't see BeforeFilter() when using Route::resource with filters in __construct

### ISSUE THREAD

**Issue by ErikVermeij7T** [barryvdh/laravel-debugbar#7]
Thanks, barryvdh.

I'm using your debugbar when developing my site. It's a nice piece of code and very handy.

But enough chitchat, here's the issue. I'm using a Controller and added it to my Routes.php like so:

```
Route::resource('dashboard/gebruikers', 'GebruikersController');
```

In the controller i have a __construct function like so:

```
public function __construct()
{
    $this->beforeFilter('dashboard');
    $this->beforeFilter('csrf', array('on' => array('put','post')));
}    
```

But now i don't see the BeforeFilter() in tab Route from the Debugbar. Please be aware that i refer to the first 'run' (if you could call it like that), the 'put' method, because it has to check the csrf-token.

I hope this helps making Debugbar an even better tool.

**Comment by manoucheka** [comment]
Some one can help me please 

public function __construct() {
   $this->beforeFilter('csrf',array('on'=>'post'));
                                  }
method is not working in my UsersController.php in laravel 5.5
