### ISSUE TITLE
Display debugbar only to certain users? L5.4

### ISSUE THREAD

**Issue by younus93** [barryvdh/laravel-debugbar#700]
Is there any way that I can set the Debugbar to enabled only for certain users?

**Comment by aik099** [comment]
In your service provider's `boot` method:

1. decide if user can see it
2. do `config(['app.debug' => $condition])` or `config(['debugbar.enabled' => $condition])`

**Comment by aik099** [comment]
Just tried disabling `app.debug` setting from middleware and it had no effect.

**Comment by aik099** [comment]
I think, that we should move code for enabling debug bar into middleware so that anybody could undo enabling instead of enabling right from service provider.
