### ISSUE TITLE
[Suggestion] Query sort resource 

### ISSUE THREAD

**Issue by webmailcontatos** [barryvdh/laravel-debugbar#701]
In my company I create a query sort resource,
Very useful for query analysis. It is possible to order by execution time and by query,
What do you think of a pull request with this functionality?
https://user-images.githubusercontent.com/11367804/29324164-8f1c315e-81b9-11e7-8be4-846c9aba0a9f.png

**Comment by salarmehr** [comment]
@webmailcontatos  Is there any PR for this?

**Comment by webmailcontatos** [comment]
@salarmehr Yes

**Comment by salarmehr** [comment]
@webmailcontatos Do you have a link? Is there any reason that it's not been merged?

**Comment by webmailcontatos** [comment]
If  want i can send pr to PHP Debug Bar project

**Comment by salarmehr** [comment]
That would be great

**Comment by webmailcontatos** [comment]
Done! 
The pr number is 410 and title is "New feature order result queries"
@salarmehr
