### ISSUE TITLE
 [Suggestion] Copy query to clipboard resource 

### ISSUE THREAD

**Issue by webmailcontatos** [barryvdh/laravel-debugbar#702]
Create feature in my company, copy query to clipboard :

![image](https://user-images.githubusercontent.com/11367804/29283467-302b696a-80fd-11e7-858a-ba20beef70bd.png)
![image](https://user-images.githubusercontent.com/11367804/29283479-40ad9146-80fd-11e7-8a92-e2d1da3c5323.png)
This feature in laravel debug bar would be very useful

**Comment by aik099** [comment]
Don't you already have this functionality - the copy icon next to each query?

Also the "Database" panel looks very different from default "Queries" panel. Do you use some custom plugin for that?

**Comment by webmailcontatos** [comment]
This image just sample, I use maximebf/debugbar. But i believe this functionality is useful for laravel debug too

**Comment by webmailcontatos** [comment]
What do you think of a pull request with this functionality? @aik099

**Comment by aik099** [comment]
It depends:

* if you occasionally copy queries, then adding copy/paste button next to each query would only make interface harder to use
* if you copy/paste a lot, then it probably is useful

If this is implemented as option, that is disabled by default then why not.

**Comment by antonioribeiro** [comment]
I'm copying them a lot lately, an option would be great :)

**Comment by webmailcontatos** [comment]
@antonioribeiro Idéia de Brasileiro kkk

**Comment by AMoktar** [comment]
That will be very helpful, laravel-debugbar is a debugging tool after all
I hope you add it 
Thanks

**Comment by cweiske** [comment]
This feature has been added in 2020-08 with commit b67283a1009ee9fdda95047638ee97aef3c20a2e.
To enable it, put `options.db.show_copy = true` into `config/debugbar.php`.

**Comment by barryvdh** [comment]
I think it's enabled always now.
