### ISSUE TITLE
Enable "Twig" collector

### ISSUE THREAD

**Issue by aik099** [barryvdh/laravel-debugbar#703]
I see, that "PHP Debug Bar" has Twig collector (see http://phpdebugbar.com/docs/bridge-collectors.html#twig), but I have no idea how to enable it considering, that I'm already using https://github.com/barryvdh/laravel-twigbridge .

I'm not sure what that collector does, because I've found no screenshots, but maybe it's already covered in TwigBridge itself.

**Comment by barryvdh** [comment]
It's not good, so not really useful. Also, twig integrates with the view collector.

**Comment by aik099** [comment]
Thanks for explaining. Closing.

**Comment by barryvdh** [comment]
I do want to create a useful one sometimes, but that should use the new profiler stuff in twig.
