### ISSUE TITLE
Not working on Laravel 5.4 / Wampserver

### ISSUE THREAD

**Issue by drickferreira** [barryvdh/laravel-debugbar#704]
I created a fresh laravel instalation and getting this error in console:
```
Uncaught SyntaxError: Unexpected token <
localhost/:84 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost/vale/_debugbar/assets/stylesheets?v=1503531012".
(index):84 Uncaught ReferenceError: jQuery is not defined
    at (index):84
(anonymous) @ (index):84
(index):86 Uncaught ReferenceError: PhpDebugBar is not defined
    at (index):86
(anonymous) @ (index):86
```
I search and try any solutions but nothing works for me...

**Comment by barryvdh** [comment]
Check if the asset URLs are working. Also see the note about catch all routes.

**Comment by drickferreira** [comment]
It was a problem with htaccess.
Solved and working now. Thanks.

**Comment by amitozdeol** [comment]
How did you solve it?

**Comment by drickferreira** [comment]
My project root is "/var/www/html/rastreador"

I made changes below on .htaccess and works.

/var/www/html/rastreador/.htaccess
> RewriteEngine On
> RewriteBase /rastreador/
> RewriteCond %{REQUEST_FILENAME} -s [OR]
> RewriteCond %{REQUEST_FILENAME} -l [OR]
> RewriteCond %{REQUEST_FILENAME} -d
> RewriteRule ^.*$ - [NC,L]
> RewriteRule ^.*$ index.php [NC,L]

/var/www/html/rastreador/public/.htaccess
> \<IfModule mod_rewrite.c>
>     \<IfModule mod_negotiation.c>
>         Options -MultiViews
>     \</IfModule>
> 		Options -Indexes
>     RewriteEngine On
> 
>     # Redirect Trailing Slashes If Not A Folder...
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteRule ^(.*)/$ /$1 [L,R=301]
> 
>     # Handle Front Controller...
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteCond %{REQUEST_FILENAME} !-f
>     RewriteRule ^ index.php [L]
> \</IfModule>
