### ISSUE TITLE
Make 2.4.x release with 1.14 version of php-debugbar

### ISSUE THREAD

**Issue by aik099** [barryvdh/laravel-debugbar#706]
Please make 2.4.x release, that is compatible with Laravel 5.4 and is using php-debugbar 1.14 version with latest fixes (e.g. showing used PHP version).

**Comment by barryvdh** [comment]
Van you test and make a Pr?

**Comment by aik099** [comment]
I would if I know how to even install it.

The only way to test it would on real Laravel app, but when I try to change my `composer.json` to use 1.14 version of php-debugbar, then I get Composer error because laravel-debugbar requires 1.13 specifically.

Theoretically the 1.14 release shouldn't be a BC break compared to 1.13 unless same versioning scheme as in Laravel is used 😄

**Comment by barryvdh** [comment]
You could probably require dev-master as 1.13 perhaps as inline alias? 
Otherwise will try after Laracon. Think it probably will work.

**Comment by aik099** [comment]
I've added `"maximebf/debugbar": "1.14.0 as 1.13.0",` to `composer.json` and `composer update` worked.

After that debug bar worked as well. No fatal errors at least. All data seems to be displayed correctly. I saw some formatting changes, but nothing critical.
