### ISSUE TITLE
QueryCollector execution time exceeded

### ISSUE THREAD

**Issue by corbosman** [barryvdh/laravel-debugbar#709]
I get the following error on laravel 5.4 with the latest 5.4 capable debugbar version:

[2017-08-30 14:37:14] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in /Users/cor/Vagrant/sites/portal/vendor/barryvdh/laravel-debugbar/src/DataCollector/QueryCollector.php:120

The debug_stacktrace contains an endless series of 0=>0 index/stack elements. This is seemingly caused by having a $with = [...] on my User model to automatically always load a relation on the user model.  When I remove the $with the problem disappears. 

Without the debugbar I have no issues with the code that is failing with the debugbar.

**Comment by barryvdh** [comment]
Can you disable the back trace option in the config? Probably need to add some limit to the depth.

**Comment by corbosman** [comment]
Disabling the back trace option prevents the maximum execution time issue from appearing.

**Comment by barryvdh** [comment]
Can you pass a limit in the debug_backtrace function here? https://github.com/barryvdh/laravel-debugbar/blob/5b321c05cdd0b480315b173af8150473ab96e806/src/DataCollector/QueryCollector.php#L188
Does it still happen when it's 50?
`$stack = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS | DEBUG_BACKTRACE_PROVIDE_OBJECT, 50);`

**Comment by barryvdh** [comment]
Added that.

**Comment by joefreire** [comment]
that's possible i set the value on config?
in my case 50 is high
