### ISSUE TITLE
Migrating from L54 -> L55 resources not loading

### ISSUE THREAD

**Issue by mikeerickson** [barryvdh/laravel-debugbar#715]
can't for the life of me figure out what is going on here. I have seen this before, but don't recall exactly what I did to eradicate the error.

- I have completely removed debugbar
- I have reinstalled debugbar
- I have cleared cache
- I have confirmed jquery is installed 

![image](https://user-images.githubusercontent.com/183153/30006730-5503aec0-90b4-11e7-8881-f6b2ae9ecaaa.png)

**Comment by barryvdh** [comment]
Ordering of the service providers perhaps. Now they're autoloaded, perhaps some is registering a catch-all route earlier on?

**Comment by marsoltys** [comment]
I've got this case.

Debugbar and another package which got catch-all route are autoloaded.
Debugbar was added later so I'm assuming that it is loaded after catch-all package.

What would be solution for that ? 

Should I add debugbar as before "discovery" age ?

**Comment by mikeerickson** [comment]
@marcorivm Yes, that is what I had to do (install the old fashioned way, not auto discovery), I made sure it was loaded first and all worked fine.

**Comment by marsoltys** [comment]
In my situation I've replaced 'catch all' route with `Route::fallback()`
