### ISSUE TITLE
Easy way to disable debugbar on certain routes / groups / controllers

### ISSUE THREAD

**Issue by Megachill** [barryvdh/laravel-debugbar#717]
Is there an easy way to completely disable debugbar for certain routes either via routes or controller etc? We need to disable in order for us to test properly our API functionality and for those we def do not want debugbar added to every response.

For example android oauth completely breaks when there is debugbar html on the response we are sending to the android clients. 

So suggestion would be something along the lines of 

`Debugbar::disable();`

**Comment by Megachill** [comment]
Ok so after a lot of research it seems that by using 

`app('debugbar')->disable();`

it'll actually disable properly without issues. I just used it on Laravel 5.5 and worked like a charm.

**Comment by bkuhl** [comment]
This disabling isn't working for me.

**Comment by lionnelpat** [comment]
Hello,  I also use  `app('debugbar')->deisable();`  and it work fine for me! 
Thank's @Megachill

**Comment by jonaswebdev** [comment]
> Hello, I also use `app('debugbar')->deisable();` and it work fine for me!
> Thank's @Megachill

I think you tried to say `disable()`(misspelling fixed) :)

Worked for me too, thanks!

**Comment by iqionly** [comment]
This working fine, just put in your route and works like a charm
Thank's @Megachill
