### ISSUE TITLE
something wrong in laravel5.5

### ISSUE THREAD

**Issue by caicaizi251** [barryvdh/laravel-debugbar#720]
it says：
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Argument 1 passed to Illuminate\Auth\TokenGuard::__construct() must implement interface Illuminate\Contracts\Auth\UserProvider, null given, called in E:\..............\vendor\laravel\framework\src\Illuminate\Auth\AuthManager.php on line 159

**Comment by aik099** [comment]
DebugBar just shows you the error. It seems, that there is something wrong in your application, not DebugBar.

**Comment by caicaizi251** [comment]
yes,,,I know the reason ，that's what you say! I must add 
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
in config/auth.php providers,,,,,I  deleted it a few days ago

**Comment by ajaaleixo** [comment]
Hi,
sorry for commenting on a closed issue but I've ran in to this exact issue now.
It seems that debugbar is using by default the "users" provider. In my case, I'm not using users but rather other table and model as my user..
would it be a good idea to check that dependency out?
thanks

**Comment by ajaaleixo** [comment]
@ahmad-sa3d thanks! 
I'm bypassing this issue by simply using the default providers config for "users".. although I'm not using that config anywhere.. it runs perfectly fine but the dependency shouldn't exist, I suppose.

**Comment by barryvdh** [comment]
Can you create a PR?

**Comment by bharat-logisticinfotech** [comment]
there may also need to check with config if your provider is different than `users`; check `config.auth.passwords`

**Comment by emotality** [comment]
Having the same issue, deleted User model as I'm using Admin, This, That etc as each have different roles and nothing alike.

Any solution yet?

Baie dankie! 😊

**Comment by emotality** [comment]
Fixed, the issue was in my `config/auth.php` file:

    'api' => [
        'driver'   => 'token',
        'provider' => 'users', // <-- Here: 'usesr' provider doesn't exist as I deleted it
    ],
