### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by MRZ2017** [barryvdh/laravel-debugbar#724]
Hi! I'm running the installation with composer require barryvdh/laravel-debugbar (so code: composer require barryvdh/laravel-debugbar --dev) but I recieve the following error message:
`composer require barryvdh/laravel-debugbar --dev
Using version ^3.0 for barryvdh/laravel-debugbar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.3.31
    - Conclusion: don't install laravel/framework v5.3.31
    - barryvdh/laravel-debugbar v3.0.0 requires illuminate/session 5.5.x -> satisfiable by illuminate/session[v5.5.0, v5.5.2].
    - barryvdh/laravel-debugbar v3.0.1 requires illuminate/session 5.5.x -> satisfiable by illuminate/session[v5.5.0, v5.5.2].
    - don't install illuminate/session v5.5.0|don't install laravel/framework v5.3.31
    - don't install illuminate/session v5.5.2|don't install laravel/framework v5.3.31
    - Installation request for laravel/framework (locked at v5.3.31, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.31].
    - Installation request for barryvdh/laravel-debugbar ^3.0 -> satisfiable by barryvdh/laravel-debugbar[v3.0.0, v3.0.1].

Installation failed, reverting ./composer.json to its original content.
`
How fix problem and install?

**Comment by aik099** [comment]
Which version of DebugBar you're trying to install on which version of Laravel?

**Comment by MRZ2017** [comment]
yes!Its done!Thanks very much! I'm running the installation with composer require barryvdh/laravel-debugbar v2.4.0

**Comment by aik099** [comment]
@MRZ2017 , does it mean that all is working correctly for you now? If so, the please close the issue on GitHub.
