### ISSUE TITLE
Cache values not escaped

### ISSUE THREAD

**Issue by Broutard** [barryvdh/laravel-debugbar#729]
When `options.cache.values` is activated and a cache value contains some HTML (a <script> tag in my case), the value seems to no be escaped... and causes troubles.

`$this->getDataFormatter()->formatVar($event->value)` don't escape value.

`htmlspecialchars($this->getDataFormatter()->formatVar($event->value))` sould do the trick.

**Comment by barryvdh** [comment]
Can you create a PR?
