### ISSUE TITLE
Issues with Read Only Database

### ISSUE THREAD

**Issue by benyanke** [barryvdh/laravel-debugbar#732]
I'm getting issues of Debugbar trying to write to my database when one of my DB connections is read only.

Is there a way to keep as much as possible of the bar running, but disable DB writes, or direct them to another location?

**Comment by barryvdh** [comment]
Debugbar shouldn't write to the database. Can you see what it's writing?

**Comment by benyanke** [comment]
I'll be digging a bit and let you know what I find.

**Comment by sirfanqadir** [comment]
Simple i used the $pdf->setEncryption('', '', array('print')); so end user can print but can not Edit  (Readonly)...
