### ISSUE TITLE
How to disable it in API Routes ? 

### ISSUE THREAD

**Issue by kjhatis** [barryvdh/laravel-debugbar#734]
\Debugbar::disable(); Didn't worked!

![debg](https://user-images.githubusercontent.com/24405562/31216235-8a52b10e-a9d0-11e7-938f-890b964e0a1c.PNG)

**Comment by barryvdh** [comment]
https://github.com/barryvdh/laravel-debugbar/blob/master/config/debugbar.php#L19

Set except to `api*`

But this shouldn't happen if you set your headers correctly. The debugbar is not appended on XHR requests or when the response is json. Are you sending the correct content type?

**Comment by kjhatis** [comment]
Yes i am Using POST, Sending JSON input and returning JSON data in responce!  where to set `api*`

**Comment by murrant** [comment]
Dang, I'm stuck on 2.4.  I'm porting a rough api to laravel.  Users don't always request return type (aka could be html).
