### ISSUE TITLE
Debugbar not displayed on php7.1+lumen5.5+dingo api

### ISSUE THREAD

**Issue by hookover** [barryvdh/laravel-debugbar#740]
composer.json
```
    "require": {
        "php": ">=7.0",
        "laravel/lumen-framework": "5.5.*",
        "illuminate/mail": "^5.5",
        "illuminate/redis": "^5.5",
        "vlucas/phpdotenv": "~2.2",
        "dingo/api":"1.0.*@dev",
        "tymon/jwt-auth": "1.0.0-rc.1",
        "guzzlehttp/guzzle": "~6.0",
        "predis/predis": "^1.1",
        "palanik/lumen-cors": "dev-master",
        "laravelista/lumen-vendor-publish": "^2.1",
        "appzcoder/lumen-routes-list": "^1.0",
        "league/flysystem": "^1.0",
        "ramsey/uuid": "^3.7",
        "overtrue/laravel-lang": "~3.0",
        "targetliu/phpredis": "^1.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~6.0",
        "mockery/mockery": "~0.9",
        "barryvdh/laravel-debugbar": "^3.1"
    },
```

bootstrap.php
```
$app->configure('debugbar');
$app->register(Barryvdh\Debugbar\LumenServiceProvider::class);
```

public/index.php
`
     $app->run();
`
---------INDEX RESULT------------
view-source:api.test.com
Lumen (5.5.2) (Laravel Components 5.5.*)

public/index.php
`
$app->run($app['request']);
`
---------INDEX RESULT------------

Lumen (5.5.2) (Laravel Components 5.5.*)<link rel='stylesheet' type='text/css' property='stylesheet' href=
**'//:/_debugbar/assets/stylesheets?v=1505741566'**
><script type='text/javascript' src=
**'//:/_debugbar/assets/javascript?v=1505741566'**
></script><script type="text/javascript">jQuery.noConflict(true);</script>
--
  | <script> Sfdump = window.Sfdump \|\| (function (doc) { var refStyle = doc.createElement('style'), rxEsc = /([.*+?^${}()\|\[\]\/\\])/g, idRx = /\bsf-dump-\d+-ref[012]\w+\b/, keyHint = 0 <= navigator.platform.toUpperCase().indexOf('MAC') ? 'Cmd' : 'Ctrl', addEventListener = function (e, n, cb) { e.addEventList
.......

**Comment by EugeneRush** [comment]
add to .env
DEBUGBAR_ENABLED=true

**Comment by barryvdh** [comment]
Any errors in the logs?

**Comment by TranThach89** [comment]
you see https://github.com/barryvdh/laravel-debugbar/issues/252
