### ISSUE TITLE
Class 'App\Http\Controllers\Debugbar' not found

### ISSUE THREAD

**Issue by cutigersfan** [barryvdh/laravel-debugbar#742]
I *think* I've RTFM and followed directions, but still get this error. I added:

`'Debugbar' => Barryvdh\Debugbar\Facade::class,`

to the config/app.php as the last entry in 'aliases' array.

I copied and pasted the 
`Debugbar::warning('Watch out…');`
command to my controller.

Using Laravel 5.5.

**Comment by decadence** [comment]
\Debugbar::warning

**Comment by cutigersfan** [comment]
That did it, thanks.
