### ISSUE TITLE
Cannot add AuthCollector to Laravel Debugba

### ISSUE THREAD

**Issue by jingling0101** [barryvdh/laravel-debugbar#744]
Cannot add AuthCollector to Laravel Debugbar: array_keys() expects parameter 1 to be array, null given
/var/www/html/work/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#450
Exception

lumen5.5.2  php7.1.10 linux

**Comment by EugeneRush** [comment]
+1

**Comment by barryvdh** [comment]
Does https://github.com/barryvdh/laravel-debugbar/commit/d5c46b6a51b2773c6c8fbd149517a7719f4ff1f7 fix it?
