### ISSUE TITLE
Not working using Eloquent API resources

### ISSUE THREAD

**Issue by DiederikvandenB** [barryvdh/laravel-debugbar#746]
Hi!

We started using Laravel 5.5's new [API resources](https://laravel.com/docs/5.5/eloquent-resources). Unfortunately though, the bar does not show up for these routes.

Is there any way to enable it for these routes?

Cheers!

**Comment by barryvdh** [comment]
The debugbar cannot inject into JSON, as it would create invalid json syntax.
