### ISSUE TITLE
Named Parameter Reuse

### ISSUE THREAD

**Issue by sonnysavage** [barryvdh/laravel-debugbar#748]
I have Emulation Mode turned on for MySQL, specifically so I can reuse named parameters.

```php
PDO::ATTR_EMULATE_PREPARES => true,
```

In the Debugbar query output, only the first instance of each named parameter has the values injected. The following instances are untouched. Fixing this seems like it would be as simple as changing a replace call from just the first to all instances, but I haven't located that portion of the code.

**Comment by barryvdh** [comment]
Probably here: https://github.com/barryvdh/laravel-debugbar/blob/d5c46b6a51b2773c6c8fbd149517a7719f4ff1f7/src/DataCollector/QueryCollector.php#L103-L114
Pr's welcome
