### ISSUE TITLE
Wrong documentation?

### ISSUE THREAD

**Issue by noesnaterse** [barryvdh/laravel-debugbar#751]
Hello,

The docs say you install it by:
`composer require barryvdh/laravel-debugbar --dev`
I think the `--dev` should not be there.

This is because it also states that you need to add `Barryvdh\Debugbar\ServiceProvider::class,` to your providers array.
While this is fine if you run 5.5 (I guess), it breaks on production sites running Laravel <5.5.

My guess would be that for earlier versions of Laravel 5.5 you need to do `composer require barryvdh/laravel-debugbar` because then it can actually find `Barryvdh\Debugbar\ServiceProvider::class` on production.

Right?

**Comment by barryvdh** [comment]
Yes, but it's still suggested only to enable it in dev.
The docs are for the latest version, for older versions, check the readme of that version.
