### ISSUE TITLE
FileNotFoundException File does not exist at path /mypath/storage/debugbar/540f2a7343ed95ee6ddaf6e64cac9b96.json

### ISSUE THREAD

**Issue by Farris27** [barryvdh/laravel-debugbar#752]
hi, 

When i go in my network browser , i have this error... 

`

FileNotFoundExceptionFile does not exist at path /Applications/MAMP/htdocs/paumelle_test_panier_moi_meme/storage/debugbar/540f2a7343ed95ee6ddaf6e64cac9b96.json
--
in Filesystem.php (line 41)

`

it's possible a conflict with a other package(generalabs/drips)? 

In my storage, i have the folder debugbar and many json files in this folder..

**Comment by barryvdh** [comment]
Not sure, check your permissions etc.

**Comment by hatamiarash7** [comment]
Same problem, any solution ?

**Comment by codehimanshu** [comment]
I am also facing the same isue.

![screenshot 2019-03-02 at 5 41 51 pm](https://user-images.githubusercontent.com/14791631/53681643-82857200-3d12-11e9-9654-d93baffa7fde.png)

**Comment by ahmadsyamim** [comment]
i solved this by 

chmod -R 777 storage/debugbar

**Comment by Edd-brother** [comment]
> i solved this by
> 
> chmod -R 777 storage/debugbar

Thanks. You saved my time from this error. Cool. Lol
Good luck buddy.

**Comment by Salman-Sali** [comment]
in stackoverflow they say not to use 777. it is a security risk they say.

use 755.

these are the commands i run for setting up a new app
sudo chown -R $USER:www-data storage
sudo chown -R $USER:www-data bootstrap/cache
chmod -R 775 storage
chmod -R 775 bootstrap/cache
