### ISSUE TITLE
Debugbar collectors not available in php CLI

### ISSUE THREAD

**Issue by scheMeZa** [barryvdh/laravel-debugbar#753]
Enabled collectors aren't registered at the point of running artisan commands. At least, that's my understanding of it.

Running:

```php
$debugbar = resolve('debugbar');
dd($debugbar->getCollectors());
```

in a php artisan command returns:
![image](https://user-images.githubusercontent.com/7773361/33431173-fac09816-d5db-11e7-82c1-ab2cae7e04e3.png)

More information on the problem:
https://github.com/hannesvdvreken/guzzle-debugbar/issues/7

**Comment by barryvdh** [comment]
Debugbar isn't enabled on the CLI, because it usually creates a lot of slowdown and isn't used (eg. updating a lot of data etc) You could enable it manually probably.
