### ISSUE TITLE
With Laravel 5.0.35 version "barryvdh/laravel-debugbar" : "~2.4" issue

### ISSUE THREAD

**Issue by rashhmijain** [barryvdh/laravel-debugbar#754]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support v5.5.2 requires php >=7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - illuminate/support v5.5.17 requires php >=7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - illuminate/support v5.5.16 requires php >=7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - illuminate/support v5.5.0 requires php >=7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - Conclusion: remove laravel/framework v5.0.35
    - Conclusion: don't install laravel/framework v5.0.35
    - Conclusion: don't install laravel/framework v5.0.34
    - Conclusion: don't install laravel/framework v5.0.33
    - Conclusion: don't install laravel/framework v5.0.32
    - Conclusion: don't install laravel/framework v5.0.31
    - Conclusion: don't install laravel/framework 5.0.30
    - Conclusion: don't install laravel/framework v5.0.29
    - Conclusion: don't install laravel/framework v5.0.28
    - Conclusion: don't install laravel/framework v5.0.27
    - Conclusion: don't install laravel/framework v5.0.26
    - Conclusion: don't install laravel/framework v5.0.25
    - Conclusion: don't install laravel/framework v5.0.24
    - Conclusion: don't install laravel/framework v5.0.23
    - Conclusion: don't install laravel/framework v5.0.22
    - Conclusion: don't install laravel/framework v5.0.21
    - Conclusion: don't install laravel/framework v5.0.20
    - Conclusion: don't install laravel/framework v5.0.19
    - Conclusion: don't install laravel/framework v5.0.18
    - Conclusion: don't install laravel/framework v5.0.17
    - Conclusion: don't install laravel/framework v5.0.16
    - Conclusion: don't install laravel/framework v5.0.15
    - Conclusion: don't install laravel/framework v5.0.14
    - Conclusion: don't install laravel/framework v5.0.13
    - Conclusion: don't install laravel/framework v5.0.12
    - Conclusion: don't install laravel/framework v5.0.11
    - Conclusion: don't install laravel/framework v5.0.10
    - Conclusion: don't install laravel/framework v5.0.9
    - Conclusion: don't install laravel/framework v5.0.8
    - Conclusion: don't install laravel/framework v5.0.7
    - Conclusion: don't install laravel/framework v5.0.6
    - Conclusion: don't install laravel/framework v5.0.5
    - Conclusion: don't install laravel/framework v5.0.4
    - Conclusion: don't install laravel/framework v5.0.3
    - Conclusion: don't install laravel/framework v5.0.2
    - Conclusion: don't install laravel/framework v5.0.1
    - barryvdh/laravel-debugbar v2.4.0 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - barryvdh/laravel-debugbar v2.4.1 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - barryvdh/laravel-debugbar v2.4.2 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - barryvdh/laravel-debugbar v2.4.3 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.0.0
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.0.0
    - Installation request for laravel/framework 5.0.* -> satisfiable by laravel/framework[5.0.30, v5.0.0, v5.0.1, v5.0.10, v5.0.11, v5.0.12, v5.0.13, v5.0.14, v5.0.15, v5.0.16, v5.0.17, v5.0.18, v5.0.19, v5.0.2, v5.0.20, v5.0.21, v5.0.22, v5.0.23, v5.0.24, v5.0.25, v5.0.26, v5.0.27, v5.0.28, v5.0.29, v5.0.3, v5.0.31, v5.0.32, v5.0.33, v5.0.34, v5.0.35, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9].
    - Installation request for barryvdh/laravel-debugbar ~2.4 -> satisfiable by barryvdh/laravel-debugbar[v2.4.0, v2.4.1, v2.4.2, v2.4.3].

**Comment by barryvdh** [comment]
Try an older version perhaps.
