### ISSUE TITLE
Installed on existed project and got an error

### ISSUE THREAD

**Issue by PeterKravets** [barryvdh/laravel-debugbar#755]
I installed it on existed project and got an error
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Argument 1 passed to Illuminate\Auth\TokenGuard::__construct() must implement interface Illuminate\Contracts\Auth\UserProvider, null given, called in /var/www/lextools/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php on line 159

When i deleted this package(LaravelDebugBar) everything was fine again.

Laravel 5.5. PHP 7.0.
LaravelDebugBar - last version

**Comment by xwk1993** [comment]
Me too, can you solve it?

**Comment by PeterKravets** [comment]
https://github.com/barryvdh/laravel-debugbar/issues/720
