### ISSUE TITLE
APP_DEBUG=true does not activate the debug bar on Lumen 5.5

### ISSUE THREAD

**Issue by khromov** [barryvdh/laravel-debugbar#757]
Setting `DEBUGBAR_ENABLED=true` resolves the issue.

Using `laravel-debugbar` version `3.1.0`

**Comment by Blizzke** [comment]
This apparently became the intended behavior per the version of Sep 18 if you do not override the config file in your own project.

`config/laravel-debugbar.php':
```
'enabled' => env('DEBUGBAR_ENABLED', null),
```
(the [diff in question](https://github.com/barryvdh/laravel-debugbar/commit/01a859752094e00aa8548832312366753272f8af#diff-1e51634d938acb3ee71d3f6687b5f192))
