### ISSUE TITLE
Filter Passwords in Configs

### ISSUE THREAD

**Issue by benyanke** [barryvdh/laravel-debugbar#759]
Currently, the app filters requests to remove passwords and keys (which is EXCELLENT) - [link](https://github.com/barryvdh/laravel-debugbar/blob/b45cee906d15a798ae60db8edf71b31355dba929/src/DataCollector/SymfonyRequestCollector.php#L112).

Is there, or could there be, an option to do the same for config, perhaps with user-configurable strings in the config file?

**Comment by barryvdh** [comment]
Duplicate of https://github.com/barryvdh/laravel-debugbar/pull/699
