### ISSUE TITLE
Cannot add AuthCollector to Laravel Debugbar when using laravel 5.5

### ISSUE THREAD

**Issue by zhousoft** [barryvdh/laravel-debugbar#761]
I got the  exception with laravel 5.5.2 and php 7.2.
Cannot add AuthCollector to Laravel Debugbar: array_keys() expects parameter 1 to be array, null given
.../vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#453Exception
array_keys() expects parameter 1 to be array, null given
..../vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#441

**Comment by zhousoft** [comment]
The d5c46b6 fix the exception，but when guards is "[]",the debugbar will not appear in web page.  After set the auth config as below:

```'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],```
than it work well.

**Comment by barryvdh** [comment]
Isn't that an upgrade step to 5.5?
