### ISSUE TITLE
Debugbar exception: Route [debugbar.assets.css] not defined.  

### ISSUE THREAD

**Issue by nezaboravi** [barryvdh/laravel-debugbar#762]
Suddenly i start to get this.
So i removed debugbar from composer and followed instructions and installed a new one. 
Then published it.
Cleared the cache, views, restarted browser, still same error.
APP_DEBUG set to true.
Using laravel 5.5 (upgraded it long time ago all the way from 5.2)
Debug bar was working until lately.
Where should i define this Route and where to point it to?

**Comment by barryvdh** [comment]
Did you clear the route cache?

**Comment by nezaboravi** [comment]
YEs sir, i did clear routes as well. 
php artisan route:cache
Route cache cleared!

**Comment by NibrasMohamedOSOS** [comment]
> I had this problem because my Laravel app was hosted in a subfolder (/api/v2) route.
> 
> So I had to change the config/debugbar.php route_prefix line from:
> 
> ```
> 'route_prefix' => '_debugbar',
> ```
> 
> to
> 
> ```
>  'route_prefix' => 'api/v2/_debugbar',
> ```

i've trued many ways. but this is the only way it worked
