### ISSUE TITLE
 syntax error, unexpected 'public' (T_PUBLIC)

### ISSUE THREAD

**Issue by leonrenkema** [barryvdh/laravel-debugbar#763]
I found when I use the last dev-master version of the debugbar that this error occurs
```
Parse error: syntax error, unexpected 'public' (T_PUBLIC)
in bestand: /vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php
        op regel: 498
```

There is a wrong "{" on the following line: https://github.com/barryvdh/laravel-debugbar/blob/d5c46b6a51b2773c6c8fbd149517a7719f4ff1f7/src/LaravelDebugbar.php#L490

Seem to be introduced in this commit: https://github.com/barryvdh/laravel-debugbar/commit/a3858e5334b9a8735cbc42ee58fbc3b4fc43bae3

**Comment by barryvdh** [comment]
Reverted that, thanks!
