### ISSUE TITLE
[Feature Request] View & Route by click open IDE

### ISSUE THREAD

**Issue by shiroamada** [barryvdh/laravel-debugbar#765]
Since latest Laravel support in Whoop open IDE (Phpstorm), can debugbar also included the feature like this, by clicking the view file and open directly for the IDE. I think it will be a great feature, instead now need to manually select it and open file from IDE.

View:
Added IDE Icon base on user config
![image](https://user-images.githubusercontent.com/2062946/34473002-fecebd1c-efa7-11e7-875d-9e3a75670769.png)

or

![image](https://user-images.githubusercontent.com/2062946/34468347-dd70fec0-ef41-11e7-9afd-925bf377d4f0.png)

Route:
![image](https://user-images.githubusercontent.com/2062946/34468351-e93cffd8-ef41-11e7-8f37-59fc261e80f0.png)

**Comment by barryvdh** [comment]
Can you make a PR? There is some xdebug integration, perhaps that can be used.

**Comment by a-komarev** [comment]
It's related to PR #567

Each IDE runs own protocol handler which listens on clicked hyperlinks and if it fits requirements then it passing this URI to IDE.

![](https://user-images.githubusercontent.com/1277526/29125254-f80b1eae-7d23-11e7-8b49-10c20ae30e19.png)

If you'll look on file table row you will see relative URI which is a good starting point for this task.

I've done something similar for Whoops exception handler links in [Laravel Whoops Editor](https://github.com/cybercog/laravel-whoops-editor) package. It's pretty tricky but working.

I can single out these requirements:
1. Keep in mind that each IDE has own URI format. So we cannot hardcode the one universal solution and need to have [configuration for each IDE](https://github.com/cybercog/laravel-whoops-editor/blob/9b841d2db610811e2a7a63ba7311a7d80f9357c5/config/whoops-editor.php#L40-L54).
2. We need to have configuration to help debugbar to know how to convert relative link to absolute in runtime, it could be tricky when we are using virtual machines, but could [solved with application paths in configuration](https://github.com/cybercog/laravel-whoops-editor/blob/9b841d2db610811e2a7a63ba7311a7d80f9357c5/config/whoops-editor.php#L56-L84).
3. We should not overwrite relative link and leave it for easier reading purposes, and just create it's copy, converted to fully qualified IDE URI.

I don't have time right now to dive into this feature implementation, but hope this will be helpful starting point.

**Comment by erlangp** [comment]
https://github.com/barryvdh/laravel-debugbar/issues/990

**Comment by pkruczynski** [comment]
This is easily configurable, e.g. in the public/.htaccess file, by adding the project directory prefix: 

`php_value     xdebug.file_link_format     phpstorm://open?file=/srv/htdocs/glx.pl/%f&line=%l`

**Comment by euperia** [comment]
I can confirm that adding the path to the `xdebug.file_link_format` option works. However, I didn't need to add the path to mine:

```
# /opt/homebrew/etc/php/8.1/conf.d/ext-xdebug.ini
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.client_host=127.0.0.1
xdebug.client_port=9003
xdebug.file_link_format="phpstorm://open?file=%f&line=%l"
```
