### ISSUE TITLE
is not working on laravel 5.5

### ISSUE THREAD

**Issue by murilolivorato** [barryvdh/laravel-debugbar#771]
I recent installed laravel-debugbar on laravel 55, but is not showing .
have a look on the HTML code -

https://ibb.co/gc1jE6

But is not showing .

**Comment by barryvdh** [comment]
Do you have any errors in your log?

**Comment by naid** [comment]
Same thing happened to me but when I fixed my Nginx config, everything works fine and the debugbar is good.

Change this:
```javascript
       location / {

                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
```

Into:
```javascript
        location / {
                try_files $uri $uri/ /index.php;
        }
```

There may be errors with how your views are rendered so you need to get more clues on what is happening with your setup.
