### ISSUE TITLE
this debug bar , is not good 

### ISSUE THREAD

**Issue by murilolivorato** [barryvdh/laravel-debugbar#772]
Sory but I dont recomend to any one , use this .

**Comment by barryvdh** [comment]
Care to explain why, I guess because of #771 ?

**Comment by naid** [comment]
Same thing happened to me but when I fixed my Nginx config, everything works fine and the debugbar is good.

Change this:
`        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
`

Into:
`        location / {
                try_files $uri $uri/ /index.php;
        }
`
