### ISSUE TITLE
Man In The Middle attack?

### ISSUE THREAD

**Issue by thecodemill** [barryvdh/laravel-debugbar#773]
I run the following to install Debugbar 2.4 into a new Laravel 5.4 project (2.4 being the latest version supported by <L5.5 according to the docs):

```
composer require barryvdh/laravel-debugbar:~2.4
```

And composer returns the following error:

```
[Composer\Repository\RepositorySecurityException]
The contents of https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature.
This could indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.
```

I've tried it a few times and receive the same error.

**Comment by jasonvarga** [comment]
Packagist was down earlier today. Just try it again.

**Comment by barryvdh** [comment]
Not related to debugbar, but yes, packagist was having some troubles yesterday.

**Comment by thecodemill** [comment]
Thanks, yes I can confirm it installed correctly a few hours later.

A side effect of this issue was that I found I had to remove the vendor directory completely and reinstall all dependencies before DebugBar would actually appear on the page. Clearing the various caches wasn't enough. Just in case anyone else hits this issue...
