### ISSUE TITLE
production.ERROR: Debugbar exception: Undefined index: email

### ISSUE THREAD

**Issue by justin81co** [barryvdh/laravel-debugbar#774]
once logging into the app, the Debugbar disappears 

look at the logs and only this line appears

production.ERROR: Debugbar exception: Undefined index: email

using laravel 5.0

**Comment by jthorpe-marco** [comment]
Are you using the 2.4 branch of debugbar? You need to use that since you're on a version of Laravel older than 5.5.

**Comment by justin81co** [comment]
2.1.4

**Comment by jthorpe-marco** [comment]
Gotcha, wish I could help more. I'm having a similar error on 5.4 and 5.5, but not exactly the same:
https://github.com/barryvdh/laravel-debugbar/issues/769
