### ISSUE TITLE
QueryCollector still collects queries when the debugbar is disabled

### ISSUE THREAD

**Issue by apokryfos** [barryvdh/laravel-debugbar#776]
The issue seems to be at around https://github.com/barryvdh/laravel-debugbar/blob/master/src/LaravelDebugbar.php#L320 

Once the debugbar starts listening to queries it will log all queries regardless of whether it's enabled or not.

This may cause issues (as it has in my case) if there are bulk update tasks which perform a lot of queries with large bindings since they cause a memory leak even if the debugbar is disabled. 

Edit: By memory leak I mean that the request itself along with the bindings is kept in memory for the duration of the request, which is how the debugbar works, but ideally disabling it should prevent it from consuming additional memory.

**Comment by aleemb** [comment]
@apokryfos This issue still persists. Ran into it on the latest release today.
