### ISSUE TITLE
view doesn't work

### ISSUE THREAD

**Issue by o2b3k** [barryvdh/laravel-debugbar#777]
<img width="1280" alt="2018-01-24 19 03 31" src="https://user-images.githubusercontent.com/16902119/35333575-6673aaa2-0139-11e8-9555-97d43c3a63f3.png">

**Comment by allrested** [comment]
Did you already set the folder permissions so everyone can access it?
![permissions](https://user-images.githubusercontent.com/4486730/35968220-cef6c772-0cf5-11e8-8db0-de0f62563ea0.png)
