### ISSUE TITLE
Class 'Barryvdh\Debugbar\ServiceProvider' not found  

### ISSUE THREAD

**Issue by amine8ghandi8amine** [barryvdh/laravel-debugbar#781]
Downloading (100%)
remote:        Generating optimized autoload files
remote:        > Illuminate\Foundation\ComposerScripts::postAutoloadDump
remote:        > @php artisan package:discover
remote:        
remote:        In ProviderRepository.php line 208:
remote:                                                               
remote:          Class 'Barryvdh\Debugbar\ServiceProvider' not found  
remote:                                                               
remote:        
remote:        Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
remote:  !     Push rejected, failed to compile PHP app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to iqs.
remote: 
To https://git.heroku.com/iqs.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: impossible de pousser des références vers 'https://git.heroku.com/iqs.git'

**Comment by tomzx** [comment]
Looks like an issue with your composer.json or your project setup, and not with this package.

**Comment by raphox** [comment]
Hi @amine8ghandi8amine ,

Maybe you are setting provider in `config/app.php`. But when you using composer autoload, itsn't required. Reference https://github.com/barryvdh/laravel-debugbar#laravel-55 "If you don't use auto-discovery, add the ServiceProvider to the providers array in config/app.php".

Remove the `Barryvdh\Debugbar\ServiceProvider::class,` of your config/app.php and it will work.
