### ISSUE TITLE
laravel 5.6 laravel-debugbar ValueExport Class not found

### ISSUE THREAD

**Issue by eaktadiur** [barryvdh/laravel-debugbar#782]
Class 'Symfony\Component\HttpKernel\DataCollector\Util\ValueExporter' not found

[screen shoot](http://prntscr.com/i7s0cm)

**Comment by tomzx** [comment]
If you go to the `vendor/symfony/http-kernel/DataCollector/Util` in your project, is the `ValueExporter.php` file there? If not, it seems you have a corrupted/incomplete `vendor` directory.

**Comment by Jurager** [comment]
Laravel 5.6 uses Symfony's http-kernel 4.0, in 3.2 valueExporter has been deprecated, and completely removed in 4.0  cloneVar, need to use cloneVar instead

**Comment by Jurager** [comment]
Made PR, hope it will be useful #784

**Comment by rjsworking** [comment]
@Jurager 
Hi, The package runs as expected on L5.6 but still get the error when enabling "events" in config\debugbar.php

Cheers

**Comment by lloricode** [comment]
im still get the same error

**Comment by lloricode** [comment]
#787 still not publish a tag for it, after that this will resolve this issue,

**Comment by A-Lawrence** [comment]
@lloricode, as it's been merged to master, setting your composer file to use "dev-master" _for now_ will pull that fix.

**Comment by lloricode** [comment]
@A-Lawrence yes, i've tested it, but, waiting this for my team :)

**Comment by barryvdh** [comment]
Tagged
