### ISSUE TITLE
Tracking database makes app occasionally crawl 

### ISSUE THREAD

**Issue by benyanke** [barryvdh/laravel-debugbar#785]
I have found that when DB query tracking is enabled, the app will occasionally crawl, making usage nearly impossible. I have been unable to debug this so far.

Have you seen any reports of this, or have any ideas of things that I could try?

**Comment by mariosvasiliou** [comment]
If you have laravel v5.5.x revert back to debugbar v3.1.1...

**Comment by benyanke** [comment]
I am on 5.4.x, but will try all the same.

**Comment by Alexander--** [comment]
@mariosvasiliou

Thanks, rolling back to previous version worked for me.

**Comment by barryvdh** [comment]
Closed in favor of #790, please check the mentioned commit https://github.com/barryvdh/laravel-debugbar/commit/664fa434e26febf04d60df0368303cf0fe14f63a
