### ISSUE TITLE
[Laravel 5.6] Call to undefined method Monolog\Logger::getMonolog()

### ISSUE THREAD

**Issue by sweebee** [barryvdh/laravel-debugbar#789]
On Laravel 5.6 I get this error.

```
Call to undefined method Monolog\Logger::getMonolog()
```

**Comment by talvbansal** [comment]
I have the same error too!

**Comment by mikassi** [comment]
I get this same error just after installing the debugbar via composer.

**Comment by garygreen** [comment]
Same problem.

**Comment by denimpax** [comment]
@garygreen, check  app/Exceptions/Handler.php.  
**getMonolog** maybe called from **report** method for slack handler or other

**Comment by kingflamez** [comment]
I also got this error, any solution?

**Comment by shaband** [comment]
i have changed 
'collectors'=>[
...............
        'log'  => false,
..............
]
in \config\debugbar.php
and it works well

**Comment by gattytto** [comment]
I do not have the debugbar package in my composer.json project, still:
```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Logger.php line 276:
                                                         
  Call to undefined method Monolog\Logger::getMonolog() 
```

**Comment by rygilles** [comment]
Same here...

**Comment by rygilles** [comment]
Ok, just find out what's wrong in my laravel project : Using Logentries in my AppServiceProvider register method.

Some clues :
1) Try to disable thirds party tools in this method.
2) Check your error handler content (App\Exceptions\Handler)
3) Check the "logging" part on this document if you are upgrading : https://laravel.com/docs/5.6/upgrade

**Comment by gattytto** [comment]
I did a composer cleancache and deleted vendor/* -rf.. then edited composer.json to use laravel/framework@5.6.*, minimum stability is dev, still composer fetches a wrong Illuminate Logger code, which calls that function that seems to not exist anymore..

**Comment by aseland123** [comment]
In Laravel 5.6 
`Logger::getMonolog()`  does not exist. you may try `Logger::getLogger()`

**Comment by insign** [comment]
I used `Log::getLogger()` and worked fine.

**Comment by XBS-Nathan** [comment]
I know this is an old issue, but i found by deleting/updating the debug configuration file in app/config/debugbar.php resolved this one for me

**Comment by NguyenNhutTien** [comment]
> In Laravel 5.6
> `Logger::getMonolog()` does not exist. you may try `Logger::getLogger()`

Thank you

**Comment by Heruvim6w** [comment]
> In Laravel 5.6
Logger::getMonolog() does not exist. you may try Logger::getLogger()

But how can I update this string:
"$this->addCollector(new MonologCollector($this->app['log']->getMonolog()))"
in app/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php?

**Comment by Heruvim6w** [comment]
>In Laravel 5.6
Logger::getMonolog() does not exist. you may try Logger::getLogger()

But how can I update this string:
"$this->addCollector(new MonologCollector($this->app['log']->getMonolog()))"
in app/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php?

**Comment by BFRS01904** [comment]
I'm still getting this error using laravel 6 ;(
