### ISSUE TITLE
Laravel Debug Bar Javascript "Correct" prepended to file

### ISSUE THREAD

**Issue by sgarwood** [barryvdh/laravel-debugbar#792]
PHP Version: 7.2
Laravel Version: 5.6

Hi,

When trying to load the debugbar on my view I get a strange error, it woud appear that somehow the work "Correct" is getting prepended to the Javascript generated by the debug bar (See below) causing the page to fail to load.

`
correct/*! jQuery v1.12.4 | (c) jQuery Foundation | jquery.org/license */
!function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error("jQuery requires a window with a document");return b(a)}:b(a)}("undefined"!=typeof window?window:this,function(a,b){var c=[],d=a.document,e=c.slice,f=c.concat,g=c.push,h=c.indexOf,i={},j=i.toString,k=i.hasOwnProperty,l={},m="1.12.4",n=function(a,b){return new n.fn.init(a,b)},o=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,p=/^-ms-/,q=/-([\da-z])/gi,r=function(a,b){return b.toUpperCase()};n.fn=n.prototype={jquery:m,constructor:n,selector:"",length:0,toArray:function(){return e.call(this)},get:function(a){return 
.
.
.
.
.
.
.
etc
`

```


javascript?v=1518535367:1 Uncaught ReferenceError: correct is not defined
    at javascript?v=1518535367:1
(anonymous) @ javascript?v=1518535367:1
dashboard:505 Uncaught TypeError: Cannot read property 'DebugBar' of undefined
    at dashboard:505
(anonymous) @ dashboard:505
dashboard:444 Uncaught TypeError: $ is not a function
    at HTMLDocument.<anonymous> (dashboard:444)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
(anonymous) @ dashboard:444
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
dashboard:262 Uncaught TypeError: $ is not a function
    at drawChart (dashboard:262)

```

Any help is appreciated.

**Comment by bertalanimre** [comment]
Following.
Or did you find the solution?
