### ISSUE TITLE
Not working in Lumen

### ISSUE THREAD

**Issue by Ajtak** [barryvdh/laravel-debugbar#797]
Hi, debugbar can not working in Lumen 5.6 (clear project).

I'm set in bootstrap/app.php:

> $app->register(Barryvdh\Debugbar\LumenServiceProvider::class);

and copy the file to config folder and enable it:

> $app->configure('debugbar');

But not working still.

I'm tried add `APP_DEBUG=true` to env file, but not working still. Debugbar is not showed.

Please fix it

**Comment by jimhill** [comment]
Just had the same issue, but looking at the config file you'll see you need to add `DEBUGBAR_ENABLED=true` to your `.env` file

**Comment by Ajtak** [comment]
I'm add directive to .env file, but not working still. I have env file correctly loaded.

**Comment by c7i** [comment]
@Ajtak Hope it can help you
> 1. php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"
> 2. $app->configure('debugbar'); //enbale custom config in bootstrap/app.php
> 3. change config.debugbar.collectors.auth to false

**Comment by johnsvenn** [comment]
Thanks guys.

For me using Lumen 5.6.1 and Debugbar 3.1.3

To get working I had to add both: 
`DEBUGBAR_ENABLED=true` to `.env` 
Change `config.debugbar.collectors.auth` to `false`
