### ISSUE TITLE
FatalThrowableError Class 'Barryvdh\Debugbar\ServiceProvider' not found

### ISSUE THREAD

**Issue by abrhambas01** [barryvdh/laravel-debugbar#802]
laravel 5.4.36

I removed  this package by  typing
$ composer remove barryvdh/laravel-debugbar -o

and then I get that error after. 

Is there something I haven't made right ? 

I did 
php artisan config:cache
composer dumpautoload

**Comment by domste** [comment]
Probably the `php artisan config:cache` command failed, because of the class dependency.
So you have to delete the cache-folder (`bootstrap/cache/) by hand.
