### ISSUE TITLE
Updating debugbar for cache collector in 5.4

### ISSUE THREAD

**Issue by jesseleite** [barryvdh/laravel-debugbar#805]
[It seems the cache collector was back-ported to the 2.4 branch](https://github.com/barryvdh/laravel-debugbar/blob/2.4/config/debugbar.php#L119), so I'm trying to update debugbar, but having trouble...

![screen shot 2018-03-13 at 11 06 56 am](https://user-images.githubusercontent.com/5187394/37350320-e23de126-26ae-11e8-8865-c83e2379ecfa.png)

Am I doing something wrong?  If I pull in ~2.4 as a tag, rather than as a branch, I don't seem to get the cache collector, but as linked above it should be available in the 2.4 branch?

Appreciate any guidance :)

**Comment by EdwinHoksberg** [comment]
Not sure if you figured it out yet, but I solved this problem like so: `composer req barryvdh/laravel-debugbar:2.4.x-dev --dev` and then republishing the config file: `php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider" --tag="config" --force`.

**Comment by jesseleite** [comment]
👍 An old project, but thanks!  Closing :)
