### ISSUE TITLE
0 passed to createDriver()

### ISSUE THREAD

**Issue by hussein-elhussein** [barryvdh/laravel-debugbar#806]
my laravel version: 5.5.39
i've tried different versions of this package, in each, i get this error:
Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 88 and exactly 1 expected

**Comment by DIqro** [comment]
Try check your .env like default of laravel
`MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null`

And then restart artisan serve.

**Comment by jorguerra** [comment]
The error persists. This is happening in my local environment running with docker. It appears all of a sudden running on Laravel 5.5.50
