### ISSUE TITLE
CSRF tokens mismatch when remember tokens for multiple guards are used

### ISSUE THREAD

**Issue by barlowm02** [barryvdh/laravel-debugbar#809]
Not sure if this is a known issue but I thought I would report it as it had been tripping me up for a few days - I was getting seemingly random CSRF mismatches from Laravel and couldn't work out the culprit.

I managed to track it down to the following reproducible conditions:

- Have multiple session guards configured (let's use 'web' and 'admin' as an example)
- Log in to 'web'
- Log in to 'admin', selecting 'remember me' and causing a `remember_admin_$hash` cookie to be generated
- Go back to a page on 'web', and either delete the session cookie (not the remember cookie!) or allow the session to expire naturally
- Refresh, so a new session is generated
- Any non-read request on 'web' will now result in a `TokenMismatchException` until the `remember_admin_$hash` cookie is deleted, at which point it will immediately begin working again

I was starting to think it was a bug in Laravel itself, until I realised that it never seems to happen in production, with the only difference being the presence of Debugbar. Sure enough, I changed `APP_DEBUG` to `false` in the .env and the problem immediately disappeared.

I've tried to back trace through the middleware stack and the last Debugbar related class the request passes through before the token match fails is MultiAuthCollector; considering the nature of the problem I assume this is likely to be the culprit?

**Comment by twopiers** [comment]
I'm seeing the exact same behavior. As soon as I turn off debugging or delete the `remember_admin_` cookie, everything works perfectly.

**Comment by StefanPrintezis** [comment]
I can confirm this is still an issue. Somehow the wrong token is loaded into the page when using debugbar.

**Comment by StefanPrintezis** [comment]
Still occurs afaik
