### ISSUE TITLE
jQuery.Deferred exception: $ is not a function TypeError: $ is not a function

### ISSUE THREAD

**Issue by kylescousin** [barryvdh/laravel-debugbar#811]
I'm getting this since recently: https://i.imgur.com/gjmu7Bc.png

This is the scripts section of the page: https://i.imgur.com/9QB5Uxq.png

Any idea why it's trying to load debugbar first?

**Comment by kylescousin** [comment]
I can't pinpoint the cause of this problem. @barryvdh Mind having a look?

**Comment by kylescousin** [comment]
Ok I've just installed a brand new laravel project with nothing else installed but Debugbar and the error is still there: https://i.imgur.com/rC6m2iD.png

**Comment by kylescousin** [comment]
Narrowed down the problem to this middleware: 

https://github.com/renatomarinho/laravel-page-speed/blob/master/src/Middleware/CollapseWhitespace.php

When using that middleware in App/Http/Kernel - Debugbar no longer works.

**Comment by barryvdh** [comment]
I suggest to turn that off in development mode ;)
