### ISSUE TITLE
Call to undefined method Monolog\Logger::listen()

### ISSUE THREAD

**Issue by ultimateBusiness** [barryvdh/laravel-debugbar#812]
Fresh project at L5.6 @ Homestead on a Mac - Package autodiscovery - no other configuration - open the site and the above error appears. 

If I change in ".env" the entry:
LOG_CHANNEL=stack
to
LOG_CHANNEL=stac  (yes - this is not valid)

Result => the Debugbar is working - any suggestions?

**Comment by ultimateBusiness** [comment]
If I delete the hole entry "LOG_CHANNEL=stack" from .env will bring the same result.

**Comment by bilfeldt** [comment]
@ultimateBusiness did you manage to solve your issue?

**Comment by kylescousin** [comment]
This has nothing to do with debugbar.

From the 5.6 upgrade guide https://laravel.com/docs/5.6/upgrade: 

"All logging configuration is now housed in its own config/logging.php configuration file. You should place a copy of the default configuration file in your own application and tweak the settings based on your application's needs."

You need to copy that file in your config folder.

**Comment by bilfeldt** [comment]
I was able to locate the error to some incompatibility with `debugbar` and the package `antonioribeiro/countries-laravel`. See this issue for more details: https://github.com/antonioribeiro/countries-laravel/issues/6

I don't know if the issue relies on `debugbar` or `antonioribeiro/countries-laravel` but would assume the latter.

**Comment by zarehesmaiel** [comment]
laravel  are using the `Monolog\Logmanager`  for all loging drivers. `monolog` not have `listene` method. and debugbar has not updated for this log storing. **so the debugbar is causing error**. 
**solution:**
\Config::set('debugbar.collectors.log', false);

**Comment by iz-ben** [comment]
Using the [comment](https://github.com/barryvdh/laravel-debugbar/issues/812#issuecomment-379365148) by @bilfeldt I was able to narrow down the problem. Deactivating `antonioribeiro/countries-laravel` sorted out the problem
