### ISSUE TITLE
[Laravel 5.6][Docker] Debugbar not visible

### ISSUE THREAD

**Issue by KuNman** [barryvdh/laravel-debugbar#816]
Hello. I can't setup debugbar as visible in my Laravel 5.6 project, hosted on Docker container.
`config/app.php` 
` 'debug' => env('APP_DEBUG', false),`
` Barryvdh\Debugbar\ServiceProvider::class,`
`'Debugbar'      => Barryvdh\Debugbar\Facade::class,`

`.env` 
`APP_ENV=local
APP_DEBUG=true`

`laravel.log`
`local.ERROR: Debugbar exception: Undefined index: guards`

Bar is not injected in blade body. I did `php artisan route:clear` few times.

**Comment by KuNman** [comment]
Workaround

`config/debugbar.php`
Collectors [
'auth => false'
]

But I still don't know why it crashes with auth enabled.

**Comment by jthorpe-marco** [comment]
Before your fix was the debugbar showing on your login screen but then disappeared once you logged in?

**Comment by ivantree** [comment]
error + 1

**Comment by ivantree** [comment]
it was not visible at all

**Comment by locojuhi** [comment]
1. try to do a vendor:publish and set in your .env `DEBUGBAR_ENABLED=true`

2. clear you cache even with the debugbar cache

3. and no matter if you have the auto discover active, register at service provider and alliases the debugbar

i had the same issue and i did those 3 thing and now it's working (remember to give the right permissions at storage/ and bootstrap/storage)

let me know if help you.

**Comment by ivantree** [comment]
Thank you, but still error

**Comment by zmarwa** [comment]
error+1 
with message: 
 Debugbar exception: Method Illuminate\Database\Query\Builder::getLoginAttribute does not exist.  

the Workaround solve it:
config/debugbar.php
Collectors [
'auth => false'
]

**Comment by erickdev93** [comment]
@zmarwa That worked for me.
