### ISSUE TITLE
Uncaught Error: Unknown language: "sql"

### ISSUE THREAD

**Issue by dimon1985** [barryvdh/laravel-debugbar#817]
Hi!
I`m response in console chrome:
javascript?v=1520325331:7 Uncaught Error: Unknown language: "sql"
And all sql queries don`t see.

**Comment by bbcreation** [comment]
I have the same problem. What did you do?

**Comment by cihantas** [comment]
Same here.

**Comment by yajubrainbox** [comment]
Hi @dimon1985 
Would you mind to share how you solved the issue? That would be really helpful!. Thank you
