### ISSUE TITLE
Flash message doesn't clean when the package is enabled

### ISSUE THREAD

**Issue by sergiq** [barryvdh/laravel-debugbar#818]
When the package is enabled its re-flash all messages and the messages does not desappear until logout/removing sessions manually/etc

When the package is disabled the flash message works as expected

Note: My app is an upgrade from Laravel 5.5 (its not a fresh one).

Environment
```
PHP 7.2.3
barryvdh/laravel-debugbar version "v3.1.4"
laravel/framework version "v5.6.13"

```

Example Code:
```
Route::get('flash', function () {
    return redirect('flash-show')->with([ 'success' => 'This is a test.' ]);
});
Route::get('flash-show', function (\Illuminate\Http\Request $request) {
    if (session()->has('success')){
        return "The flash session exist: " . session()->get('success');
    }
    else
    {
        return "The flash session is empty";
    }
});
```

**Comment by Twinsen-** [comment]
I confirm the problem with laravel 5.5 and debugbar 2.3 and 3.1.4
Session::flash acts like Session::put
