### ISSUE TITLE
Extending Debugbar

### ISSUE THREAD

**Issue by mfour-merickson** [barryvdh/laravel-debugbar#822]
Hey @barryvdh 

Is there a system in place whereby I could create custom buttons/tabs for display application specific information?  

I know I can "hack" something together to attain what I want, but I am more curious if you have added some sort of "extension/plugin" interface which will not require hacking the core (and be save from future updates)

**Comment by mfour-merickson** [comment]
Thanks, I will have a look

**Comment by kaichristiansen** [comment]
Anyone have an example of this? I would like to add API calls. I will have a look too but just wondered if there might be more info or a cheatsheet, etc. :-D.
Thanks for the debugbar!
