### ISSUE TITLE
v3 queries do not show proper trace

### ISSUE THREAD

**Issue by Ciaro** [barryvdh/laravel-debugbar#825]
I have noticed on a couple of projects, v3 of the debugbar (in combo with Laravel 5.6) do not show proper tracing of where the error originated. It always shows for every query Dispatcher as last caller.

![afbeelding](https://user-images.githubusercontent.com/891736/39243006-62aff89a-488c-11e8-80ac-3931bb900b57.png)

**Comment by OzanKurt** [comment]
#803
