### ISSUE TITLE
Laravel debugbar not allowed to send the emails.

### ISSUE THREAD

**Issue by bindesh** [barryvdh/laravel-debugbar#829]
Recently I have added laravel-debugbar in my application. If I enabled the debugbar it is working perfectly but causing the problem while sending emails. It always gives STMP configuration mismatch error. Meanwhile, If I disabled the debugbar it allows me to send the emails with the same configuration. 
I have tried to find the solution but was not able to do it.
Did I miss anything to configure Laravel-debugbar properly?

Can any-body help me on this?

**Comment by robiparvez** [comment]
Turning mail to false in the DataCollectors config section resolves this problem.

'mail' => false, // Catch mail messages
