### ISSUE TITLE
Problem with CSP when using Laravel gates

### ISSUE THREAD

**Issue by Teerr** [barryvdh/laravel-debugbar#830]
Hello,
today we were experiencing weird behaviour of the debugbar. On our site, we use Content-Security-Policy, so `unsafe-eval` is disabled. We have also included our own jQuery script. And here is the thing: 

Debugbar works on the whole site, except one page. Controller of this page uses gate. And the problem is, the debugbar for this case uses it's own included jquery (not ours), and this jquery version contains call `a.eval.call(a,b)` which causes the problem. 

I am not sure if this is a problem of package barryvdh/laravel-debugbar directly, or package maximebf/debugbar or jquery itself. I am not even sure if I understand the problem correctly. We solved it temporarily by disabling gate collector (BTW: config collector causes the same problem). 

Sorry if I write it to wrong (package) repository.
![image](https://user-images.githubusercontent.com/9195796/39925322-72a87b72-552b-11e8-8e90-ff11b19e4dd4.png)

**Comment by barryvdh** [comment]
Do newer jquery version not have this problem? If so, we can upgrade.

**Comment by Teerr** [comment]
Yes, since jQuery 3 (I think) has been eval removed.

**Comment by barryvdh** [comment]
I've updated to jQuery 3: https://github.com/maximebf/php-debugbar/commit/f3d4a0c549b7bb5468d52b90e0acc45b81d3935b

You can get the php-debugbar dev version (`1.15.x@dev`) to try it.
