### ISSUE TITLE
Can not collect queries which executed in AppServiceProvider

### ISSUE THREAD

**Issue by cloudop** [barryvdh/laravel-debugbar#831]
I'v made some database executions in /app/Providers/AppServiceProvider.php::boot method.
But the query doesn't show in the "Queries" tab.
Anyone know how to collect these queries?
My Laravel version is 5.6.17, Laravel-debugbar version is 3.1.4

**Comment by natelloyd** [comment]
Same. Just upgraded from 5.3 to 5.6 and noticed this.

**Comment by ulcuber** [comment]
"laravel/framework": "5.5.*"
"barryvdh/laravel-debugbar": "^3.1"
Same

**Comment by swvjeff** [comment]
I'm having trouble with this too (except that I'm trying to call addMessage() instead of log DB queries). It appears the Debugbar collectors aren't loaded yet by the time my Service Provider's boot() method is being called. Curious if there's a way to fix this?

**Comment by ulcuber** [comment]
> I'm having trouble with this too (except that I'm trying to call addMessage() instead of log DB queries). It appears the Debugbar collectors aren't loaded yet by the time my Service Provider's boot() method is being called. Curious if there's a way to fix this?
I think there is no need to execute queries in providers. Queries should be placed in way to be called on demand.

**Comment by swvjeff** [comment]
> I think there is no need to execute queries in providers. Queries should be placed in way to be called on demand.

I'm just trying to call Debugbar::addMessage() in my service provider

**Comment by sadekd** [comment]
Same problem

`\App\Providers\FrontServiceProvider::class` is registered in `app.php[providers]`

also tried manually add `\Barryvdh\Debugbar\ServiceProvider::class,` into `app.php[providers]` before my `\App\Providers\FrontServiceProvider::class` - still not working

PHP 7.2
Laravel 5.7
DebugBar 3.2

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class FrontServiceProvider extends ServiceProvider
{
    public function boot()
    {
        \View::share(
            'allActiveCategoriesTree',
            \App\Category::onlyActive()->get()->toTree()
        );
    }
}
```

**Comment by MarcosBL** [comment]
Maybe this can help https://github.com/barryvdh/laravel-debugbar/issues/617#issuecomment-514682655
