### ISSUE TITLE
Directly display debug bar without using a blade

### ISSUE THREAD

**Issue by ajcastro** [barryvdh/laravel-debugbar#832]
I am working on json rest api.
Is there a feature how can I use Debugbar directly without using a blade? Because for me to see the debugbar output, I need to return a view from the controller. 
I am hoping that I can do something to directly output debugbar instead creating a blade file just to output debugbar.

I am thinking something like this:
```
Debugbar::info($data1);
Debugbar::info($data2);
Debugbar::info($data3);

Debugbar::renderAndStop();
// or return it from controller
return Debugbar::render();
// or lets make a dd in debugbar
Debugbar::dd($data);
```

**Comment by barryvdh** [comment]
You can just return a string 'ok' for example

**Comment by ajcastro** [comment]
really? I will try it if works.

**Comment by ajcastro** [comment]
@barryvdh , this works but only if you are inside the controllers,.. what if you are inside the other classes or sevices, and on that certain line or breakpoint you want to profile the runtime especially the queries,. how are you going to do it? 

For me, I suggest like `Debugbar::dd($data);`.. what do you think?

**Comment by matiazar** [comment]
> You can just return a string 'ok' for example

but if I return a collection, 
for example, I made 
  return(User::all()); 
I dont see the debugbar
