### ISSUE TITLE
"?method=&uri=&ip=" is adding while login in Laravel 5.4

### ISSUE THREAD

**Issue by webribs** [barryvdh/laravel-debugbar#833]
I'm using Laravel 5.4 and using this in composer

`"barryvdh/laravel-debugbar": "~2.4"`

I've enabled debugger in .env file 
`DEBUGBAR_ENABLED=true`

and getting this `?method=&uri=&ip=` in url when is submit login form.

`http://localhost:8000/login?method=&uri=&ip=`

**Comment by barryvdh** [comment]
did you perhaps forgot to close a form tag?

**Comment by AdamKv** [comment]
I'm have the same problem, it's not the form tags...

**Comment by MarkTierney1975** [comment]
Same here. I have a table with a search filter. I'm using $request->flash() in the controller.

**Comment by shira79** [comment]
Hello, I faced the same problem and solved it.

If the debugger is enabled, a form for openhandler is drawn.
https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/Resources/openhandler.js#L95-L101

Perhaps this form has been submitted.




<img width="1372" alt="スクリーンショット 2022-03-21 14 42 51" src="https://user-images.githubusercontent.com/42834409/159210417-f6f266df-866f-45f0-9179-c5f51ba29e7e.png">
