### ISSUE TITLE
Is it possible to profile using debugbar while running phpunit tests?

### ISSUE THREAD

**Issue by ajcastro** [barryvdh/laravel-debugbar#835]
Is it possible to profile using debugbar while running phpunit tests? Because I want to see a performance and query report while running phpunit tests.

**Comment by barryvdh** [comment]
Don't think so

**Comment by afraca** [comment]
Maybe this is helpful:
https://github.com/barryvdh/laravel-debugbar/pull/841#issuecomment-405827616

**Comment by diogogomeswww** [comment]
*LaravelDebugbar.php:760*
`$this->enabled = $configEnabled && !$this->app->runningInConsole() && !$this->app->environment('testing');`

this will disable debugbar when running the tests
