### ISSUE TITLE
Dynamically load debugbar

### ISSUE THREAD

**Issue by garygreen** [barryvdh/laravel-debugbar#836]
Currently, the debugbar loads all information on every page load, even when the debugbar is hidden. This slows down development and also interferes with the network / remote tab by creating additional ajax requests when your not using debugbar.

Would it be a good idea to dynamically load the debugbar only once you've click on the icon?

**Debugbar information still loads, even though it's not visible**

![image](https://user-images.githubusercontent.com/1702638/40727569-0df202da-6420-11e8-9fc9-b92423ba651a.png)

If this was the case, this would also stop additional ajax requests when your debugging the network tab but haven't got debugbar open which is mildy annoying:

![image](https://user-images.githubusercontent.com/1702638/40727725-62529934-6420-11e8-935a-8903f7ecb0c7.png)

**Comment by garygreen** [comment]
If this is difficult to implement or not something welcome to a PR, would it be possible for your own app to dynamically load debugbar dynamically, maybe by calling some public API like:

```
document.querySelector('a.load-debugger', function() {
   debugbar.load();
});
```

Or something similar?

**Comment by ajcastro** [comment]
you can set `DEBUGBAR_ENABLED=false` in your `.env`

**Comment by garygreen** [comment]
> How about you can set DEBUGBAR_ENABLED=false in your .env

Of course you can do that, but that's not what I'm suggesting. What would be good is if you could have debugbar enabled but switch it on/off dynamically from the ICON in the bottom left corner. So, it's enabled but doesn't collect any information / debugging until you click it and again disable debugging once you close the panel again - if that requires reloading the page to collect the debugging information, then so be it (it can just be an option "DEBUGBAR_DYNAMIC")

This would save having to manually go back and forth between your config and toggle the env / config settings to turn it off, it'll speed up development as pages will load quicker when your not debugging but can turn it back on at click of button.

If this is tricky to implement then I can think of a way of having this kind of functionality in a third party package, maybe a "lazyload-laravel-debugger" package of sorts?
