### ISSUE TITLE
Identify which queries are duplicate 

### ISSUE THREAD

**Issue by ajcastro** [barryvdh/laravel-debugbar#838]
I think it is good to put an icon or something or any way for us to see which among the queries are duplicate so it would be easy to find them instead of checking each queries one by one. :smiley: 

![image](https://user-images.githubusercontent.com/4918318/40885706-3d1ce9d0-675e-11e8-8a37-c2c0a0b8b657.png)

**Comment by tomzx** [comment]
Duplicate of #810 (ironic).

**Comment by ajcastro** [comment]
Follow this comment https://github.com/barryvdh/laravel-debugbar/issues/260#issuecomment-395639215
