### ISSUE TITLE
Attach debugbarinfo to "ask for support" email

### ISSUE THREAD

**Issue by jozeflambrecht** [barryvdh/laravel-debugbar#839]
I am using this package to debug my application (in development mode) and it is a huge help so far. (thanks for that!) I was wondering if I could (in production mode) attach this kind of data to a support email. So when a user sends me a "ask for support" email using a modal form, this data is attached to the email/notification. Or is there another way to do this?

**Comment by barryvdh** [comment]
Nope

**Comment by jozeflambrecht** [comment]
Ok, clear as a bell 😄
