### ISSUE TITLE
ajax request missing

### ISSUE THREAD

**Issue by gamevnlc** [barryvdh/laravel-debugbar#843]
I use laravel 5.6 with datatables, i already enabled `capture_ajax` config. But ajax request is still not display

![image](https://user-images.githubusercontent.com/2215185/41389139-b5cb149a-6fc1-11e8-9f3b-bf4b12c7e582.png)

![image](https://user-images.githubusercontent.com/2215185/41389126-ae5c11aa-6fc1-11e8-846b-52c931f1316f.png)

**Comment by FilipQL** [comment]
Same issue here.  I have`'capture_ajax' => true,` but queries are not listed.

Debugbar: v3.1.5
Laravel v5.6.26

**Comment by bluec** [comment]
Same here, not seeing any queries logged for datatables ajax requests

Debugbar: v3.1.5
Laravel v5.6.27

**Comment by endytc** [comment]
Same issue here, I have same problem with datatable, ajax request not showing in debugbar

**Comment by barryvdh** [comment]
I think data tables does a hard exit instead of a proper response.

**Comment by MathTV** [comment]
Same problem here. Queries related to page loads are shown in the debug bar, but subsequent queries executed on the server in response to AJAX requests (originating from jqGrid (http://www.trirand.com/blog/) do not appear.

**Comment by shawnheide** [comment]
For anyone else having this issue with DataTables, a workaround I found is to listen for the `xhr.dt` event and then pass the response to phpdebugbar manually.
```html
<script>
    $('body').on('xhr.dt', function (e, settings, data, xhr) {
        if (typeof phpdebugbar != "undefined") {
            phpdebugbar.ajaxHandler.handle(xhr);
        }
    });
</script>
```

I also had an issue with some of the response headers being blank so I just added a check for that as well:
```html
<script>
    $('body').on('xhr.dt', function (e, settings, data, xhr) {
        if (typeof phpdebugbar != "undefined") {
            if (xhr.getAllResponseHeaders()) {
                phpdebugbar.ajaxHandler.handle(xhr);
            }
        }
    });
</script>
```

**Comment by wrabit** [comment]
Worthy of being in docs?

**Comment by Slivicon** [comment]
Thank you shawnheide for this solution. I also decided to put it in my layout blade file wrapped in a blade if so that it only even shows up in the html source when debug=true (debugbar is being used):

```blade
@if(config('app.debug'))
<script>
    $('body').on('xhr.dt', function (e, settings, data, xhr) {
        if (typeof phpdebugbar != "undefined") {
            if (xhr.getAllResponseHeaders()) {
                phpdebugbar.ajaxHandler.handle(xhr);
            }
        }
    });
</script>
@endif
```

**Comment by JamesAnelay** [comment]
I've just experienced this same issue, a few of my ajax requests were missing & I couldn't figure out quite why. Ended up just deferring my app.js until after the debug bar.

```</div>
<script src="{{mix('js/app.js')}}" defer></script>
</body>
```

**Comment by decadence** [comment]
@JamesAnelay your solution works for me, thanks!

**Comment by lionslair** [comment]
> I've just experienced this same issue, a few of my ajax requests were missing & I couldn't figure out quite why. Ended up just deferring my app.js until after the debug bar.
> 
> ```
> ...
> </div>
> <script src="{{mix('js/app.js')}}" defer></script>
> </body>
> ```

This had been driving me nuts for months
