### ISSUE TITLE
[REQUEST] Display queries were duplicated

### ISSUE THREAD

**Issue by taimaiduc** [barryvdh/laravel-debugbar#844]
Can we display different color of queries were duplicated
`11 statements were executed, 2 of which were duplicated, 9 unique`

**Comment by steveheinsch** [comment]
I created a little bookmarklet. Just make a bookmark and use this for the "location"
```
javascript:(function(){%20if%20(typeof%20toggleSqlDuplicate%20!==%20'function')%20{%20window.toggleSqlDuplicate=function%20(){$('div.phpdebugbar-widgets-sqlqueries%20li').not('.phpdebugbar-widgets-sql-duplicate').toggleClass('hidden');}%20}%20toggleSqlDuplicate();%20})();
```
All it does is toggle hiding/showing the queries that `aren't` dupes, so it leaves you with `only` the dupes.

**Comment by Briareos17** [comment]
Realy need this in package!
