### ISSUE TITLE
XSS security problem

### ISSUE THREAD

**Issue by jordyvandomselaar** [barryvdh/laravel-debugbar#845]
Steps to reproduce:

1. Enable debug bar
2. Render a form that puts the inserted value back into the input on submit (search bar, etc)
3. Insert `"><script>alert('hoi')</script>` into the input
4. Submit
5. Problems occur

**Comment by barryvdh** [comment]
Can you submit a PR?

Please do note that the debugbar should only ever be activated on your development machines, so you control your own input.

**Comment by jordyvandomselaar** [comment]
I'll see what I can do.

This is correct, and luckily we only ever use it on dev machines, but during testing we thought we had a XSS problem, so we started looking for problems that didn't exist hahahahaha.

**Comment by jordyvandomselaar** [comment]
Turns out it's a problem in the underlying phpdebugbar package.
