### ISSUE TITLE
Render with nonce/hash parameter

### ISSUE THREAD

**Issue by screenager** [barryvdh/laravel-debugbar#847]
As the default installation injects the code just before `</body>,` the script and assets will be blocked by the browser if you enforce strong CSP headers for injection protection.

It would be nice workaround if by setting 'inject' to false, and rendering the debugbar manually in your master template, one could also add nonce or hash parameter:

```
$renderer = Debugbar::getJavascriptRenderer();
echo $renderer->renderHead(['nonce' => 'ogCHUYO6kVuNXlvGPcB8dcFIM7p');
..
echo $renderer->render(['nonce' => 'ogCHUYO6kVuNXlvGPcB8dcFIM7p');
```

so the result would be something like
```
<link nonce="ogCHUYO6kVuNXlvGPcB8dcFIM7p" ..  />
..
<script type="text/javascript" nonce="ogCHUYO6kVuNXlvGPcB8dcFIM7p">
  var phpdebugbar = new PhpDebugBar.DebugBar();
  ..
```

Doesn't seem to me that #569 is related, but correct me if I'm wrong

**Comment by barryvdh** [comment]
Yeah I was having a similar problem, must see what the best way is. Perhaps a callback to set it or something.

**Comment by ncrewsSouthern** [comment]
Running into this same issue.  I'm using https://github.com/spatie/laravel-csp  to set policies and working through the console.log to resolve issues.   I need to add nonce's to the Style and 2 script elements injected

**Comment by jannejava** [comment]
Any news on this? Would be great to pass along a nonuce.

**Comment by dovca** [comment]
Any progress? The debugbar is currently the only package blocking me from using CSP.

**Comment by jannejava** [comment]
Same for me. Currently disabled debugbar. Is there any way we can help or assist? @barryvdh you had some ideas?

**Comment by ncrewsSouthern** [comment]
For those using laravel-csp or trying to.  looks like there is a config option to enable/disable in the ENV file, you could use this to drop the CSP policy/headers from  dev/testing.

the following is found in config/csp.php( have not used or tested this yet )

    'enabled' => env('CSP_ENABLED', true),

**Comment by jtallinger** [comment]
Would also like to see a proper fix for this issue. Disabling CSP locally is to ask for problem in production. :) 

My current work around with Spatie/laravel-csp, in a custom policy:
```
// To allow Laravel debugbar and Whoops error handling in local environment
if (config('app.env') == 'local') {
    $this->reportOnly();
}
```
At least in that way it is possible to keep an eye in console for violations.

**Comment by liepumartins** [comment]
Still no progress?

Report only mode for local is poor workaround as debugbar will generate enormous amount of CSP warnings and the console becomes filled and unreadable.

Are we (CSP users) really such a minority?

**Comment by barryvdh** [comment]
Sorry I don't use it often. But what is exactly required, just the nonce to the scripts? So we can extend https://github.com/barryvdh/laravel-debugbar/blob/master/src/JavascriptRenderer.php to inject a nonce in all script, but we need to have a way to determine the nonce. We could obviously just support Spatie and doe something like `function_exists('csp_nonce')`, or check if the View has a shared variable like in https://github.com/fruitcake/laravel-telescope-toolbar/blob/master/resources/views/head.blade.php

**Comment by jtallinger** [comment]
Thumbs up for the idea of `function_exists('csp_nonce')`, I'd guess that is what most users use anyway with Laravel. And if not using that package then option is to define and bootstrap own function named csp_nonce.

**Comment by barryvdh** [comment]
Is thet script and style nonce always the same?

**Comment by barryvdh** [comment]
We could also make it a config option, eg. define the callable in the config (`'csp_callback' => 'csp_nonce'`) and use that.

**Comment by jtallinger** [comment]
With Spatie script and style use same nonce, I'd guess that is quite typical case for any usage of nonce.

**Comment by liepumartins** [comment]
Callback idea sounds excellent as it would allow any CSP package or custom solution.
Yes, usually the nonce is the same for `style` and `script` tags.

Much appreciated!

**Comment by barryvdh** [comment]
Partial PR: https://github.com/barryvdh/laravel-debugbar/pull/1013

**Comment by jtallinger** [comment]
For anyone coming here and wondering if this is solved and how to make it work. I solved it by using a recent version of the package (>Sep 2023 / version >3.12.2) and by adding following to app/Providers/AppServiceProvider.php (Laravel 10):

```php
if ($this->app->isLocal()) {
    // Set CSP nonce for Laravel Debugbar during development
    if (class_exists(\Barryvdh\Debugbar\Facades\Debugbar::class) && app()->bound('debugbar')) {
        app('debugbar')->getJavascriptRenderer()->setCspNonce(csp_nonce());
    }
}
```

Finally no more CSP warnings during development. Thanks for an excellent package and thanks for the work to get this issue solved 😀 👍

**Comment by Seyid-cmd** [comment]
@jtallinger thank you, that works .

**Comment by MizouziE** [comment]
@jtallinger Thank you! This idea needs to be held up way higher so everyone can see it 🙏
