### ISSUE TITLE
Add support for Laravel 5.7

### ISSUE THREAD

**Issue by lucasdcrk** [barryvdh/laravel-debugbar#863]
Hi, Laravel 5.7 arrived and this package is not compatible (yet) with 5.7 :(

**Comment by Jeroen-G** [comment]
In what way? I'm using it in 5.7

**Comment by hoRacy** [comment]
@Jeroen-G  - when you use gates & policies you have a ReflectionClass error.

**Comment by bitw** [comment]
In config/debugbar.php set false in parameter gate
`'gate'            => false, // Display Laravel Gate checks`
