### ISSUE TITLE
ReflectionFunction::__construct() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Bluesik** [barryvdh/laravel-debugbar#864]
When using policies in Laravel 5.7 I get the above mentioned error. (Debugbar v3.2)
It also happens on a fresh copy of Laravel.

It's thrown in Illuminate\Auth\Access\Gate.php @ callbackAllowsGuests
Parameter passed to the ReflectionFunction constructor:
array:2 [▼
  0 => GateCollector 
  1 => "addCheck"
]

It happens only when there is no authenticated user.

It occurs when calling the authorize method in the controller:
$this->authorize('action', $model);

And when using the @can blade directive
@can('view', $model)

**Comment by Bluesik** [comment]
Setting gate collector to false in debugbar's config seems to fix the issue.

**Comment by Vilfago** [comment]
Same issue, posted on Laracasts and found afterwards it was coming from Debugbar
For more information : https://laracasts.com/discuss/channels/laravel/laravel-57-policy-issue

**Comment by lloricode** [comment]
is there way to fix this? because gate collection is much helpful when finding a failed permission

**Comment by hassanazimi** [comment]
Same issue. I'd never known If i didn't find this posts

**Comment by CecileV** [comment]
Same issue. This post is very helpful.

**Comment by Finesse** [comment]
> Setting gate collector to false in debugbar's config seems to fix the issue.

You can uninstall Debugbar, it will fix the issue too
