### ISSUE TITLE
  Class 'Barryvdh\Debugbar\ServiceProvider' not found In ProviderRepository.php line 208

### ISSUE THREAD

**Issue by fan153693** [barryvdh/laravel-debugbar#865]
I got this ,When I uninstall debubar
![image](https://user-images.githubusercontent.com/7405726/45204637-6dbfa880-b2b2-11e8-99c6-1742380ba917.png)

**Comment by dimitriacosta** [comment]
You need to remove two lines on your `config/app.php` file:
`'Debugbar' => Barryvdh\Debugbar\Facade::class,`
and
`'Debugbar' => Barryvdh\Debugbar\Facade::class,`

Then you need to do `php artisan package:discover` and you're done
