### ISSUE TITLE
Is there any way to emulate clockwork without injecting the template?

### ISSUE THREAD

**Issue by ryanmortier** [barryvdh/laravel-debugbar#881]
Most of the time I inject the template as it suites my needs but sometimes I'd like to disable it but still emulate the clockwork headers. Is there any way to do this currently?

**Comment by barryvdh** [comment]
There is an inject option you can disable.

**Comment by ryanmortier** [comment]
Hmm I tried that option but it turned off the clockwork stuff. I'll try it again.
