### ISSUE TITLE
Query numbers get reduced by itself!

### ISSUE THREAD

**Issue by mohamadreza89** [barryvdh/laravel-debugbar#882]
I'm using Laravel 5.7 and when I load a page, It shows 14 queries in the query tab which is almost correct but in one second they get disappeared and the total number of queries shrinks to 3 which is faulty for sure and the duration also decrease from 30ms to 15ms (sometimes it shows 0 us)

**Comment by barryvdh** [comment]
That is probably an Ajax request?

**Comment by mohamadreza89** [comment]
it's not Ajax request ...  it's from server ... also the request duration sometimes shows 0. The weird thing is that it shows correctly at first but just after a second they get changed.
