### ISSUE TITLE
Ajax response made invalid due to debugbar injection

### ISSUE THREAD

**Issue by BARNZ** [barryvdh/laravel-debugbar#885]
I have page with lots of ajax requests so I set `capture_ajax` to `false` in the debugbar config to prevent slowdown while developing since I dont need them logged.

However once I disable this option debugbar starts including stuff in my ajax responses (it seems like its only the responses that return simple strings or numbers)

This screenshot below shows an ajax response from the server with the value of `15` but debugbar injects a link tag in there, breaking any client-side behavior relying on this value.

![image](https://user-images.githubusercontent.com/2202345/47401897-95ee6280-d79f-11e8-9276-baa0a426610d.png)

I understand that when `inject` is set to `true` this sort of behavior is meant to happen, but I was under the assumption this didn't occur for ajax type requests?

**Comment by barryvdh** [comment]
How are you sending your ajax requests? Are you setting the correct content type?

**Comment by BARNZ** [comment]
In the controller I'm just returning `$model->id` in this case

**Comment by barryvdh** [comment]
`return response()->json($model->id);` perhaps?

**Comment by BARNZ** [comment]
If I return the entire model in the controller all is fine, returning a simple string or primitive triggers it

**Comment by BARNZ** [comment]
Yeah thats my workaround for now.

**Comment by barryvdh** [comment]
I think Axios doesn't send the X-Requested-With headers, so not really much we can do about it. I would suggest to always send actual json responses, even for just string values.

**Comment by BARNZ** [comment]
I have it configured to send the correct headers as I rely on these myself in other areas of the system.

![image](https://user-images.githubusercontent.com/2202345/47621750-37d7cb80-db61-11e8-80aa-7b8e548799fa.png)

![image](https://user-images.githubusercontent.com/2202345/47621758-5047e600-db61-11e8-941d-f0d7a7acd591.png)

**Comment by razchen** [comment]
I'm facing the same problem with Axios. Any solution here?
