### ISSUE TITLE
Since v3.2.1 model ids are 0 after create()

### ISSUE THREAD

**Issue by dtvmedia** [barryvdh/laravel-debugbar#888]
We experienced a very strange bug today, were after an Model create call the id of the returning model was always just 0. It turns out that the debugbar causes the problem, more precisely after the changes of commit [#0e4c5fad](
https://github.com/barryvdh/laravel-debugbar/commit/0e4c5fada69ccbfca06ea6b9e9e797ac2dec745a) the problem occurs.

```
dd(Setting::query()->create([
     'name' => 'test' ,
     ...
]));
```
Result:
```
#attributes: array:13 [▼
    "name" => "test"
    ...
    "id" => 0
]
```

**Versions:**
Laravel: 5.7.13
Debugbar: 3.2.1

**Comment by jordonbaade** [comment]
I'm having this problem as well, just confirmed it was debug-bar by reinstalling all packages in my project one by one.

Turning the config option explain to false did fix it for me. Thanks @bastian-schur 

Feel like I had this enabled for some time before the issue started but I can't say for sure.

Laravel: 5.7.22
Debugbar: 3.2.1

**Comment by barryvdh** [comment]
Thanks, can you submit a pr to revert the change?

**Comment by barryvdh** [comment]
Not really why that would happen though, the explain is a separate query?

**Comment by bastian-schur** [comment]
I think it's not right to do a revert. The commit resolved a regex issue, so the explain function never ran before. This has never been noticed before, because explain never ran.

Why the Explain caused a problem I could not find out yet. After some debugging, I found out that at least the correct ID of eloquent comes back. But somewhere this must have been discarded again.

For the moment, I would first adapt the documentation in the config that explain should not be used until we find the cause.

**Comment by barryvdh** [comment]
Okay I think we should probably only allow select then for now. Anyone up for a PR? Otherwise I'll take a look soonish

**Comment by hrs-o** [comment]
@barryvdh I was late for noticing but how is this PR? #903

And I checked the behavior of PDO.
From the output of this code, you can see that lastInsertId becomes 0 with EXPLAIN.
Therefore, if `QueryCollector::addQuery` is called before obtaining lastInsertId, will be 0.

```php
<?php
try {
    $pdo = new PDO('mysql:host=localhost;dbname=root', 'root', 'root');
    $mail = time();
    $insertQuery = <<<SQL
INSERT INTO `users` (`name`, `email`, `password`)
VALUES
	('name', $mail, 'pass');
SQL;
    $pdo->query($insertQuery);

    $beforeId = $pdo->lastInsertId('id');
    $explainQuery = "EXPLAIN {$insertQuery}";
    $pdo->query($explainQuery);
    $afterId = $pdo->lastInsertId('id');


    echo "before: {$beforeId}" . PHP_EOL;
    echo "after: {$afterId}";
} finally {
    $pdo = null;
}
```

**Comment by barryvdh** [comment]
Yeah so no way around that I suppose (or we'd have to do it BEFORE). But probably best to disable it for update/delete/insert.

**Comment by ipontt** [comment]
Quick question: What does the `(...) for MySQL 5.6.3+` means in the comment that was added on the config file? Is this behavior not the same with PostgreSQL or SQLite?
