### ISSUE TITLE
Problem with LoggedIn named page

### ISSUE THREAD

**Issue by sudinem** [barryvdh/laravel-debugbar#890]
Hi,

I've one loggedInAs page which is for switching user i.e. to logged in as another user. The functionality stops working when I enable the debug bar. 

It overrides my defined url and sends the request to this url : 
http://localhost:8080/loggedInAs?method=&uri=&ip=

When I disable the debug bar, it  working fine. Its a strange problem. I resolved it by disabling debug bar on this particular method. 

I'm posting this as an issue to contribute in the developer's community. Happy Coding :)

**Comment by shira79** [comment]
Please see here. https://github.com/barryvdh/laravel-debugbar/issues/833#issuecomment-1073504598
