### ISSUE TITLE
Composer error in production

### ISSUE THREAD

**Issue by dimitriacosta** [barryvdh/laravel-debugbar#893]
I've been trying to run a composer install as the documentation explains here [Laravel Deployment](https://laravel.com/docs/5.7/deployment#optimization) with this command `composer install --optimize-autoloader --no-dev` but I am getting an error, I think it's because of the `--no-dev` flag because I've installed the package as a dev dependencie.

I think it would be better to change de dependencie as a normal dependencie but I was wondering if it is the only solution for this issue.

![screenshot from 2018-12-06 12-45-33](https://user-images.githubusercontent.com/5995547/49608892-2e5b3380-f957-11e8-9e5d-014e4fa1e4f0.png)

**Comment by mpryvkin** [comment]
See #921 for solution. Basically you need to remove the service provider (`Barryvdh\Debugbar\ServiceProvider::class`) from `config/app.php`.

**Comment by dimitriacosta** [comment]
Thank you @mpryvkin it worked
