### ISSUE TITLE
Random Exception - hasCollector does not exist

### ISSUE THREAD

**Issue by Evaske** [barryvdh/laravel-debugbar#899]
I've been using the debug bar without any issues for the last few weeks then all of a sudden today I have got two exceptions appearing that I can't work out where they're coming from or why they've suddenly appeared.

I initially thought it was my code causing it so rolled back a bit with Git but the error was still there. I've tried restarting the machine and also restarting Valet with no luck.

The errors aren't appearing on my staging environment at the moment, just my local development.

The exceptions are:

`Cannot add LogsCollector to Laravel Debugbar: Class hasCollector does not exist
/Users/Name/Development/Name/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#277`

`Class hasCollector does not exist
/Users/Name/Development/Name/vendor/laravel/framework/src/Illuminate/Container/Container.php#779
ReflectionException`

Using the following versions:

PHP: 7.3.0
Laravel: 5.7.20
Debug-bar: 3.2.1

**Comment by kofoworola** [comment]
Any help with this?
