### ISSUE TITLE
Can you use debugbar on routes that do not return a view?

### ISSUE THREAD

**Issue by randohinn** [barryvdh/laravel-debugbar#900]
I would like to use this package to debug some of my routes, that do not return a view, and instead, do something like this, from inside a controller

```php
public function show(Request $request) {
    $page = Page::whereSiteId($request->input('site-id'))->whereSlug($request->input("page-slug"))->first();
    $blocks = Block::whereSiteId($request->input("site-id"))->wherePageId($page->id)->get();
    return $blocks;
}
```
Is it possible to have debugbar appear on these kinds of routes as well?

**Comment by barryvdh** [comment]
If it's HTML, the debugbar is added.
