### ISSUE TITLE
Info, addMessage or any of the other specified messages do not exist / work

### ISSUE THREAD

**Issue by btassone** [barryvdh/laravel-debugbar#905]
So I can see them in the code in the package. Its added to composer, the DebugBar is showing up but I am unable to use any of the functions DebugBar::info, DebugBar::addMessage, etc

Tried adding via
```
use DebugBar\DebugBar;

and

use DebugBar
```

The latter one says Class not found. So not sure what im doing wrong here or this just doesnt work anymore. Composer routes are psr4 not sure that has anything to do with it since in the docs it talks about psr3. Can anyone help?

**Comment by shawndibble** [comment]
Did you find the solution to this? I am also experiencing the same thing.
