### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by leewillis77** [barryvdh/laravel-debugbar#909]
Currently this package is uninstallable on Laravel 5.8.

**Comment by barryvdh** [comment]
Fixed https://github.com/barryvdh/laravel-debugbar/releases/tag/v3.2.3

**Comment by drewjoh** [comment]
THANK YOU Barry for your super fast response and update!  You're amazing!  Keep up the great work. 💪🏼🙇🏼‍♂️

**Comment by leewillis77** [comment]
Awesome, thanks!

**Comment by JBreit** [comment]
I couldn't get version 3.2.3 to work.  Am I doing something wrong perhaps? Where there changes to the configuration that the documentation doesn't show? I normally don't have issues with this package. Is the 3.2.3 still unstable and that why I can't get it to work?

**Comment by Dannymx** [comment]
Still broken with Laravel 5.8.15

**Comment by leewillis77** [comment]
Debugbar working fine here on Laravel 5.8.15. 

@Dannymx When you say it's "broken" can you provide some more information about what exactly isn't working.

**Comment by Dannymx** [comment]
@leewillis77 Fresh install of Laravel and Debugbar, and .env set to `APP_DEBUG=true`. I cannot get the Debugbar to show up.

**Comment by leewillis77** [comment]
That definitely works for me. I just did the following:

```
$ laravel new dbartest
$ cd dbartest
$ composer require barryvdh/laravel-debugbar
```

Viewing the resulting Laravel site shows up the debugbar just fine.

Maybe some other issue is affecting things for you? (composer config / outdated installer / PHP version / local config). How are you testing this?

**Comment by leewillis77** [comment]
Can you reproduce with a fresh Laravel install (as per my example)?

My guess is that another package you have installed is interfering or you have some stale config or similar that's affecting things. Either way, I can confirm that debugbar v3.2.3 works fine out-of-the-box with Laravel 5.8.15.

**Comment by leewillis77** [comment]
Give that's the case, I'm going to close this issue (since the original problem has long since been resolved). If you're still having issues on a fresh install @Dannymx I'd suggest opening a fresh issue with as much information about your setup as you can muster. Good luck!

**Comment by afsarpervez** [comment]
> Fixed https://github.com/barryvdh/laravel-debugbar/releases/tag/v3.2.3

I don't know how to install from the downloaded source file (stored in my local drive). 
However, I tried it from composer through _composer require barryvdh/laravel-debugbar:3.2.3 --dev_   and it works. Now the interface appears in the browser too.

**Comment by najathi** [comment]
composer require barryvdh/laravel-debugbar:3.2.3 --dev

**Comment by SuganyaUitoux** [comment]
Hi,
I am not able to view all the queires using Laravel Debugger. Only few are getting displayed. Can you please help me with this.

Laravel - 5.8 
Debugger - 3.4

**Comment by afsarpervez** [comment]
> Hi,
> I am not able to view all the queires using Laravel Debugger. Only few are getting displayed. Can you please help me with this.
> 
> Laravel - 5.8
> Debugger - 3.4

try this
composer require barryvdh/laravel-debugbar:3.2.3 --dev

**Comment by khalilahmad2894** [comment]
@afsarpervez  
your awnser was so accurate and concise.
solved my problem instantly
thank you

**Comment by razaqofficial** [comment]
> `composer require barryvdh/laravel-debugbar:3.2.3 --dev`
> 
> or
> 
> `composer require barryvdh/laravel-debugbar:~3.2 --dev`

Thanks

**Comment by khalilahmad2894** [comment]
Thanks
