### ISSUE TITLE
Cannot add ViewCollector to Laravel Debugbar

### ISSUE THREAD

**Issue by RicardoRamirezR** [barryvdh/laravel-debugbar#912]
Hi there, what I'm missing? any clues

![captura de pantalla 2019-02-27 a la s 9 57 02 p m](https://user-images.githubusercontent.com/6526545/53538262-f50c0d00-3ada-11e9-8f37-318900020dd8.png)

Laravel: 5.8.2, 5.7.28
Laravel Debugbar: v3.2.3

**Comment by shatterproof** [comment]
Tried everything to resolve this, restarting computer as a last resort finally seems to have done it.
