### ISSUE TITLE
Lumen 5.8.1 & laravel-debugbar 3.2.3 didn't work

### ISSUE THREAD

**Issue by Stanislav2014** [barryvdh/laravel-debugbar#915]
Do this instruction:

>For Lumen, register a different Provider in bootstrap/app.php:
if (env('APP_DEBUG')) {
 $app->register(Barryvdh\Debugbar\LumenServiceProvider::class);
}
To change the configuration, copy the file to your config folder and enable it
$app->configure('debugbar');

but didn't work. 

In Laravel 5.8 work correctly

**Comment by Jaswinder00** [comment]
I am experiencing the same issue. I am thinking about downgrading Lumen to 5.7 if this does not work

**Comment by Stanislav2014** [comment]
on Lumen 5.7 didn't work to

**Comment by Jaswinder00** [comment]
Yeah, It did not work for me either. I hope we find a solution.

**Comment by Jaswinder00** [comment]
Anyone got this to work?

**Comment by luisfigook** [comment]
for lumen5.7,  add a file "app.php" in "config" folder, add a line  "'debug' => env('APP_DEBUG', true)", then it will work.
reasan see the debugbar ServiceProvider.php code ` /**

       // this line get the config from config/app.php 
       if (!$this->app['config']->get('app.debug')) {
            return;
        }
        
        $configPath = __DIR__ . '/../config/debugbar.php';
        $this->publishes([$configPath => $this->getConfigPath()], 'config');

        $routeConfig = [
            'namespace' => 'Barryvdh\Debugbar\Controllers',
            'prefix' => $this->app['config']->get('debugbar.route_prefix'),
            'domain' => $this->app['config']->get('debugbar.route_domain'),
            'middleware' => [DebugbarEnabled::class],
        ];
`

**Comment by Jaswinder00** [comment]
Tried, but did not work. Any other solution?

**Comment by litianhan** [comment]
Try this:
if (env('APP_DEBUG')) {
$app->configure('app');
$app->configure('debugbar');
$app->register(Barryvdh\Debugbar\LumenServiceProvider::class);
}

**Comment by bryanlopezinc** [comment]
Same issue.  Recommended solutions not working

**Comment by bryanlopezinc** [comment]
Still no fix?

**Comment by pifeifei** [comment]
on  Laravel Framework 5.8.14    didn't work to

**Comment by Dannymx** [comment]
Doesn't work on Laravel Framework 5.8.13

**Comment by Jimmea** [comment]
Not working on new lastest lumen 5.8

**Comment by thebennies** [comment]
updating bootstrap/app.php work for me:
```
    if (env('APP_DEBUG')) {
        $app->configure('app');
        $app->configure('debugbar');
        $app->register(Barryvdh\Debugbar\LumenServiceProvider::class);
    }
```
no need to create config/app.php.
using laravel-debugbar (3.2) on Lumen (5.8.12) (Laravel Components 5.8.*) PHP (7.3.8)

**Comment by huzhangzheng** [comment]
lumen5.8 can work,but i cant get sql on the message board

**Comment by salvationarinze** [comment]
How can I use the debugbar display on the browser when lumen is the api backend?

**Comment by bryanlopezinc** [comment]
Maybe you should try telescope
