### ISSUE TITLE
Extra debug bar displaying in iframe

### ISSUE THREAD

**Issue by bkno** [barryvdh/laravel-debugbar#916]
I have an iframe on the page (src is external app) but debugbar is present on both the parent window (Laravel app) and in the iframe.

Is it possible to prevent it appearing in the iframe?

**Comment by RashidAliAnsari** [comment]
> I have an iframe on the page (src is external app) but debugbar is present on both the parent window (Laravel app) and in the iframe.
> 
> Is it possible to prevent it appearing in the iframe?

hello friend... 
how you solve it ??? i have same problem!
