### ISSUE TITLE
Laravel Nova > partial support

### ISSUE THREAD

**Issue by preliot** [barryvdh/laravel-debugbar#920]
Debugbar is not working properly with Laravel Nova. Views and Gate show information for a second and then they are cleared.

laravel/framework: 5.8.*
laravel/nova: 2.0.0

**Comment by barryvdh** [comment]
Debugbar follows Ajax requests, so upon new requests the data switches. But you can select the previous request in the drop-down on the right.

**Comment by preliot** [comment]
Thanks @barryvdh. This solves my issue.

If possible, i would prefer to see them in one place, perhaps grouped by request. Now it is confusing if you don't now this.

**Comment by osamaAbdullah** [comment]
@barryvdh thank you
