### ISSUE TITLE
Removing debugbur corrupted whole project...

### ISSUE THREAD

**Issue by Kovanija** [barryvdh/laravel-debugbar#921]
First of all, I have to say that this tool brings much power, but this tool is completely shit when we talk about integration and REMOVING.

Removing barryvdh corrupted whole project with one line of code : 
composer remove barryvdh/laravel-debugar

I cannot use php artisan serve, php artisan config:cache, I cannot use NOTHING and I get

![image](https://user-images.githubusercontent.com/21163851/55289245-2de21f00-53c4-11e9-91d0-62e74a67427b.png)

What is wrong in this, @barryvdh ? Always problem with this one all the time in every project.

Also, I cannot fix this even if I remove whole vendor directory and use composer install or update.

I removed it from every line in project including config/app.

**Comment by Kovanija** [comment]
[2019-03-31 12:46:30] local.ERROR: Class 'Barryvdh\Debugbar\ServiceProvider' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Barryvdh\\Debugbar\\ServiceProvider' not found at C:\\Users\
eman\\epicfantasyshop\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php:208)

This is the error I get in log file, as I see it is in vendor. But even removing vendor and doing composer install does nothing about this. Also, composer.json is also fine.

**Comment by Kovanija** [comment]
![image](https://user-images.githubusercontent.com/21163851/55289788-76e9a180-53cb-11e9-8d91-95b622020e18.png)

**Comment by barryvdh** [comment]
Remove the service provider from config/app.php. Since Laravel 5.5 you don't need to add it all, it's auto discovered.
