### ISSUE TITLE
Laravel Validation Errors Not Displayed in Session Tab

### ISSUE THREAD

**Issue by pridly** [barryvdh/laravel-debugbar#926]
The validation error messages used to display in the debugbar's session tab but now it is not visible while other variables are present as they should. But when I `dd(session()->all())`. The error bag is there and displays all the validation errors and messages as expected.

I suspect it happened after upgrading to Laravel 5.8 from 5.7. 
Please Help.

Currently Using Laravel 5.8.14
Debugbar 3.2.3
On WIndows 10

**Comment by joveice** [comment]
Same here.
Laravel 5.8.14
Debugbar 3.2.3
Fedora 29
Php 7.2.14

**Comment by NEGits** [comment]
Here too.

-Laravel 5.8.23
-Debugbar 3.2.4
-PHP Version: 7.2.17
-Ubuntu 18.04.2 LTS

**Comment by Wulfheart** [comment]
Any progress on this?

**Comment by aleksandrkorchak** [comment]
Similarly:
-Laravel 5.8.33
-Debugbar 3.2.7
-Homestead (Ubuntu 18.04, PHP 7.3.7)

return back()
                ->withErrors(['msg' => "Error message"])
                ->withInput();

![1](https://user-images.githubusercontent.com/8844643/64185347-a8cccb80-ce75-11e9-82e6-eefc0639e918.png)

**Comment by akihizashi** [comment]
Here too.

-Laravel 6x
-Debugbar 3.2.x
-PHP Version: 7.3.10
-Ubuntu 18.04.2 LTS

**Comment by pridly** [comment]
It's more than an year since I posted the issue, but no progress...the issue still persists in the latest version.

**Comment by ahmed-aliraqi** [comment]
@barryvdh any progress on this?

**Comment by evd1ser** [comment]
Hello!
I found the solution (not brilliant but works)
in file `Http/Kernel.php` move Middlewares:
```
\Illuminate\Session\Middleware\StartSession::class,
\Illuminate\View\Middleware\ShareErrorsFromSession::class,
```
from $middlewareGroups => ['web'=>[/\* was here \*/]]
to protected $middleware = [/\* now moved to this place \*/]

<img width="635" alt="Снимок экрана 2020-09-05 в 14 19 05" src="https://user-images.githubusercontent.com/15332093/92303994-c221bf80-ef82-11ea-9118-630cadb7bd69.png">


and errorBag show in session:
<img width="1680" alt="Снимок экрана 2020-09-05 в 14 14 20" src="https://user-images.githubusercontent.com/15332093/92303964-84bd3200-ef82-11ea-8b60-337290549651.png">

**Comment by waiyan13** [comment]
@evd1ser It's an ugly hack but it works. So when we go for production, can we move those back since debugbar is only meant for development?

**Comment by evd1ser** [comment]
> @evd1ser It's an ugly hack but it works. So when we go for production, can we move those back since debugbar is only meant for development?

Yes, its only for Debugbar work =)

**Comment by waiyan13** [comment]
Still wish it is patched in future versions of debugbar.

**Comment by barryvdh** [comment]
Not really sure, so the issue is that validation errors are never visible?

**Comment by waiyan13** [comment]
The usecase I have is for ensuring `QueryException` is handled properly. In my `UserController`,

```
try {
    // This will throw QueryException
    $newUser = $this->userService->saveUser($userInfo);
} catch(\Throwable $e) {
    return redirect()
        ->route('dashboard.user.showForm')
        ->withError('Something went wrong. Please contact your administrator');
}

```
Something like this. So if I don't do as @evd1ser as suggested, that error message never shows up.

**Comment by NEGits** [comment]
The problem is that session variables end up seem to end up in the wrong request.

Suppose I edit some model. First I do a GET request to the Model/Edit route. Then I do a POST request to the Model/Update route. This generates an error, which generates another GET request to the Model/Edit route:

![Screenshot 2020-09-09 at 10 43 38](https://user-images.githubusercontent.com/33746490/92576089-63618c00-f289-11ea-8d82-c0c0bbdd236f.png)

What used to happen (a couple of Laravel versions ago I guess) was that the error messagebag and the old input and other session variables would be visible in Debugbar in the second GET request, which is automatically displayed after the error is generated and you are redirected, because it was the last request of course.

This isn't the case anymore. They now end up in the POST request, which you manually have to open in Debugbar.

**Comment by HapLifeMan** [comment]
Hey @barryvdh any news on this? Would be appreciated to solve this bug 😊

**Comment by emmanuelbarturen** [comment]
i found the solution! 
errors appears in stacked item
![image](https://user-images.githubusercontent.com/11076563/123555235-184a3400-d74a-11eb-81ab-c8f944e177fa.png)

**Comment by leecolarelli** [comment]
> i found the solution!
> errors appears in stacked item
> ![image](https://user-images.githubusercontent.com/11076563/123555235-184a3400-d74a-11eb-81ab-c8f944e177fa.png)

My debugbar does not have a dropdown where shown in your screenshot.

**Comment by kossa** [comment]
> Hello! I found the solution (not brilliant but works) in file `Http/Kernel.php` move Middlewares:
> 
> ```
> \Illuminate\Session\Middleware\StartSession::class,
> \Illuminate\View\Middleware\ShareErrorsFromSession::class,
> ```
> 
> from $middlewareGroups => ['web'=>[/* was here */]] to protected $middleware = [/* now moved to this place */]
> 
> <img alt="Снимок экрана 2020-09-05 в 14 19 05" width="635" src="https://user-images.githubusercontent.com/15332093/92303994-c221bf80-ef82-11ea-9118-630cadb7bd69.png">
> 
> and errorBag show in session: <img alt="Снимок экрана 2020-09-05 в 14 14 20" width="1680" src="https://user-images.githubusercontent.com/15332093/92303964-84bd3200-ef82-11ea-8b60-337290549651.png">

Works fine but any risk about changing middlewares?
