### ISSUE TITLE
Uncaught TypeError: PhpDebugBar.Widgets.TemplatesWidget is not a constructor

### ISSUE THREAD

**Issue by snowlyg** [barryvdh/laravel-debugbar#930]
Uncaught TypeError: PhpDebugBar.Widgets.TemplatesWidget is not a constructor

**Comment by OzanKurt** [comment]
What was the problem?

**Comment by snowlyg** [comment]
@OzanKurt Sorry,  I don't remeber it now.

**Comment by OzanKurt** [comment]
All good found it. 😄 

Just cleared the Application Cache from Chrome.

**Comment by snowlyg** [comment]
@OzanKurt :laughing:
