### ISSUE TITLE
Javascript Error: Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by xJoeyv** [barryvdh/laravel-debugbar#934]
Hi,

I just installed Debugbar and I get a JS error. Does any1 know the issue?
```
Uncaught SyntaxError: Unexpected token <
``` 
_http://project.test/_debugbar/assets/javascript?v=1559914473_

**Comment by NastuzziSamy** [comment]
Got the same here with Laravel 5.8

**Comment by sngrl** [comment]
Got the similar error on Laravel 5.5, 5.6, 5.8 at /_debugbar/assets/javascript
`.replace(>/gm,"&gt;")`

**Comment by sngrl** [comment]
Find the problem: don't use RenatoMarinho\LaravelPageSpeed middlewares in app/Http/Kernel.php
