### ISSUE TITLE
Storage gets to 656 MB

### ISSUE THREAD

**Issue by dragonfire1119** [barryvdh/laravel-debugbar#94]
I was looking at my application and I noticed that the size of my app is huge. So I narrowed it down to app/storage/debugbar witch ways in at 656 MB witch is huge. Are all these .json needed? Is there anyway to put a cleaner that cleans these out sometimes so they don't stack up like this? I also notice that the app bogs down sometimes with the debugbar on.

**Comment by ElsayedAhmed19** [comment]
How can I retrieve logged data from storage files? @barryvdh

**Comment by barryvdh** [comment]
Click the browse button on the debugbar

**Comment by abrhambas01** [comment]
Hey is there anyway we can stop debugbar from producing this .json files ?  Cause I believe there's no use to it as for me personally , because I'm just a dumb end user..

**Comment by Nurulpro** [comment]
when I Use It in a function it not working 
Artisan::call('debugbar:clear');

**Comment by jonjieviduya** [comment]
I know this is too late to answer, but here's how I solved it.

1. Run `php artisan debugbar:clear` to clear all the json files, or simply delete the debugbar directory inside the storage directory.

2. Publish the config file using the command below:
`php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"`

3. Set `enabled` to false, like so:
```
'storage' => [
    'enabled'    => false,
    'open'       => env('DEBUGBAR_OPEN_STORAGE'), // bool/callback.
    'driver'     => 'file', // redis, file, pdo, socket, custom
    'path'       => storage_path('debugbar'), // For file driver
    'connection' => null,   // Leave null for default connection (Redis/PDO)
    'provider'   => '', // Instance of StorageInterface for custom driver
    'hostname'   => '127.0.0.1', // Hostname to use with the "socket" driver
    'port'       => 2304, // Port to use with the "socket" driver
]
```

**Comment by AlexMordred** [comment]
We have multiple projects with debugbar on a single server. I just noticed that the server is running out of disk space and decided to check what takes up space. Turns out the `/storage/debugbar` folders in those projects take up 16GB each. I don't think this is normal.

**Comment by AlexMordred** [comment]
We have multiple projects with debugbar on a single server. I just noticed that the server is running out of disk space and decided to check what takes up space. Turns out the `/storage/debugbar` folders in those projects take up 16GB each. I don't think this is normal.

I checked the setting to disable the storage but it says "You can disable this, so the debugbar stores data in headers/session, but this can cause problems with large data collectors.", so I'm not sure if disabling the storage will be safe since it led to 16GB of json files in the first place.

**Comment by parallels999** [comment]
maybe https://github.com/php-debugbar/php-debugbar/issues/726#issuecomment-2688278182

Also, you shouldn't have the debugbar active all the time, much less on your production server.
debugbar consumes resources and slows down the application.

**Comment by barryvdh** [comment]
hmm but it should automatically delete it, right? https://github.com/barryvdh/laravel-debugbar/blob/a6bbe5d8b8bb907de06d080e7b2ccbe515d76151/src/Storage/FilesystemStorage.php#L50

**Comment by barryvdh** [comment]
I did some tests and for me it deletes everything after 24 hour. Not every request, but 5/100 so 5% chance. So to get to 16GB, you either have it enabled on some live/production site (which I definitely do NOT recommend) or something is going wrong with the garbage collection.

**Comment by parallels999** [comment]
>something is going wrong with the garbage collection.

It never worked for me. `logrotate` did the trick for me

**Comment by barryvdh** [comment]
> > something is going wrong with the garbage collection.
> 
> It never worked for me. `logrotate` did the trick for me

With the laravel-debugbar version? the php-debugbar does not have garbagecollect.

Could you check if the garbage collect fails for some reason? Although I would expect an error in that case.

**Comment by parallels999** [comment]
> With the laravel-debugbar version?

Current [v3.16.0](https://github.com/barryvdh/laravel-debugbar/releases/tag/v3.16.0)

> the php-debugbar does not have garbagecollect.

i know that

> Could you check if the garbage collect fails for some reason? Although I would expect an error in that case.

Since logrotate already fixed it, I haven't bothered to check the actual error, I'll do it when I have time.

**Comment by parallels999** [comment]
Ok, I tried increasing `$gc_probability` to 100 and it works, I think it's just a matter of luck.  🤷
