### ISSUE TITLE
Class 'Barryvdh\Debugbar\LumenServiceProvider' not found

### ISSUE THREAD

**Issue by AlexandrIgn** [barryvdh/laravel-debugbar#941]
I use Lumen 5.8 with Debugbar. I'm set app.php: 
`'if (env('APP_DEBUG')) {
$app->configure('app');
   $app->configure('debugbar');
   $app->register(Barryvdh\Debugbar\LumenServiceProvider::class);
   }'`
And change config.debugbar.collectors.auth to false. In the local environment, the panel is displayed and everything works. But after deploying to heroku: 

> Class 'Barryvdh\Debugbar\LumenServiceProvider' not found. 

How can I fix this?

**Comment by barryvdh** [comment]
You're not supposed to use it in production. You probably have installed it as dev only and that's why it's missing in Heroku.
