### ISSUE TITLE
can debugbar show recent logs? like yii2-debug

### ISSUE THREAD

**Issue by scau009** [barryvdh/laravel-debugbar#942]
like this 
![image](https://user-images.githubusercontent.com/18747266/60696082-c5509400-9f16-11e9-83bf-2b4c9bdfe77b.png)
we can get recent debug datas but not only one request

**Comment by agravelot** [comment]
I think this button will be your best friend 
![image](https://user-images.githubusercontent.com/13699253/61721579-f4656300-ad68-11e9-83ee-8cd0953f6cae.png)

**Comment by barryvdh** [comment]
Yes indeed, you can browse/filter old requests.
