### ISSUE TITLE
TypeHint Error - Unusable

### ISSUE THREAD

**Issue by laurenwilliams92** [barryvdh/laravel-debugbar#943]
"message": "Argument 2 passed to Barryvdh\\Debugbar\\LaravelDebugbar::modifyResponse() must be an instance of Symfony\\Component\\HttpFoundation\\Response, instance of Illuminate\\View\\View given, called in /var/www/lauren.admin.jtc.dev.helastel.net/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php on line 74",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",

**Comment by barryvdh** [comment]
Do you have any middleware or special responses? A view should be converted to a Response before it gets to the debugbar.

**Comment by laurenwilliams92** [comment]
No, no middleware or special responses. Just installed straight out of the box, the example page does not work either.

On 11 Aug 2019, at 21:08, Barry vd. Heuvel <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have any middleware or special responses? A view should be converted to a Response before it gets to the debugbar.
