### ISSUE TITLE
Debugbar not showing in Laravel 5.8 + Caffeinated Modules

### ISSUE THREAD

**Issue by sidneycorreia** [barryvdh/laravel-debugbar#951]
Debugbar not showing in views inside modules

![image](https://user-images.githubusercontent.com/9578259/62938844-40268d80-bda6-11e9-92f6-fbf5ae40b2b1.png)

![image](https://user-images.githubusercontent.com/9578259/62938877-4e74a980-bda6-11e9-9ee7-40a7c6713590.png)

**Comment by barryvdh** [comment]
What is 'Caffeinated Modules' ?

**Comment by sidneycorreia** [comment]
Is a package that allow creates "mini-laravel" structures to organize application. https://caffeinatedpackages.com/guide/packages/modules.html

**Comment by skyroot1000** [comment]
Please try
php artisan route:clear

It works for me.
