### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by alphametric** [barryvdh/laravel-debugbar#953]
This package is currently not able to be installed in v6 of Laravel.

**Comment by barryvdh** [comment]
Just because of composer or is something broken? It's not released yet, is it?

**Comment by alphametric** [comment]
Just composer. Not out yet but I’m August.

**Comment by barryvdh** [comment]
Then please create an PR to add it.

**Comment by barryvdh** [comment]
Added in https://github.com/barryvdh/laravel-debugbar/commit/e43aa86bb3a92cea79f84ab268fbd038c0869e63

**Comment by alphametric** [comment]
Thanks :)
