### ISSUE TITLE
Undefined Offset: 1 caused by MultiAuthCollector.php

### ISSUE THREAD

**Issue by chops888** [barryvdh/laravel-debugbar#955]
After migrating to 5.8, Laravel doesnt seem to set the recaller cookie at all. In any case, when debugbar loads, it tries to get the user by token, without validating the token first. Problem is in src/DataCollector/MultiAuthCollector.php -- notice is thrown in $recaller->token(), as there is no string to explode.

Broken code: 
        `
if ($guard instanceof SessionGuard) {

            $recaller = new Recaller($guard->getRequest()->cookies->get($guard->getRecallerName()));

            $provider = $this->auth->createUserProvider($config['provider']);
            $user = $provider->retrieveByToken($recaller->id(), $recaller->token());
            if ($user) {
	            return $user;
            }
            
        }
`

Fixed code with validation of recaller cookie string:

`
if ($guard instanceof SessionGuard) {

            $recaller = new Recaller($guard->getRequest()->cookies->get($guard->getRecallerName()));

            if($recaller->valid()){
	            $provider = $this->auth->createUserProvider($config['provider']);
	            $user = $provider->retrieveByToken($recaller->id(), $recaller->token());
	            if ($user) {
		            return $user;
	            }
            }
            
        }
`

**Comment by barryvdh** [comment]
I'm going to disable this collector until is fixed in an easy/reliable way.

**Comment by barryvdh** [comment]
So like this: https://github.com/barryvdh/laravel-debugbar/commit/bf19d9362d0efd1e97c67a76f13f8085953bbbbd

**Comment by barryvdh** [comment]
Should be good
