### ISSUE TITLE
Incompatible with Laravel 6

### ISSUE THREAD

**Issue by BrandonSurowiec** [barryvdh/laravel-debugbar#956]
Since Laravel 6 no longer uses the `str_` and `arr_` helpers every instance will need to be updated to use the Arr:: and Str:: classes directly.

**Comment by barryvdh** [comment]
Okay, can you send a PR?

**Comment by BrandonSurowiec** [comment]
Yep. Won't get to it until tonight.

**Comment by BrandonSurowiec** [comment]
Didn't take very long, so I made the PR: #957

**Comment by barryvdh** [comment]
Thanks!

**Comment by BrandonSurowiec** [comment]
No problem! There were no `array_` helpers used.
