### ISSUE TITLE
V3.2.6 still cannot be installed with Laravel 6

### ISSUE THREAD

**Issue by DesmondPang** [barryvdh/laravel-debugbar#958]
**LaravelDebugbar.php:101** 
` $this->is_lumen = str_contains($this->version, 'Lumen');`

There is a **str_contains** function which causes error when Composer calls Illuminate\Foundation\ComposerScripts::postAutoloadDump during installation.

**Comment by barryvdh** [comment]
Should already be fixed with latest Dev version

**Comment by barryvdh** [comment]
And tagged
