### ISSUE TITLE
Models Collector - Renders wrong if too many model types detected

### ISSUE THREAD

**Issue by zack6849** [barryvdh/laravel-debugbar#961]
Hey There!

I saw @reinink 's talk and was really excited to get my hands on this PR, because it looked really helpful

Thanks for the addition by the way, it looks great, but there is a slight rendering issue.

If i'm on a  page with only like 2 types of models loading, it looks fine, like so:

![Screenshot_2019-08-26-1](https://user-images.githubusercontent.com/1343898/63692972-e039d900-c7e0-11e9-93a6-e50c1ff1c8dd.png)

However, when I load a complicated page with a lot of models (This one is just a report, a pretty bad one i'm working on, mind you), it look like this:

![Screenshot_2019-08-26 Screenshot](https://user-images.githubusercontent.com/1343898/63692983-e7f97d80-c7e0-11e9-8d50-3bd45a55ec58.png)

Notably, the numbers are acting funky and rendering on lines funny, and i'm not even sure what's going on with the bottom bar there

It's still functional, just looks weird, thought I might let you guys know!

**Comment by hmshafeeq** [comment]
@reinink Adding further, I have noticed the same behavior on Firefox, it works fine on chrome. 

![image](https://user-images.githubusercontent.com/6695370/63758800-c7f7b600-c8d5-11e9-8c60-5dc6fd01e9fb.png)

Thanks for adding this wonderful module in laravel debugbar.

**Comment by CedNet** [comment]
I still see this issue in the latest version 3.3 (just upgrade from 3.2). 

I'd appreciate a 2nd look into this.

![image](https://user-images.githubusercontent.com/1974807/81146959-9a413180-8f79-11ea-8fcd-a3747709fdd2.png)

**Comment by barryvdh** [comment]
@CedNet I think this is a different issue. Please create a new issue.

The models collector layout is updated.
