### ISSUE TITLE
How to display hydrated models?

### ISSUE THREAD

**Issue by marvix** [barryvdh/laravel-debugbar#964]
Hello,

I could not find a way to display the "hydrated models", is it released?

Thanks,

**Comment by barryvdh** [comment]
Enable it in the config: https://github.com/barryvdh/laravel-debugbar/blob/master/config/debugbar.php#L125

**Comment by marvix** [comment]
I enabled before my first post. I'm using version 3.2, is this right version?

Thanks,
![image](https://user-images.githubusercontent.com/3768431/64204032-9070a700-ce9d-11e9-9dcd-fe4a1f02ae76.png)

![image](https://user-images.githubusercontent.com/3768431/64204092-b433ed00-ce9d-11e9-9bc5-dd224fb65431.png)

**Comment by barryvdh** [comment]
Think so yeah

**Comment by marvix** [comment]
Did not work!

**Comment by MarcinDyszkiewicz** [comment]
I have the same issue. I'm using version v3.2.8 and laravel 6.3

**Comment by gagelafleur** [comment]
Jonathan Reinink mentioned the Hydrated Modules part of the bar in a tweet from 7/22/19 

> "To help illustrate performance issues better during my LaraconUS talk, I've added a custom Laravel Debugbar metric called "hydrated models". It provides a quick count of how many Eloquent models were created during a request...which can have a huge impact on performance. "

Sounds like something he set up himself and that it may or may not end up making in into the package.

**Comment by SagarNaliyapara** [comment]
@reinink how we can have Models tab?

**Comment by SagarNaliyapara** [comment]
Add following in `config/debugbar.php` in `collectors` array
```
'models' => true,
```

then run following command and you'll have models tab,
```
php artisan cache:clear
php artisan config:cache
```
