### ISSUE TITLE
Larvel version

### ISSUE THREAD

**Issue by parnissolle** [barryvdh/laravel-debugbar#966]
Same way that `PhpInfoCollector` does for PHP version, could we have an entry for Laravel version in the widget?
Thanks.

**Comment by barryvdh** [comment]
Should be there; https://github.com/barryvdh/laravel-debugbar/blob/master/src/DataCollector/LaravelCollector.php

**Comment by parnissolle** [comment]
Exactly! I missed out the step to run `php artisan vendor:publish` to override the config.
Thanks 👍
