### ISSUE TITLE
Widget icon

### ISSUE THREAD

**Issue by parnissolle** [barryvdh/laravel-debugbar#968]
Why not using the real Laravel logo?
Maybe somthing like `fa-laravel` or something way close with the new trademark logo...

Part of code found in this file: `src/DataCollector/LaravelCollector.php`
```php
...
"version" => [
        "icon" => "github",
        "tooltip" => "Version",
        "map" => "laravel.version",
        "default" => ""
],
...
```

**Comment by barryvdh** [comment]
Yeah it didn't exist in the first Don't Awesome versions
