### ISSUE TITLE
Exclude Debugbar on Staging, but keep debug true

### ISSUE THREAD

**Issue by jasperf** [barryvdh/laravel-debugbar#969]
Locally we have

```
APP_DEBUG=true
APP_LOG_LEVEL=debug
```

which would work for Debugbar. On staging we have this too as we do want to see what goes wrong there. On production we turned it off of course.. 

But question here is, can I not show Debugbar on staging? Or do I simply not have to worry as `composer require barryvdh/laravel-debugbar --dev` simply only runs on localhost? I am using Valet with a custom .test url. Would love to use Debugbar there, just not on staging.

Thanks for the feedback!

**Comment by jonathanpel** [comment]
Late answer, but In your config/debugbar.php you should have "'enabled' => env('DEBUGBAR_ENABLED', null)," set by default.
With that, you should be able to add "DEBUGBAR_ENABLED=false" in your .env file on your staging setup to disable debugbar only there.

**Comment by jasperf** [comment]
@jonathanpel Thanks for the explanation. Better late than never as they say. Did not know about / did not think about the option to set it as `null` in the `config/debugbar.php` Thanks man!
!

**Comment by jasperf** [comment]
For others. Do `php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"` to have debugbar.php in your config directory as explained in the README.md file.
