### ISSUE TITLE
How to hide database credentials?

### ISSUE THREAD

**Issue by emergingdzns** [barryvdh/laravel-debugbar#977]
I can't figure out how to hide the database credentials. I'd really rather not expose that information, even locally. It's dangerous for it to even be an option.

**Comment by tomandersen** [comment]
Agreed. We would like to occasionally turn on debugbar on say an ngrok server, or a staging server, but the entire ENV comes down....

**Comment by Bulliby** [comment]
Maybe you can try https://laravel.com/docs/6.x/configuration#hiding-environment-variables-from-debug ?

**Comment by tomandersen** [comment]
Thanks! Not 100% useful, as I don’t really need to echo ANY env out to debug_bar, exceptions, etc. 

So a whitelist would be better, also if the black list supported wildcards, etc.

I know its not a debug bar thing 

—tom
