### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by farshadff** [barryvdh/laravel-debugbar#978]
hi are there any plan for making this very usefull package to work with laravel 6 ??

**Comment by barryvdh** [comment]
what doesn't work?

**Comment by farshadff** [comment]
When i try to install it on laravel 6 it throws error :
```
   - Installation request for laravel/framework 6.0 -> satisfiable by laravel/framework[v6.0.0].
    - Installation request for barryvdh/laravel-debugbar ^3.2 -> satisfiable by barryvdh/laravel-debugbar[3.2.x-dev, v3.2.0, v3.2.1, v3.2.2, v3.2.3, v3.2.4].
```

**Comment by farshadff** [comment]
that was solved i needed to refresh the terminal as it was just updated to laravel 6 it would not read the laravel for some reason . thanks
