### ISSUE TITLE
Profiling artisan commands

### ISSUE THREAD

**Issue by bkuhl** [barryvdh/laravel-debugbar#98]
I'd like to use this module to profile our API, artisan commands, and other scripts that don't involve rendering any web visible pages.  Is there a way to spit some of this out to a log?

**Comment by aliazizi** [comment]
@barryvdh It's seem its removed, but the function is already exist
How to use it?

**Comment by mgralikowski** [comment]
I have no idea how to use `collectConsole` method but I have a simple workaround to profiling CLI command (see queries).

```
class ToolsController extends AdminController
{
    public function artisan($command)
    {
        return \Artisan::call($command);
    }
}
```

Put it somewhere and run from browser: _localhost/backend/tools/artisan/fatigue:notifications-set_

**Comment by wanderlusted18** [comment]
@barryvdh I`m new to DebugBar and struggling a bit with trying to profile an artisan command that runs for 5 mins. Could you please describe step by step how profiling with the capture_console option should work? 

@mgralikowski I also tried your workaround, but it does not work for me (AdminController is an unknown class), if I replace it with Controller, I got a route not found error. Could you please detail out the steps of your workaround? 

Many thanks both!

**Comment by mgralikowski** [comment]
@wanderlusted18 It is just a copy & paste from my personal project, just replace AdminController with a standard Laravel Controller. You don't even need a Controller, sth like this should be enough:

```php
Route::get('/artisan/{command}', function (Request $request, string $command) {
    return \Artisan::call($command);
});
```

**Comment by wanderlusted18** [comment]
@mgralikowski Thanks for the clarification, with your above suggestion I can trigger the artisan command from the browser. Unfortunately after 18-19 sec I get a "This page isn’t working localhost is currently unable to handle this request HTTP ERROR 500" I have the feeling the somehow the browser times out. I already set max_execution_time = 0 in the php.ini. From the command line, I can run the command without any problems (it takes 5 mins). Any idea why it does not get executed completely when triggered from the browser? Thanks!
