### ISSUE TITLE
Debugbar not showing on my js frontend

### ISSUE THREAD

**Issue by DimaBDV** [barryvdh/laravel-debugbar#980]
### End User Info
-- Laravel Version: 5.8.29

-- PHP Version: 7.2.10

-- Database Driver & Version: MySQL 5.7-x64

-- Web Server Driver & Version: NGINX 1.12 (openserver 5.2.2)

-- OS Driver and Version: Windows 10

___
#### nginx proxy config

location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://127.0.0.1:3000;
    }
    location ~(/api|/oauth) {
        root       "%hostdir%";
        index      index.php index.html index.htm;
	    try_files $uri $uri/ /index.php?$query_string;
    }
    access_log off;
    error_page 404 /index.php;
    sendfile off;

larvel-debugbar\config\debugbar.php
'except' => [
        'telescope*'
    ],
___
I dont see debugbar on my js client(frontend) and all api routes,
i tried drawing view (api controller > return view(...) ), but this not helped me succeed on this problem.
If i use `route web` debugbar is drawing, but this not uses my js client (frontend)

P.S. sorry if i copied closed issue. i don't found them

**Comment by skyroot1000** [comment]
Please try
php artisan route:clear

It works for me.

**Comment by DimaBDV** [comment]
> Please try
> php artisan route:clear
> 
> It works for me.

This not working for me.
My JS client is a separate server. I provided the nginx config. Laravel is a backend server.

**Comment by carlclone** [comment]
it can't be used as an api , because the bar is render by html

**Comment by barryvdh** [comment]
Correct
