### ISSUE TITLE
Is laravel-debugdar fully compatible with Laravel 6.*? 

### ISSUE THREAD

**Issue by kulvirKaur** [barryvdh/laravel-debugbar#981]
I want to know that this package is fully compatible with Laravel 6.* or not. Or are you going to publish any update in future in order to make it compatible with Laravel 6.* ?

**Comment by barryvdh** [comment]
I think it is.

**Comment by kulvirKaur** [comment]
So, I can update my Laravel app from 5.8 to 6.* version and this package will work fine with it, right?

**Comment by barryvdh** [comment]
I guess so.

**Comment by kulvirKaur** [comment]
Ok, thanks! But you doesn't seems to be sure about it.

**Comment by barryvdh** [comment]
Well I haven't used it much yet, but I didn't see any problems. Why not just install it and try?
