### ISSUE TITLE
[feature request] open detected file to an editor

### ISSUE THREAD

**Issue by erlangp** [barryvdh/laravel-debugbar#990]
currently debugbar is showing detected file for example like:

Views:
`layouts.auth (\resources\views\layouts\auth.blade.php)`

Route:
` \vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php:18-21`

i usually manually find and open that file in an editor.
i think is better if we able to directly click that line to open it in an editor.

here is an example implementation by other lib: https://github.com/facade/ignition/blob/1.13.0/resources/js/components/Shared/editorUrl.js

**Comment by raveren** [comment]
+1 just don't blindly copy the Ignition implementation - it uses hard coded configuration values for Phpstorm that don't work on Windows. Simply allow us to pass in our custom file link formats please <3

**Comment by erlangp** [comment]
@raveren i tried using sublime too.. but currently not working using the "subl://" :(

**Comment by erlangp** [comment]
I just tried to make a plugin for laravel-debugbar to open vscode via a button. only experiment :D https://packagist.org/packages/erlangparasu/laravel-debugbar-vscode

**Comment by raveren** [comment]
Yo, changed a minor thing in code by @erlangp now it works with PhpStorm:

https://github.com/raveren/laravel-debugbar-phpstorm

Remote Call plugin required - you can get it from inside PhpStorm's plugin marketplace.

**Comment by yangweijie** [comment]
> 
for latest version remote call plugin cant't install , for replace [ide-remote-control](https://plugins.jetbrains.com/plugin/19991-ide-remote-control/reviews)  can open file with the format 
`http://localhost:63342/api/file/?file=%file&line=%line`

 as subl i run with a exe  can open in windows.

**Comment by raveren** [comment]
fix in https://github.com/barryvdh/laravel-debugbar/pull/1412
