### ISSUE TITLE
Facade.php @method declares string instead of variadic? Method call is provided 2 parameters, but the method signature uses 1 parameters

### ISSUE THREAD

**Issue by keniWilliamsEst** [barryvdh/laravel-debugbar#997]
I am new to this. I have noticed this for some time and I am unsure of whether it is my environment or something I have missed. 
in Facade.php I see  
`@method static void info(string $message)`
and in LaravelDebugBar.php it is
` @method void info(...$message)`

To stop the inspection I changed `string $message` to `...message` and now I don't get the inspection issue, which is what I would like. I don't think it is a good idea to modify the src.

Is this a bug?

**Comment by laravel-enthusiast** [comment]
I have a similar issue with Facede.php:13 * @method static void info(mixed $message).
If i pass anything but a string phpstan argues:
  `Parameter #1 $message of static method Barryvdh\Debugbar\Facade::info() expects string, <any other type> given.`
just sayin'... great work btw!
